### ISSUE TITLE
Error when trying to configure and build out of tree

### ISSUE THREAD

**Issue by clementperon** [zlib-ng/zlib-ng#1]
Calling the configure script from another directory in order to build out of tree will create an error :
cannot open zlib.h: No such file

**Comment by Dead2** [comment]
Confirmed. I'll have a look at this at some point.
Patches accepted if someone wants to do some simple fixes.

**Comment by nicorac** [comment]
Me too.
Any update on this?

**Comment by Dead2** [comment]
This will hopefully be resolved as part of a bigger upgrade of the build system, at the moment there is a bigger unresolved issue that prevents it from being usable as a system-wide replacement for zlib.
(the buffer size issue)

**Comment by mtl1979** [comment]
I can implement this pretty easily now that I have my Linux box plugged in...

**Comment by mtl1979** [comment]
I have a test version that worked for me... Look at [zlib-ng/test1](https://github.com/mtl1979/zlib-ng/tree/test1) if you want to test... If there is any problems, send me a private message...

**Comment by Dead2** [comment]
With the exception of the mkdir I commented upon, this looks good.
I will need to do a bit of testing before merging this though, will try to get that done sometime this weekend.
Please prepare a pull request whenever you have the time and I will pull it if it passes testing.

**Comment by mtl1979** [comment]
I will prepare the pull request when enough people have tested the changes... It's too big change to assume that if it works on one setup, it works on all setups... The "mkdir -p" is kinda weird but absolutely necessary on the first build...
