### ISSUE TITLE
Add support for multiple architectures in universal app bundles

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#1016]
Right now CMake only detects one architecture. But with Xcode it is possible to have multiple architectures in each binary. For example, you can have `x86` and `arm` in a single universal binary. This depends on `CMAKE_OSX_ARCHITECTURES`. In `detect-arch.cmake` we currently only check the first architecture and use that.

https://github.com/zlib-ng/zlib-ng/blob/c0cca0854206e25b41f1ee403dfb9a522ba85328/cmake/detect-arch.cmake#L6-L9

**Comment by mtl1979** [comment]
There is multiple issues with adding support for fat binaries containing code for multiple architectures. Basically we need to have separate feature detection and build flags for all the architectures and then combine them as one binary.

I remember using fat binaries when MacOS switched from PowerPC processors to Intel processors.

I haven't even looked up if CMake has complete built-in support for fat binaries.

**Comment by nmoinvaz** [comment]
Since there is a solution in #1085 I am closing this.

**Comment by triplef** [comment]
While building each arch manually works fine, it would be nice if there was support for having CMake do the work for us by building with `-DCMAKE_OSX_ARCHITECTURES="arm64;x86_64"`, which works fine with other projects.

In the meantime it’d be great if the [wiki article about building for Apple Silicon](https://github.com/zlib-ng/zlib-ng/wiki/Build-tips#building-with-configure-on-apple-silicon) could be updated with this info.
