### ISSUE TITLE
adler32 unit test does not test all optimized functions

### ISSUE THREAD

**Issue by mscastanho** [zlib-ng/zlib-ng#1017]
`adler32_test` makes calls to adler32, which actually maps to an specific implementation through the functable.
The consequence is that only one implementation is tested. This can be (and probably is) mitigated in the CI by creating different targets disabling some features that control which implementation will be used at runtime.

But ideally, the code should test all adler32 implementations the host is capable of running.

**Comment by nmoinvaz** [comment]
I agree it is mitigated by CI. Some of these implementations are hardware specific so it is not possible to test every implementation obviously. 

I reviewed the code coverage reports and it seems that `arch/power/adler32_vmx.c` is not tested at all. I wonder if the reporting is off:
 * GHA run https://github.com/zlib-ng/zlib-ng/runs/3508029170?check_suite_focus=true reports `WITH_POWER8=OFF` and shows it is compiling in adler32_vmx.c and slide_hash_vmx.c
 * https://codecov.io/gh/zlib-ng/zlib-ng/src/develop/arch/power/power.c shows the lines for setting VMX feature flags are being hit.

**Comment by KungFuJesus** [comment]
Hah, I have a quad powermac G5 with a modernish installation of gentoo I could test this with :).  Doesn't help with the CI issues, though.
