### ISSUE TITLE
Request: Add option of user-specified function prefixes

### ISSUE THREAD

**Issue by gdevenyi** [zlib-ng/zlib-ng#1025]
Many projects which follow the cmake-based "superbuild" route of building all their dependencies during compile (particularly, ITK and VTK) like to prefix the functions of commonly used libraries as to guarantee they don't clash with system libraries accidentally.

Previously ITK had been using a forked zlib with mangled symbols https://gitlab.kitware.com/third-party/zlib/-/compare/master...for%2Fitk-v1.2.11-2017-01-15-cacf7f1d but want to transition to zlib-ng as their officially bundled codebase.

With the existing PREFIX features in zbuild.h I'd like to propose adding a user-specified prefix option to facilitate such use cases. I'm looking at adding a PR myself, but I need to learn the cmake part of things for this to work properly.

**Comment by mtl1979** [comment]
That's already in our To-Do list... I can't say currently how long it will take to implement. 
We wanted to make the first official build first and then start adding more features.

If you make a pull request, we can help with getting cmake and configure to support it.

**Comment by dzenanz** [comment]
Is there any update on this?

**Comment by gdevenyi** [comment]
I think the infrastructure already exists at https://github.com/zlib-ng/zlib-ng/blob/develop/zbuild.h#L41-L55

But I don't know cmake well enough to make this configurable in such a way that we could use it (yet)

**Comment by mtl1979** [comment]
The main issue is that the prefix is still hard-coded in the externally visible headers... What we need is version of those files that have the prefix adjusted to user-defined one. I know it can be done with simple string substitution during configuration step.

**Comment by dzenanz** [comment]
Some inspiration can be found in the last dozen commits in this [branch](https://gitlab.kitware.com/third-party/zlib/-/commits/for/itk-v1.2.11-2017-01-15-cacf7f1d). I assume majority of that work has been done in some form in `zlib-ng`.

**Comment by dzenanz** [comment]
> simple string substitution during configuration step

That is usually accomplished by https://cmake.org/cmake/help/latest/command/configure_file.html using `@ONLY` syntax.

**Comment by mtl1979** [comment]
@dzenanz String substitution is quite easy with both cmake and configure, but I haven't really looked up how it can be done using nmake.

**Comment by nmoinvaz** [comment]
I don't know it is something we want to support for nmake. nmake makefiles don't really support everything that configure and cmake do anyways as it is.

**Comment by mtl1979** [comment]
@nmoinvaz currently nmake just copies the unmodified file, but if we change those files, it will break nmake.

**Comment by dzenanz** [comment]
I will give this a try - at least for CMake. Then one of you could "port" it to `configure`.

**Comment by dzenanz** [comment]
[PR in ITK](https://github.com/InsightSoftwareConsortium/ITK/pull/2708) works for me. Waiting for patches here to be merged: #1043, #1042, and #1041 or #1040.
