### ISSUE TITLE
Validation with pngtest

### ISSUE THREAD

**Issue by Adenilson** [zlib-ng/zlib-ng#103]
It would be nice if we could create a test suite (or at least a protocol of tasks) that should be done with a build of zlib-ng before a new version is released.

One nice tool to validate zlib(s) is 'pngtest', as it will open a png, decompress it, write it out and compare the generated file X source file.

From the source: "If the files are identical, this shows that the basic chunk handling, filtering, and (de)compression code is working properly.  It does not currently test all of the transforms, although                 
it probably should.".

**Comment by Adenilson** [comment]
The 3 files are quite different in the sense of PNG features used and they are known for all 3 passing pngtest while linked with Canonical zlib.

![g](https://cloud.githubusercontent.com/assets/959744/24776894/bd96455e-1ad7-11e7-9cb7-41c9bc119d9b.png)
![zebrahighres-min](https://cloud.githubusercontent.com/assets/959744/24776895/bd9b6660-1ad7-11e7-9dfb-9dc99bd0d021.png)
![zopfli](https://cloud.githubusercontent.com/assets/959744/24776896/bd9ec3dc-1ad7-11e7-9ca7-beeaaf1f8a12.png)

**Comment by Adenilson** [comment]
Checksums (md5sum):
a) google logo: 80fa4bcab0351fdccb69c66fb55dcd00
b) smaller img: d96fe2a2c9b2dd194cc8d183e5cf574d
c) bigger img: 3c477bdb7fd1f9b0b02bad9ddb567649

**Comment by mtl1979** [comment]
Some tests can only be done when zlib-ng is built as static library as we are not planning to export all the internal functions required to perform the validity tests. Some tests require modifying the existing test program to support zlib-ng specific features. Some tests might require building zlib-ng with two or more different flag sets and comparing the results. In the past we have had problems with using pngtest to verify correct operating of zlib-ng as some zlib-ng versions fail completely but some version combinations work depending on which version of libpng and zlib-ng we use, and on which operating system the test is run.

**Comment by nmoinvaz** [comment]
We can do this in CMakeLists.txt with:
```
    if(ZLIB_COMPAT AND NOT BUILD_SHARED_LIBS)
        set(LIBPNG_SOURCE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/lib/libpng)
        set(LIBPNG_INSTALL_DIR ${CMAKE_CURRENT_BINARY_DIR}/install/libpng)

        set(LIBPNG_CMAKE_ARGS
            -DCMAKE_INSTALL_PREFIX=${LIBPNG_INSTALL_DIR}
            -DZLIB_LIBRARY=$<TARGET_FILE:zlib>
            -DZLIB_INCLUDE_DIR=${CMAKE_CURRENT_SOURCE_DIR}
            -DPNG_TESTS=ON -DPNG_STATIC=OFF)

        include(ExternalProject)

        ExternalProject_Add(libpng
            PREFIX ${LIBPNG_SOURCE_DIR}
            GIT_REPOSITORY https://github.com/glennrp/libpng
            BUILD_IN_SOURCE 1
            UPDATE_COMMAND ""
            TEST_BEFORE_INSTALL ON
            CMAKE_ARGS "${LIBPNG_CMAKE_ARGS}")
    endif()
```

It will compile pngtest with zlib-ng in compatibility mode. Then it will run the tests that are part of libpng's CMakeLists.txt. Currently some of the tests fail:
```
  The following tests FAILED:
         16 - pngstest-1.8-none (Failed)
         18 - pngstest-linear-none (Failed)
         20 - pngstest-none-none (Failed)
         22 - pngstest-sRGB-none (Failed)
  Errors while running CTest
```

**Comment by nmoinvaz** [comment]
This is now part of CI when pull requests occur.
