### ISSUE TITLE
Is calling the library zlib-ng2.dll necessary?

### ISSUE THREAD

**Issue by hmaarrfk** [zlib-ng/zlib-ng#1044]
https://github.com/zlib-ng/zlib-ng/blob/92107a92d3cfb11cc464c24ef2a73c2d7d05d2ba/CMakeLists.txt#L1022

I'm packaging this library for conda forge and trying to use it in a downstream project.

The challenge i find is that the naming convention is different between windows and Linux. 

While i understand this is often true for historic libraries,

I'm wondering if we should just stick to the name zlib-ng and not add an other suffix 

Let me know what name you think is most appropriate.

i kinda wish I had 

`zlib-ng.dll`
and a matching `.lib` file

**Comment by Dead2** [comment]
This is actually related to #1045.
Having the so-version in the name is especially important on windows, where AFAIK there are little other protections available when you have an updated library and an outdated application, or if you wanted to have two different versions of the dll in the same folder due to two different but related applications using two different versions.

**Comment by hmaarrfk** [comment]
hmm. alright. I'll keep things as is.

do you have FindZLIB_NG files for cmake?

**Comment by hmaarrfk** [comment]
I guess the second question is 

```
zlib-ng2.dll
zlib-ng.lib
```
is what came out after I compiled with the following options

```
cmake -G "NMake Makefiles" ^
      -DCMAKE_BUILD_TYPE:STRING="Release" ^
      -DCMAKE_INSTALL_PREFIX:PATH="%LIBRARY_PREFIX%" ^
      -DCMAKE_PREFIX_PATH:PATH="%LIBRARY_PREFIX%" ^
      -DBUILD_SHARED_LIBS=1 ^
      ..
```
https://github.com/conda-forge/zlib-ng-feedstock/blob/master/recipe/bld.bat

Is that intentional?

**Comment by mtl1979** [comment]
`zlib-ng.lib` is the import library used by linker to create import table that reference entries in the export table of the dll file... It's specific to Windows and follows same naming convention as stock zlib.

**Comment by nmoinvaz** [comment]
> do you have FindZLIB_NG files for cmake? 

https://github.com/zlib-ng/minizip-ng/pull/574/files#diff-9513dde0d4d2e07d9e0363caa44d4c9d9ac1624c4603bbb33cb5fb75be376b3b
