### ISSUE TITLE
Improvement suggestion for Zlib-ng

### ISSUE THREAD

**Issue by Videogamer555** [zlib-ng/zlib-ng#1045]
As of now, the ng version has the same problem as the official Zlib. The functions InflateInit, InflateInit2, DeflateInit, and DeflateInit2 are simply macros for the functions InflateInit), InflateInit2_, DeflateInit_, and DeflateInit2_  where each of the actual functions has an underscore character at the end of its name. The macros are VERY USEFUL ones too, making it so the programmer doesn't need to worry about stuff like providing a version number for the library too the function (for some reason the actual functions want to know the version number of the library they are in). Unfortunately somebody utilizing ZLib (or ZLib-ng) in a programming language that's not C or C++, will be UNABLE to use these macros, FORCING the programmer to add extra time-wasting keystrokes to his typing of his code, as he types code to tell the function what version of the library it's running in (as well as to do some of the other things that the macros normally did). This is NOT good.

The remedy I propose, is to simply take the macros, and make them into actual functions, and then export these new functions alongside the old ones (the new functions will call the old functions, just like the macros did before, and the old functions will still be exported in case there's some reason that you might need to call them directly, but most applications will never require calling those old clunky functions).

**Comment by mtl1979** [comment]
There is overhead in converting macros to functions as externally visible functions can't be inlined. I've worked with C# and other alternative programming languages for last 9 months and my solution was to have separate thunk library to expose the macros to just the programs that are not written in C/C++. This also made it possible that I can use PIE (position independent executable) on platforms that require relative addressing for also executables.

Using thunk library also allows converting or explicit casting between variable types that are not allowed in other programming languages, like unsigned integers in C#.

**Comment by Dead2** [comment]
The reason those macros are there is, as you noticed, to provide the version number. But you seem to have misunderstood the method of delivery and reason.
The version number of zlib/zlib-ng gets compiled into the binary of the application using the library, when calling these functions with the version number, zlib/zlib-ng can then determine whether the application has been compiled with the same or a compatible version of the library as what is currently installed. Avoiding potential corruption and/or crashes by refusing to work if the actual library does not feel confident that it is compatible with the version the application was expecting.

That said, I personally think this is very old-school, and might be more useful on windows than on linux.
So I have been considering removing this for zlib-ng native, and rather go with modern versioning methods, IF we can do that without loosing too much of the protection. Potentially keep it for windows if needed? Not ideal since that would make the API different on that platform.

**Comment by Videogamer555** [comment]
> 
> 
> There is overhead in converting macros to functions as externally visible functions can't be inlined. I've worked with C# and other alternative programming languages for last 9 months and my solution was to have separate thunk library to expose the macros to just the programs that are not written in C/C++. This also made it possible that I can use PIE (position independent executable) on platforms that require relative addressing for also executables.
> 
> Using thunk library also allows converting or explicit casting between variable types that are not allowed in other programming languages, like unsigned integers in C#.

You are correct that it can't be inlined, but that's the cost of making this DLL's functions easy to call in non-C programming languages such as Visual Basic (my ABSOLUTE FAVORITE programming language, due to how SUPER EASY it is to write programs with). Instead of writing an entire chunk of code to handle window messages (which get even more complicated when you have several controls like buttons in the window) in a GUI application, VB6's internals handle ALL of that, showing you (the programmer) just EVENTS that correspond to different inputs into your GUI. This makes it SUPER EASY to write a full GUI application, without having to know how to program the GUI itself to exist. You just need to program the BEHAVIOR of the application. In C or C++ you need to waste time writing code just to make the GUI exist.

I really would hope, for the convenience of people (such as myself) using non-C programming languages, that you will maybe make a separate fork of the code, with all the macros turned into exported functions, even if you intend to keep the main fork of the code using macros.

**Comment by mtl1979** [comment]
@Videogamer555 Suggestions are always welcome, but it's ultimately @Dead2 who decides which suggestions get highest priority... Some suggestions might be counterintuitive and not a really good idea to implement.

**Comment by nmoinvaz** [comment]
This should be resolved now in `develop` with modern zlib-ng API.

**Comment by Videogamer555** [comment]
> 

What do you mean in "develop"? And what do you mean by the modern API?

**Comment by mtl1979** [comment]
> > 
> 
> What do you mean in "develop"? And what do you mean by the modern API?

`develop` branch in Git...

**Comment by nmoinvaz** [comment]
When not using ZLIB_COMPAT option.
