### ISSUE TITLE
Some small improvement of speed

### ISSUE THREAD

**Issue by blueboar2** [zlib-ng/zlib-ng#1046]
In the inflate.c file there are such lines of sode:

                ((BITS(8) << 8) + (hold >> 8)) % 31) {
                SET_BAD("incorrect header check");
                break;

These lines check that ZLIB header is correct. If we move to assembly, then checking remainder with a zero would be AND EAX, 31 / JZ xxx.

But, unfortunately, GCC/CLANG compilers don't optimize this area (I think because they don't know, if this value is signed or not, but I'm not sure), and generate actual division code. So, they divide this value by 31 and take the remainder. It is very slow comparing to AND. Also, from GCC 9.x there is some optimization - instead of DIV this value by 31, compiler replaces division to multiplying by the magic number (08421085h). It is faster method than division, but neverthless, much slower than just AND command.

So, I propose to replace this line to  ((BITS(8) << 8) + (hold >> 8)) & 31 != 0) {
or something like this to help compilers generate more fast code (it will be also smaller in size)

**Comment by mtl1979** [comment]
Modulo is not same as bitwise AND, that's why compiler won't optimize it. Most processors do both division and modulo as one instruction, so there isn't any speed gain using alternatives.

**Comment by blueboar2** [comment]
Sorry, I understood. I mistakenly assumed not 31, but 32.
