### ISSUE TITLE
Is zlib-ng fully compatible with zlib? Can zlib and zlib-ng decompress each other?

### ISSUE THREAD

**Issue by minchai23** [zlib-ng/zlib-ng#1047]

**Comment by mtl1979** [comment]
We have tests to confirm zlib can decompress files created by zlib-ng and vice versa. I can't still say zlib-ng is 100% compatible, but we fix issues as we find them.

**Comment by nmoinvaz** [comment]
Also see #905.

**Comment by minchai23** [comment]
Thank you for your answer.
