### ISSUE TITLE
Cross compile with CHOST=arm-linux-gnueabihf creates bus error on target.

### ISSUE THREAD

**Issue by chemwolf6922** [zlib-ng/zlib-ng#1058]
zlib-ng version: 2.0.5
compile process:
```bash
CHOST=arm-linux-gnueabihf ./configure
make
```
output of configure:
```
Using arm-linux-gnueabihf-ar
Using arm-linux-gnueabihf-ranlib
Checking for compiler... arm-linux-gnueabihf-gcc
Checking for shared library support... Building shared library libz-ng.so.2.0.5 with arm-linux-gnueabihf-gcc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for strerror... Yes.
Checking for unistd.h... Yes.
Checking for ptrdiff_t... Yes.
Checking for ANSI C compliant compiler...  Yes.
Checking for -fno-semantic-interposition... Yes.
Checking for -fno-lto... Yes.
Checking for attribute(visibility(hidden)) support... Yes.
Checking for attribute(visibility(internal)) support... Yes.
Checking for __builtin_ctz ... Yes.
Checking for __builtin_ctzll ... Yes.
Check whether -mfpu=neon is available ... Yes.
Checking for sys/sdt.h ... No.
ARM floating point arch: -mfloat-abi=hard
ARCH: armv8-a+crc
Using arch directory: arch/arm
```
Run the generated minigzip example on target and it produced a bus error
```
./minigzip peiceOfData (~15MB)
Bus error
```
The target device did not have any analyze tools in place. That's all the information I can get for now.
The toolchain is correct as it is the target toolchain of the devices' buildroot project. And builds all other packages without similar errors.

**Comment by mtl1979** [comment]
I would try disabling ACLE instruction set support first... If compiler tells it supports ACLE, then the build system tries to enable it as "arm" is generic target and does give no clue if processor should support ACLE or not...

**Comment by chemwolf6922** [comment]
Thanks for the solution. It works now. 
This ACLE support problem seems to be around for quite some time according to other opening issues. Looking forward for a fix in the future releases.

**Comment by mtl1979** [comment]
When using configure, by default we always target the best processor that the specific compiler supports when cross-compiling... configure doesn't support overriding processor detection, but cmake does.
Almost all "optional" features that are enabled by default, can be disabled on command-line.
