### ISSUE TITLE
C6385: Reading invalid data from 's->bl_count':

### ISSUE THREAD

**Issue by pavel-pimenov** [zlib-ng/zlib-ng#1064]
https://github.com/zlib-ng/zlib-ng/blob/develop/trees.c#L240
VC++ 2022
zlib-ng\trees.c(240): warning C6385: Reading invalid data from 's->bl_count':  the readable size is '32' bytes, but '-2' bytes may be read.

**Comment by nmoinvaz** [comment]
See https://github.com/madler/zlib/issues/185#issuecomment-269916428
