### ISSUE TITLE
Cmake not supporting 16 bit devices 

### ISSUE THREAD

**Issue by dhn1** [zlib-ng/zlib-ng#1110]
I believe there is a small omission in the cmake file when detecting the size of pointers. This causes cmake to fail when cross-compiling for devices with 16 bit pointers (Arm v7). The amendment below seems to fix the issue - zlib-ng builds and works.

    if(${SIZEOF_DATA_PTR} MATCHES "2")
        set(PTRDIFF_TYPE "uint16_t")
    elseif(${SIZEOF_DATA_PTR} MATCHES "4")
        set(PTRDIFF_TYPE "uint32_t")
    elseif(${SIZEOF_DATA_PTR} MATCHES "8")
        set(PTRDIFF_TYPE "uint64_t")
    else()
        message(FATAL_ERROR "sizeof(void *) is neither 16, 32 nor 64 bit")
    endif()

**Comment by mtl1979** [comment]
zlib-ng officially doesn't support anymore configurations with 16-bit pointers. 16-bit pointers can cause overflow and wraparound in rare conditions.

**Comment by dhn1** [comment]
That is a shame, these smaller devices really benefit from zlib-ng. Is there an older version that does support 16bit and still have most of the optimisations?

**Comment by mtl1979** [comment]
Older commits in GitHub might have bugs that have been fixed in subsequent commits. It might be possible to just revert the parts that disabled the support for 16-bit configurations, but I haven't really compiled comprehensive list of affected files or functions.
