### ISSUE TITLE
static build depends on building fuzzers (fails for static cross-builds)

### ISSUE THREAD

**Issue by rockdaboot** [zlib-ng/zlib-ng#1125]
When cross-building a static zlib-ng, I run into
```
x86_64-w64-mingw32-gcc -L/home/tim/src/wget2/x86_64-w64-mingw32/lib -m64 -o checksum_fuzzer -lFuzzer  -lstdc++ checksum_fuzzer.o libz.a -lpthread
/usr/bin/x86_64-w64-mingw32-ld: cannot find -lFuzzer
collect2: error: ld returned 1 exit status
```

My work-around is to remove `fuzzers` from the `static` make target (feels like a hack).
I am at commit 30c89988e2399e8da18adedb4ba666e08f078db8.

The recipe is
```
CROSS_PREFIX="x86_64-w64-mingw32-" \
ARCH="x86_64" \
CFLAGS="-O2" \
CC=x86_64-w64-mingw32-gcc \
./configure --prefix=$INSTALLDIR --static --64 --zlib-compat
make -j
```

Please let me know if I don't use the build system correctly (only need to build `libz.a`).

**Comment by mtl1979** [comment]
Building fuzzers should be disabled by default, and I see nowhere in the command-line that building them is enabled... This might be case of stale Makefiles from earlier build.

**Comment by rockdaboot** [comment]
Just look at `Makefile.in` - removing the fuzzers from the static make target looks like
```
diff --git a/Makefile.in b/Makefile.in
index ca2b112..4646f2c 100644
--- a/Makefile.in
+++ b/Makefile.in
@@ -154,7 +154,7 @@ PIC_OBJS = $(PIC_OBJC)
 
 all: static shared
 
-static: adler32_test$(EXE) crc32_test$(EXE) example$(EXE) minigzip$(EXE) fuzzers makefixed$(EXE) maketrees$(EXE) makecrct$(EXE)
+static: adler32_test$(EXE) crc32_test$(EXE) example$(EXE) minigzip$(EXE) makefixed$(EXE) maketrees$(EXE) makecrct$(EXE)
 
 shared: adler32_testsh$(EXE) crc32_testsh$(EXE) examplesh$(EXE) minigzipsh$(EXE)
 
```

Please see `fuzzers` appearing in the original dependency list.

**Comment by rockdaboot** [comment]
So my full recipe is
```
rm -rf zlib-ng
git clone https://github.com/zlib-ng/zlib-ng
cd zlib-ng
sed -i '/^static: /s/ fuzzers / /' Makefile.in
CROSS_PREFIX="x86_64-w64-mingw32-" \
ARCH="x86_64" \
CFLAGS="-O2" \
CC=x86_64-w64-mingw32-gcc \
./configure --prefix=$INSTALLDIR --static --64 --zlib-compat
make -j
make install
cd ..
```

**Comment by mtl1979** [comment]
I even tried "make static" explicitly and it didn't build any of the fuzzers as the target in Makefile is empty...

Only way zlib-ng's Makefile enables fuzzing without configure knowing is if it is run with non-empty `LIB_FUZZING_ENGINE`, which would be visible in the command line. Resetting `LIB_FUZZING_ENGINE` to empty string is the proper solutions in that case.

**Comment by mtl1979** [comment]
> x86_64-w64-mingw32-gcc -L/home/tim/src/wget2/x86_64-w64-mingw32/lib -m64 -o checksum_fuzzer -lFuzzer  -lstdc++ checksum_fuzzer.o libz.a -lpthread

In above target, it suggests `LIB_FUZZING_ENGINE` is set to `-lFuzzer -lstdc++`, but there is no path specified, so it can't find the library.

**Comment by rockdaboot** [comment]
> n above target, it suggests LIB_FUZZING_ENGINE is set to Fuzzer, but there is no path specified, so it can't find the library.

Oh no, sorry. You are right. I indeed reused an open console where I previously used fuzzing. Totally went out of my mind after a few days of absence from th keyboard.

Shame on me to waste your time :-|
I highly appreciate your patience <3
