### ISSUE TITLE
some git-2.35.1 tests fail with zlib-ng-2.0.6 in compat mode

### ISSUE THREAD

**Issue by xry111** [zlib-ng/zlib-ng#1149]
Three git-2.35.1 tests fail on my system with libz.so.1 provided by zlib-ng-2.0.6:

```
not ok 35 - basic atom: head objectsize:disk
not ok 91 - basic atom: tag objectsize:disk
not ok 92 - basic atom: tag *objectsize:disk
```

By `LD_PRELOAD` the original libz.so (from old zlib) these tests pass.

I'm not sure if this is a bug in zlib-ng, or a mere difference unexpected by git.

**Comment by nmoinvaz** [comment]
I think they are relying on the output size of zlib datastream for their tests which is not necessary the same as what zlib-ng might produce. See https://github.com/zlib-ng/zlib-ng/discussions/905. However, you'd probably want to get one of the git developers to verify that is the case.

**Comment by nmoinvaz** [comment]
If you find out there is an actual bug please reopen.

**Comment by xry111** [comment]
> If you find out there is an actual bug please reopen.

I don't think this is an actual bug.
