### ISSUE TITLE
Speed up inflate_fast by up to 1.5x on x86_64

### ISSUE THREAD

**Issue by nigeltao** [zlib-ng/zlib-ng#117]
FYI I have an upstream PR to speed up inflate_fast by up to 1.5x on x86_64. Happy to discuss how you'd like to merge it into zlib-ng, if you're interested.

https://github.com/madler/zlib/pull/292

See also https://github.com/madler/zlib/pull/256 by Simon Hosie.

**Comment by Dead2** [comment]
Your changes look interesting, and we'd love to see a PR from you.
If your changes are arch-generic, then they can go into the global files, if they are arch-dependent then they need to go into the arch subdirs. It should be pretty easy to figure out.

I have not looked into @simhos01 PR that you reference, but I suspect they have already been merged in our codebase. There was some collaboration in this repo where Simon's patches were suggested and improved upon, so I think the result of that is probably what is in that PR.

Your changes will not be included into the next stable release, but we are ready for the one after that. For now, just make the PR against the develop branch, I can change it to another branch when we make one ready for the next release.

**Comment by nigeltao** [comment]
FYI, I will make a PR, but I'm currently waiting on discussions with other Chromium zlib experts on how to best structure the patch (in terms of e.g. file layout, variable names, macro usage) to maximize the likelihood of being accepted upstream to https://github.com/madler/zlib. I've asked madler himself (on https://github.com/madler/zlib/pull/292), but I don't think he's very responsive (which is fine, I'm sure zlib is not the only thing in his life).

**Comment by mtl1979** [comment]
@nigeltao Just remember that what's accepted in madler/zlib isn't same as what's accepted here as zlib-ng has deprecated some integer type aliases due to fact that we are targeting more modern compilers.

**Comment by sebpop** [comment]
All the good bits from nigeltao's patch have been integrated in zlib-ng.
Can we close this issue?

**Comment by nmoinvaz** [comment]
I think this issue can be closed.
