### ISSUE TITLE
Error with libpng and zlib-ng (ZLIB_VERNUM != PNG_ZLIB_VERNUM)

### ISSUE THREAD

**Issue by mauer** [zlib-ng/zlib-ng#1174]
Hi,

I'm started a new project where I need zlib and libpng. I actually never worked with both libraries before, so after quite a bit of search I decided to use zlib-ng instead of the original zlib, as the CMAKE support is somewhat better.

Unfortunately, when compiling my project on Ubuntu 20.04 is get the following message from libpng:
`error: ZLIB_VERNUM != PNG_ZLIB_VERNUM`

I'm using the following settings in my CMakeList.txt:
```
# Add zlib
message("-- Configuring build scripts for zlib")
set(ZLIB_COMPAT ON CACHE BOOL "Override option" FORCE)
set(WITH_NEW_STRATEGIES OFF CACHE BOOL "Override option" FORCE)
add_subdirectory(zlib-ng)

# Add libpng
message("-- Configuring build scripts for libpng")
set(PNG_BUILD_ZLIB ON CACHE BOOL "Override option" FORCE)
set(PNG_SHARED OFF CACHE BOOL "Override option" FORCE)
set(PNG_EXECUTABLES OFF CACHE BOOL "Override option" FORCE)
set(PNG_STATIC ON CACHE BOOL "Override option" FORCE)
set(PNG_TESTS  OFF CACHE BOOL "Override option" FORCE)
add_subdirectory(libpng)
```

Am I missing something or is zlib-ng not really compatible with libpng 1.6.37?

Any help would be highly appreciated to get this working.

Thanks,
Marco

**Comment by nmoinvaz** [comment]
You have to link libpng against zlib-ng using `target_link_libraries` or some other method. We also have a CI example that uses libpng for our tests: https://github.com/zlib-ng/zlib-ng/blob/develop/.github/workflows/libpng.yml. In that we pass the zlib library to libpng's CMake.

Also it sounds like libpng is being built with zlib already? Does `PNG_BUILD_ZLIB` need to be turned off?

**Comment by mauer** [comment]
PNG_BUILD_ZLIB should be ON if the library was built as a sub-project. I had a look at your CI and changed my options. It's working fine building on macOS and Ubuntu Linux, but using mingw64 to cross-compile for the windows platform is giving me a new error:

`/build/lib/zlib-ng/zlib.h:39:10: fatal error: zconf.h: No such file or directory`

Interesting part is, that the file is actually in the binary output directory. Really annoying as all other platforms are finally working fine.

**Comment by mtl1979** [comment]
`add_subdirectory` should have two parameters, second one will be used to find generated files.

**Comment by mauer** [comment]
It's really weird, it's compiling fine on Ubuntu, macOS and Windows using MSYS2. Just the cross-compile from Ubuntu for Windows doesn't work. It's working fine with other projects I'm working on.

It's probably something small - as always :-)

That's the CMakeList.txt I'm using, maybe some CMake experts see a mistake I made.

```
# Add zlib-ng
message("-- Configuring build scripts for zlib-ng")
set(BUILD_SHARED_LIBS OFF CACHE BOOL "Override option" FORCE)
set(ZLIB_COMPAT ON CACHE BOOL "Enable compatibility to libpng" FORCE)
set(ZLIB_ENABLE_TESTS OFF CACHE BOOL "Disable all tests" FORCE)
add_subdirectory(zlib-ng)

# Add libpng
message("-- Configuring build scripts for libpng")
set(PNG_SHARED OFF CACHE BOOL "Override option" FORCE)
set(PNG_STATIC ON CACHE BOOL "Override option" FORCE)
set(PNG_TESTS  OFF CACHE BOOL "Override option" FORCE)
add_subdirectory(libpng)

```

**Comment by nmoinvaz** [comment]
Here is another CMake example that you can gleen some information from. It compiles `pigz` using `zlib`.
https://github.com/zlib-ng/zlib-ng/blob/319755304904e9f65644d0e2f5504c123f68794e/test/pigz/CMakeLists.txt#L135
You have to include zlib build directory, where zconf.h is generated to, to the libpng project.

**Comment by nmoinvaz** [comment]
Also the Wiki has some info:
https://github.com/zlib-ng/zlib-ng/wiki/Common-build-problems

**Comment by nmoinvaz** [comment]
What we do is:
```
add_subdirectory(zlib-ng ${CMAKE_CURRENT_BINARY_DIR} EXCLUDE_FROM_ALL)

# By setting these variables, `find_package` will use them to determine where zlib is.
set(ZLIB_ROOT ${CMAKE_CURRENT_SOURCE_DIR}/zlib-ng CACHE PATH "Root path to local zlib")
# Set include directory to build directory specified in add_subdirectory for zlib-ng.
set(ZLIB_INCLUDE_DIR ${CMAKE_CURRENT_BINARY_DIR} CACHE STRING "Include directory for zlib")
set(ZLIB_LIBRARY $<TARGET_FILE:zlib> CACHE STRING "Link local zlib library")

add_subdirectory(libpng)
```

**Comment by nmoinvaz** [comment]
It seems like the problem is with your build configuration pulling in system zlib or libpng is being built against the system zlib. Please let us know if the cmake methods suggested don't work.
