### ISSUE TITLE
2.0.5: perl Compress-Raw-Zlib module build fails

### ISSUE THREAD

**Issue by kloczek** [zlib-ng/zlib-ng#1234]
Looks like it is some inccmpatibility beteen zlib and zlib-ng.
I cannot build Compress-Raw-Zlib perl module against system installed `zlib-ng` (no problem with zlib).
Git repo of the module https://github.com/pmqs/Compress-Raw-Zlib/
Log of building rpom package:
```console
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.8Y6nie
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd /home/tkloczko/rpmbuild/BUILD
+ rm -rf Compress-Raw-Zlib-2.103
+ /usr/bin/tar -xof -
+ /usr/bin/gzip -dc /home/tkloczko/rpmbuild/SOURCES/Compress-Raw-Zlib-2.103.tar.gz
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd Compress-Raw-Zlib-2.103
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ /usr/bin/rm -rf zlib-src
+ RPM_EC=0
++ jobs -p
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.uyWk4U
+ umask 022
+ cd /home/tkloczko/rpmbuild/BUILD
+ cd Compress-Raw-Zlib-2.103
+ CFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none'
+ CXXFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none'
+ FFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules'
+ FCFLAGS='-O2 -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fdata-sections -ffunction-sections -flto=auto -flto-partition=none -I/usr/lib64/gfortran/modules'
+ LDFLAGS='-Wl,-z,relro -Wl,--as-needed -Wl,--gc-sections -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -flto=auto -flto-partition=none -fuse-linker-plugin -Wl,--build-id=sha1'
+ CC=/usr/bin/gcc
+ CXX=/usr/bin/g++
+ FC=/usr/bin/gfortran
+ AR=/usr/bin/gcc-ar
+ NM=/usr/bin/gcc-nm
+ RANLIB=/usr/bin/gcc-ranlib
+ export CFLAGS CXXFLAGS FFLAGS FCFLAGS LDFLAGS CC CXX FC AR NM RANLIB
+ OLD_ZLIB=False
+ BUILD_ZLIB=False
+ ZLIB_LIB=/usr/lib64
+ ZLIB_INCLUDE=/usr/include
+ /usr/bin/perl Makefile.PL INSTALLDIRS=vendor 'OPTIMIZE= ' NO_PACKLIST=1 NO_PERLLOCAL=1
Parsing config.in...
Auto Detect Gzip OS Code..
Setting Gzip OS Code to 3 [Unix/Default]
Looks Good.
Up/Downgrade not needed.
Checking if your kit is complete...
Warning: the following files are missing in your kit:
        zlib-src/adler32.c
        zlib-src/compress.c
        zlib-src/crc32.c
        zlib-src/crc32.h
        zlib-src/deflate.c
        zlib-src/deflate.h
        zlib-src/infback.c
        zlib-src/inffast.c
        zlib-src/inffast.h
        zlib-src/inffixed.h
        zlib-src/inflate.c
        zlib-src/inflate.h
        zlib-src/inftrees.c
        zlib-src/inftrees.h
        zlib-src/trees.c
        zlib-src/trees.h
        zlib-src/uncompr.c
        zlib-src/zconf.h
        zlib-src/zlib.h
        zlib-src/zutil.c
        zlib-src/zutil.h
Please inform the author.
Generating a Unix-style Makefile
Writing Makefile for Compress::Raw::Zlib
Writing MYMETA.yml and MYMETA.json
+ /usr/bin/make -O -j48 V=1 VERBOSE=1
Running Mkbootstrap for Zlib ()
chmod 644 "Zlib.bs"
"/usr/bin/perl" -MExtUtils::Command::MM -e 'cp_nonempty' -- Zlib.bs blib/arch/auto/Compress/Raw/Zlib/Zlib.bs 644
cp lib/Compress/Raw/Zlib.pm blib/lib/Compress/Raw/Zlib.pm
"/usr/bin/perl" "/usr/share/perl5/vendor_perl/ExtUtils/xsubpp"  -typemap '/usr/share/perl5/ExtUtils/typemap' -typemap '/home/tkloczko/rpmbuild/BUILD/Compress-Raw-Zlib-2.103/typemap'  Zlib.xs > Zlib.xsc
mv Zlib.xsc Zlib.c
gcc -c  -I/usr/include -D_REENTRANT -D_GNU_SOURCE -O2 -flto=auto -ffat-lto-objects -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -fstack-protector-strong -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -fwrapv -fno-strict-aliasing -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64    -DVERSION=\"2.103\" -DXS_VERSION=\"2.103\" -fPIC "-I/usr/lib64/perl5/CORE"  -DNO_VIZ -DZ_SOLO   -DGZIP_OS_CODE=3 -DUSE_PPPORT_H Zlib.c
In file included from Zlib.xs:34:
/usr/include/zlib.h:1781:31: error: unknown type name 'gzFile'
 1781 | Z_EXTERN int Z_EXPORT gzgetc_(gzFile file);  /* backward compatibility */
      |                               ^~~~~~
/usr/include/zlib.h:1791:13: error: unknown type name 'gzFile'
 1791 |    Z_EXTERN gzFile Z_EXPORT gzopen64(const char *, const char *);
      |             ^~~~~~
/usr/include/zlib.h:1792:48: error: expected ')' before 'off64_t'
 1792 |    Z_EXTERN z_off64_t Z_EXPORT gzseek64(gzFile, z_off64_t, int);
      |                                                ^
      |                                                )
/usr/include/zlib.h:1840:35: error: unknown type name 'gzFile'
 1840 | Z_EXTERN int Z_EXPORTVA gzvprintf(gzFile file, const char *format, va_list va);
      |                                   ^~~~~~
In file included from Zlib.xs:743:
constants.h: In function 'constant':
constants.h:370:18: warning: assignment to 'IV' {aka 'long int'} from 'void *' makes integer from pointer without a cast [-Wint-conversion]
  370 |       *iv_return = Z_NULL;
      |                  ^
make: *** [Makefile:348: Zlib.o] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.uyWk4U (%build)
```
The sam esituation is when perl is build (which have bundled that module)
https://github.com/Perl/perl5/issues/19566

**Comment by mtl1979** [comment]
The compiler flags are wrong and that causes errors with gzFile.

**Comment by Dead2** [comment]
The build system for this module seems to attempt to build zlib(-ng) statically by itself instead of relying on zlib(-ng)s own build system. This way of doing it will be very sensitive to changes in zlib, and zlib-ng has changed A LOT under the hood compared to zlib.

The right™️ way to do this is to either link to zlib(-ng)s shared library (.so), or link statically (.a).
I am afraid this perl module probably needs changes to its Makefile.PL to enable it to link to either.

**Comment by mtl1979** [comment]
Either removing `-DZ_SOLO` from compiler flags or upgrading to more recent version of zlib-ng should fix the errors with `gzFile` not being defined during compiling.

I was the one who fixed the issue of zlib-ng not honoring `Z_SOLO` in compatibility mode.

**Comment by Dead2** [comment]
@mtl1979 I don't think that is true in this case. It seems like this Makefile.PL tries to compile the zlib sourcefiles by name directly instead of using Makefile or CMakeFiles.txt from zlib/zlib-ng.

**Comment by mtl1979** [comment]
@Dead2 Those warnings are noise as `BUILD_ZLIB` is set to `False`.

**Comment by Dead2** [comment]
Hm, perhaps. I have not inspected the Makefile.PL itself.

**Comment by mtl1979** [comment]
I've used Perl a lot in the past ;)

**Comment by kloczek** [comment]
> Either removing `-DZ_SOLO` from compiler flags or upgrading to more recent version of zlib-ng should fix the errors with `gzFile` not being defined during compiling.

`-DZ_SOLO` is used with regular zlib.
In other words looks like there is no here 100% API compatybility.
Am I right?

**Comment by mtl1979** [comment]
> `-DZ_SOLO` is used with regular zlib.
> In other words looks like there is no here 100% API compatybility.
> Am I right?

Even zlib does not guarantee 100% API compatibility between versions. I'm not maintainer of zlib-ng, so I can't make such promises but I can fix any issues that community reports.

**Comment by mtl1979** [comment]
zlib-ng 2.0.6 should have the issue fixed... It's up to package manager of the distribution to keep packages up-to-date.

**Comment by kloczek** [comment]
> zlib-ng 2.0.6 should have the issue fixed... It's up to package manager of the distribution to keep packages up-to-date.

May I ask to point on exact commit?
I would be really glad to test that on my build infrastructure 😄

**Comment by Dead2** [comment]
@kloczek Look at releases subpage: https://github.com/zlib-ng/zlib-ng/releases
Left side has a link to the commit, it is also the tip of the `stable` branch.
The PR in question is #1022

**Comment by nmoinvaz** [comment]
If this is still an issue with newer version of zlib-ng please reopen.

**Comment by pmqs** [comment]
I'm the author of [Compress-Raw-Zlib](https://github.com/pmqs/Compress-Raw-Zlib). @kloczek created a ticket in one of my modules to report more or less the same issue (see https://github.com/pmqs/IO-Compress/issues/46). I had a go at getting zlib-ng working with my code, so I thought I'd share what I did here.

To see if I could reproduce the issue I synced the latest zlib-ng & built with `ZLIB_COMPAT=ON`

Building [Compress-Raw-Zlib](https://github.com/pmqs/Compress-Raw-Zlib) with zlib_ng gives the following compiler warnings, but it does compile OK.

```
$ ZLIB_LIB=/media/paul/zlib-ng/build ZLIB_INCLUDE=/media/zlib-ng/build BUILD_ZLIB=0  perl5.32.1 Makefile.PL
$ make
cp lib/Compress/Raw/Zlib.pm blib/lib/Compress/Raw/Zlib.pm
Running Mkbootstrap for Zlib ()
chmod 644 "Zlib.bs"
"/usr/bin/perl5.32.1" -MExtUtils::Command::MM -e 'cp_nonempty' -- Zlib.bs blib/arch/auto/Compress/Raw/Zlib/Zlib.bs 644
x86_64-linux-gnu-gcc -c  -I/media/paul/Linux-Shared/base/git/zlib-ng/build -D_REENTRANT -D_GNU_SOURCE -DDEBIAN -fwrapv -fno-strict-aliasing -pipe -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -O2 -g   -DVERSION=\"2.103\" -DXS_VERSION=\"2.103\" -fPIC "-I/usr/lib/x86_64-linux-gnu/perl/5.32/CORE"  -DNO_VIZ -DZ_SOLO   -DGZIP_OS_CODE=3 -DUSE_PPPORT_H Zlib.c
In file included from Zlib.xs:743:
constants.h: In function ‘constant’:
constants.h:370:18: warning: assignment to ‘IV’ {aka ‘long int’} from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
  370 |       *iv_return = Z_NULL;
      |                  ^
In file included from Zlib.xs:34:
Zlib.xs: In function ‘XS_Compress__Raw__Zlib_crc32_combine’:
/media/paul/Linux-Shared/base/git/zlib-ng/build/zlib.h:1813:27: warning: implicit declaration of function ‘crc32_combine64’; did you mean ‘crc32_combine’? [-Wimplicit-function-declaration]
 1813 | #    define crc32_combine crc32_combine64
      |                           ^~~~~~~~~~~~~~~
/media/paul/Linux-Shared/base/git/zlib-ng/build/zlib.h:1813:27: note: in definition of macro ‘crc32_combine’
 1813 | #    define crc32_combine crc32_combine64
      |                           ^~~~~~~~~~~~~~~
Zlib.xs: In function ‘XS_Compress__Raw__Zlib_adler32_combine’:
/media/paul/Linux-Shared/base/git/zlib-ng/build/zlib.h:1812:29: warning: implicit declaration of function ‘adler32_combine64’; did you mean ‘adler32_combine’? [-Wimplicit-function-declaration]
 1812 | #    define adler32_combine adler32_combine64
      |                             ^~~~~~~~~~~~~~~~~
/media/paul/Linux-Shared/base/git/zlib-ng/build/zlib.h:1812:29: note: in definition of macro ‘adler32_combine’
 1812 | #    define adler32_combine adler32_combine64
      |                             ^~~~~~~~~~~~~~~~~
rm -f blib/arch/auto/Compress/Raw/Zlib/Zlib.so
LD_RUN_PATH="/media/paul/Linux-Shared/base/git/zlib-ng/build" x86_64-linux-gnu-gcc  -shared -L/usr/local/lib -fstack-protector-strong  Zlib.o  -o blib/arch/auto/Compress/Raw/Zlib/Zlib.so  \
   -L/media/paul/Linux-Shared/base/git/zlib-ng/build -lz   \
  
chmod 755 blib/arch/auto/Compress/Raw/Zlib/Zlib.so
Manifying 1 pod document
```

The problem comes when I run my test harness

```
$ make test
...
t/02zlib.t ......... 1/349 
#     Failed test (t/02zlib.t at line 501)
#          got: 1
#     expected: -3

#     Failed test (t/02zlib.t at line 535)
#          got: 1
#     expected: -3
# Looks like you failed 2 tests of 349.
t/02zlib.t ......... Dubious, test returned 2 (wstat 512, 0x200)
Failed 2/349 subtests 
...
```

The issue here is a fix that was added to `zlib 1.2.12` that changed the return code `inflate` returned when inflating to a sync point. 

```
    # Z_STREAM_END returned by 1.12.2, Z_DATA_ERROR for older zlib
    if (ZLIB_VERNUM >= ZLIB_1_2_12_0)
    {
        cmp_ok $status, '==', Z_STREAM_END ;
    }
    else
    {
        cmp_ok $status, '==', Z_DATA_ERROR ;
    }
```

Given that I have no control over what version of zlib gets used, I have to check the zlib version to decide which return code to use. In this instance zlib-ng 1.2.11 behaviour doesn't match zlib 1.2.11

I'm sure I can easily code up a change to support zlib-ng - can use the presence of `ZLIBNG_VERSION` to tell the two versions of zlib apart. 

Enhancement request to myself created at https://github.com/pmqs/Compress-Raw-Zlib/issues/9

**Comment by Dead2** [comment]
@pmqs We were targeting zlib 1.2.12 before release, however zlib did not release for several years so we had to revert the version number to 1.2.11 since we were not sure nothing new would appear later. We were not aware that 1.2.12 broke the backwards compatibility though, so that threw a wrench into things.

Presence of `ZLIBNG_VERSION` would probably be a good check in your case.

Next release from develop will target zlib 1.2.12 (or newer). 
I am considering pushing a new minor release for the current stable branch with recent fixes though, although fishing out the relevant ones is not an easy task any more since develop has diverged quite a bit. I am not sure whether we should update the version number for the current stable branch as well, it might fix this kind of discrepancy though.
@mtl1979 @nmoinvaz

**Comment by mtl1979** [comment]
@Dead2 zlib 1.2.12 is still quite unstable... It has known issues that essentially make it dud and unusable... I would wait a while to see if Mark Adler gets things fixed and then do final decision if we want to keep "full" compatibility.

**Comment by pmqs** [comment]
@Dead2 

> @pmqs We were targeting zlib 1.2.12 before release, however zlib did not release for several years so we had to revert the version number to 1.2.11 since we were not sure nothing new would appear later. We were not aware that 1.2.12 broke the backwards compatibility though, so that threw a wrench into things.
>
> Presence of `ZLIBNG_VERSION` would probably be a good check in your case.

Thanks, that's good to know.

> Next release from develop will target zlib 1.2.12 (or newer). I am considering pushing a new minor release for the current stable branch with recent fixes though, although fishing out the relevant ones is not an easy task any more since develop has diverged quite a bit. I am not sure whether we should update the version number for the current stable branch as well, it might fix this kind of discrepancy though. @mtl1979 @nmoinvaz

I'll may hold off releasing anything until the next zlib-ng release. I also need to see what happens when I use older versions of zlib-ng. Looking at the releases page, It seems 2.0.0 is the first version of zlib-ng I should support. If I find any more issues, I'll report back


thanks 
Paul

**Comment by nmoinvaz** [comment]
We do need a new version at some point even if it is alpha or beta or whatever.

**Comment by mtl1979** [comment]
> We do need a new version at some point even if it is alpha or beta or whatever.

Yup... Would be nice to have a new release around June... That still gives some time to merge more patches.

**Comment by nmoinvaz** [comment]
@kloczek it looks like you were able to build perl with zlib-ng. Can we close this issue?

**Comment by kloczek** [comment]
Closing (sorry forgot to do that).
Thank you 👍
