### ISSUE TITLE
deflateBound() returns a value that is too small

### ISSUE THREAD

**Issue by iii-i** [zlib-ng/zlib-ng#1235]
The following (IMHO reasonable) test fails:

```
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <zlib.h>

int main(void) {
  unsigned char Plain[1] = "\x06";
  unsigned char Compressed[130];
  z_stream Strm;
  int Bound;

  memset(&Strm, 0, sizeof(Strm));
  assert(deflateInit2(&Strm, 0, 8, 31, 1, Z_DEFAULT_STRATEGY) == Z_OK);
  Bound = deflateBound(&Strm, 1);
  Strm.next_in = Plain;
  Strm.next_out = Compressed;
  Strm.avail_in = sizeof(Plain);
  Strm.avail_out = sizeof(Compressed);
  assert(deflate(&Strm, Z_FINISH) == Z_STREAM_END);
  assert(Strm.avail_in == 0);
  assert(Bound >= Strm.next_out - Compressed);
  assert(deflateEnd(&Strm) == Z_OK);
}
```

The actual compressed data size is 24, the `deflateBound()` return value is 23. Tested on x86_64, commit 81d91d6f.

**Comment by mtl1979** [comment]
This has been reported before... We need more data to fix the calculation inside deflateBound(). Basically we need to test with multiple input sizes to see how much the difference of return value of deflateBound() and the actual compressed size is.

**Comment by iii-i** [comment]
Right, I remember this being discussed, but I haven't found an open issue.
So I've decided to make one and attach a reproducer.

**Comment by mtl1979** [comment]
@nmoinvaz might be able to make a test that runs the code with multiple input sizes...

**Comment by Dead2** [comment]
I assume this is is without DFLTCC enabled?

See #1071
I tried to account for what I could, but in the end there was a fair bit of guesswork and experimentation involved. Obviously you found a case that proves these guesses wrong.

**Comment by mtl1979** [comment]
@Dead2 For lengths smaller than 9, the return value is 1 too little due to shift in DEFLATE_QUICK_OVERHEAD() macro... I have a PR coming that adjusts the return value of deflateBound() to account the underflow.

**Comment by iii-i** [comment]
This is on x86_64, I found it with a fuzzer (https://github.com/iii-i/zlib-fuzz).
#1236 makes things better, but fuzzing now gives me the following:

```
#include <assert.h>
#include <stdio.h>
#include <string.h>
#include <zlib.h>
int main(void) {
  unsigned char Plain[0] = "";
  unsigned char Compressed[128];
  z_stream Strm;
  memset(&Strm, 0, sizeof(Strm));
  assert(deflateInit2(&Strm, 0, 8, -15, 3, Z_DEFAULT_STRATEGY) == Z_OK);
  int Bound = deflateBound(&Strm, 0);
  Strm.next_in = Plain;
  Strm.next_out = Compressed;
  Strm.avail_in = 0; Strm.avail_out = 128; assert(deflate(&Strm, Z_FINISH) == Z_STREAM_END);
  assert(Strm.avail_in == 0);
  assert(Bound >= Strm.next_out - Compressed);
  assert(deflateEnd(&Strm) == Z_OK);
}
```

**Comment by mtl1979** [comment]
I'm pretty sure passing 0 to deflateBound() is not going to work in any case...

**Comment by iii-i** [comment]
This snippet works fine on plain zlib, so it might make sense to support it.
Also, zlib manual does not restrict sourceLen to be nonzero.

**Comment by mtl1979** [comment]
I can add special case when sourceLen is `0`, but it's gonna get ugly...

**Comment by Dead2** [comment]
I previously made this test to check output sizes (based on a contributed testcase). It should probably be turned into a proper test

```
#include <stdio.h>
#include <stdlib.h>
#include <sys/random.h>

#include "zlib-ng.h"

void bounds_test(const int len) {
  unsigned char buffer[len];

  fprintf(stderr, "\nTesting: %d\n", len);

  if (getrandom(buffer, len, GRND_RANDOM) != len) {
    perror("getrandom()");
    exit(1);
  }

  zng_stream c_stream; /* compression stream */
  int err;
  int estimateLen = 0;
  unsigned char *outBuf = NULL;

  c_stream.zalloc = Z_NULL;
  c_stream.zfree = Z_NULL;
  c_stream.opaque = (voidpf)0;
  c_stream.avail_in = len;
  c_stream.next_in = (z_const unsigned char *)buffer;
  c_stream.avail_out = 0;
  c_stream.next_out = outBuf;

  int wbits = -MAX_WBITS; // MAX_WBITS = 15 (-8 to -15 for raw deflate, 8-15 for deflate, 16-31 for gzip)
  int complevel = 1;      // 0-9
  int memlevel = 1;       // 1-8

  err = zng_deflateInit2(&c_stream, complevel, Z_DEFLATED, wbits, memlevel, Z_DEFAULT_STRATEGY);
  if (err != Z_OK) {
    fprintf(stderr, "deflateInit2() error: %d\n", err);
    exit(1);
  }

  /* calculate actual output length and update structure */
  estimateLen = zng_deflateBound(&c_stream, len);
  fprintf(stderr, "Estimated: %d\n", estimateLen);
  outBuf = malloc(estimateLen);

  if (outBuf != NULL) {
    /* update zlib configuration */
    c_stream.avail_out = estimateLen;
    c_stream.next_out = outBuf;

    /* do the compression */
    err = zng_deflate(&c_stream, Z_FINISH);

    if (err == Z_STREAM_END) {
      fprintf(stderr, "Actual: %ld (Success)\n", c_stream.total_out);
    } else {
      fprintf(stderr, "deflate() error: got %d; expected Z_STREAM_END (%d)\n",
              err, Z_STREAM_END);
      exit(1);
    }
  }

  err = zng_deflateEnd(&c_stream);
  if (err != Z_OK) {
    fprintf(stderr, "deflateEnd() error: %d\n", err);
    exit(1);
  }

  free(outBuf);
}

int main(int argc, char *argv[]) {
    int i;
    const int tests[24] = { 0, 1, 2, 3, 4, 5, 8, 16,
                            32, 64, 128, 256, 258, 512, 1024, 2048,
                            4096, 8192, 16384, 32768, 65536, 1 << 18, 1 << 20, 1 << 22 };

    for (i=0; i < 24; i++) {
        bounds_test(tests[i]);
    }
}
```

Interestingly, with the same DeflateInit2 settings as the fuzzer above, this testcase succeeds just fine.
```
Testing: 0
Estimated: 3
Actual: 2 (Success)

Testing: 1
Estimated: 5
Actual: 3 (Success)

Testing: 2
Estimated: 6
Actual: 4 (Success)

... etc
```

I am not sure how this test differs from the above for the 0-byte case, with the exception of the result checking of course. Is this something arch/build dependent? I'd be interested to see what the predicted and actual sizes were for your test.

As you can see, when I made my code changes, I made sure we had at least 1 extra byte just in case I had overlooked something, so the failure would suggest that the actual size for 0bytes ends up at 4 bytes in your case..?

**Comment by iii-i** [comment]
I tested this with a very simple build: commit 81d91d6f, `ZLIB_COMPAT=ON`, x86_64.
The predicted bound is 3, the actual size is 5: `01 00 00 ff ff`.

Btw, @mtl1979's commit df44db5 seems to work fine.

**Comment by Dead2** [comment]
@iii-i Do you get the same result with my testcase? If not, any idea what changes are needed to reproduce?
I would look more into this, but I have to run now, won't be back for 6 hours and might not have time to look at this again today 😞

**Comment by iii-i** [comment]
Your test begins to fail if I set complevel 0.

**Comment by mtl1979** [comment]
I don't know why deflateBound on that code path is off by additional 1 byte for every 8 bytes of input... As in 0 byte input is off by 2 before my patch, 1-8 bytes input is off by 1, and 17-24 bytes are also off by one, but in other direction...

I tried to adjust the macro calculating the deflate_quick overhead by removing the `- 8` part and not adding `sourceLen` before the macro, but it still failed. It might need adding 2 bytes instead of sourceLen, but I was too sleepy to tinker it more... I do consider having extra room with higher lengths acceptable compromise to making the code more unreadable.

I did use memset() to initialize input while testing, so longer lengths should compress better.

**Comment by Dead2** [comment]
@iii-i Oh, I thought I had set that, but seems I didn't.

That is interesting though, why would compressing 0 bytes use more space in level 0 than level 1?
Do we emit an extraneous sync or something, because I don't think there is any real reason for it to be bigger in this (very) specific case.

Would be interesting to know whether we output a 0 byte level 0 "compressed" stream differently than zlib does or this is something inherited.

**Comment by iii-i** [comment]
Both zlib and zlib-ng emit an empty stored block on level 0, which is at least 5 bytes. On level 1 we get a fixed block instead.

**Comment by nmoinvaz** [comment]
This is resolved now in `develop`.
