### ISSUE TITLE
Configuration install package for CMake

### ISSUE THREAD

**Issue by rcdailey** [zlib-ng/zlib-ng#124]
Hi,

I recently contributed [a pull request](https://github.com/madler/zlib/pull/295) to the madler/zlib project with changes to CMake to support configuration packages. However, this project is moving very slowly. I'd like to see if you are interested in my changes. If so, I am happy to move them to this project. I hate that there are so many forks of zlib to worry about, I just want to find someone that plans to accept changes and keep things maintained with relatively short turnaround times.

As you review the PR, bear in mind I still have some work to do:

* Use `zlib::` namespace for exported targets
* Restore the exporting of both static and shared library targets (this is only to maintain parity with existing structure; however it's something we can discuss. Ideally (and idiomatic to CMake installations) the user should install either static or shared, but not both.

Thanks in advance for your feedback.

**Comment by rcdailey** [comment]
@Dead2 Would love to get your feedback.

**Comment by mtl1979** [comment]
@rcdailey We can't require minimum of cmake 3.0 because not all distributions have it yet as optional package.

**Comment by rcdailey** [comment]
Ok I'll keep this change for myself then until you can take it. Thanks.
