### ISSUE TITLE
Coverage?

### ISSUE THREAD

**Issue by vinniefalco** [zlib-ng/zlib-ng#125]
I'd like to see a code coverage report badge. Something like the ones on this page:
https://github.com/boostorg/beast/blob/develop/README.md

**Comment by mtl1979** [comment]
codecov currently fails with clang builds due to broken 32-bit support. Trying to upgrade to newer clang will introduce linker bug which needs to be fixed by Ubuntu repository maintainers.

**Comment by vinniefalco** [comment]
Okay, compile using 64-bit?

**Comment by vinniefalco** [comment]
I'm sure you can find a work-around for the linker bug. Is there a description of it?

**Comment by mtl1979** [comment]
@vinniefalco https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808181

**Comment by mtl1979** [comment]
@vinniefalco 64-bit compiling is default on platforms and compilers that support it but some decently modern systems still only support 32-bit compiling.

**Comment by vinniefalco** [comment]
You don't need a 32-bit build to get coverage. I am certain that with the right .travis.yml you can build the zlib tests successfully, run them, and get a coverage report.

**Comment by mtl1979** [comment]
@vinniefalco You are right in that it's possible to write very complex .travis.yml file, but currently it is very low priority and it would take enormous time to keep the complex .travis.yml updated if some build configurations need to be added or changed.

**Comment by vinniefalco** [comment]
There's nothing complex about it, to get a coverage report you only need one additional configuration. Or better yet, just modify one of the existing configurations to also produce coverage data. You don't need coverage for **every configuration**, just one.

**Comment by mtl1979** [comment]
@vinniefalco I don't think you understand how Travis defines configurations... There is no easy way to edit single configuration as all configurations are defined in multi-dimensional matrix that combines all possible choices (compiler, platform, configure flags)

**Comment by vinniefalco** [comment]
Just add an environment variable, say `VARIANT`. In one of your configurations set it to the string "coverage." For all others, leave it empty. Example:
https://github.com/boostorg/beast/blob/develop/.travis.yml#L32

Modify the build script to add the necessary code coverage command line switches, when `VARIANT==coverage`. You need `--coverage` on the compile flags and `--coverage` on the link flags.
https://github.com/boostorg/beast/blob/develop/CMakeLists.txt#L140

Finally, write a simple shell script for running the tests. When `VARIANT==coverage`, invoke codecov as per the documentation and then upload the report:
https://github.com/boostorg/beast/blob/develop/tools/build-and-test.sh#L125

**Comment by mtl1979** [comment]
@vinniefalco We're not stupid, we know how to use coverage with gcc and clang, that doesn't change the fact that it adds too much complexity to workaround limitations and bugs in gcc and clang (we can't use gcc newer than 4.9, or clang older than 3.9.1 with coverage builds) on the build servers. 

You can see the results from the test run I made at https://codecov.io/gh/mtl1979/zlib-ng

**Comment by vinniefalco** [comment]
Well if it is impossible to get coverage information with each CI build then I guess I should close this, thank you for considering it.
