### ISSUE TITLE
NEON instructions not enabled on `armv7-linux-gnueabihf`

### ISSUE THREAD

**Issue by NobodyXu** [zlib-ng/zlib-ng#1280]
When compiling this project on `armv7-linux-gnueabihf` through [rust-lang/libz-sys](https://github.com/rust-lang/libz-sys/blob/main/build_zng.rs) in PR https://github.com/ryankurte/cargo-binstall/pull/150, the [build] failed with:

```
  /usr/lib/gcc-cross/arm-linux-gnueabihf/5/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
   #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
```

I think this is probably a bug in this project, where `mfloat-abi=softfp` or `-mfpu=neon` is not specified.

[build]: https://github.com/ryankurte/cargo-binstall/runs/6667297576?check_suite_focus=true

**Comment by mtl1979** [comment]
It overrides so many cmake variables that it would be useful to know what exactly gets passed to compiler. zlib'ng's CMakeLists.txt does add "-mfloat-abi" to the compiler command-line.

**Comment by NobodyXu** [comment]
> It overrides so many cmake variables that it would be useful to know what exactly gets passed to compiler. zlib'ng's CMakeLists.txt does add "-mfloat-abi" to the compiler command-line.

The [`build.rs`] only overrides:

```
let compact = false;

cmake
        .define("BUILD_SHARED_LIBS", "OFF")
        .define("ZLIB_COMPAT", if compat { "ON" } else { "OFF" })
        .define("ZLIB_ENABLE_TESTS", "OFF")
        .define("WITH_GZFILEOP", "ON");
```

for `armv7-linux-gnueabihf` target.

[`build.rs`]: https://github.com/rust-lang/libz-sys/blob/main/build_zng.rs

**Comment by NobodyXu** [comment]
@mtl1979 Here is the [log](https://github.com/ryankurte/cargo-binstall/runs/6667297576?check_suite_focus=true#step:7:409) of `cmake`.

**Comment by mtl1979** [comment]
@NobodyXu That log doesn't contain command-line passed to compiler... It does however contain error messages that suggest the compiler wasn't detected correctly as incompatible compiler flags have been passed.

**Comment by mtl1979** [comment]
Looking at ARM documentation, it seems -d16 suffix means that the ARMv7 processor doesn't have NEON unit, so NEON support should be disabled in cmake command-line. zlib-ng tries to use NEON if the compiler supports it, but in this case the compiler advertises it supports NEON, but NEON support is still unusable due to targeted processor.

**Comment by NobodyXu** [comment]
I am using [cross](https://github.com/cross-rs/cross/#supported-targets) to do the cross compilation and looking at the [log](https://github.com/ryankurte/cargo-binstall/runs/6667297576?check_suite_focus=true#step:7:412), it seems that it is using `gcc-5.4.0`, which could be the source of error.

**Comment by NobodyXu** [comment]
I will close this as it is probably a bug in `gcc-5.4.0` and the PR https://github.com/ryankurte/cargo-binstall/pull/150 sidestep this problem by removing `armv7-linux-gnueabihf`.
