### ISSUE TITLE
2.0.6: perl test suite is failing

### ISSUE THREAD

**Issue by kloczek** [zlib-ng/zlib-ng#1287]
Looks like with zlib-ng 2.0.6 I'm not able to pass perl test suite because it fails in `./cpan/Compress-Raw-Zlib/t/02zlib.t`, `../cpan/IO-Compress/t/005defhdr.t`, `../cpan/IO-Compress/t/cz-03zlib-v1.t` test units

zlib-ng build using cmake with
```spec
%cmake \
        -D WITH_GZFILEOP=ON \
        -D WITH_MAINTAINER_WARNINGS=OFF \
        -D WITH_NATIVE_INSTRUCTIONS=OFF \
        -D WITH_SANITIZERS=OFF \
        -D ZLIB_COMPAT=ON \
        -D ZLIB_ENABLE_TESTS=ON \
```

More details it is possible to find in https://github.com/Perl/perl5/issues/19566

**Comment by nmoinvaz** [comment]
It is likely the perl tests need to be updated. Often tests from other projects rely on a bit for bit identical deflate stream (to zlib) being produced and we don't make that guarantee. See also #905.

**Comment by kloczek** [comment]
May I ask you please drop that comment in perl ticket as well? .. pleae 😄

**Comment by nmoinvaz** [comment]
Sure. 

One issue is also possibly that zlib-ng does not report 1.2.12 version which we are now fully compatible with and I have opened a PR for that here #1289.
```
#   Failed test at t/02zlib.t line 501.
#          got: 1
#     expected: -3

#   Failed test at t/02zlib.t line 535.
#          got: 1
#     expected: -3

#   Failed test at t/02zlib.t line 1097.
#          got: '18446744072013011631'
#     expected: '2598427311'
# Looks like you failed 3 tests of 353.
```
https://github.com/Perl/perl5/blob/dd834db38c17eed742a7adc0c4baad02341dcd03/cpan/Compress-Raw-Zlib/t/02zlib.t#L528-L538

**Comment by nmoinvaz** [comment]
```
#   Failed test '  CINFO matches'
#   at t/005defhdr.t line 184.
#          got: '7'
#     expected: '5'
```
```
      CINFO (Compression info)
         For CM = 8, CINFO is the base-2 logarithm of the LZ77 window
         size, minus eight (CINFO=7 indicates a 32K window size). Values
         of CINFO above 7 are not allowed in this version of the
         specification.  CINFO is not defined in this specification for
         CM not equal to 8.
```
`CINFO` should be checked that it is <= 7, unless you are explicitly specifying window size when creating the deflate stream. I don't see anywhere where it is setting the window size when creating the stream.

```
#   Failed test '  FCHECK matches'
#   at t/005defhdr.t line 187.
#          got: '1'
#     expected: '9'
```
Because `CINFO` is different I suspect `FCHECK` is not what is expected either. It would be better to do `FCHECK` calculation manually to verify than to rely on fixed value.

**Comment by kloczek** [comment]
@nmoinvaz looking on your comments I'm uessing that all those symptoms says that it is test suite issue and not zlib-ng or .x module code. Am I right? 🤔

**Comment by nmoinvaz** [comment]
I would say it is very likely not a functional issue with zlib-ng.

**Comment by pmqs** [comment]
I have a change in progress to add support for zlib-ng running in either native or compat mode that is (almost) working on my dev box.

I'm using ticket https://github.com/pmqs/Compress-Raw-Zlib/issues/9 to track this work.

**Comment by pmqs** [comment]
This ticket can be closed. Perl support for zlib-ng added in [Compress::Raw::Zlib 2.200](https://github.com/pmqs/Compress-Raw-Zlib/releases/tag/v2.200). Uploaded to CPAN (https://metacpan.org/dist/Compress-Raw-Zlib)

**Comment by nmoinvaz** [comment]
@pmqs did the tests in Perl get updated?

**Comment by pmqs** [comment]
Yes @nmoinvaz  - I've added github workflow to test with all zlib-ng versions from 2.0.0 onwards for both Linux & MacOS. Windows will follow at some point once I figure out how to do it.
