### ISSUE TITLE
z_crc_t is missing from zlib-compat mode

### ISSUE THREAD

**Issue by Jan200101** [zlib-ng/zlib-ng#1296]
zlib-ng does not implement the `z_crc_t` typedef in compat mode resulting in applications like [quazip](https://github.com/stachenov/quazip) not building.

`z_crc_t` was removed in https://github.com/zlib-ng/zlib-ng/commit/4db4cfdb5badc8860f7410732b12c45216d709b3

**Comment by mtl1979** [comment]
It should be enough to define `z_crc_t` as `uint32_t` in zconf.h.in ... We don't need to support compilers that don't have fixed size integer types.
