### ISSUE TITLE
Unexpected CINFO value with compression level 1

### ISSUE THREAD

**Issue by pmqs** [zlib-ng/zlib-ng#1302]
If I run `minideflate` (built with 2.0.6) with a compression level of 1 and  windows bits of 15 I'd expect the zlib header `CINFO` field to be `7`, but it is `5`.

```
$ build/minideflate  -w 15 -1  -c crc32.c | hexdump -C | head
00000000  58 09 d2 d7 52 48 2e 4a  36 36 d2 4b 56 d0 d5 55  |X...RH.J66.KV..U|
```

Compression levels 0 and 1 through 9 have a `CINFO` value of `7` as expected.

With the equivalent test in  zlib I see `CINFO` set to `7` for all compression levels.

Is this defined behaviour?

**Comment by nmoinvaz** [comment]
In 2.0.6 we did have a smaller window size for level 1 which uses a different deflate algorithm.
https://github.com/zlib-ng/zlib-ng/blob/b56a2fd0b126cfe5f13e68ab9090cd4f6a773286/deflate.c#L302-L305

```
      CINFO (Compression info)
         For CM = 8, CINFO is the base-2 logarithm of the LZ77 window
         size, minus eight (CINFO=7 indicates a 32K window size). Values
         of CINFO above 7 are not allowed in this version of the
         specification.  CINFO is not defined in this specification for
         CM not equal to 8.
```

So `13 - 8 = 5`. 

I would say it is expected for 2.0.6, however in `develop` we no longer have this limitation.

**Comment by pmqs** [comment]
Thanks @nmoinvaz 

just checked `develop` & it does indeed use the expected `CINFO`  value of`7`

```
$ build/minideflate  -w 15 -1  -c configure | hexdump -C | head
00000000  78 01 52 56 d4 2f 2d 2e  d2 4f ca cc d3 4f cd 2b  |x.RV./-..O...O.+|
```

I have some  downstream code that tests the `CINFO` value in the zlib header is always  `7` when the window bits option is set to 15. I'll add a special case for `zlib-ng` <= 2.0.6 & Level == 1
