### ISSUE TITLE
Dealing with ZLIBNG_VERNUM format change in downstream code

### ISSUE THREAD

**Issue by pmqs** [zlib-ng/zlib-ng#1303]
I see that the `develop` branch uses a 32-bit encoding for `ZLIBNG_VERNUM` while the 2.0.x releases use a 16-bit encoding

This in `develop`
```
#define ZLIBNG_VERNUM 0x02010000L   /* MMNNRRMS: major minor revision status modified */
```

and this in `2.0.6` 
```
#define ZLIBNG_VERNUM 0x2060
```
I can understand the flexibility that this change adds, but it is a possible source of confusion for downstream code that needs to check `ZLIBNG_VERNUM`.

A  candidate for a short paragraph in the wiki perhaps?

**Comment by nmoinvaz** [comment]
Yes, that change would be a good idea to add to the wiki.

**Comment by nmoinvaz** [comment]
I have documented it here: https://github.com/zlib-ng/zlib-ng/wiki#versioning. Any edits are welcome.
