### ISSUE TITLE
m1 max arch detection problem

### ISSUE THREAD

**Issue by smjs** [zlib-ng/zlib-ng#1315]
On Apple M1 Max the configure script determines the ARCH as arm64 rather than aarch64. That leads to it not configuring in the neon optimisations. The configure script uses:
 gcc -std=c11 -print-multiarch  | sed 's/-.*//g'
to identify the architecture and that returns:
arm64
(the complete string that 'gcc -std=c11 -print-multiarch'  returns is 'arm64-apple-darwin21.5.0')
That causes it to enter the wrong case in the case in the swtich where it configures neon (arm* rather than aarch64).

Compiler is:
gcc --version
Apple clang version 13.1.6 (clang-1316.0.21.2.5)
Target: arm64-apple-darwin21.5.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin

MacOS version:
system_profiler SPSoftwareDataType | grep 'System Version'
      System Version: macOS 12.4 (21F79)

Problem occurs in 2.0.6 and master

**Comment by mtl1979** [comment]
Instead of reordering the tests, I think the best solution is to rewrite contents of `ARCH` before the switch block...

**Comment by smjs** [comment]
I think you also need to modify the check in check_neon_ld4_intrinsics() to:

        if test "$CC_ARCH" = "aarch64" || test "$CC_ARCH" = "aarch64_be" || test "$CC_ARCH" = "arm64"; then

**Comment by mtl1979** [comment]
> I think you also need to modify the check in check_neon_ld4_intrinsics() to:
> 
> ```
>     if test "$CC_ARCH" = "aarch64" || test "$CC_ARCH" = "aarch64_be" || test "$CC_ARCH" = "arm64"; then
> ```

Already did modify that ;)

**Comment by KungFuJesus** [comment]
There are big endian aarch64 implementations floating around?  I've yet to see that, hah.

**Comment by mtl1979** [comment]
@KungFuJesus I thought ARM was dual-endian... it's both little- and big-endian at the same time...

**Comment by KungFuJesus** [comment]
> @KungFuJesus I thought ARM was dual-endian... it's both little- and big-endian at the same time...

I think technically the architecture doesn't explicitly define an endianness one way or the other but I've yet to see a bi-endian or even big endian variant of it in the wild.

**Comment by mtl1979** [comment]
@KungFuJesus Endianess is left for microarchitectures to define... I haven't checked endianess of any of my ARM devices, but I only have heard of 32-bit big-endian ARM devices, but that doesn't prove anything...

**Comment by nmoinvaz** [comment]
This issue should now be resolved in develop branch.
