### ISSUE TITLE
Python2 zlib test fail with zlib-ng compat

### ISSUE THREAD

**Issue by danyspin97** [zlib-ng/zlib-ng#1321]
Hi! I am currently testing zlib-ng in compat mode as zlib provider for openSUSE Tumbleweed. While doing so I am encountering some test failures when zlib-ng doesn't behave exactly like zlib. I think it would be worth discussing if the test should be updated or zlib-ng could follow zlib more closely.

I am building zlib-ng 2.0.6 like this:
```
./configure \
    --zlib-compat \
    --without-optimizations \
    --with-dfltcc-deflate \
    --with-dfltcc-inflate
```

python2 zlib tests failing with the following output ([full build log here](https://build.opensuse.org/package/live_build_log/home:dspinella:zlib-ng-staging/python-base/standard/i586)):
```
 test test_zlib failed -- Traceback (most recent call last):
   File "/home/abuild/rpmbuild/BUILD/Python-2.7.18/Lib/test/test_zlib.py", line 650, in test_wbits
     zlib.decompress(zlib15, 14)
 AssertionError: error not raised
```

The error is happening [here](https://github.com/python/cpython/blob/v2.7.18/Lib/test/test_zlib.py#L650). Snippet from the source code:

```python
    def test_wbits(self):
        co = zlib.compressobj(1, zlib.DEFLATED, 15)
        zlib15 = co.compress(HAMLET_SCENE) + co.flush()
        self.assertEqual(zlib.decompress(zlib15, 15), HAMLET_SCENE)
        self.assertEqual(zlib.decompress(zlib15, 32 + 15), HAMLET_SCENE)
        with self.assertRaisesRegexp(zlib.error, 'invalid window size'):
            zlib.decompress(zlib15, 14)
```

`HAMLET_SCENE` is the string to compress, hardcoded in the test file.

Python2 is currently EOL, but I think it's still important to address this, because it might happen in other applications/libraries.

**Comment by mtl1979** [comment]
Switching to smaller window size is allowed as long as the data fits, so this is not a bug.

**Comment by danyspin97** [comment]
> Switching to smaller window size is allowed as long as the data fits, so this is not a bug.

Then is this a bug in zlib implementation or a breaking change in the latest releases?

I will have a deeper look at the zlib python library to check. Thanks for the answer :)

**Comment by danyspin97** [comment]
After having a look at the zlib python module (which is written in C), I have found the part that is not working correctly ([link](https://github.com/python/cpython/blob/v2.7.18/Modules/zlib/inflate.c#L695):

```c
            len = BITS(4) + 8;
            if (state->wbits == 0)
                state->wbits = len;
            if (len > 15 || len > state->wbits) {
                strm->msg = (char *)"invalid window size";
                state->mode = BAD;
                break;
            }
```

An exception is raised when using zlib and the tests succeed. When using zlib-ng, the exception is not raised and the test fails. It seems to me that this is indeed zlib-ng behaving differently than zlib.

**Comment by nmoinvaz** [comment]
Have you tried the latest develop branch code?

**Comment by danyspin97** [comment]
> Have you tried the latest develop branch code?

Not yet. I'll update the package with the latest develop branch code and report back.

**Comment by nmoinvaz** [comment]
Any word on whether or not the latest develop branch works?

**Comment by danyspin97** [comment]
Hi and sorry for the delay, I was in vacation. I will try the develop branch this week and report back :)

**Comment by nmoinvaz** [comment]
@danyspin97 were you able to try it?

**Comment by danyspin97** [comment]
I have just updated the source. Open Build Service will now rebuild all the packages, including python, but it will take time. I'll come back tomorrow with the new results.

This is the OBS project with a minimal set of packages required to bootstrap a system, if you are interested:

https://build.opensuse.org/project/show/home:dspinella:zlib-ng-staging

Please not that the version still says 2.0.6 but it's the latest develop branch.

**Comment by danyspin97** [comment]
I can confirm that python tests now succeed with the develop branch. Thank you all for your support! :)
