### ISSUE TITLE
cmake: Error due to Content PNG already populated

### ISSUE THREAD

**Issue by sbates130272** [zlib-ng/zlib-ng#1327]
Hi all

I am getting the following error when I perform a second cmake operation with a new set of variables set.

Stephen

batesste@bunbeg:~/zlib-ng/build$ cmake -D WITH_BENCHMARKS=1 -D WITH_BENCHMARK_APPS=1 ..
-- Using CMake version 3.22.1
-- ZLIB_HEADER_VERSION: 1.2.12
-- ZLIBNG_HEADER_VERSION: 2.1.0.devel
-- Arch detected: 'aarch64'
-- Basearch of 'aarch64' has been detected as: 'arm'
-- Architecture-specific source files: arch/arm/arm_features.c;arch/arm/crc32_acle.c;arch/arm/insert_string_acle.c;arch/arm/adler32_neon.c;arch/arm/chunkset_neon.c;arch/arm/compare256_neon.c;arch/arm/slide_hash_neon.c
-- git version: v1.5.5 normalized to 1.5.5
-- Version: 1.5.5
-- Performing Test HAVE_STD_REGEX -- success
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Symbol prefix: 
CMake Error at /usr/share/cmake-3.22/Modules/FetchContent.cmake:1136 (message):
  Content PNG already populated in /home/batesste/zlib-ng/build/_deps/png-src
Call Stack (most recent call first):
  test/benchmarks/CMakeLists.txt:62 (FetchContent_Populate)

-- Configuring incomplete, errors occurred!
See also "/home/batesste/zlib-ng/build/CMakeFiles/CMakeOutput.log".
See also "/home/batesste/zlib-ng/build/CMakeFiles/CMakeError.log".

**Comment by nmoinvaz** [comment]
If you remove 
```
FetchContent_GetProperties(PNG)

if(NOT PNG_POPULATED)
    FetchContent_Populate(PNG)
endif()
```
.. from `test/benchmarks/CMakeLists.txt` does it work for you?

**Comment by sbates130272** [comment]
@nmoinvaz yes that does work.

**Comment by nmoinvaz** [comment]
This is now resolved in develop branch.

**Comment by sbates130272** [comment]
Thanks @nmoinvaz!
