### ISSUE TITLE
Problem linking against kmod and Qt-5.9.2

### ISSUE THREAD

**Issue by sfroberg** [zlib-ng/zlib-ng#136]
Good day

Im currently in process of cross-compiling system for Raspberry PI 3 with 
buildroot (https://buildroot.org/)  and when linking against zlib-ng (I build it with "--zlib-compat --neon --acle" ) I encountered few things and also have few questions:

1. kmod package complains about missin gzFile type. Commenting out WITH_GZFILEOP from zconf.h & zlib.h helped. I noticed that vanilla zlib.h and zconf.h does not have WITH_GZFILEOP at all, so why was it added ?

2. Qt-5.9.2 QByteArray uses compress/uncompress functions but they nag about pointer mismatch. It expected uLong for length arguments like in original zlib.h but I understand that size_t is the standard way to handle length argument. So who should patch this (Qt? vanilla zlib.h ? ) ?

3. The --zlib-compat configure switch is needed so that packages expecting Zlib API will build correctly right?

4. What is the lowest ARM arch/cpu that zlib-ng should work? Would it example work with Raspberry PI Zero W that has Arch/CPU of: ARMv6Z / ARM1176JZF-S ?
(After several tries, I have zlib-ng currently compiled for 32-bit mode of ARMv8-A / Cortex-A53 with following gcc flags: -march=armv8-a+crc --mfpu=crypto-neon-fp-armv8 --mtune=cortex-a53 )

Best Regards
-S-

**Comment by mtl1979** [comment]
1. This will be fixed later when we isolate private defines out of zlib.h
2. Qt 5.9 is broken in many ways, you need to use temporary variable until this is fixed in zlib-ng
3. Yes
4. Some features currently require ARMv7 or ARMv8, but if you disable them, you can try to compile.

**Comment by sfroberg** [comment]
@mtl1979  Thank you! :-)

**Comment by mtl1979** [comment]
@sfroberg removing WITH_GZFILEOP tests from zlib.h and zconf.h is actually part of what we are currently working on, so you can test the code on "renamelib" branch when the patch is merged in.
