### ISSUE TITLE
Debian package before Debian 12 freeze

### ISSUE THREAD

**Issue by Neustradamus** [zlib-ng/zlib-ng#1369]
It is possible to add zlib-ng (and same time for minizip-ng) in Debian before the Debian 12 freeze?

Thanks in advance.

**Comment by mtl1979** [comment]
We don't plan release dates of zlib-ng based on freeze dates of any Linux distribution... Next minor release of zlib-ng will have small number of bug fixes, but next major release will have quite a lot of changes and most likely will not be ready before the freeze of Debian 12.

**Comment by todd-richmond** [comment]
any chance of more regular releases? 2.0.6 came out > 1 year ago and many significant improvements since, but no one can use them w/o picking a random git hash without any guarantee of stability. Every 6 months would be helpful

**Comment by okias** [comment]
Currently it's too late for `bookworm`, but there is ITP https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1002056

**Comment by Neustradamus** [comment]
Debian 12 has been released:
- https://www.debian.org/News/2023/20230610

**Comment by nmoinvaz** [comment]
zlib-ng 2.1.3 was released on Jun 29.
