### ISSUE TITLE
MSVC warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)

### ISSUE THREAD

**Issue by phprus** [zlib-ng/zlib-ng#1389]
Warning ``inflate.c(1356,9): warning C4334: '<<': result of 32-bit shift implicitly converted to 64 bits (was 64-bit shift intended?)`` introduced in commit 3eab3173ac7d1d53457452f3cd1eaeea5b2d43df

This warning is present in CI output:
https://github.com/zlib-ng/zlib-ng/actions/runs/3686988352/jobs/6239982515#step:12:37

cc @iii-i

**Comment by mtl1979** [comment]
Fixed in #1377...

**Comment by dzenanz** [comment]
I encounter the same issue too.
