### ISSUE TITLE
Please fix zlib_name_mangling mess

### ISSUE THREAD

**Issue by pps83** [zlib-ng/zlib-ng#1400]
Instead of having two files (`zlib_name_mangling-ng.h.in` and `zlib_name_mangling.h.in`) wouldn't that be beneficial to have a single file `zlib_name_mangling.h` so that instead of having stuff like 
```
...
#define _dist_code            @ZLIB_SYMBOL_PREFIX@_dist_code
...
```
that uses an external step of preprocessing/replacement to generate `zlib_name_mangling.h`+`zlib_name_mangling-ng.h` zlib-ng could have `zlib_name_mangling.h` checked in with such contents:
```
#ifdef ZLIB_SYMBOL_PREFIX
#define ZLIB_PREFIX(x) ZLIB_SYMBOL_PREFIX ## x
...
#define _dist_code                  ZLIB_PREFIX(_dist_code)
...
#define zng_dist_code               ZLIB_PREFIX(zng__dist_code)
...
```

Then `ZLIB_SYMBOL_PREFIX` could be defined by the project (that builds zlibng or uses it), or it could be defined in `zconf.h` or whatever equivalent is used now.

**Comment by mtl1979** [comment]
Using macros inside preprocessor defines would cause issues with evaluation order of the preprocessor. It's supposed to be dumb-proof. Generally anything that is specified on command-line, can be redefined in any header that is included before the mangling header and that can cause linker failures. String substitution works best for anything that is defined during configure stage (either `configure` or first run of cmake).

**Comment by pps83** [comment]
> Using macros inside preprocessor defines would cause issues with evaluation order of the preprocessor.

Please explain what you mean? It seems that even some c files are generated.

> Generally anything that is specified on command-line, can be redefined in any header that is included before the mangling header and that can cause linker failures.

Yes, that's why `#define ZLIB_SYMBOL_PREFIX abc_` could be part of zconf.h which is supposed to be included by each file of the project.

**Comment by mtl1979** [comment]
Nested preprocessor macros and defines use lazy evaluation, which means they are evaluated from bottom to top starting from the line that use the preprocessor token. Literal preprocessor defines are technically string substitutions that work from top to bottom instead. 

In most cases developers should try to avoid using preprocessor tokens that can be substrings of other preprocessor tokens. This is why we use `zng_` and `z_` prefixes directly in some files. For example, Windows is notoriously known for defining and using very common tokens internally causing issues if any third-party library or program tries to use the same tokens for other purposes.

**Comment by pps83** [comment]
I've done quite a bit of heavy macro preprocessor mumbo-jumbo, yes, it has some catches/issues, but zlib-ng use case is fairly basic imo. Can you show a simple case that really shows the issue you are trying to describe. All that lazy evaluation is a non-issue imo if done properly in the project.

Not exactly sure, perhaps, you are trying to describe an issue that this solves:

instead of:
```#define ZLIB_PREFIX(x) ZLIB_SYMBOL_PREFIX ## x```
it could be:
```
#define ZLIB_PREFIX_(a,b) a ## b
#define ZLIB_PREFIX(x) ZLIB_PREFIX_(ZLIB_SYMBOL_PREFIX, x)
```
?

**Comment by mtl1979** [comment]
We would still need to use string substitution to inject value for `ZLIB_SYMBOL_PREFIX` as that can't be passed from command-line to compiler. In worst case, it would trigger rebuild of unrelated files unless we limit the scope for the command-liine parameter and that would just make things even messier. Everything would also need to be duplicated for configure and cmake.

**Comment by pps83** [comment]
Yes, I tried to enable prefix and compare versions with/without. Actual code gets diffs, so, perhaps the change would be not as straightforward as I initially thought.
One other thing. I did compare `zlib.h` vs `zlib-ng.h` and zlib-ng.h uses `int32_t` all over the place instead of `int`. This is **very** strange. Generic code shouldn't use these types like that, it's just not normal. Should just use int, and use `intXX_t` types where you need specific size only (like serialization etc).

**Comment by mtl1979** [comment]
The real issue is consistency.... Using "long" or "long long" will break the code for Windows and mixing `int64_t` and `int` makes the code less readable...

Also, when moving data between general-purpose registers and vector registers, the bit-widths must be exact match, not just smaller or equal size, otherwise compiler will throw error on some architectures where implicit cast is disabled.
