### ISSUE TITLE
TZCNT performance question

### ISSUE THREAD

**Issue by phprus** [zlib-ng/zlib-ng#1419]
A ``__builtin_ctz*`` emulation has been written for Microsoft Visual C++:
https://github.com/zlib-ng/zlib-ng/blob/d144fc06bfa575ddfa8143cedd0873f36a2c7568/fallback_builtins.h#L15-L25

For x86 there is a check for the presence of the ``tzcnt`` instruction. In this case, even if the processor does not support ``tzcnt``, the code will execute correctly and return the correct value (https://stackoverflow.com/questions/43880227/why-does-tzcnt-work-for-my-sandy-bridge-processor).

I don't understand if the overhead of the ``if (x86_cpu_has_tzcnt)`` condition is really less than the performance difference of the real ``tzcnt`` and the old ``rep bsf``?
Maybe it makes sense to completely remove this runtime check and for x86 always call ``tzcnt``? This can simplify the dynamic dispatch code by reducing the number of cpu features flags in global variables.

cc @Dead2, @mtl1979 , @pps83

**Comment by nmoinvaz** [comment]
I've done benchmark tests in the past using deflatebench and removed that if statement and it made no noticeable difference. That if statement seems to be a red herring that a lot of people look at when looking for performance improvements. You can always put it in zlib-ng's Google benchmark code and see if it makes a difference for you. My tests were not isolated to that single function, but involved all compression/decompression.

Here is the one commit https://github.com/zlib-ng/zlib-ng/pull/113/files which is reverted. The comment there says that `tzcnt` is equivalent to `bsf` on Intel machines, but `tzcnt` is faster on AMD. My tests used an Intel machine.

> Maybe it makes sense to completely remove this runtime check and for x86 always call tzcnt?

That is what the `X86_NOCHECK_TZCNT` option allows you to do for those people who are concerned about it.

**Comment by mtl1979** [comment]
There is quite a few instructions that behave differently on AMD and Intel processors. To be compatible with processors of both manufacturers, the compiler sometimes needs to emit extra instructions... 

When people compile for the current processor, the compiler can eliminate certain instructions that are needed in generic build. Most processors are smart enough to know that if certain jump is always taken, the next instruction is prefetched correctly and there is no noticeable delay.

**Comment by phprus** [comment]
@nmoinvaz 
Thank you for your opinion!

My question is a continuation of the discussion in PR #1405

If all cpu features checks are localized in the ``init_functable`` function, then all of this can be made truly thread-safe.

https://github.com/zlib-ng/zlib-ng/blob/d144fc06bfa575ddfa8143cedd0873f36a2c7568/functable.c#L14

Now there are two problem places:
1) ``tzcnt`` conditions
2) conditions in file:
https://github.com/zlib-ng/zlib-ng/blob/d144fc06bfa575ddfa8143cedd0873f36a2c7568/arch/x86/crc32_fold_pclmulqdq_tpl.h#L83


I have some ideas how to change the code in the ``crc32_fold_pclmulqdq_tpl.h`` file and I'm testing them now.

And I would suggest removing the ``tzcnt`` check if it does not bring performance losses. The situation is complicated by the fact that I have very few Windows computers and testing is difficult for me.

**Comment by nmoinvaz** [comment]
I can definitely see the benefit of keeping all feature flags isolated to a single file; what you are trying to do is worthwhile. The only other way that I can think of would be to have a `functable.builtin_ctz` that used `tzcnt` if the CPU had BMI1 flag enabled or used `BitScanForward` if not. But that has its own performance drawbacks because it can't be inlined.

**Comment by phprus** [comment]
@mtl1979 
> There is quite a few instructions that behave differently on AMD and Intel processors.

We don't need to look at many instructions. We only need ``tzcnt``.
If this check can be removed without loss of performance, it will allow us to simplify the code in ``functable.c``. 

We can make this code completely thread-safe without TLS and/or support processors with different features on different cores with TLS.

**Comment by nmoinvaz** [comment]
It almost sounds like a better way to do it would be to have a compile-time option like `FORCE_TZCNT` that would force the use of `tzcnt`, but in all other instances use `BitScanForward`, then we can dump the cpu flag. It would just be required that the user would be running on hardware that supported it.

Like I said, during my tests I didn't notice any difference so I have no strong opinion regarding keeping it or taking it out. It is something we get a lot of questions about. It should probably be Google benchmarked on Intel and AMD, but I don't have an AMD machine. Even so I have my doubts about whether or not there is a real benefit.

**Comment by mtl1979** [comment]
> @mtl1979
> 
> > There is quite a few instructions that behave differently on AMD and Intel processors.
> 
> We don't need to look at many instructions. We only need `tzcnt`. If this check can be removed without loss of performance, it will allow us to simplify the code in `functable.c`.

`tzcnt` is one of them... The performance difference is a lot bigger on AMD processors. This means any benchmarking has to be done on processor that has the performance gain.

**Comment by phprus** [comment]
@nmoinvaz 

> The only other way that I can think of would be to have a functable.builtin_ctz that used tzcnt if the CPU had BMI1 flag enabled or used BitScanForward if not

Yes, this way will disable inlining, which is bad for a single commands function.

> It would just be required that the user would be running on hardware that supported it.

``tzcnt`` will work on processors without ``tzcnt`` (BMI1)!
Why it works is explained here: https://stackoverflow.com/questions/43880227/why-does-tzcnt-work-for-my-sandy-bridge-processor

It's only a performance issue.

**Comment by mtl1979** [comment]
> It almost sounds like a better way to do it would be to have a compile-time option like `FORCE_TZCNT` that would force the use of `tzcnt`, but in all other instances use `BitScanForward`, then we can dump the cpu flag. It would just be required that the user would be running on hardware that supported it.

We already have compile-time option to force using `tzcnt`... Only thing left is to flip the logic so that it never checks the processor support and use the fallback path always... But that kinda defeats the definition of zlib-ng being optimized for modern processors.

**Comment by pps83** [comment]
> I don't understand if the overhead of the `if (x86_cpu_has_tzcnt)` condition is really less than the performance difference of the real `tzcnt` and the old `rep bsf`?

I've mentioned long time ago (relevant discussion ctlz in: https://github.com/zlib-ng/zlib-ng/pull/570), but I was absolutely shocked with that code. Conditional branch there is a huge penalty imo, absolutely outweighs any benefit (if any) of tzcnt over bsf. Gladly, there is now a way to force TZCNT with `X86_NOCHECK_TZCNT`, I'd never ever allow such branch for a single instruction. In my code/branch I do force it. I totally flipped when I saw that. I'm still shocked when I think about it, makes me think if I should be touching zlib-ng.

**Comment by mtl1979** [comment]
Even I wouldn't touch zlib-ng yet... There is a lot of bad code, but the fact is that it's not my project... For many years nothing really got merged because my and @dead2 branches diverged too much... But in the end we just started from scratch and things started to go forward...

**Comment by phprus** [comment]
@mtl1979

> tzcnt is one of them... The performance difference is a lot bigger on AMD processors.

Could you please do tests on AMD and Windows (Visual C++ build)?

if
> zlib-ng being optimized for modern processors.

we can remove this runtime check, because BMI1 is available in AMD's Jaguar, Piledriver and newer processors, and in Intel's Haswell and newer processors. These processors were released 10 years ago.

On older processors, the code will continue to work, but with unknown (untested) performance.

**Comment by pps83** [comment]
I actually use [libdeflate](https://github.com/ebiggers/libdeflate), much cleaner and faster overall than any zlib/zlib-ng fork. I do keep zlib-ng as a replacement for zlib for testing/verification.

**Comment by pps83** [comment]
> I've done benchmark tests in the past using deflatebench and removed that if statement and it made no noticeable difference. That if statement seems to be a red herring that a lot of people look at when looking for performance improvements. You can always put it in zlib-ng's Google benchmark code and see if it makes a difference for you. My tests were not isolated to that single function, but involved all compression/decompression.

Most likely, the code that uses tzcnt is simply doesn't do much (e.g. it's a tiny fraction from overall compression/decompression load). Still, code that does a branch for a single instruction is huge sign of smell regardless if it has any perf impact. If there is none, it should just do the old bsf way. I recall that the code in zlib uses bsf without checks for zero input or something like that.

**Comment by mtl1979** [comment]
> @mtl1979
> 
> > tzcnt is one of them... The performance difference is a lot bigger on AMD processors.
> 
> Could you please do tests on AMD and Windows (Visual C++ build)?

I don't have AMD hardware currently...

> 
> if
> 
> > zlib-ng being optimized for modern processors.
> 
> we can remove this runtime check, because BMI1 is available in AMD's Jaguar, Piledriver and newer processors, and in Intel's Haswell and newer processors. These processors were released 10 years ago.

Obviously trying to support 10 years old Intel/AMD processors doesn't make much sense... Except that I run ~20 years old processor that outperforms my 3 year old x86-64 processor by factor of 10... Gotta love when I have to use Debian, because Ubuntu has long time ago stopped supporting my processor.

**Comment by phprus** [comment]
>  I recall that the code in zlib uses bsf without checks for zero input or something like that.

There are checks for non zero when calling ``__builtin_ctz*``, since the ``__builtin_ctz*`` functions in GCC require a non-zero argument.

**Comment by mtl1979** [comment]
There's right time for every discussion or change... Maybe now the long-time contributors could revote on simplifying this code... Then anyone can make a pull request for the change.
