### ISSUE TITLE
"modern cmake"

### ISSUE THREAD

**Issue by MrSapps** [zlib-ng/zlib-ng#142]
It appears that "modern" cmake uses "exported" targets these days...

Is there any plans to "upgrade" this project to cmake 3.X? To use these features?

**Comment by mtl1979** [comment]
Not all required operating systems have cmake 3.0 yet... So until those repositories are updated, we have to stick with the current minimum version requirement. Keeping another configuration file for cmake 3.x and later would double the work when something gets changed in the source code.

**Comment by MrSapps** [comment]
I see, any clue which platforms are lagging in cmake versions?

**Comment by mtl1979** [comment]
Yup... But have to dig that information from old tickets or wait for @Dead2 to answer if he remembers better ;)

**Comment by MrSapps** [comment]
Eh I'll close this for now then I guess

**Comment by BotellaA** [comment]
Any plan on exporting CMake targets? CMake3 is now very common.
