### ISSUE TITLE
gzopen* et all are needed

### ISSUE THREAD

**Issue by vinpublic** [zlib-ng/zlib-ng#143]
libxml and many other software need gzopen* functions and friends:
./.libs/libxml2.so: undefined reference to `gzopen64'
./.libs/libxml2.so: undefined reference to `gzwrite'
./.libs/libxml2.so: undefined reference to `gzdirect'
./.libs/libxml2.so: undefined reference to `gzclose'
./.libs/libxml2.so: undefined reference to `gzdopen'
./.libs/libxml2.so: undefined reference to `gzread'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:1119: xmllint] Error 1
make[2]: *** Waiting for unfinished jobs....
./.libs/libxml2.so: undefined reference to `gzopen64'
./.libs/libxml2.so: undefined reference to `gzwrite'
./.libs/libxml2.so: undefined reference to `gzdirect'
./.libs/libxml2.so: undefined reference to `gzclose'
./.libs/libxml2.so: undefined reference to `gzdopen'
./.libs/libxml2.so: undefined reference to `gzread'
collect2: error: ld returned 1 exit status

zlib-ng is built with --zlib-compat.

**Comment by mtl1979** [comment]
I checked on both my operating systems and those symbols are correctly defined. What operating system and compiler version did you use?

**Comment by vinpublic** [comment]
@mtl1979 Source Mage GNU/Linux, x86_64, gcc 7.2.0.

what branch are you using? develop? in develop zlib.h has these functions commented.

**Comment by mtl1979** [comment]
develop, gcc 6.3.0

**Comment by vinpublic** [comment]
@mtl1979 still, [this line](https://github.com/Dead2/zlib-ng/blob/860d7a30f20f0c1e71bc0d8b0d84b88293326f6c/zlib.h#L1273) is commented, is it not?

**Comment by mtl1979** [comment]
@vinpublic yes, but it's not mentioned in the linker output as required symbol...

**Comment by vinpublic** [comment]
@mtl1979 so, what CPPFLAGS one should use to compile stuff like libxml?

**Comment by mtl1979** [comment]
I used (on Ubuntu 14.04):
> CPPFLAGS="-I/mnt/c/build/git/zlib-ng -DWITH_GZFILEOP" LDFLAGS=-L/mnt/c/build/git/zlib-ng CC=gcc-7 ./configure

**Comment by vinpublic** [comment]
@mtl1979 I had to use these -DWITH_GZFILEOP -DZLIB_COMPAT -DX86_64 -DZ_LARGE64 for libxml2, but it doesn't work for others, such as xorg-server, which says:
  CCLD     Xorg
/usr/lib/libfontenc.so: undefined reference to `gzopen'
/usr/lib/libfontenc.so: undefined reference to `gzclose'
/usr/lib/libfontenc.so: undefined reference to `gzgetc'
collect2: error: ld returned 1 exit status
make[4]: *** [Makefile:805: Xorg] Error 1

is your system 32 bit? seems like 64 bit issue only.

**Comment by mtl1979** [comment]
My system is 64-bit... If you need that many defines, most likely you have two conflicting installations of zlib and some of the flags to decide which one to use are missing. You have to use absolute paths to zlib-ng for both preprocessor and linker (CPPFLAGS and LDFLAGS).

**Comment by vinpublic** [comment]
@mtl1979 no, not my case. manual installation seemed to fix that. however, found runtime bugs which were fixed by [this crude patch](https://gist.github.com/vinpublic/fe773926ed892cea971dc7317ff7c6ba).

The bugs were about library version mismatch and caused segfaults in Xorg, firefox, kodi, etc.

**Comment by mtl1979** [comment]
@vinpublic That's a clear sign you are mixing files from two incompatible versions of zlib...

**Comment by vinpublic** [comment]
anyway, closing this issue. sorry for bothering. too weird case in source based distribution.
