### ISSUE TITLE
zlib compat version is still `1.2.11.zlib-ng` ?

### ISSUE THREAD

**Issue by abcfy2** [zlib-ng/zlib-ng#1452]
Glad to here zlib-ng 2.0.7 released, but why zlib compat version is still `1.2.11.zlib-ng` ?

I remembered zlib-ng already support zlib 1.2.13 API right ? Should we set this version string to `1.2.13.zlib-ng` ?

**Comment by nmoinvaz** [comment]
2.0.7 is a bug fix release for 2.0.6. The 2.0.6 is compatible with zlib 1.2.11. The `dev` branch should be compatible with zlib 1.2.13. There is no release yet that targets newer version of zlib.

**Comment by abcfy2** [comment]
Got it. Thanks.
