### ISSUE TITLE
Language bindings?

### ISSUE THREAD

**Issue by rhpvorderman** [zlib-ng/zlib-ng#1456]
I wonder if there is a comprehensive list of language bindings for zlib-ng somewhere. Obviously C and C++ can use the headers directly. 
If there is a list, I would like to get https://github.com/pycompression/python-zlib-ng on it. This is a simple port of python's zlib module to use zlib-ng. It can function as a drop-in replacement. I think this is quite useful as it allows people who use python to use zlib-ng without needing to know how to write C or C++ or even to compile it. 

I know there are also rust bindings as the crabz program uses them. These could be included on the list as well.

**Comment by nmoinvaz** [comment]
We can start a section in the GitHub Wiki.

**Comment by KungFuJesus** [comment]
There are motivations to use the zlib-ng's non-compat API, I'm sure.  But I will say, if you're just looking to drop zlib-ng in place of zlib, LD_PRELOAD'ing the library is enough to do so.  Writing a new binding for something that's 100% API compatible might be overkill, unless there's a specific feature you're extracting from zlib-ng that the original bindings to zlib weren't already.

**Comment by gcflymoto** [comment]
@rhpvorderman great idea! I would love to see a section on ports that are using the **new** API, as I am not sure how even to search the web for such ports. For example, is there a version of pigz that supports the new API? we're rebuilding pigz with zlib-ng in compatibility mode.

**Comment by rhpvorderman** [comment]
@gcflymoto I think you don't need to search the web. When such a list is created, anyone who uses the new API would like to be on it to promote visibility for their project. It is a bit of a n=1 example, but I created the python bindings for zlib-ng and came here looking for a list.

**Comment by nmstoker** [comment]
@nmoinvaz is this suitable?

* [Language Bindings](https://github.com/zlib-ng/zlib-ng/wiki/Language-Bindings)

**Comment by nmoinvaz** [comment]
Yeah that looks great 👍🏼

**Comment by rhpvorderman** [comment]
@nmstoker Awesome! Thanks for putting python-zlib-ng on the list.
