### ISSUE TITLE
Detect Arch Malfunctioning

### ISSUE THREAD

**Issue by atyshka** [zlib-ng/zlib-ng#1462]
The detect arch script is malfunctioning for me on a fresh installation of Ubuntu 20.04. Here is the output:
```
-- Using CMake version 3.16.3
-- ZLIB_HEADER_VERSION: 1.2.11
-- ZLIBNG_HEADER_VERSION: 2.0.6
-- Arch detected: 'Change Dir: /home/alex/kinect-driver/build/_deps/zlib-build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/make cmTC_147f8/fast && /usr/bin/make -f CMakeFiles/cmTC_147f8.dir/build.make CMakeFiles/cmTC_147f8.dir/build
make[1]: Entering directory '/home/alex/kinect-driver/build/_deps/zlib-build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_147f8.dir/detect-arch.c.o
/usr/bin/c89-gcc   -std=c99 -o CMakeFiles/cmTC_147f8.dir/detect-arch.c.o   -c /home/alex/kinect-driver/build/_deps/zlib-src/cmake/detect-arch.c
c89-gcc called with non ANSI/ISO C option -std=c99
make[1]: *** [CMakeFiles/cmTC_147f8.dir/build.make:66: CMakeFiles/cmTC_147f8.dir/detect-arch.c.o] Error 1
make[1]: Leaving directory '/home/alex/kinect-driver/build/_deps/zlib-build/CMakeFiles/CMakeTmp'
make: *** [Makefile:121: cmTC_147f8/fast] Error 2

'
```
Is the problem that the c89 compiler doesn't understand the c99 flag? I'm not sure why the c89 compiler is being invoked since /usr/bin/c99-gcc is also present.

**Comment by userdocs** [comment]
Before anything else, the latest release is `2.0.7` and your issue shows `-- ZLIBNG_HEADER_VERSION: 2.0.6`

Have you tried with the latest release?

https://github.com/zlib-ng/zlib-ng/releases/tag/2.0.7

**Comment by atyshka** [comment]
Zlib is a recursive dependency in my project so I'm not using the latest version. I was able to force my main project to use a newer gcc and the issue was resolved. However I might suggest a less brittle solution for detecting the architecture as in #1313, I know cross-compiling is a bit challenging though.
