### ISSUE TITLE
functable atomics

### ISSUE THREAD

**Issue by grooverdan** [zlib-ng/zlib-ng#147]
Question that I got hinted at; Given writing to a function pointer isn't guaranteed to be atomic, does the functable implementation need to wrap these retrieval/updatein atomic acquire/store?

Arguing that two parallel initializations will write the same value and therefore be the same value doesn't detract that 
a) the function pointer may be called where 1/2 its address in a different function.
b) the intermediate state of a pointer is probably undefined while a store operation is occurring.

**Comment by mtl1979** [comment]
it is very unlikely that high 32-bits of two functions of same small library are different. There is no atomic read/writes anywhere in either zlib or zlib-ng as it's inherently single-threaded and such not considered thread-safe.

**Comment by nmoinvaz** [comment]
@Dead2 I think this issue can be closed now.
