### ISSUE TITLE
Vcpkg: zlib-ng with compat feature

### ISSUE THREAD

**Issue by netcorefan1** [zlib-ng/zlib-ng#1471]
Hello,
I want to inform all that I submitted a [pull request](https://github.com/microsoft/vcpkg/pull/30937) in the official vcpkg repo in order to add support for compatibility mode as a feature.
Unfortunately is not as easy as i thought, therefore suggestions and ideas are welcome.
Thanks

**Comment by Dead2** [comment]
I don't think we have anyone that can really help much with vcpkg issues, and it looks like an issue on their end, not ours.
