### ISSUE TITLE
The zng_ functions are not available in the static library

### ISSUE THREAD

**Issue by powturbo** [zlib-ng/zlib-ng#1473]
The zng_* functions are generated in the shared library but not in the static library libz-ng.a when compiled without any parameter (ZLIB_COMPAT=OFF).

**Comment by mtl1979** [comment]
Please attach copy of output from command "nm -B libz-ng.a" and full command-line and output of both cmake steps.

**Comment by powturbo** [comment]
I've redone the compiles and tests, it's working now.
