### ISSUE TITLE
zlib.h does not define z_size_t

### ISSUE THREAD

**Issue by haampie** [zlib-ng/zlib-ng#1485]
Some projects seem to depend on a define of `z_size_t` in `zlib.h`, for example here:

https://github.com/CODARcode/MGARD/blob/393ba508a2205d250d61fb8728cac3e7f733c76d/src/format.cpp#L182

but zlib-ng doesn't define this, even though the comment talks about it:

https://github.com/zlib-ng/zlib-ng/blob/1c2698f9be19a8d837a83d2a08e938f22c3f3202/zlib.h.in#L1403-L1409

Grepping gives no other results:

```c
$ grep z_size_t -r .
./include/zlib.h:   defines size_t, then z_size_t is identical to size_t.  If not, then z_size_t
```

Should it be defined (and used) in `zlib.h`?

**Comment by mtl1979** [comment]
Stock zlib has inconsistent use of `z_size_t` that introduce possible integer overflows and as such it's not used in externally visible headers in zlib-ng. We are waiting for Mark Adler to fix the remaining issues in zlib API before fixing in zlib-ng.
