### ISSUE TITLE
Question about benchmark

### ISSUE THREAD

**Issue by ZhaoyangJoker** [zlib-ng/zlib-ng#1501]
**When compression level  is bigger than 2, the advantage of zlib-ng over zlib in compression speed becomes very small。

Here is my machine information and test results。Is this result correct？**

CPU INFO:
model name      : Intel(R) Xeon(R) Gold 6266C CPU @ 3.00GHz
cpu cores       : 4
processor       : 0~7
clflush size    : 64
cache_alignment : 64
cpu MHz         : 3000.000
cache size      : 30976 KB

System info:
Linux Rbj4a-bi-32-236-3 4.18.0-147.5.1.2.h340.eulerosv2r9.x86_64

Compiler info:
Thread model: posix
Supported LTO compression algorithms: zlib
gcc version 10.2.0 (GCC)

The result:

Zlib-ng with zlib-ng's minigzip:
OS: Linux 4.18.0-147.5.1.2.h340.eulerosv2r9.x86_64 #1 SMP Sat Jan 30 09:00:44 UTC 2021 x86_64
CPU: x86_64
Tool: minigzip Size: 140,328 B
Levels: 0-9
Runs: 200        Trim worst: 120

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 0    100.008%      0.050/0.057/0.062/0.003        0.051/0.065/0.070/0.004      535,075,728
 1     54.165%      1.747/1.765/1.773/0.006        0.657/0.688/0.696/0.008      153,422,996
 2     43.877%      1.545/1.571/1.579/0.006        0.325/0.341/0.347/0.005       62,140,932
 3     42.381%      1.511/1.522/1.527/0.004        0.245/0.254/0.258/0.003       46,684,570
 4     41.665%      1.503/1.514/1.519/0.004        0.205/0.213/0.218/0.003       39,338,830
 5     41.211%      1.727/1.740/1.746/0.004        0.198/0.211/0.215/0.003       38,910,121
 6     41.036%      1.718/1.734/1.739/0.005        0.160/0.173/0.178/0.004       32,287,513
 7     40.784%      1.801/1.810/1.814/0.003        0.130/0.140/0.143/0.003       25,671,718
 8     40.707%      1.753/1.762/1.766/0.003        0.097/0.104/0.108/0.003       19,217,360
 9     40.419%      2.087/2.097/2.102/0.004        0.097/0.103/0.106/0.002       19,081,493

 avg1  48.625%                        1.557                          0.229
 avg2  54.028%                        1.730                          0.255
 tot                               1245.704                        183.425      971,831,261
 

Zlib with zlib's minigzip:
OS: Linux 4.18.0-147.5.1.2.h340.eulerosv2r9.x86_64 #1 SMP Sat Jan 30 09:00:44 UTC 2021 x86_64
CPU: x86_64
Tool: minigzip Size: 123,024 B
Levels: 1-9
Runs: 200        Trim worst: 120

 Level   Comp   Comptime min/avg/max/stddev  Decomptime min/avg/max/stddev  Compressed size
 1     44.167%      3.907/3.933/3.945/0.008        0.971/1.002/1.010/0.008      125,104,818
 2     43.321%      2.084/2.103/2.110/0.005        0.470/0.484/0.491/0.006       61,353,658
 3     42.636%      1.866/1.878/1.884/0.005        0.358/0.370/0.376/0.004       46,965,870
 4     41.482%      1.812/1.828/1.835/0.006        0.303/0.314/0.319/0.004       39,166,120
 5     41.218%      1.960/1.977/1.983/0.005        0.301/0.311/0.315/0.003       38,917,572
 6     40.815%      2.365/2.380/2.387/0.005        0.253/0.264/0.269/0.004       32,113,714
 7     40.631%      3.208/3.221/3.228/0.006        0.206/0.216/0.220/0.003       25,575,100
 8     40.509%      3.852/3.864/3.869/0.004        0.150/0.160/0.164/0.003       19,123,707
 9     40.493%      4.169/4.180/4.186/0.004        0.151/0.160/0.163/0.003       19,116,525

 avg1  41.697%                        2.818                          0.364
 tot                               2029.050                        262.369      407,437,084

**Comment by mtl1979** [comment]
I don't see any problem in benchmarks you posted. 
On level 3, zlib-ng takes average of 1.522 and zlib takes 1.878.
On level 9, zlib-ng takes average of 2.097 and zlib takes 4.180.

**Comment by ZhaoyangJoker** [comment]
@mtl1979 Thank you ！
I have one more question，why the improvement of level 5 is worse than level 3 and level 9
On level 1, zlib-ng takes average of 1.765 and zlib takes 3.933.
On level 9, zlib-ng takes average of 2.097 and zlib takes 4.18
On level 5, zlib-ng takes average of 1.740 and zlib takes 1.977

**Comment by mtl1979** [comment]
> @mtl1979 Thank you ！
> I have one more question，why the improvement of level 5 is worse than level 3 and level 9
> On level 1, zlib-ng takes average of 1.765 and zlib takes 3.933.
> On level 9, zlib-ng takes average of 2.097 and zlib takes 4.18
> On level 5, zlib-ng takes average of 1.740 and zlib takes 1.977

It highly depends on data being compressed. Level 5 doesn't really use very aggressive parameters.
