### ISSUE TITLE
the relation of ZLIB_COMPAT and WITH_GZFILEOP

### ISSUE THREAD

**Issue by richael02** [zlib-ng/zlib-ng#152]
I'm wondering about the relation of ZLIB_COMPAT and WITH_GZFILEOP. DOES any of the two depend on the other?

**Comment by mtl1979** [comment]
As far as I have understood enabling ZLIB_COMPAT implies enabling WITH_GZFILEOP, but not the other way around.

**Comment by richael02** [comment]
So I don't know why using ZLIB_COMAPT to enable WITH_GZFILEOP? In the source code , ZIB_COMPAT is used to enable padding, but WITH_GZFILEOP is related to large file operations. They seem like  different things.

**Comment by mtl1979** [comment]
The padding stuff is going to change pretty soon when the latest changes are merged in... It was temporary solution. WITH_GZFILEOP is all about gzip-related disk I/O-functions that are emulated if WITH_GZFILEOP isn't enabled.

**Comment by richael02** [comment]
So will you  still use ZLIB_COMPAT to enable  WITH_GZFILEOP  or make some modification ?

**Comment by mtl1979** [comment]
ZLIB_COMPAT will not disappear anywhere... I'm not sure if we will allow enabling WITH_GZFILEOP without also enabling ZLIB_COMPAT using configure.

**Comment by richael02** [comment]
So  you will still keep both options : ZLIB_COMPAT and WITH_GZFILEOP and will not make them independent  when  using cmake ?

**Comment by mtl1979** [comment]
All flags are independent by default when using cmake, we can only set defaults.

**Comment by Dead2** [comment]
ZLIB_COMPAT is about the zlib api being compatible.
WITH_GZFILEOP is about including gzip-related functions.
Any mix of those should be legal. Stock zlib can also be compiled without the gzip functions btw.
