### ISSUE TITLE
Since 2.1.0, unpigz hangs in chunkcopy_safe

### ISSUE THREAD

**Issue by Vogtinator** [zlib-ng/zlib-ng#1525]
Originally reported downstream: https://bugzilla.opensuse.org/show_bug.cgi?id=1212735

When using `unpigz` to decompress .tar.gz files, it hangs with 100% CPU inside `chunkcopy_from`, with `len == 5` while `tocopy == 0`.
This is because `out == from` and this is not properly handled by the function.

A bisect shows that this broke with 49a6bb5d413fef477a76111e1a5946452ff9d4a8.
Adding just `if(out == from) return out + len;` fixes it, the output has the expected checksum.

5MiB sample file attached, it breaks after 700KiB already: [sample.tar.gz](https://github.com/zlib-ng/zlib-ng/files/11872162/sample.tar.gz)

**Comment by KungFuJesus** [comment]
@Vogtinator Would you mind submitting a pull request?

**Comment by Vogtinator** [comment]
Can do. Is it expected that `chunkcopy_safe` is called with source and destination being equal?

From my limited understanding of `INFLATE_FAST`, this could possibly happen if `out` and `window` are part of the same allocation and magically aligned such that there is perfect overlap?

**Comment by phprus** [comment]
Maybe use ``memmove`` instead of the current implementation for overlapped regions?

**Comment by KungFuJesus** [comment]
@phprus the problem is that we need the side effects of an overlapped memcpy. This code is mimicking a byte by byte copy, not a safe memmove.

This comment I left here explains it pretty thoroughly: https://github.com/zlib-ng/zlib-ng/blob/49a6bb5d413fef477a76111e1a5946452ff9d4a8/inflate_p.h#L229

Ahh, you might have been suggesting to use memcpy for the first non-overlapped bit.  That doesn't quite solve the problem, though, as the computed non-overlapping area is 0, not that out == from. So effectively, we hit the bottom while loop copying 0 bytes, forever.  The fix proposed should work and be pretty optimal, to boot.

**Comment by KungFuJesus** [comment]
> Can do. Is it expected that `chunkcopy_safe` is called with source and destination being equal?
> 
> From my limited understanding of `INFLATE_FAST`, this could possibly happen if `out` and `window` are part of the same allocation and magically aligned such that there is perfect overlap?

Admittedly this is not an input scenario I imagined happening but I suppose it's possible.  The proposed solution here would probably handle that best (simply returning with the new location of out + len).

**Comment by Vogtinator** [comment]
https://github.com/zlib-ng/zlib-ng/pull/1526

I managed to build a 1.5MiB .tar.gz which reproduces the issue, but I did not have success adding a test case to `test/pigz`. For some reason the pigz built there does not show the issue...

**Comment by KungFuJesus** [comment]
It would not surprise me if every pigz version didn't see the issue. I wasn't aware that pigz had its own decompressor, is that trying to do things in parallel as well?

**Comment by Vogtinator** [comment]
> It would not surprise me if every pigz version didn't see the issue. I wasn't aware that pigz had its own decompressor, is that trying to do things in parallel as well?

Kind of:

https://github.com/madler/pigz/blob/cb8a432c91a1dbaee896cd1ad90be62e5d82d452/pigz.c#L251-L257

**Comment by KungFuJesus** [comment]
Hmm, I wouldn't imagine that might cause the decompression streams to suddenly vary in alignment where this perfect overlap disappears.  In theory, a compressed file should have the same exact decompression sequence.  I guess it could be possible that pigz has an early exit when calling deflate at the tail end of the stream or something?  It could be worth trying to add a reproducing test but if it depends on a specific version of pigz (and only pigz), maybe that's enough of a reason to leave it alone.

**Comment by Vogtinator** [comment]
There might also be some differences in how pigz is built here as part of the testsuite (using static zlib-ng) and as part of the distro (vanilla zlib dynamically linked, with LTO)
