### ISSUE TITLE
ZLIBNG_VER_STATUS related build failure of perl 5.38.0 with zlib-ng 2.1.3

### ISSUE THREAD

**Issue by haampie** [zlib-ng/zlib-ng#1543]
See https://gitlab.spack.io/spack/spack/-/jobs/7711837

cc -c  -I/home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/zlib-ng-2.1.3-336bvhbgdrysvjersb3j5j3cwlxb2jql/include -D_REENTRANT -D_GNU_SOURCE -DAPPLLIB_EXP="/home/software/spack/[padded-to-256-chars]/morepadding/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/perl-5.38.0-qgkulwfhciigujcnklxnk6hkpor6adph/lib/perl5" -fwrapv -fno-strict-aliasing -pipe -fstack-protector-strong -I/home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/gdbm-1.23-xpyyzcrwdav47volmutsdrioid7x4npe/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_FORTIFY_SOURCE=2 -Wall -Werror=pointer-arith -Werror=vla -Wextra -Wno-long-long -Wno-declaration-after-statement -Wc++-compat -Wwrite-strings -O2   -DVERSION=\"2.204_001\" -DXS_VERSION=\"2.204_001\" -fPIC "-I../.."  -DNO_VIZ      -DGZIP_OS_CODE=3  -DPerl_crz_BUILD_ZLIB=0 Zlib.c
In file included from Zlib.xs:37:
constants.h: In function 'constant':
/home/software/spack/[padded-to-256-chars]/linux-ubuntu20.04-x86_64_v3/gcc-11.1.0/zlib-ng-2.1.3-336bvhbgdrysvjersb3j5j3cwlxb2jql/include/zlib.h:57:27: error: 'F' undeclared (first use in this function); did you mean 'OF'?
   57 | #define ZLIBNG_VER_STATUS F         /* 0=devel, 1-E=beta, F=Release */
      |                           ^

**Comment by haampie** [comment]
Similar to https://github.com/zlib-ng/zlib-ng/discussions/1517

Looks like that define is completely useless it it's either a digit or a letter?

```
#define ZLIBNG_VER_STATUS F /* 0=devel, 1-E=beta, F=Release */
```

**Comment by haampie** [comment]
@pmqs did you figure this out?

**Comment by haampie** [comment]
Found https://github.com/pmqs/Compress-Raw-Zlib/issues/24

**Comment by haampie** [comment]
Applied https://github.com/pmqs/Compress-Raw-Zlib/commit/0a8fb7141a43b8e49609fb06f05fad5150a97c2a as a patch, which makes the build pass.

Is that sufficient for Perl 5.38 or do I need more @pmqs?

**Comment by pmqs** [comment]
> Applied [pmqs/Compress-Raw-Zlib@0a8fb71](https://github.com/pmqs/Compress-Raw-Zlib/commit/0a8fb7141a43b8e49609fb06f05fad5150a97c2a) as a patch, which makes the build pass.
> 
> Is that sufficient for Perl 5.38 or do I need more @pmqs?

No - all is good. This change is now in Compress-Raw-Zlib 2.204
