### ISSUE TITLE
Minizip implementation

### ISSUE THREAD

**Issue by Dead2** [zlib-ng/zlib-ng#156]
We removed minizip early on when we were trying to shed as much as possible of the unrelated code and workarounds for all kinds of old scenarios. The Chromium people have spoken up regarding minizip though, since they depend on minizip for unpacking things such as addons in .zip files. That makes sense since they already use zlib and there is little point in having two nearly identical libraries in the code.

contrib/minizip needs to be fetched from zlib, and all the old ifdef blocks that are related to zip-support needs to be implemented as well. Most can likely be copied over nearly as-is, but some might need a bit more TLC due to unrelated changes in zlib-ng.

I am hoping some volunteer will step up and try their hands on this task, as this is the last big must-have feature that remains on our TODO before releasing a stable version of zlib-ng. This task should not be very difficult, and it does not require an intimate knowledge of zlib internals or the deflate algorithm, so it should be a good task for someone wanting to get their feet wet without requiring a life-west.

**Comment by nmoinvaz** [comment]
I compiled zlib-ng against my [minizip](https://github.com/nmoinvaz/minizip) fork. In my repository there is a test folder with test.py that failed to create a 50MB zip file and dumped a bunch of "bit length overflow" errors from zlib-ng. So it looks like there is some additional work that may needed.

**Comment by mtl1979** [comment]
"bit length overflow" isn't actually an error, it's just a trace message for handling a special case. I suspect the real error is elsewhere but no trace messages are printed as the code is missing.

**Comment by nmoinvaz** [comment]
You are right. I had mistaken them for errors and they were only trace messages. All my tests passed. 

You mentioned in this issue that there were #defines that needed to be imported from the stock zlib - but I'm not sure which ones you were referring to. 

I did notice that the typedef for z_crc_t is missing which is in zlib 1.2.6+.
`typedef unsigned long z_crc_t;`
https://github.com/madler/zlib/blob/cacf7f1d4e3d44d871b605da3b647f07d718623f/zconf.h#L428

I had difficulties getting the repo working without using ./configure on Windows. I think it was missing zconf.h. I like how in the stock zlib, everything is ready to go and don't need to run ./configure - zconf.h already exists. I think ZLIB_COMPAT should be turned on by default.

Anyways that is my feedback.

**Comment by Dead2** [comment]
Hmm, maybe I was remembering wrong. I might have remembered the PKZIP_BUG_WORKAROUND define, but that is still present in our code. (Dunno whether it actually works in all codepaths though, that would likely be a good candidate for a unit-test).

In that case, if we could get inter-compatibility, as a sub-module or something (with a git sub-module link or manually), that would be great. Your fork looks like it matches our work quite well, and we could recommend using your minizip in combination with our zlib fork.
There would of course be a need for changes, probably on both ends, since our code has evolved quite a lot from stock zlib. We have focused a lot on making the code easier to understand for outsiders, without lots of the "portability" stuff for really really old systems and compilers and using standard types where appropriate.
Regarding ZLIB_COMPAT, we will probably want to focus on the zlib-ng API instead of the old zlib API as default for zlib-ng. After all, dynamically linked zlib-ng in compat mode will not work well in a process that requires another library that pulls in stock zlib as well. If you use the zlib-ng API though, there will be no conflict. For example you can compile nginx with zlib-ng without getting into trouble because openssl loads stock zlib into the process also.

In any case, thanks for testing, this is great news. 👍

**Comment by Dead2** [comment]
Btw, feel free to join us in the irc channel #zlib-ng on freenode. I am always logged in, but not always present. I will reply eventually though :)

**Comment by mtl1979** [comment]
@nmoinvaz `z_crc_t` and few other zlib-specific types were deprecated and removed in zlib-ng... We use now `uint32_t` for checksum related functions (crc32, adler32)...

On Windows, you should just copy zconf.h.in to zconf.h (or zconf-ng.h.in to zconf-ng.h) like the Visual C++ Makefile in win32 subdirectory does... Otherwise you might get error about missing unistd.h.

zconf.h is used in zlib-compatibility mode (when `ZLIB_COMPAT` is defined) and zconf-ng.h is used for new code.

**Comment by nmoinvaz** [comment]
Sounds good. Let me know if there are any changes that I can make to make things better to integrate with. The only thing I can see so far is the missing typedef for `z_crc_t`.

**Comment by nmoinvaz** [comment]
I have made some changes and removed the need for z_crc_t. All that is needed to get zlib-ng working with my minizip fork is pointing the following defines to zlib-ng paths and compiling with `ZLIB_COMPAT`.

cmake -DZLIB_LIBRARY:FILEPATH="C:\source\zlib-ng\zlibstaticd.lib" .
cmake -DZLIB_INCLUDE_DIR:PATH="C:\source\zlib-ng\\" .

**Comment by Dead2** [comment]
Sounds like we should get this tested, documented and perhaps included as a git submodule.

**Comment by nmoinvaz** [comment]
What would you want tested, documented, and where would you want the submodule in the repository?

**Comment by donny-dont** [comment]
CMake has external project support if you wanted to use that. Then you wouldn't need a submodule. That of course assumes youd just build it through CMake and not autotools though.

https://cmake.org/cmake/help/v3.12/module/ExternalProject.html

**Comment by nmoinvaz** [comment]
I like that idea. However I am having a bit of difficulty with cmake. I was trying to get minizip to put its output binaries in the same directory as zlib when building, but it seems that with ExternalProject_Add it is not possible to specify where the build gets put - it seems to always want to install the project.

```
option(WITH_MINIZIP "Build minizip library" ON)
if (WITH_MINIZIP)
    get_target_property(ZLIB_LIBRARY zlibstatic LOCATION_DEBUG)
    message(STATUS "Hello")
    message(STATUS ${CMAKE_INSTALL_PREFIX})
    ExternalProject_Add(minizip
        GIT_REPOSITORY    https://github.com/nmoinvaz/minizip.git
        GIT_TAG           master
        SOURCE_DIR        "${CMAKE_BINARY_DIR}/minizip"
        INSTALL_DIR       "${CMAKE_BINARY_DIR}/minizip-install"
        BINARY_DIR        "${CMAKE_BINARY_DIR}/minizip-build"
        CMAKE_ARGS
            -DZLIB_LIBRARY=${ZLIB_LIBRARY}
            -DZLIB_INCLUDE_DIR=${CMAKE_SOURCE_DIR}
            -DBUILD_TEST=ON
    )
endif()
```

**Comment by sebpop** [comment]
Can we close this bug now?

**Comment by nmoinvaz** [comment]
Instead of including minizip in zlib cmake, I've included zlib in minizip cmake as ExternalProject. If you use these options in minizip cmake, it will compile with zlib-ng:

`-DZLIB_REPOSITORY=https://github.com/Dead2/zlib-ng -DZLIB_TAG=develop`

I don't think it is necessary to have zlib-ng include minizip as ExternalProject or submodule anymore.

**Comment by Dead2** [comment]
That is unfortunate, since that does not allow configuring of zlib-ng parameters. Also, can it use a shared zlib-ng library in non-compat mode?

**Comment by nmoinvaz** [comment]
No, it will only work with `ZLIB_COMPAT=ON` which it sets by default. I haven't found a way to easily pass in parameters to ExternalProject_Add call from command line.

**Comment by nmoinvaz** [comment]
I think it is better for zlib-ng not to include any contribs - which is one thing that you removed from the old zlib. It is better that projects that utilize zlib-ng reference it, rather than the other way around imo.

**Comment by Dead2** [comment]
We need a minizip implementation that supports our non-compat mode, and if that means we import the old minizip from zlib/contribs, that is better than nothing. Chromium for example depends on minizip for addons etc, and using minizip w/stock zlib while using zlib-ng for everything else would be bad form.
However, if @nmoinvaz's minizip were to get full support for zlib-ng, we could just point to that instead.

**Comment by nmoinvaz** [comment]
It appears to work okay with ZLIB_COMPAT turned off. But maybe somebody else can try it to make sure. From what I have heard, future versions of chromium will use my version of minizip.

**Comment by nmoinvaz** [comment]
However, it might give you the best flexibility to include minizip on your end. You can go down the path of including minizip as a git submodule or cmake ExternalProject but i'm afraid that if you include a copy of minizip in your repository, regardless of where it comes from, you will end up having to be responsible for maintaining it unless you explicitly state somewhere that you don't accept pull requests for it. If you take a look at what happened to madler, he no longer maintains the contribs in his zlib and most of those projects are dead.

**Comment by nmoinvaz** [comment]
I have made some changes to the cmake project in my dev branch which will allow you to also pass in arguments to external zlib project.

**Comment by nmoinvaz** [comment]
Actually it still does require `ZLIB_COMPAT` because it is expecting the zlib compatible api function names. In other words, function names that don't begin with "zng_". I'm not exactly sure why this is a make or break for zlib-ng minizip integration. If anybody has an alternative approach that allows minizip to work with zlib and zlib-ng please let me know.

**Comment by mtl1979** [comment]
@nmoinvaz I would just check if one of the externally visible zlib-ng symbols or macros are present without ```ZLIB_COMPAT``` and then use ```zng_``` prefix, otherwise use empty or ```z_``` prefix. This can be implemented using same workarounds as zlib-ng uses internally (the three PREFIX macros).

**Comment by nmoinvaz** [comment]
I thought about that, but I would essentially just have a copy of that PREFIX macro in my own code. But I am wondering what is the **value** of NOT having `ZLIB_COMPAT`.

**Comment by mtl1979** [comment]
Some structures max out at 16 or 32 bits when using ```ZLIB_COMPAT```. Without ````ZLIB_COMPAT``` the maximum is 64 bits.

**Comment by nmoinvaz** [comment]
I see. Ok I made some changes that should resolve it. It's ugly but whatever.

**Comment by mtl1979** [comment]
To be able to support multiple API versions of some library sometimes requires ugly hacks or workarounds. It's just matter of how much ugliness is required.

**Comment by Dead2** [comment]
Zlib-ng wants to appear in distros at some point, and we cannot expect the distro to replace zlib with zlib-ng. So that means we need to rename the library and all the public functions etc so as not to collide with stock zlib.
Imagine apache being compiled with zlib-ng and loading php with a module compiled with zlib, those would cause unpredictable behavior or even crash because it might call some functions from zlib and some from zlib-ng, and that would not work since the internal structures are not the same.
So zlib-compat is for legacy support and it is not our primary goal.

Some of our changes are mostly internal, but results in a different stream struct externally, and some changes are datatype changes, where we use datatypes that are of a constant size no matter what platform instead of for example int and long that only define a minimum size and lead to different behavior on different platforms.

Your changes look good to me, except for the wrong zstream name that I assume you probably found already.

**Comment by nmoinvaz** [comment]
I think this can be closed unless there is something else that needs to be done.

**Comment by nmoinvaz** [comment]
My [minizip](https://github.com/zlib-ng/minizip-ng) repository has now been moved to zlib-ng organization. I will close, but if there is still a need please reopen.
