### ISSUE TITLE
Compiler error spack installing zlib-ng@2.1.3%gcc@9.1.0+compat+opt build_system=autotools arch=linux-centos7-zen2

### ISSUE THREAD

**Issue by cameronrutherford** [zlib-ng/zlib-ng#1564]
I updated Spack for another project, and automatically used `zlib-ng` instead of `zlib` as the `zlib-api` provider, and was getting some quite mysterious-to-me compiler errors that I wanted to document.

[spack-build-out (6).txt](https://github.com/zlib-ng/zlib-ng/files/12441547/spack-build-out.6.txt)

Apologies for not trimming output, but hopefully I can help debug further.

**Comment by phprus** [comment]
Duplicate: #1559

**Comment by cameronrutherford** [comment]
I am using plain zlib for now so I am going to close since this is a duplicate. Thanks for the quick response!
