### ISSUE TITLE
how to build using configure?

### ISSUE THREAD

**Issue by mausalimi** [zlib-ng/zlib-ng#1566]
i did exactly as told.

./configure
make

but all i get is 

make: *** No rule to make target '/home/user/zlib-ng-develop/test/example.c', needed by 'example.o'.  Stop.

**Comment by nmoinvaz** [comment]
Can you attach your configure command output?

**Comment by mausalimi** [comment]
sure. it is surprisingly short. but i get a makefile both in src dir and test.

$ ./configure
Checking for compiler... gcc
Checking for Symbol versioning... No.
Checking for shared library support... Building shared library libz-ng-2.dll with gcc.
Checking for off64_t... Yes.
Checking for fseeko... Yes.
Checking for posix_memalign... No.
Checking for aligned_alloc... No.
Checking for strerror... Yes.
Checking for getauxval() in sys/auxv.h... No.
Checking for unistd.h... Yes.
Checking for ptrdiff_t... Yes.
Checking for ANSI C compliant compiler...  Yes.
Checking for -fno-semantic-interposition... Yes.
Checking for -fno-lto... Yes.
Checking for attribute(aligned) ... Yes.
Checking for _Thread_local ... Yes.
Checking for __builtin_ctz ... Yes.
Checking for __builtin_ctzll ... Yes.
Checking for AVX2 intrinsics ... Yes.
Checking for AVX512 intrinsics ... Yes.
Checking for AVX512 k-mask intrinsics ... No.
Check whether -mtune=cascadelake works ... No.
Check whether -mtune=skylake-avx512 works ... Yes.
Checking for AVX512VNNI intrinsics ... No.
Checking for SSE4.2 intrinsics ... Yes.
Checking for SSE2 intrinsics ... Yes.
Checking for SSSE3 intrinsics ... Yes.
Checking for PCLMULQDQ intrinsics ... Yes.
Checking for VPCLMULQDQ intrinsics ... No.
Checking for XSAVE intrinsics ... Yes.
Uname: MINGW64_NT-6.1
ARCH: i686
Using arch directory: arch/x86
Architecture-specific static object files: x86_features.o slide_hash_avx2.o chunkset_avx2.o compare256_avx2.o adler32_avx2.o adler32_avx512.o adler32_sse42.o insert_string_sse42.o chunkset_sse2.o compare256_sse2.o slide_hash_sse2.o adler32_ssse3.o chunkset_ssse3.o crc32_pclmulqdq.o
Architecture-specific shared object files: x86_features.lo slide_hash_avx2.lo chunkset_avx2.lo compare256_avx2.lo adler32_avx2.lo adler32_avx512.lo adler32_sse42.lo insert_string_sse42.lo chunkset_sse2.lo compare256_sse2.lo slide_hash_sse2.lo adler32_ssse3.lo chunkset_ssse3.lo crc32_pclmulqdq.lo


this is in mingw

**Comment by mausalimi** [comment]
cmake doesn't work either... so it seems this can't be build using a simple mingw / gcc setup

**Comment by mausalimi** [comment]
ok, using cmake it works.

**Comment by mausalimi** [comment]
btw, i use it in a video codec (for realtime encoding in a retro emulator), and i can say, the improvement is beyond my expectations!

**Comment by mtl1979** [comment]
Considering uname is saying `MINGW64_NT` and configure is saying architecture is `i686`, it means the installed gcc is targeting incorrect architecture... For 32-bit version of MinGW, the output of uname should be `MINGW32_NT`.
