### ISSUE TITLE
About Algorithm Optimization of SVE Instruction

### ISSUE THREAD

**Issue by leeq2016** [zlib-ng/zlib-ng#1569]
Does the maintainer now accept the algorithm optimized by the arm SVE instruction?
@Dead2

**Comment by Dead2** [comment]
We would not be able to confirm any speedups, as SVE is only present in recent server-scale cpus and we don't have access to any of those for testing.

I did talk to an ARM engineer about this a couple months ago, and he thought it likely would not be a big win, and that he personally would instead implement NEON because it is more suited for the kind of workload in addition to the much wider reach it has.

That said; If a PR is made, can show good speedups and passes code reviews, then sure.

**Comment by leeq2016** [comment]
> 


ok, got it, thank you very much for your answer.

**Comment by leeq2016** [comment]
> We would not be able to confirm any speedups, as SVE is only present in recent server-scale cpus and we don't have access to any of those for testing.
> 
> I did talk to an ARM engineer about this a couple months ago, and he thought it likely would not be a big win, and that he personally would instead implement NEON because it is more suited for the kind of workload in addition to the much wider reach it has.
> 
> That said; If a PR is made, can show good speedups and passes code reviews, then sure.

I have used the SVE instruction to optimize the adler32 algorithm, and tested it on Huawei Taishan 1951 (which supports 256-bit-width SVE instruction) and got good results. It is about 3.x times faster than the algorithm written in libz's native C language.

[root@xxx adler32]# ./benchmark 1000000
  Libz alg: Time used:    608 us, 1644.7 Mb/s.
  SVE  alg: Time used:    166 us, 6024.1 Mb/s.

[root@xxx adler32]# ./benchmark 10000000
  Libz alg: Time used:   6484 us, 1542.3 Mb/s.
  SVE  alg: Time used:   2034 us, 4916.4 Mb/s.

But I don't know how it compares with zlib-ng's current neon algorithm. After I extract arch/arm/adler32_neon.c, the comparison test seems to be a bit problematic. It is much slower than the native C language algorithm.

**Comment by leeq2016** [comment]
> > We would not be able to confirm any speedups, as SVE is only present in recent server-scale cpus and we don't have access to any of those for testing.
> > I did talk to an ARM engineer about this a couple months ago, and he thought it likely would not be a big win, and that he personally would instead implement NEON because it is more suited for the kind of workload in addition to the much wider reach it has.
> > That said; If a PR is made, can show good speedups and passes code reviews, then sure.
> 
> I have used the SVE instruction to optimize the adler32 algorithm, and tested it on Huawei Taishan 1951 (which supports 256-bit-width SVE instruction) and got good results. It is about 3.x times faster than the algorithm written in libz's native C language.
> 
> [root@xxx adler32]# ./benchmark 1000000   Libz alg: Time used: 608 us, 1644.7 Mb/s.   SVE alg: Time used: 166 us, 6024.1 Mb/s.
> 
> [root@xxx adler32]# ./benchmark 10000000   Libz alg: Time used: 6484 us, 1542.3 Mb/s.   SVE alg: Time used: 2034 us, 4916.4 Mb/s.
> 
> But I don't know how it compares with zlib-ng's current neon algorithm. After I extract arch/arm/adler32_neon.c, the comparison test seems to be a bit problematic. It is much slower than the native C language algorithm.


Sorry, I made a mistake during the testing process. I forgot to add -O2 when compiling the adler32_neon algorithm as a dynamic library, and added -O2 for the C algorithm. Judging from my new test results, the current performance of zlib-ng's adler32_neon is similar to that of my sve algorithm.

**Comment by nmoinvaz** [comment]
Would you be willing to share your algorithm?

**Comment by leeq2016** [comment]
> Would you be willing to share your algorithm?

Sure, I'll create pr later in this repo :)
