### ISSUE TITLE
RVV runtime detect by SIGILL handler

### ISSUE THREAD

**Issue by Xeonacid** [zlib-ng/zlib-ng#1587]
Currently, RVV runtime detection uses `hwcap` which is only supported on kernel 6.5+.

For lower kernel version, we may use the following approach:
- Set `features->has_rvv = 1` initially
- Register a SIGILL handler which sets `features->has_rvv = 0`
- Try to execute an RVV instruction
- If RVV is unsupported, it would fall into the SIGILL handler

I'm unsure if you are happy with this approach so I'm filling an issue first.

**Comment by mtl1979** [comment]
We don't use workarounds for other architectures if hwcap or similar feature check isn't supported. I don't think there is enough RVV users to warrant trying to support older kernel versions. This is kind of similar as trying to support compilers that can't target current architecture.
