### ISSUE TITLE
configure and --native

### ISSUE THREAD

**Issue by HansBull** [zlib-ng/zlib-ng#1592]
Since 0cb2b376ab840f7e7677558e9132273947cc8ae6 , `--native` has been removed. Invoking `configure` with  this option (btw, what are the alternatives now?) now fails. 
While it may be discutable whether a deprecation warning or a no-op would have been a better solution, it is certain that `README.md` has to be updated accordingly

**Comment by mtl1979** [comment]
I was against removing `--native` flag in `configure` as `cmake` isn't usable for all scenarios yet... Instead the maintainer did merge some fixes I made to the `cmake` build system.

As far as I know sooner than later whole `configure` file will be deprecated and removed, but that will likely happen when the next major version is released.

**Comment by nmoinvaz** [comment]
The readme has been updated. Please use cmake going forward for native instruction support.
