### ISSUE TITLE
ssize_t is POSIX only

### ISSUE THREAD

**Issue by donny-dont** [zlib-ng/zlib-ng#160]
Both `gzread.c` and `gzwrite.c` use `ssize_t`. The signed size type is only present in POSIX and is not present when building on Windows.

This means that on Windows you cannot build in compatibility mode.

Potential fix is just using an `int` instead of `ssize_t`.

**Comment by mtl1979** [comment]
Visual C++ has had ssize_t for ages... the code is only missing including the correct header.

**Comment by donny-dont** [comment]
My bad I didn't see https://msdn.microsoft.com/en-us/library/windows/desktop/aa383751(v=vs.85).aspx#SSIZE_T.

**Comment by mtl1979** [comment]
@Dead2 will fix the missing include when he is online... See Dead2/zlib-ng#161

**Comment by Dead2** [comment]
Fixed
