### ISSUE TITLE
libgit2 test suite failures with zlib-ng in compat mode

### ISSUE THREAD

**Issue by joebonrichie** [zlib-ng/zlib-ng#1600]
https://github.com/libgit2/libgit2#running-tests

Tested libs: 
 - ZLIB-NG: 2.1.4 compat mode
 - zlib 1.3.0 canonical 

Against:
 - libgit2 HEAD
 - libgit2 1.3.0
 - libgit2 1.5.2
 - solbuild (via libgit2)

I have found failing tests in the libgit2 testsuite with zlib-ng (compat mode) installed/ld_preloaded. This propagates to applications using libgit2 such as [solbuild](https://github.com/getsolus/solbuild) which will fail to clone repositories with zlib-ng installed. The tests pass as expected with canonical zlib installed. Please let me know if you can replicate.

Rebuilding libgit2 against zlib-ng-devel in compat mode doesn't seem to resolve the issue.

The following tests fail for me with zlib-ng installed:

1/12 Offline
``` 
  1) Failure:
pack::packbuilder::create_pack [/home/ninya/libgit2/tests/libgit2/pack/packbuilder.c:143]
  String mismatch: hex != "5d410bdf97cf896f9007681b92868471d636954b"
  '5f688cedc3a5132f15fc3352a35bc5dcb6a536a4' != '5d410bdf97cf896f9007681b92868471d636954b' (at byte 1)

  2) Failure:
pack::packbuilder::get_name [/home/ninya/libgit2/tests/libgit2/pack/packbuilder.c:151]
  String mismatch: "7f5fa362c664d68ba7221259be1cbd187434b2f0" != git_packbuilder_name(_packbuilder)
  '7f5fa362c664d68ba7221259be1cbd187434b2f0' != 'f120f6bbad709d0e3c021ca8f9d7c26c3882497b' (at byte 0)

  3) Failure:
pack::packbuilder::write_default_path [/home/ninya/libgit2/tests/libgit2/pack/packbuilder.c:159]
  Expression is not true: git_fs_path_exists("objects/pack/pack-7f5fa362c664d68ba7221259be1cbd187434b2f0.idx")

  4) Failure:
pack::packbuilder::permissions_standard [/home/ninya/libgit2/tests/libgit2/pack/packbuilder.c:184]
  Function call failed: (stat("pack-7f5fa362c664d68ba7221259be1cbd187434b2f0.idx", &statbuf))
  error -1 - no error

  5) Failure:
pack::packbuilder::permissions_readonly [/home/ninya/libgit2/tests/libgit2/pack/packbuilder.c:184]
  Function call failed: (stat("pack-7f5fa362c664d68ba7221259be1cbd187434b2f0.idx", &statbuf))
  error -1 - no error

  6) Failure:
pack::packbuilder::permissions_readwrite [/home/ninya/libgit2/tests/libgit2/pack/packbuilder.c:184]
  Function call failed: (stat("pack-7f5fa362c664d68ba7221259be1cbd187434b2f0.idx", &statbuf))
  error -1 - no error
```

3/12 Online
```
  1) Failure:
online::clone::can_checkout_a_cloned_repo [/home/ninya/libgit2/tests/libgit2/online/clone.c:243]
  Function call failed: (git_clone(&g_repo, "http://github.com/libgit2/TestGitRepository", "./foo", &g_options))
  error -1 - error reading from the zlib stream

  2) Failure:
online::fetch::doesnt_retrieve_a_pack_when_the_repository_is_up_to_date [/home/ninya/libgit2/tests/libgit2/online/fetch.c:133]
  Function call failed: (git_clone(&_repository, "https://github.com/libgit2/TestGitRepository.git", "./fetch/lg2", &opts))
  error -1 - error reading from the zlib stream

  3) Failure:
online::shallow::clone_depth_zero [/home/ninya/libgit2/tests/libgit2/online/shallow.c:27]
  Function call failed: (git_clone(&repo, "https://github.com/libgit2/TestGitRepository", git_str_cstr(&path), &clone_opts))
  error -1 - error reading from the zlib stream
```

4/12 online_customcert
```
  1) Failure:
online::customcert::file [/home/ninya/libgit2/tests/libgit2/online/customcert.c:68]
  Function call failed: (git_clone(&g_repo, "https://test.libgit2.org:1443/anonymous/test.git", "./cloned", ((void *)0)))
  error -1 - error reading from the zlib stream

  2) Failure:
online::customcert::path [/home/ninya/libgit2/tests/libgit2/online/customcert.c:76]
  Function call failed: (git_clone(&g_repo, "https://test.libgit2.org:2443/anonymous/test.git", "./cloned", ((void *)0)))
  error -1 - error reading from the zlib stream
```

**Comment by Dead2** [comment]
It looks like all the Offline tests are failing because they expect zlib-ng to produce bit-exact output to zlib, it does not. Therefore compressed data will differ, even though it will decompress to the same.
The hardcoded hashes starts here: https://github.com/libgit2/libgit2/blob/45fd9ed7ae1a9b74b957ef4f337bc3c8b3df01b5/tests/libgit2/pack/packbuilder.c#L143

The Online tests might be incompatibility problems that needs investigating and fixing.

**Comment by Dead2** [comment]
@joebonrichie Btw, how did you install zlib-ng?
Package or self-compiled? Please provide full compile log or link to package.

If this was self-compiled, there is a chance that it failed because libgit2 was not recompiled with zlib-ng's zlib.h and library in mind.

**Comment by joebonrichie** [comment]
zlib-ng build log: https://bpa.st/C3SQ

> If this was self-compiled, there is a chance that it failed because libgit2 was not recompiled with zlib-ng's zlib.h and library in mind.

Rebuilding libgit2 against zlib-ng headers didn't seem to make a difference (zlib-ng-devel installed)

**Comment by nmoinvaz** [comment]
You have to update the tests too.

**Comment by joebonrichie** [comment]
Last good release is 2.0.7. From 2.1.0-beta-1 I run into this issue. Looks like 2.1.0 was a fairly big release so it'll take a while to bisect it.

**Comment by joebonrichie** [comment]
Bisected to: 8550a90de4dcb8589a7d48fe308c4c45bba5a466. 

Unfortunately, the commit doesn't revert cleanly so can't test it reverted on top of 2.1.4.

**Comment by joebonrichie** [comment]
Below is a partial revert of 8550a90de4dcb8589a7d48fe308c4c45bba5a466 that I can apply on top of develop which fixes issues with libgit2. Some minimal general testing of other applications it seems to be _fine_.

```diff
diff --git a/inflate.c b/inflate.c
index a01e10f7..6ceb5154 100644
--- a/inflate.c
+++ b/inflate.c
@@ -268,38 +268,18 @@ static int32_t updatewindow(PREFIX3(stream) *strm, const uint8_t *end, uint32_t
 
     /* len state->wsize or less output bytes into the circular window */
     if (len >= state->wsize) {
-        /* Only do this if the caller specifies to checksum bytes AND the platform requires
-         * it (s/390 being the primary exception to this. Also, for now, do the adler checksums
-         * if not a gzip based header. The inline adler checksums will come in the near future,
-         * possibly the next commit */
-        if (INFLATE_NEED_CHECKSUM(strm) && cksum) {
-            /* We have to split the checksum over non-copied and copied bytes */
-            if (len > state->wsize)
-                inf_chksum(strm, end - len, len - state->wsize);
-            inf_chksum_cpy(strm, state->window, end - state->wsize, state->wsize);
-        } else {
-            memcpy(state->window, end - state->wsize, state->wsize);
-        }
+        memcpy(state->window, end - state->wsize, state->wsize);
 
         state->wnext = 0;
         state->whave = state->wsize;
     } else {
         dist = state->wsize - state->wnext;
-        /* Only do this if the caller specifies to checksum bytes AND the platform requires
-         * We need to maintain the correct order here for the checksum */
-        dist = MIN(dist, len);
-        if (INFLATE_NEED_CHECKSUM(strm) && cksum) {
-            inf_chksum_cpy(strm, state->window + state->wnext, end - len, dist);
-        } else {
-            memcpy(state->window + state->wnext, end - len, dist);
-        }
+        if (dist > len)
+            dist = len;
+        memcpy(state->window + state->wnext, end - len, dist);
         len -= dist;
         if (len) {
-            if (INFLATE_NEED_CHECKSUM(strm) && cksum) {
-                inf_chksum_cpy(strm, state->window, end - len, len);
-            } else {
-                memcpy(state->window, end - len, len);
-            }
+            memcpy(state->window, end - len, len);
 
             state->wnext = len;
             state->whave = state->wsize;
@@ -631,9 +611,7 @@ int32_t Z_EXPORT PREFIX(inflate)(PREFIX3(stream) *strm, int32_t flush) {
                 state->head->hcrc = (int)((state->flags >> 9) & 1);
                 state->head->done = 1;
             }
-            /* compute crc32 checksum if not in raw mode */
-            if ((state->wrap & 4) && state->flags)
-                strm->adler = state->check = functable.crc32_fold_reset(&state->crc_fold);
+            strm->adler = state->check = CRC32_INITIAL_VALUE;
             state->mode = TYPE;
             break;
 #endif
@@ -1045,17 +1023,9 @@ int32_t Z_EXPORT PREFIX(inflate)(PREFIX3(stream) *strm, int32_t flush) {
                 out -= left;
                 strm->total_out += out;
                 state->total += out;
+                if (INFLATE_NEED_CHECKSUM(strm) && (state->wrap & 4) && out)
+                    strm->adler = state->check = UPDATE(state->check, put - out, out);
 
-                /* compute crc32 checksum if not in raw mode */
-                if (INFLATE_NEED_CHECKSUM(strm) && state->wrap & 4) {
-                    if (out) {
-                        inf_chksum(strm, put - out, out);
-                    }
-#ifdef GUNZIP
-                    if (state->flags)
-                        strm->adler = state->check = functable.crc32_fold_final(&state->crc_fold);
-#endif
-                }
                 out = left;
                 if ((state->wrap & 4) && (
 #ifdef GUNZIP
@@ -1126,6 +1096,8 @@ int32_t Z_EXPORT PREFIX(inflate)(PREFIX3(stream) *strm, int32_t flush) {
     strm->total_in += in;
     strm->total_out += out;
     state->total += out;
+    if (INFLATE_NEED_CHECKSUM(strm) && (state->wrap & 4) && out)
+        strm->adler = state->check = UPDATE(state->check, strm->next_out - out, out);
 
     strm->data_type = (int)state->bits + (state->last ? 64 : 0) +
                       (state->mode == TYPE ? 128 : 0) + (state->mode == LEN_ || state->mode == COPY_ ? 256 : 0);
-- 
```

More details: 
x86_64, zenv2, gcc 13.2.0, binutils 2.41, glibc 2.38, 6.5.11

**Comment by mtl1979** [comment]
Can you do a pull request so the revert can be reviewed properly...

**Comment by nmoinvaz** [comment]
We should fix the problem.

**Comment by KungFuJesus** [comment]
> We should fix the problem.

Definitely.  Folding that copy into the checksum computation was a meaningful win I'd rather not undo.  The suspicious thing your revert is doing that I don't think the head of develop is right now is here:
+            strm->adler = state->check = CRC32_INITIAL_VALUE;

Could perhaps just adding that there fix it?

*edit* - looks as though the reset function does return that.  That final delta there looks novel from the state of HEAD, though.

**Comment by KungFuJesus** [comment]
Test suite seems to be passing for me with that change in place, let me propose a PR.

**Comment by KungFuJesus** [comment]
@joebonrichie does https://github.com/zlib-ng/zlib-ng/pull/1602/ fix this test for you?

**Comment by KungFuJesus** [comment]
If it does, it may not be a bad idea to incorporate this test (or one like it) into the CI.

**Comment by joebonrichie** [comment]
> @joebonrichie does #1602 fix this test for you?

Applying ontop of 2.1.4 doesn't resolve the issue for me unfortunately

I'm typically running `./libgit2_tests -sonline -Q` after building libgit2 with tests enabled for testing. With #1602 `online::clone` now _sometimes_ passes but `online::customcert` still always fails as before.

Also, if this helps, `online::clone` doesn't always fail the same way run-to-run, it's quite sporadic.

**Comment by KungFuJesus** [comment]
Hmm, well I've reproduced it, at least with LD_PRELOAD.  I'll build with the headers and do a more thorough debugging effort soon.

To clarify, the above partial revert permanently fixed it for you?  Not sporadically?

**Comment by joebonrichie** [comment]
> To clarify, the above partial revert permanently fixed it for you? Not sporadically?

Correct

**Comment by KungFuJesus** [comment]
So that patch breaks a lot of tests.  I suspect what's happening is it's forcing the checksum to complete rather than keeping it in it's partially running sum state, and it happens to populate strm->adler && state->check at exactly the right moment.  Now, truth be told I've rarely interacted with zlib's interfaces directly, usually I'm leveraging something else's code for it.  From what I understand, these are internal variables that we (and zlib proper) use to check correctness.  Is it sensible / normal for things to access these variables in a public manner @nmoinvaz, @mtl1979, @dead2?

In any case, I'm going to have to mess around with this to catch potential control flow exits to make sure that checksum is fully completed.

**Comment by KungFuJesus** [comment]
Interestingly, taking the folded crc32 calculation out of the equation entirely by disabling pclmulqdq still makes this fail, and random and intermittent intervals.  The failure is cryptic, I wish it would produce a stack trace or verbose error message.  Maybe I have to hit these tests from a debugger.

**Comment by KungFuJesus** [comment]
Man, when this fails is constantly changing.  Is this library accessing something in a thread unsafe manner or something?

**Comment by mtl1979** [comment]
@KungFuJesus I think this case falls in to category I described earlier as abusing inherent features of stock zlib's internals... I wanted a PR just so it will be easier to pinpoint which one of the changes is the culprit as I wasn't sure the patch is as clean as it could get. 

In the end if we seriously want to be replacement for zlib, zlib-ng must take account possible side effects of every single function, not just the end results of the externally visible functions.

**Comment by KungFuJesus** [comment]
FWIW it does seem to be inflate returning an error, somehow.  Looks like there's a data checksum error (zerr is incorrect data check).  This is odd.

**Comment by mtl1979** [comment]
> FWIW it does seem to be inflate returning an error, somehow. Looks like there's a data checksum error (zerr is incorrect data check). This is odd.

That's what I assumed, but wasn't sure why... I could see only two possibilities, overlapping data or off-by-one type of corner case that isn't caught by existing tests...

**Comment by KungFuJesus** [comment]
So, every time it hits this, the bad checksum calculation is 1.  Do we initialize it to 1 at any point? Hah, yep, that's the initial value.  So it's somehow never running the bytes through the checksum by that point.

**Comment by KungFuJesus** [comment]
the bytes themselves look fine and are at non-zero lengths:
```The program being debugged has been started already.
Start it from the beginning? (y or n) y
Starting program: /scratchdir/adam/libgit2/build/libgit2_tests -sonline
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Loaded 381 suites: 
Started (test status codes: OK='.' FAILURE='F' SKIPPED='S')

online::badssl....
online::clone...
Breakpoint 1, inflate (strm=0x555555bcc048, flush=4) at /home/adam/scratch/zlib-ng/inflate.c:1066
1066	                    fprintf(stderr, "expected: %x, got: %x\n", ZSWAP32(hold), state->check);
(gdb) up
#1  0x00005555557b8a15 in git_zstream_get_output_chunk (out=0x555555bccf20, out_len=0x7fffffffcb88, zstream=0x555555bcc048) at /home/adam/scratch/libgit2/src/util/zstream.c:126
126			zstream->zerr = inflate(&zstream->z, zstream->flush);
(gdb) p zstream
$1 = (git_zstream *) 0x555555bcc048
(gdb) p *zstream
$2 = {z = {next_in = 0x7ffff7f757a4 "4\372\301\231\006\272\232!\201\351\261\315\343ܳ\027\360\265*\3131", avail_in = 21, total_in = 25, 
    next_out = 0x555555bccf20 "alone in the dark\n40c8116da865b2d65593a6bb9cd2a\ntype commit\ntag annotated_tag\ntagger nulltoken <emeric.fermas@gmail.com> 1346358124 +0200\n\nYou've been tagged!\nulltoken <emeric.fermas@\nle.com> 11129127"..., avail_out = 8192, total_out = 18, msg = 0x0, state = 0x555555bd9580, zalloc = 0x7ffff7f91c0d <zcalloc>, 
    zfree = 0x7ffff7f91c33 <zcfree>, opaque = 0x0, data_type = 88, adler = 1, reserved = 0}, type = GIT_ZSTREAM_INFLATE, in = 0x7ffff7f757a4 "4\372\301\231\006\272\232!\201\351\261\315\343ܳ\027\360\265*\3131", in_len = 21, flush = 4, zerr = 0}
```

**Comment by KungFuJesus** [comment]
I _think_ the issue is buried somewhere in the updatewindow logic but I don't see where this corner would be or why it's special.  We initialize the adler checksum to 1.  Clearly when we hit this "CHECK" case, out is already 0, so we're not running any bytes through the checksum.  The updatewindow function both copies the window and checksums it for every case we need a checksum, it appears.  @nmoinvaz you were involved with the original updatewindow function, can you think of a reason this might be happening?

**Comment by nmoinvaz** [comment]
> So, every time it hits this, the bad checksum calculation is 1. Do we initialize it to 1 at any point? Hah, yep, that's the initial value.

Is the problem with the code, the adler checksum or the crc32 checksum? Adler32 is 1, crc32 is 0.

**Comment by KungFuJesus** [comment]
90% sure it's adler32 with plain old deflate.  The checksum is coming back as the initial value, meaning somehow we ran through the bytes without updating the checksum at all (or we have an extremely unlikely coincidence that the sum wrapped to 1 in all of these failures).  Is there maybe a path here that manages to avoid inf_chksum_* entirely?

*edit* looks like case "COPY" is a literal memcpy, without checksumming the bytes.  Perhaps this is it?

**Comment by KungFuJesus** [comment]
Hmm, I turned on the uber debug and verbosity options to show the state of inflate.  This is what I see on the first failed test:
```inflate: allocated
inflate: reset
inflate:   zlib header ok
inflate:     fixed codes block (last)
inflate:         literal '0'
inflate:         literal '4'
inflate:         literal 'a'
inflate:         literal 'e'
inflate:         literal 't'
inflate:         literal 0x00
inflate:         literal 0xf4
inflate:         literal 0xe0
inflate:         literal 0x9e
inflate:         literal 0xa2
inflate:         literal 0xa7
inflate:         literal 'w'
inflate:         literal 0x18
inflate:         literal 0xf6
inflate:         literal 0xdd
inflate:         literal 0x93
inflate:         literal '$'
inflate:         literal 0xb8
inflate:         end of block
expected: c50f8d, got: 1
```

**Comment by KungFuJesus** [comment]
Hmm, the pattern seems to be with fixed code literals, and not all the time.  I added a few more trace messages to see what's happening.  The updatewindow routine doesn't evidently need to be invoked because for some of these chunks it's fine with never calling it:

```inflate: allocated
inflate: reset
inflate:   zlib header ok
inflate:     fixed codes block (last)
inflate:         inf_fast
inflate:         literal '0'
inflate:         literal '4'
inflate:         literal '1'
inflate:         literal 'x'
inflate:         literal 0xae
inflate:         literal 'W'
inflate:         literal 0xc3
inflate:         literal '#'
inflate:         literal 0x9c
inflate:         literal 0xa0
inflate:         literal 0xf9
inflate:         end of block
inflate:   check matches trailer
   inf_leave, no update window
inflate: end
inflate: allocated
inflate: reset
inflate:   zlib header ok
inflate:     dynamic codes block (last)
inflate:       table sizes ok
inflate:       code lengths ok
inflate:       codes ok
inflate:         inf_fast
inflate:         literal 'j'
inflate:         literal 't'
inflate:         literal '0'
inflate:         literal 'a'
inflate:         literal 'c'
inflate:         literal '8'
inflate:         literal 'c'
inflate:         literal '1'
inflate:         literal 'a'
inflate:         literal '5'
inflate:         literal 'd'
inflate:         literal '5'
inflate:         literal 'a'
inflate:         literal 'b'
inflate:         literal 'd'
inflate:         literal 0x0a
inflate:         literal 'p'
inflate:         literal 'c'
inflate:         literal 'm'
inflate:         literal 0x0a
inflate:         literal 'g'
inflate:         literal 'n'
inflate:         literal 't'
inflate:         literal 'e'
inflate:         length 3
inflate:         distance 14
inflate:         length 4
inflate:         distance 18
inflate:         literal 'r'
inflate:         literal 'u'
inflate:         literal 't'
inflate:         literal 'e'
inflate:         literal '<'
inflate:         literal 'e'
inflate:         literal 'c'
inflate:         literal 'e'
inflate:         literal 'a'
inflate:         literal 'g'
inflate:         literal 'i'
inflate:         length 3
inflate:         distance 63
inflate:         literal '1'
inflate:         literal '6'
inflate:         literal '8'
inflate:         literal '4'
inflate:         literal '0'
inflate:         literal '0'
inflate:         literal 'Y'
inflate:         literal '''
inflate:         literal ' '
inflate:         length 3
inflate:         distance 56
inflate:         length 5
inflate:         distance 73
inflate:         literal 0x0a
inflate:         end of block
inflate:   check matches trailer
   inf_leave, no update window
inflate: end
inflate: allocated
inflate: reset
inflate:   zlib header ok
inflate:     fixed codes block (last)
inflate:         inf_fast
inflate:         literal 'o'
inflate:         literal ' '
inflate:         inf_fast
inflate:         literal ' '
inflate:         literal 't'
inflate:         literal 'h'
inflate:         literal 'e'
inflate:         literal ' '
inflate:         literal 'd'
inflate:         literal 'a'
inflate:         literal 'r'
inflate:         literal 'k'
inflate:         literal 0x0a
inflate:         end of block
   inf_leave, no update window
expected: 3e030634, got: 1
```

**Comment by KungFuJesus** [comment]
Ok, so the sequence of fixed literals that do make it through appear to have a non-zero set of "remaining out bits" for the tail end there and that's why those are passing.  It seems like our failure mode is a sequence of short literals that don't have any bits left to populate by the time the "check" is hit at the end.

So I think I identified the gist of the issue but the question becomes where do we insert the missing checksum portions for when this is happening and how do we detect it?

**Comment by KungFuJesus** [comment]
Hmm, I have a hacky fix in place but it's definitely not robust, yet.  I _think_ we need a way to signify that none of the bytes ran through the checksum by the time we reached there. 

Ok wait, I might have something.  Let me do more test.  I suspect this is related to the pigz bug as well. To not make this behave inefficiently I think I do need a "checksum dirty" bit to work with.  It feels hacky but I don't otherwise see a pattern where it might be falling through the cracks.

**Comment by KungFuJesus** [comment]
> > So, every time it hits this, the bad checksum calculation is 1. Do we initialize it to 1 at any point? Hah, yep, that's the initial value.
> 
> Is the problem with the code, the adler checksum or the crc32 checksum? Adler32 is 1, crc32 is 0.

I'm fairly certain it's the adler path, not the CRC path.

**Comment by joebonrichie** [comment]
Ah nice timing, I can confirm that #1602 now fixes the issue. I also tested applications using libgit2 such as solbuild and gnome-builder which would previously fail to clone repositories, now they succeed.

**Comment by mtl1979** [comment]
Seems like #1602 is still failing some checks, so needs a little bit more work...

**Comment by KungFuJesus** [comment]
Yeah I'm marking it as a draft. I think I know what I need to do to fix it, though.

**Comment by nmoinvaz** [comment]
It would be great to add this case to the CI. What is the minimal reproduction case?

**Comment by KungFuJesus** [comment]
So I tried to extract and save that off from libgit2 but was met with limited success.  The file runs through minigzip without an error (on develop and this branch) but somehow fails completely through minideflate.  The output when run through minigzip is identical to what it was prior to running through it, so I suspect I hadn't extracted it correctly.  Here's what I had attempted:

```C
      if ((error = git_zstream_get_output_chunk(buffer, &len, &obj->zstream)) < 0) {
          git_mwindow_close(&obj->mw);
          FILE *badFile = fopen("/tmp/git_bad_stream.deflate", "w");
          fwrite(in, sizeof(char), window_len, badFile);
          fclose(badFile);
          git_error_set(GIT_ERROR_ZLIB, "error reading from the zlib stream (out chunk)");
          return -1;
      }
```

Maybe it was dumb to try to just deserialize a chunk?  I'm guessing we've somehow missed a header.  This is the buffer that basically gets fed directly into the inflate function, with Z_FINISH as the flag.

**Comment by KungFuJesus** [comment]
Hmm, ok I copied out the bad packfile, maybe I could work this into a test.  Assuming it doesn't require taking libgit2 along for the ride, anyway.

**Comment by nmoinvaz** [comment]
I think `minideflate` will probably allow you the most flexibility to be able to reproduce it as a part of a CMake test. I suggest adding the unit test as a separate PR, so we can merge it to confirm it fails, and then rebase your PR on top of it, and confirm it fixes it.

**Comment by KungFuJesus** [comment]
The problem is that I think it's a special custom git file format with several potential streams in it:
```
adam@eggsbenedict ~/scratch/libgit2/build $ file /tmp/bad_git2_packfile
/tmp/bad_git2_packfile: Git pack, version 2, 70 objects
adam@eggsbenedict ~/scratch/libgit2/build $ ~/scratch/zlib-ng/build/minideflate -k -c -d /tmp/bad_git2_packfile 
Failed to open file: /tmp/bad_git2_packfile
```

**Comment by KungFuJesus** [comment]
So I think I might have it.  Strangely it requires minigzip, though.

**Comment by KungFuJesus** [comment]
Hmm, I can't reproduce the failure though.  It might be very specific to their window size.  Looks like their window length is 21 bytes?  I'm not entirely sure if we're setting that or they are

**Comment by nmoinvaz** [comment]
`minideflate` I think has args for the window size.

**Comment by KungFuJesus** [comment]
> `minideflate` I think has args for the window size.

This file doesn't seem to work through minideflate, though.

**Comment by KungFuJesus** [comment]
```
adam@eggsbenedict ~/scratch/libgit2/build $ ~/scratch/zlib-ng/badbuild/minideflate -k -d -c /tmp/pack_git2_3d498e78704d3a02.gz
Failed to open file: /tmp/pack_git2_3d498e78704d3a02.gz
adam@eggsbenedict ~/scratch/libgit2/build $ ~/scratch/zlib-ng/badbuild/minideflate -k -d -c /tmp/pack_git2_3d498e78704d3a02
Failed to open file: /tmp/pack_git2_3d498e78704d3a02
adam@eggsbenedict ~/scratch/libgit2/build $ ~/scratch/zlib-ng/build/minideflate -k -d -c /tmp/pack_git2_3d498e78704d3a02.gz
Failed to open file: /tmp/pack_git2_3d498e78704d3a02.gz
```
Neither the artifact of the bad build nor the good one are able to do anything with it with minideflate.  minigzip on the other hand likes it just fine:

```
adam@eggsbenedict ~/scratch/libgit2/build $ ~/scratch/zlib-ng/build/minigzip -k -d /tmp/pack_git2_3d498e78704d3a02.gz
adam@eggsbenedict ~/scratch/libgit2/build $ ~/scratch/zlib-ng/build/minigzip -k -c -d /tmp/pack_git2_3d498e78704d3a02.gz
PACKFxÌANÄ0
           Ð}O]6PÅqâ$BpvpÛq$ÚÄñé,æ쾾Þÿûfæ(ÄÀ(µçNHSS4£ÅBjAyºðfëîÈ ÃA
                                                                   @j#ICBR°VKdñîGAi

D@H"AéC»Úñ")Ý}¥²^X02åÂ[ɥjfàQëÄ×ýtÞܫûpï·ðÄóu¾U/öËËåÛf=/ÏbD÷ÓÑ._ûnÿNo¶}W=ُóêïÞñڝ7?ýÃ`nxKj1D÷:Eï¼ÊÐ-~Brìâ´Z-ې1Bßã/àUz5º*¤æ±0ù:gç]"'ԢÍ	Ñ
V9«+w]TGÍsÀ:cÐ䨢%±Ø]®<!­;ö¡,VKÞgTm9:L]Øs?f
Qf÷qÞ:üÀþ哧ÛôDßzçåú¯lËÍdçèà#¢ÙérCßPͯöBé¼Ê|Ë:6(æ[iQä@xÅtQ·¤(5U!9Å$)9-ÙÈ<%ÑÌ(Ù,ÉÂÄ %ÕÜÀ )Õ0ÙÌ Ñ<ÕÌÒÒÔ(Ñtbl±ÁĽÆæÆ
º@5\\nù¥E%
ú\7·ûá_x»ÇxqB/£áÄ>+QCc]s.®̢DýDC.°<	NxAjÄ0
                                              E÷9v³j¥±eC)íºk`)rg Iã¿E/PøÏã½ÑÝI+ÓÂé\<D$£b(TP¤V­Õ2Ýj÷m@ dE^,d¦De;S<+ªå?_Z&Ê\*5/°qNG¦¦Ü
YlÃâM¦z½ÃÂÇã<×ù>?ЫÿÔõöí³íë
                          ¨
xËm                        O(ÓA×ëþtz÷þ堽nvຍlún«Q
Â0
  áÿ=E.àL³ui@DϠ ]SÜ£¯»ÿ^xëj:d$}aër
hRGs±LX[tµ©BÆ^½OÙ(IQâÛhP-È29Ýês^á
¸ïqÒfkvºØGÇåmÍ0gðޓx
ÒÂÑýt|Õj¬îfÃ<eHÇDî
x[                 ³w@ê
xËQÿ³ـ5d"ºuÌû ¤àòm·àßápîm*°÷l3TI4SñìX\ï°'R¦Øû$Q23/:6¨6Yªèd+!F٪PÄ²çXJ®âØðÚ^Ó7xÂc3wk·««~y?ÚÕi¸"º.xíښÍïÖ􏩹kFr,h~u³@¦
Â0
  á÷¢p&ig:ÑO Hº
               ΍ځÇ×]Á·þZÌ|¢AÉ8qà¶S9¨t9plÝ"Å^էÐÓ1 æ>w2²&JÚÁ,j	¬õ1ñwÛâ(ÍÚlt¶LËӚ<O'Ô!E~
xËM                                                                                      à~:µÚ«»å]½îÜ%_@m
Â0@á}N
      X3L~@D7@i&(X[b
_{w^o"S
Â0     ¡F[݈ÍhK±z¦j\69WZrW×Y§ÄL 9)<ãØR*è|%ô¢òÚïsÓg}Ó×-yXNòÉÓòa§£L¬ޙ`úéôè]þXÕåÑÞ]óA}Û?ð
  ÿ3E 8uêÖB008>T¥ãSVàïtº««Wc"*Ôl!õ¢ÔAͬȉ²[dµ©z=Ô8É2wî9E¤¢Ð
```
Clearly not a plaintext format.

**Comment by nmoinvaz** [comment]
Perhaps it has a hard time auto-detecting the wrapper? Have you tried `-w 15 -s 4` for `minideflate`? 15 for window bits, and 4 for `Z_FINISH`.

**Comment by KungFuJesus** [comment]
```
adam@eggsbenedict ~/scratch/libgit2/build $ ~/scratch/zlib-ng/build/minideflate -k -w 15 -s 4 -d /tmp/pack_git2_3d498e78704d3a02.gz
Failed to open file: /tmp/pack_git2_3d498e78704d3a02.gz
```

**Comment by nmoinvaz** [comment]
Can you attach your files here?

**Comment by KungFuJesus** [comment]
Sure.
[pack_git2_3d498e78704d3a02.gz](https://github.com/zlib-ng/zlib-ng/files/13419768/pack_git2_3d498e78704d3a02.gz)

**Comment by nmoinvaz** [comment]
That appears to be a git pack file. AFAIK it shouldn't be working in `minigzip` or `minideflate`. I wasn't able to reproduce the `Failed to open file: `, but instead `minideflate` returned a -3. And `minigzip` just copied the file instead of inflating it. Perhaps that copy functionality has to do with this function: https://github.com/zlib-ng/zlib-ng/blob/6592accb2541aa637844cabef16b7adbb4cec4e1/gzread.c.in#L144

There is a probably an GZIPPED object in that PACK file that it is failing on. From what I can tell there is a PACK index that contains the offsets to each gzip data. It might be easier to loop through and grab that gzip test to test against if I had that PACK index file. Or perhaps you could look in the debugger and see the first several bytes of the failed data stream and we can find it with a hex editor?

**Comment by nmoinvaz** [comment]
I am having trouble reproducing simplifying the test case as well. @KungFuJesus your code to write the bad file is good. 

I think there may be a bug in `git_packfile_stream_read` that it is sending more input after `Z_FINISH` flush type is initially sent. What I am seeing is it sends 25 bytes with `Z_FINISH` and then sends 21 bytes with `Z_FINISH`.

**Comment by KungFuJesus** [comment]
> I am having trouble reproducing simplifying the test case as well. @KungFuJesus your code to write the bad file is good but I don't think it is writing out the entire file.
> 
> ```c
> int git_packfile_stream_open(git_packfile_stream *obj, struct git_pack_file *p, off64_t curpos)
> {
> 	memset(obj, 0, sizeof(git_packfile_stream));
> 	obj->curpos = curpos;
> 	obj->startpos = curpos;
> 
> ...
> 
> if ((error = git_zstream_get_output_chunk(buffer, &len, &obj->zstream)) < 0) {
>           git_mwindow_close(&obj->mw);
>           in = pack_window_open(obj->p, &obj->mw, obj->startpos, &window_len);
>           FILE *badFile = fopen("/tmp/git_bad_stream.deflate", "w");
>           fwrite(in, sizeof(char), window_len, badFile);
>           fclose(badFile);
>           git_error_set(GIT_ERROR_ZLIB, "error reading from the zlib stream (out chunk)");
>           return -1;
>       }
> ```
> 
> I think there may be a bug in `git_packfile_stream_read` that it is sending more input after `Z_FINISH` flush type is initially sent. What I am seeing is it sends 25 bytes with `Z_FINISH` and then sends 21 bytes with `Z_FINISH`. AFAIK it should only be sending `Z_FINISH` then there is no more input data. It does not reset using `inflateReset` between calls with `Z_FINISH`.
> 
> https://github.com/libgit2/libgit2/blob/d9475611fec95cacec30fbd2c334b270e5265d3b/src/util/zstream.c#L104C2-L110C3
> 
> For `-s=online::clone`:
> 
> ```
> offset 6027 len 25
> window len 6052 offset 0
> in 25 flush 4
> in_used 25
> offset 6052 len 21
> window len 6073 offset 0
> in 21 flush 4
> ```
> 
> It seems like there is some network call (probably why it is hard to consistently reproduce it) in this test that is streaming in data and sending it to be decompressed, therefore the initial call to `pack_window_open` doesn't return the entire `window_len`, it returns only first 25 bytes. Again, I think that might be a problem if `Z_FINISH` is going to be used. Using `zstream->flush = Z_NO_FLUSH;` causes the tests to pass, however `Z_FINISH` should also be called at the end.
> 
> ![image](https://user-images.githubusercontent.com/1364432/284765928-ee7d8161-c8b3-44ed-9859-1530ab40bfe5.png)

Interesting, so I guess maybe it's not pulling the entire request through the socket?  That wouldn't quite explain the issue reported with pigz-ng, though.  Either that, or pigz-ng behaves the same way (the reported issue certainly isn't dealing with HTTP streams there, though).  In the interest of behaving compatibly with things interacting with zlib, I still think we should merge the PR.

**Comment by nmoinvaz** [comment]
I was wrong, so I deleted my comment. What I did find, I posted in the PR.

**Comment by KungFuJesus** [comment]
This issue should be fixed with PR 1600, now. Unknown on that other issue with pigz-ng without confirmation from the filer, but seems probable.

**Comment by joebonrichie** [comment]
Resolved for me. Thanks for the work!
