### ISSUE TITLE
Benchmarks: Consider adding minimal libwebp decoding tests

### ISSUE THREAD

**Issue by joebonrichie** [zlib-ng/zlib-ng#1606]
Related to #1170.

Very similarly to `libpng`, `libwebp` gets a good speedup from being used with zlib-ng. Consider adding some webp decoding tests as part of "Application Specific Benchmarks" to keep an eye on performance.

*Tested Libs*
Canonical zlib:    v1.3; built with UNALIGNED OK, O3, LTO and using x86-64-v3 hwcaps libs
zlib-ng-compat:  v2.1.5; built with O3, LTO, PGO and using x86-64-v3 hwcaps libs

*Against*
libwebp: v1.3.2; built with O3, LTO, and using x86-64-v3 hwcaps libs

Test Case: `hyperfine "dwebp 3.webp -o /dev/null"`  
Test File: https://www.gstatic.com/webp/gallery/3.webp
canonical: mean 197.8 ms
zlib-ng: mean 87.6 ms

Test Case: `hyperfine "dwebp 4.webp -o /dev/null"`  
Test File: https://www.gstatic.com/webp/gallery/4.webp
canonical: mean 89.5 ms
zlib-ng : mean 66.7 ms

In my testing I did not measure a speedup from encoding webp files only decoding unless the files being encoded were being encoded from png files. This speedup is purely due to the existing speedup from decoding png files. You may not get the same results as I due to use of aggressive compiler optimizations & making use of glibc hwcaps functionality.

**Comment by mtl1979** [comment]
You are free to submit a pull request to add more benchmarks... Once the pull request is created, other contributors can help with any issues integrating with zlib-ng, including conforming to our coding style.

Adding new benchmarks is two-fold issue... We add tests to catch compatibility issues and benchmarks to catch regressions causing speed penalty. Especially when it comes to compatibility mode of zlib-ng, we have low tolerance on any compatibility issues introduced by new changes to zlib-ng.

**Comment by joebonrichie** [comment]
dwebp encodes to .png by default, encoding to -yuv doesn't show much of a speed up. Methodology was flawed, much of the speedup in libpng once again. Closing.
