### ISSUE TITLE
functable overhead

### ISSUE THREAD

**Issue by haampie** [zlib-ng/zlib-ng#1608]
I traced zlib-ng with perf and noticed that the `quick_insert_string` function call is the 'hottest' couple instructions in `deflate_medium` when compiled with GCC 13.2.0:

![image](https://github.com/zlib-ng/zlib-ng/assets/194764/65754326-81a4-48ac-b49e-1d8f7d6a433e)

Replacing that function pointer directly with `quick_insert_string_sse42` makes the overhead go away.

Makes me wonder: has zlib-ng considered using ifunc (gcc extension) instead of function pointers? Is there a way to make the dispatch static instead of dynamic when targeting a specific architecture?

Edit: ah, it's actually dynamic cause the implementation depends on certain parameters... In any case, looks like at runtime the function is resolved every call even if it's effectively constant.

**Comment by phprus** [comment]
Try removing ``Z_TLS`` from the ``functable`` definition to avoid tls overhead.
This should be safe to execute on x86(_64), but may generate ThreadSanitizer warnings.

**Comment by haampie** [comment]
That fixes it yeah. I don't think there's any significant gain though, would have to do a proper benchmark.

**Comment by nmoinvaz** [comment]
We could do what we did with `inflate_fast` (in that it uses a template and there is a separate version of it for each instruction set) but do it for all the deflate algorithms as well.

**Comment by nmoinvaz** [comment]
> Replacing that function pointer directly with quick_insert_string_sse42 makes the overhead go away.

What does the overhead equate to in terms of performance?

**Comment by phprus** [comment]
Which is greater: TLS overhead or overhead of calling a function by pointer?

**Comment by phprus** [comment]
If the main overhead is in TLS, then I have one idea on how to remove it for x86 and arm.

**Comment by KungFuJesus** [comment]
If I had to guess it'd probably be TLS overhead. Initializing the tables before an lwp fork would certainly fix that, I would think.

TLS requires this weird indirection through the segment registers on x86.

**Comment by phprus** [comment]
``functable`` without TLS:
https://github.com/phprus/zlib-ng/tree/functable-atomic-1

Requires all CPUs cores to support the same instruction set.

**Comment by nmoinvaz** [comment]
Your branch changes look interesting.

**Comment by KungFuJesus** [comment]
Oh yeah, 64 bit atomics would also be a much more straightforward and obvious approach, hah.  At least it prevents the torn store situation.  To date I don't think I've seen an architecture that has some cores that support some instructions and some that don't (the AVX512 lunacy with early Adler Lake is the closest example I can think of, but they still presented a homogeneous ISA to the user).   Even if that scenario did exist, though, TLS doesn't protect you from an illegal instruction on another core unless you are evaluating the CPU capabilities before launch every time, because threads can be migrated to different cores.

**Comment by phprus** [comment]
PR for review and testing: #1609

**Comment by nmoinvaz** [comment]
The following changes have been made in `develop`:
* `functable` no longer uses `Z_TLS`
* Implemented `-D WITH_RUNTIME_CPU_DETECTION=OFF` which should further reduce any overhead
* `inflate_fast` is also now a part of `functable`
