### ISSUE TITLE
Codecov upload errors

### ISSUE THREAD

**Issue by Dead2** [zlib-ng/zlib-ng#1639]
So, the past few days we are (again) having problems with CI failing due to upload errors.

One is the usual 502 (i think) error where the codecov uploader cannot fetch a storage url.

And also, with every release there ends up just being too many uploads for codecov so it errors out with:
```[2024-01-12T12:54:33.401Z] ['error'] There was an error running the uploader: Error uploading to [https://codecov.io:](https://codecov.io/) Error: There was an error fetching the storage URL during POST: 400 - [ErrorDetail(string='Too many uploads to this commit.', code='invalid')]```

One possible solution could be to have each workflow collect and upload together (ie: per yaml file).
This would reduce our upload count, and make retrying uploads easier (no need to recompile and rerun tests for all the failed uploads).
It would also reduce tracking of coverage per job harder, so an option here would be to for example make labels per arch or something to retain some of the detail.

Another option (for the release builds) is to somehow make sure we don't re-upload the same workflow job for different branches when they have the same commit. (Upon release, we push the same commit to `Develop`, `Stable` and `2.1.x`, causing all tests and uploads to be run three times). If we could somehow cache workflow_job+commit results and just skip the tests and return a success based on the cache (but re-run if failed). That would leave those jobs without logs though, so we'd have to hunt down the log from another branch (unless we just replayed the logs? a little bit dirty perhaps).

The best would have been if Github just reused the actions workflow results automatically (it would have to be a setting/parameter per workflow, to signal that this workflow ignores what branch it comes from), but I don't think anything like that exists.

<br>
Does anyone have experiences with any solutions like this or know of solution examples from other projects?

**Comment by mtl1979** [comment]
HTTP 502 error means rate limit was exceeded, the uploader should retry after few seconds. This is very common if the destination server uses reverse proxy like CloudFlare.

What comes to error HTTP error 400 (```Too many uploads to this commit.```), one solution would actually be for them to use a proxy that checks the repository, coverage tag and commit hash from the request and if combination of those all is already as key in cache, link with cached result.

**Comment by nmoinvaz** [comment]
> One possible solution could be to have each workflow collect and upload together (ie: per yaml file).

This is possible. I haven't had the need to do anything like that before though.

> Another option (for the release builds) is to somehow make sure we don't re-upload the same workflow job for different branches when they have the same commit. (Upon release, we push the same commit to Develop, Stable and 2.1.x, causing all tests and uploads to be run three times). If we could somehow cache workflow_job+commit results and just skip the tests and return a success based on the cache (but re-run if failed). 

It sounds very complex and like a scenario that only you would run into.

**Comment by Dead2** [comment]
> It sounds very complex and like a scenario that only you would run into.

It very much is, however the end result is that on our front page (readme) the badges show the Stable build as failed. Not a huge problem, but probably not the impression we want to make on other people. The stable badge will keep saying `Failing` until next release now, will test to only push the release commit to `stable` and `2.1.x`, and only once those are ok push it to `develop` as well.. If I remember

**Comment by nmoinvaz** [comment]
I think if we fix the first problem, it will also fix the second.
