### ISSUE TITLE
Compatibility regression on zlib-ng-git

### ISSUE THREAD

**Issue by ms178** [zlib-ng/zlib-ng#1661]
With 20498320cdd38ac6db265596598e47e2d0602850 and compiled with Clang-19 via autoconf with `--zlib-compat`, I now see a build failure `configure: error: zlib not installed` when trying to compile libpng-git. This used to work fine with earlier snapshots of zlib-ng.

**Comment by ms178** [comment]
Further testing revealed, that I can only reproduce this failure when zlib-ng was compiled with a very recent Clang-19 snapshot (49ee2ffc65b7660bfe84cd842e083d6c0ee3e991), not when it was compiled with GCC 13.2.1 - this might be a compiler issue after all.

**Comment by mtl1979** [comment]
It's always a bad idea to use unstable or snapshot versions of compilers for anything else than testing the actual compiler... zlib-ng doesn't even support `autoconf`, so it's completely unsupported and thus can't be a regression in zlib-ng itself.

Whenever there is any issue, it's always required to post full build logs including any command-line parameters for each step, as otherwise we can't add workarounds for any compatibility issues.

**Comment by ms178** [comment]
It would be great to know if zlib-ng-git was tested against a stable version of Clang? 

If there were build failures, I would have provided logs but the zlib-ng build itself went fine, just after installation, the generated binary seems to be broken (and points to a fairly recent regression somewhere as I could build a working zlib-ng-git binary with an older Clang-19 snapshot a couple of days ago). 

Good to know that the configure/make way is now unsupported. As I just noticed, Arch upstream does use CMAKE nowadays and will switch my personal PKGBUILD over to use that instead.

Here is the old one:

[PKGBUILD.txt](https://github.com/zlib-ng/zlib-ng/files/14213490/PKGBUILD.txt)

OS is CachyOS. 

Here are the flags used in /etc/makepkg.conf:

```
export CC=clang
export CXX=clang++
export CC_LD=lld
export CXX_LD=lld
export AR=llvm-ar
export NM=llvm-nm
export STRIP=llvm-strip
export OBJCOPY=llvm-objcopy
export OBJDUMP=llvm-objdump
export READELF=llvm-readelf
export RANLIB=llvm-ranlib
export HOSTCC=clang
export HOSTCXX=clang++
export HOSTAR=llvm-ar
export CPPFLAGS="-D_FORTIFY_SOURCE=0"
export CFLAGS="-O3 -march=native -mtune=native -maes -mbmi2 -mpclmul -mllvm -inline-threshold=1500 -mllvm -extra-vectorizer-passes -mllvm -enable-cond-stores-vec -mllvm -slp-vectorize-hor-store -mllvm -enable-loopinterchange -mllvm -enable-loop-distribute -mllvm -enable-unroll-and-jam -mllvm -enable-loop-flatten -mllvm -interleave-small-loop-scalar-reduction -mllvm -unroll-runtime-multi-exit -mllvm -aggressive-ext-opt -mllvm -enable-interleaved-mem-accesses -mllvm -enable-masked-interleaved-mem-accesses -fno-math-errno -fno-trapping-math -falign-functions=32 -funroll-loops -fno-semantic-interposition -fcf-protection=none -mharden-sls=none -fomit-frame-pointer -mprefer-vector-width=256 -flto -fwhole-program-vtables -fsplit-lto-unit -mllvm -adce-remove-loops -mllvm -enable-ext-tsp-block-placement -mllvm -enable-gvn-hoist -mllvm -enable-dfa-jump-thread -Wno-error -ffp-contract=fast -fdata-sections -ffunction-sections -fno-unique-section-names -fsplit-machine-functions -fgnuc-version=6.5.0"
export CXXFLAGS="${CFLAGS} -Wp,-U_GLIBCXX_ASSERTIONS"
export LDFLAGS="-Wl,--lto-CGO3 -Wl,--gc-sections -Wl,--icf=all -Wl,--lto-O3,-O3,-Bsymbolic-functions,--as-needed -fcf-protection=none -mharden-sls=none -Wl,-mllvm -Wl,-extra-vectorizer-passes -Wl,-mllvm -Wl,-enable-cond-stores-vec -Wl,-mllvm -Wl,-slp-vectorize-hor-store -Wl,-mllvm -Wl,-enable-loopinterchange -Wl,-mllvm -Wl,-enable-loop-distribute -Wl,-mllvm -Wl,-enable-unroll-and-jam -Wl,-mllvm -Wl,-enable-loop-flatten -Wl,-mllvm -Wl,-interleave-small-loop-scalar-reduction -Wl,-mllvm -Wl,-unroll-runtime-multi-exit -Wl,-mllvm -Wl,-aggressive-ext-opt -Wl,-mllvm -Wl,-enable-interleaved-mem-accesses -Wl,-mllvm -Wl,-enable-masked-interleaved-mem-accesses -march=native -maes -mbmi2 -mpclmul -flto -fwhole-program-vtables -fuse-ld=lld -Wl,-zmax-page-size=0x200000 -Wl,-mllvm -Wl,-adce-remove-loops -Wl,-mllvm -Wl,-enable-ext-tsp-block-placement -Wl,-mllvm -Wl,-enable-gvn-hoist -Wl,-mllvm -Wl,-enable-dfa-jump-thread -Wl,--push-state -Wl,-whole-archive -ljemalloc_pic -Wl,--pop-state -lpthread -lstdc++ -lm -ldl -Wl,--undefined-version"
export CCLDFLAGS="$LDFLAGS"
export CXXLDFLAGS="$LDFLAGS"
export ASFLAGS="-D__AVX__=1 -D__AVX2__=1 -D__FMA__=1"
```

**Comment by ms178** [comment]
By the way, the new Cmake-based PKGBUILD runs some checks which all pass with the current Clang-19 snapshot and the mentioned cflags. Update: The Clang-built binary doesn't work with that way either.

[CTestCostData.txt](https://github.com/zlib-ng/zlib-ng/files/14213740/CTestCostData.txt)
[LastTest.log](https://github.com/zlib-ng/zlib-ng/files/14213741/LastTest.log)
[CMakeCache.txt](https://github.com/zlib-ng/zlib-ng/files/14213752/CMakeCache.txt)

**Comment by mtl1979** [comment]
When using configure, libpng should create `config.log` which has output from all the tests including when it tries to find zlib and `zlibVersion` function.

**Comment by mtl1979** [comment]
I tested with clang 17.0.2 (which is latest I have), libpng-1.6.29 and development version of zlib-ng and it did output:

`-- Found ZLIB: /mnt/c/build/git/zlib-ng/clang-17-compat/libz.so (found version "1.3.0")`

I installed clang 18.1.0 and clang 19.0.0 and tested without passing custom root for zlib installation and this is what I got:

```
-- The C compiler identification is Clang 19.0.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /usr/bin/clang-19 - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Found ZLIB: /usr/local/lib/libz.so (found version "1.3.1")
```

It obviously finds zlib-ng first as zlib version installed in Ubuntu is 1.2.13.

**Comment by ms178** [comment]
Thanks for taking a look!

Here is the log from lib32-libpng-git when lib32-zlib-ng-git was compiled with Clang-19:

[config.log](https://github.com/zlib-ng/zlib-ng/files/14225571/config.log)

I see: `ld.lld: error: undefined symbol: z_zlibVersion`

Ok, analyzing the log revealed an issue with the used PGO-profile: ` ld.lld: error: linking module flags 'ProfileSummary': IDs have conflicting values in '/usr/bin/../lib64/gcc/x86_64-pc-linux-gnu/13.2.1/../../../../lib32/libz.a(zutil.o at 432270)' and 'ld-temp.o'`

It finds zlib-ng and compiles fine if I delete the PGO-profile.

Here is the log without the PGO-profile: 
[config_without_PGO.log](https://github.com/zlib-ng/zlib-ng/files/14225651/config_without_PGO.log)
