### ISSUE TITLE
Migrate from codecov/codecov-action@v3 to codecov/codecov-action@v4

### ISSUE THREAD

**Issue by mtl1979** [zlib-ng/zlib-ng#1674]
* Version 3 of codecov-action has been discontinued as it uses Node v16, which was discontinued in GitHub Actions
* Version 4 of codecov-action breaks support for forks as it will require implicitly adding CodeCov token in all forks due to switch to CLI version of upload tool, the command-line parameters have changed too...

Pros;
* Less upload errors due to too many coverity reports with same token
* No nagging about deprecation of Node v16 in build logs

Cons:
* Needs updating all forked repositories
* Some v3 features are still missing or unsupported

**Comment by nmoinvaz** [comment]
AFAIK, we don't use tokenless uploads and we always specify the token. So I don't think anything changes wrt forks.

**Comment by nmoinvaz** [comment]
This appears to be complete as your PR is now merged into `develop`.
