### ISSUE TITLE
Possible redefinition of OS_CODE on macOS

### ISSUE THREAD

**Issue by Blzut3** [zlib-ng/zlib-ng#1702]
When using upstream Clang 18 instead of Apple Clang included in Xcode, `TARGET_OS_MAC` is defined in addition to `__APPLE__` causing OS_CODE to be redefined.

```
In file included from zlib-ng/inflate.c:7:
zlib-ng/zutil.h:119:11: warning: 'OS_CODE' macro redefined [-Wmacro-redefined]
  119 | #  define OS_CODE 19
      |           ^
zlib-ng/zutil.h:107:11: note: previous definition is here
  107 | #  define OS_CODE  7
```

It looks like upstream zlib got rid of the TARGET_OS_MAC check: https://github.com/madler/zlib/commit/4bd9a71f3539b5ce47f0c67ab5e01f3196dc8ef9

**Comment by mtl1979** [comment]
This should be fixed with #1703.
