### ISSUE TITLE
MacOS CI builds failing

### ISSUE THREAD

**Issue by Dead2** [zlib-ng/zlib-ng#1719]
Seems an updated Github Actions MacOS image has broken our CI

From a quick look, I noticed the following:
- Configure fails without any good info.
- pip fails and suggests using pipx or venv.

**Comment by nmoinvaz** [comment]
> Configure fails without any good info.

You can get the logs from any failed CI run:
![image](https://github.com/zlib-ng/zlib-ng/assets/1364432/74040913-a65d-4e9d-898b-2e8d5ea3a653)

The first one shows:
```bash
=== ztest3622.c ===
#include <stdint.h>
#include <stdio.h>
#include <stdarg.h>
#include "zconf-ng.h"
int main() {
#ifdef STDC
  return 0;
#endif
  return 1;
}
===
gcc-11 -c -O2 -std=c11 -Wall -Wextra -DNDEBUG -DNO_FSEEKO -DNO_STRERROR -DWITH_GZFILEOP ztest3622.c
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/_types.h:32,
                 from /opt/homebrew/Cellar/gcc@11/11.4.0/lib/gcc/11/gcc/aarch64-apple-darwin23/11/include-fixed/stdint.h:61,
                 from /opt/homebrew/Cellar/gcc@11/11.4.0/lib/gcc/11/gcc/aarch64-apple-darwin23/11/include/stdint.h:9,
                 from ztest3622.c:1:
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/cdefs.h:554:30: error: missing ')' after "__has_attribute"
  554 | #if __has_cpp_attribute(clang::unsafe_buffer_usage)
      |                              ^
/Library/Developer/CommandLineTools/SDKs/MacOSX14.sdk/usr/include/sys/cdefs.h:554:31: error:  ':' without preceding '?'
  554 | #if __has_cpp_attribute(clang::unsafe_buffer_usage)
      |                               ^
(exit code 1)
Checking for ANSI C compliant compiler...  No.
Error: ANSI C compatible compiler needed, cannot continue.
** ./configure aborting.
--------------------
```
Perhaps it is related to this one?
https://github.com/protocolbuffers/protobuf/issues/9185

**Comment by phprus** [comment]
Draft: https://github.com/phprus/zlib-ng/tree/macos-ci-1

**Comment by nmoinvaz** [comment]
I'm not so sure reverting to `macos-13` is a good long-term solution. Regarding pip, I think we should use venv.

**Comment by phprus** [comment]
``macos-13`` - x86 tests
``macos-latest`` - ARM64 tests

If we don't need x86 tests on macos, I will remove ``macos-13`` after testing is complete.

**Comment by mtl1979** [comment]
Reverting to older version is usually only a temporary solution until "upstream" has fixed the issue or there is workaround that can be applied cleanly even after the upstream fix lands. Apple is known to break things and fix their regressions with considerable delay.

This isn't much different from Ubuntu breaking support for PowerPC/Power in later versions, thus requiring downgrade to older release.

**Comment by phprus** [comment]
@mtl1979 
This is gcc bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114007

Reverting to an older version (``macos-13``) is only needed for testing x86 macos.
All tests also run on ``macos-latest``.

**Comment by mtl1979** [comment]
> @mtl1979 This is gcc bug: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=114007
> 
> Reverting to an older version (`macos-13`) is only needed for testing x86 macos. All tests also run on `macos-latest`.

I have had my share of gcc bugs... Some took years to fix... One was still unfixed after 6 years even though several major releases of gcc were released in between.... As I said, sometimes reverting to older version is the best choice while waiting for permanent fix or solution. I'm still using gcc 6.5 myself as that was the last one that did work on my work server...
