### ISSUE TITLE
Issues with installing zlib-ng during the spack install gcc@12

### ISSUE THREAD

**Issue by mishra0960** [zlib-ng/zlib-ng#1724]
I still get error with zlib-ng. I am using Al92 on a DELL Server. I am doing exactly what is says on page https://spack-tutorial.readthedocs.io/en/latest/tutorial_stacks.html#setup-the-compiler. Here is what we have in my script

git clone --depth=100 --branch=releases/v0.22 https://github.com/spack/spack.git ~/spack
cd ~/spack 
. share/spack/setup-env.sh
spack --version
spack compiler find
spack env activate --create ~/stacks
spack env status
spack add gcc@12 %gcc@11 +binutils
spack env view disable
spack config edit
spack concretize
spack install

my gcc version is gcc-11.4.1 

The errors I get are 

==> Installing zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6 [10/31]
==> No binary for zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6 found: installing from source
==> Fetching https://github.com/zlib-ng/zlib-ng/archive/2.1.6.tar.gz
==> No patches needed for zlib-ng
==> zlib-ng: Executing phase: 'autoreconf'
==> zlib-ng: Executing phase: 'configure'
==> zlib-ng: Executing phase: 'build'
==> Error: ProcessError: Command exited with status 2:
    'make' '-j16' 'V=1'

5 errors found in build log:
130    /home/aidune/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL-DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DWITH_GZFILEOP -I/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src -c -o gzread.o /tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6kveajesfq473asln7viitn352gsokiy6/spack-src/gzread.c
     
131    make[1]: Leaving directory '/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src/arch/x86'

132    /home/aidune/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOPDHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL -DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DWITH_GZFILEOP -I/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src -c -o gzwrite.o /tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src/gzwrite.c

133    make[1]: Leaving directory '/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src/arch/x86'

 134    /home/aidune/spack/lib/spack/env/gcc/gcc -O2  -std=c11 -Wall -DNDEBUG -DHAVE_SYMVER -D_LARGEFILE64_SOURCE=1 -DHAVE_POSIX_MEMALIGN -DHAVE_ALIGNED_ALLOC -DHAVE_SYS_AUXV_H -DZLIB_COMPAT -DWITH_GZFILEOP -DHAVE_VISIBILITY_HIDDEN -DHAVE_VISIBILITY_INTERNAL-DHAVE_ATTRIBUTE_ALIGNED -DHAVE_BUILTIN_CTZ -DHAVE_BUILTIN_CTZLL -DX86_FEATURES -DX86_AVX2 -DX86_AVX512 -DX86_MASK_INTRIN -DX86_AVX512VNNI -DX86_SSE42 -DX86_SSE2 -DX86_SSSE3 -DX86_PCLMULQDQ_CRC -DX86_VPCLMULQDQ_CRC -DWITH_GZFILEOP -I/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src -c -o minigzip.o /tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src/test/minigzip.c
    
 135    /tmp/ccqvV2ZR.s: Assembler messages:
  >> 136    /tmp/ccqvV2ZR.s:212: Error: unsupported instruction `vpdpbusd'
  >> 137    /tmp/ccqvV2ZR.s:216: Error: unsupported instruction `vpdpbusd'
  >> 138    /tmp/ccqvV2ZR.s:268: Error: unsupported instruction `vpdpbusd'

 139    cp arch/x86/x86_features.o x86_features.o
  >> 140    make[1]: *** [Makefile:123: adler32_avx512_vnni.o] Error 1
 141    make[1]: Leaving directory '/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src/arch
            /x86'
  >> 142    make: *** [Makefile:167: arch/x86/adler32_avx512_vnni.o] Error 2
     143    make: *** Waiting for unfinished jobs....
     144    make[1]: Leaving directory '/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src/arch/x86'
     145    make[1]: Leaving directory '/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src/arch/x86'
     146    make[1]: Leaving directory '/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src/arch/x86'
     147    make[1]: Leaving directory '/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src/arch/x86'
     148    make[1]: Leaving directory '/tmp/aidune/spack-stage/spack-stage-zlib-ng-2.1.6-kveajesfq473asln7viitn352gsokiy6/spack-src/arch/x86'

**Comment by KungFuJesus** [comment]
If the compiler is working but the assembler isn't, it seems probable you're using a binutils that is too old.

**Comment by mishra0960** [comment]
My issue was solved by doing the following

spack compiler find
spack env activate --create ~/stacks
spack env status
spack add ***@***.*** +binutils ^zlib
spack env view disable
spack concretize
spack install
________________________________

**Comment by mtl1979** [comment]
This issue should be reported to spack repository if it isn't already... Seems like there is/was a dependency issue.

**Comment by mishra0960** [comment]
Hi Mika,

I did submit an issue report to spack.

The answer I got was to use an alternate solution

% spack add ***@***.*** +binutils ^zlib

This works for my software.

Shekhar

________________________________

**Comment by mtl1979** [comment]
@nmoinvaz This can be closed, not issue in zlib-ng itself.
