### ISSUE TITLE
`Z_NULL` isn't fully compatible with zlib

### ISSUE THREAD

**Issue by poscat0x04** [zlib-ng/zlib-ng#1733]
In zlib, `Z_NULL` is defined as `0` where in zlib-ng it is defined as `NULL`. This can cause type errors.

**Comment by mtl1979** [comment]
There are other small differences too... Some types are always `const` in zlib-ng but sometimes non-const in stock zlib. zlib-ng doesn't try to be 100% source compatible with zlib, as some types can be redefined in stock zlib, but are potentially unsafe when redefined to incorrect value or type.

**Comment by poscat0x04** [comment]
Can I close as wontfix now?

**Comment by phprus** [comment]
@mtl1979
As I see, ``Z_NULL`` is not used in zlib-ng code.
Maybe set ``Z_NULL`` to ``0`` in ``zlib.h`` for compatibility?

**Comment by mtl1979** [comment]
> @mtl1979 As I see, `Z_NULL` is not used in zlib-ng code. Maybe set `Z_NULL` to `0` in `zlib.h` for compatibility?

That's one possibility and we've already done same solution for similar issues...

**Comment by phprus** [comment]
@mtl1979 
PR #1736
