### ISSUE TITLE
Failed to build Wireshark with zlib-g and with WITH_GZFILEOP set

### ISSUE THREAD

**Issue by AndersBroman** [zlib-ng/zlib-ng#1743]
We are using gzopen() in a file this fails to build with the zlib-ng from vcpkg as zlib-ng.h has
<pre>
ifdef WITH_GZFILEOP
                        /* gzip file access functions */

/*
     This library supports reading and writing files in gzip (.gz) format with
   an interface similar to that of stdio, using the functions that start with
   "gz".  The gzip format is different from the zlib format.  gzip is a gzip
   wrapper, documented in RFC 1952, wrapped around a deflate stream.
*/

typedef struct gzFile_s *gzFile;    /* semi-opaque gzip file descriptor */

Z_EXTERN Z_EXPORT
gzFile zng_gzopen(const char *path, const char *mode);
</pre>

In findZLIBNG.cmake I added a check for zng_gzopen and if it exists set WITH_GZFILEOP 1
Now thw build fails as gzFile_s is defined twice:
<pre>
#ifdef WITH_GZFILEOP

/* gzgetc() macro and its supporting function and exposed data structure.  Note
 * that the real internal state is much larger than the exposed structure.
 * This abbreviated structure exposes just enough for the gzgetc() macro.  The
 * user should not mess with these exposed elements, since their names or
 * behavior could change in the future, perhaps even capriciously.  They can
 * only be used by the gzgetc() macro.  You have been warned.
 */
struct gzFile_s {
    unsigned have;
    unsigned char *next;
    z_off64_t pos;
};
</pre>
Comparing wit zlib.h the second defenition is guarded by
#ifndef Z_SOLO
perhaps this def is not needed in zlib-ng?

**Comment by mtl1979** [comment]
`Z_SOLO` shouldn't be defined when building without zlib compatibility, It was deprecated a long time ago, but added back to compatibility mode, because some projects relied on it being supported.

**Comment by AndersBroman** [comment]
Not sure what you are saying. In the current zlib-ng if you buld against the lib with WITH_GZFILEOP true(in the linking project) it fails. If it is not true you can't use zng_gzopen().
Some define is needed to skip the second definition of gzFile_s, if it is needed at all?

**Comment by AndersBroman** [comment]
"C:\development\build\Wireshark.sln" (default target) (1) ->
       "C:\development\build\ALL_BUILD.vcxproj.metaproj" (default target) (27) ->
       "C:\development\build\dumpcap.vcxproj.metaproj" (default target) (44) ->
       "C:\development\build\wsutil\wsutil_static.vcxproj.metaproj" (default target) (45) ->
       "C:\development\build\wsutil\wsutil_static.vcxproj" (default target) (107) ->
       (ClCompile target) -> 
         C:\development\wireshark-x64-libs\zlib-ng-2.1.5-1-x64-windows-ws\installed\x64-windows\include\zlib-ng.h(1792,8): error C2011: 'gzFile_s': 'struct' type redefinition [C:\development\build\wsutil\wsutil_static.vcxproj]

**Comment by AndersBroman** [comment]
The problem was that both zlib-ng.h and zlib.h was included in one place - sorry for the noice.
