### ISSUE TITLE
Failed to configure when cross compiling shared library with Android SDK

### ISSUE THREAD

**Issue by t3sserakt** [zlib-ng/zlib-ng#1748]
version 1.2.11

export NDK=/home/user/Android/Sdk/ndk/26.1.10909125
export TOOLCHAIN=$NDK/toolchains/llvm/prebuilt/linux-x86_64
export TARGET=$1
export API=$2
export AR=$TOOLCHAIN/bin/llvm-ar
export CC=$TOOLCHAIN/bin/$TARGET$API-clang
export AS=$CC
export CXX=$TOOLCHAIN/bin/$TARGET$API-clang++
export LD=$TOOLCHAIN/bin/ld
export RANLIB=$TOOLCHAIN/bin/llvm-ranlib
export STRIP=$TOOLCHAIN/bin/llvm-strip

PATH=$PATH:$TOOLCHAIN/bin/

./configure --shared

In the configure.log I got

No shared library support; try without defining CC and CFLAGS

I executed the test from line 421 of the configure script

/home/user/Android/Sdk/ndk/26.1.10909125/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android25-clang -shared -Wl,-soname,libz.so.1,--version-script,zlib.map -g -O0 -Wall -fPIC  -o ztest1181.so test.o
ld.lld: error: version script assignment of 'ZLIB_1.2.0' to symbol 'compressBound' failed: symbol not defined
ld.lld: error: version script assignment of 'ZLIB_1.2.0' to symbol 'deflateBound' failed: symbol not defined
ld.lld: error: version script assignment of 'ZLIB_1.2.0' to symbol 'inflateBack' failed: symbol not defined
ld.lld: error: version script assignment of 'ZLIB_1.2.0' to symbol 'inflateBackEnd' failed: symbol not defined
ld.lld: error: version script assignment of 'ZLIB_1.2.0' to symbol 'inflateBackInit_' failed: symbol not defined
ld.lld: error: version script assignment of 'ZLIB_1.2.0' to symbol 'inflateCopy' failed: symbol not defined
ld.lld: error: version script assignment of 'local' to symbol 'deflate_copyright' failed: symbol not defined
ld.lld: error: version script assignment of 'local' to symbol 'inflate_copyright' failed: symbol not defined
ld.lld: error: version script assignment of 'local' to symbol 'inflate_fast' failed: symbol not defined
ld.lld: error: version script assignment of 'local' to symbol 'inflate_table' failed: symbol not defined
ld.lld: error: version script assignment of 'local' to symbol 'zcalloc' failed: symbol not defined
ld.lld: error: version script assignment of 'local' to symbol 'zcfree' failed: symbol not defined
ld.lld: error: version script assignment of 'local' to symbol 'z_errmsg' failed: symbol not defined
ld.lld: error: version script assignment of 'local' to symbol 'gz_error' failed: symbol not defined
ld.lld: error: version script assignment of 'local' to symbol 'gz_intmax' failed: symbol not defined
ld.lld: error: version script assignment of 'ZLIB_1.2.0.2' to symbol 'gzclearerr' failed: symbol not defined
ld.lld: error: version script assignment of 'ZLIB_1.2.0.2' to symbol 'gzungetc' failed: symbol not defined
ld.lld: error: version script assignment of 'ZLIB_1.2.0.2' to symbol 'zlibCompileFlags' failed: symbol not defined
ld.lld: error: version script assignment of 'ZLIB_1.2.0.8' to symbol 'deflatePrime' failed: symbol not defined
ld.lld: error: version script assignment of 'ZLIB_1.2.2' to symbol 'adler32_combine' failed: symbol not defined
ld.lld: error: too many errors emitted, stopping now (use --error-limit=0 to see all errors)
clang-17: error: linker command failed with exit code 1 (use -v to see invocation)

What can I do to fix this?

Thx in advance.

**Comment by t3sserakt** [comment]
I s this 

` -Wl,--undefined-version`

a reliable fix?

**Comment by mtl1979** [comment]
The real issue is that `--version-script` is set too early in `LDSHAREDFLAGS` causing lld to choke...

**Comment by Dead2** [comment]
Fixed by #1750, please reopen if you still have problems.
