### ISSUE TITLE
current vs 1.9.9

### ISSUE THREAD

**Issue by divonlan** [zlib-ng/zlib-ng#1751]
A question rather than an issue:

I have data, now decompressed, that was originally compressed with zlib-ng 1.9.9. I need to recompress it to be binary identical to the original 1.9.9 compression, but I would rather use the most recent version if possible (assuming bug fixes and performance enhancements).

My question is: does the current version of zlib-ng produce binary-identical gz data to zlib-ng 1.9.9 (assuming the same function arguments of course)?

**Comment by Dead2** [comment]
No, the current version does not produce binary identical compressed data. We have had many minor changes to the compression strategies since 1.9.9 that can and do change the binary output.
