### ISSUE TITLE
Windows error C4242: 'function': Conversion from 'unsigned int' to 'Pos', possible loss of data

### ISSUE THREAD

**Issue by carlossanlop** [zlib-ng/zlib-ng#1760]
In the https://github.com/dotnet/runtime repo, we are getting a warning in Windows that was fixed back in 2019 by @nmoinvaz: https://github.com/zlib-ng/zlib-ng/issues/288

The errors:

```
C:\Users\calope\source\repos\runtime\src\native\external\zlib-ng\deflate_fast.c(61): error C4242: 'function': conversion from 'unsigned int' to 'Pos', possible loss of data
C:\Users\calope\source\repos\runtime\src\native\external\zlib-ng\deflate_quick.c(105): error C4242: 'function': conversion from 'unsigned int' to 'Pos', possible loss of data
C:\Users\calope\source\repos\runtime\src\native\external\zlib-ng\deflate_rle.c(61): error C4242: 'function': conversion from 'unsigned int' to 'Pos', possible loss of data
```

The offending code lines are:
- https://github.com/zlib-ng/zlib-ng/blob/d54e3769be0c522015b784eca2af258b1c026107/deflate_fast.c#L61
- https://github.com/zlib-ng/zlib-ng/blob/d54e3769be0c522015b784eca2af258b1c026107/deflate_quick.c#L105
- https://github.com/zlib-ng/zlib-ng/blob/d54e3769be0c522015b784eca2af258b1c026107/deflate_rle.c#L61

Which call `check_match` defined here, but has not been modified in the last 3 years: https://github.com/zlib-ng/zlib-ng/blame/develop/deflate_p.h#L14-L48

We're currently [consuming](https://github.com/dotnet/runtime/blob/main/src/native/external/zlib-ng-version.txt#L1) release https://github.com/zlib-ng/zlib-ng/releases/tag/2.1.6 (from January 10th)

This is how we build zlib-ng: https://github.com/dotnet/runtime/blob/main/src/native/external/zlib-ng.cmake

Note that we're suppressing wd4242 and wd4244 with a compile option but we _need_ to remove them as we should not be hiding memory warnings: https://github.com/dotnet/runtime/blob/efb09a57ddebfe213f43eea4289608031fe7795a/src/native/external/zlib-ng.cmake#L18-L19

I see there are a few newer releases that came after 2.1.6, and had several bug fixes, but I was unable to find a PR that looked like it fixed the issue. Is this a known problem? Any ideas how can I fix it?

**Comment by carlossanlop** [comment]
Looking deeper, the fixes from 2019 in #288 were for a different file than the one I listed above, `inffast.c`, which does not exist anymore in the `develop` branch. So these are new failures.

**Comment by carlossanlop** [comment]
I think the root cause is that ZLIB_DEBUG is turned on by default, in which case the `check_match` macro gets a proper definition, and that's when WD4242 and WD4244 show up.

But there's no simple way of turning on ZLIB_DEBUG because this line will unilaterally turn it on when building using the Debug configuration:

https://github.com/zlib-ng/zlib-ng/blob/d54e3769be0c522015b784eca2af258b1c026107/CMakeLists.txt#L562

I figured that we can include ZLIB_DEBUG among the [Build options](https://github.com/zlib-ng/zlib-ng?tab=readme-ov-file#build-options) so that it can be turned off using `set`. The default value can still be `ON`, but it will only invoke the like in the CMakeLists.txt if the config is Debug too.

I have a change locally that I proposed in the dotnet/runtime repo first, and then I can submit a PR here too: https://github.com/dotnet/runtime/pull/105433

**Comment by carlossanlop** [comment]
The ZLIB_DEBUG issue will only fix WD4244, but WD4242 happens in arm platforms coming from `slide_hash_chain`. I'm testing a separate fix for that, it's unrelated to ZLIB_DEBUG.

**Comment by mtl1979** [comment]
`Pos` is defined as `unsigned short`, so the warning is kinda correct... Easy fix would be to change the function signature to use `unsigned int` instead... As `check_match` is inlined function that isn't externally visible, it shouldn't break our ABI.

**Comment by carlossanlop** [comment]
> `Pos` is defined as `unsigned short`, so the warning is kinda correct... Easy fix would be to change the function signature to use `unsigned int` instead... As `check_match` is inlined function that isn't externally visible, it shouldn't break our ABI.

Thanks for the suggestion, I could consider it.

Im actively working on a fix in my dotnet/runtime PR. Would you mind taking a look? Once merged, I can send a PR here with the same changes. We would only have to review it once. https://github.com/dotnet/runtime/pull/105433
