### ISSUE TITLE
inflate_fast_avx2 causes corrupted -- crc32 mismatch with pigz

### ISSUE THREAD

**Issue by giuseppe** [zlib-ng/zlib-ng#1772]
Opening as a follow-up for https://github.com/madler/pigz/issues/123 (it contains more details)

Originally reported here: https://github.com/containers/podman/issues/23822

pigz fails with a  CRC32 mismatch error when decompressing a blob file. The same file passed the integrity check when tested with gzip.

Steps to reproduce:

Pull the container image with skopeo:
```
$ skopeo copy docker://docker.io/ollama/ollama:0.3.8-rocm oci:/var/tmp/ollama
```

Attempt to decompress the layer 1db71b1d7c67607172266cd839e3e429bf523aab5b0df4761fc0d05ec55dc727:

```
$ pigz -d < /var/tmp/ollama/blobs/sha256/1db71b1d7c67607172266cd839e3e429bf523aab5b0df4761fc0d05ec55dc727 > /dev/null
pigz: skipping: <stdin>: corrupted -- crc32 mismatch
```

The same file passes the integrity test with gzip:

```
$ gzip --test /var/tmp/ollama/blobs/sha256/1db71b1d7c67607172266cd839e3e429bf523aab5b0df4761fc0d05ec55dc727 && echo ok
ok
```

If I apply the following patch to disable using `inflate_fast_avx2`, the issue does not happen, `--without-unaligned` at configure time does not seem to make any difference:

```diff
diff --git a/functable.c b/functable.c
index dd8f7731..10abb358 100644
--- a/functable.c
+++ b/functable.c
@@ -115,7 +115,7 @@ static void init_functable(void) {
         ft.adler32_fold_copy = &adler32_fold_copy_avx2;
         ft.chunkmemset_safe = &chunkmemset_safe_avx2;
         ft.chunksize = &chunksize_avx2;
-        ft.inflate_fast = &inflate_fast_avx2;
+        //ft.inflate_fast = &inflate_fast_avx2;
         ft.slide_hash = &slide_hash_avx2;
 #  ifdef HAVE_BUILTIN_CTZ
         ft.compare256 = &compare256_avx2;
```

**Comment by Dead2** [comment]
What Fedora version is this on, and what specific rpm versions of pigz and zlib-ng?
And for the self-compiled zlib-ng, what release(s)/commit(s) is this tested with?

I see that Fedora 40 and Rawhide are still based on 2.1.7, but I am unsure what you were using.

**Comment by giuseppe** [comment]
> What Fedora version is this on, and what specific rpm versions of pigz and zlib-ng? And for the self-compiled zlib-ng, what release(s)/commit(s) is this tested with?

the error happens on Fedora 40.

The self-compiled zlib-ng is based on `develop`:

```
$ git log -1
commit e4fb3803afb8b46131abdeaaf927575d06621b0a
Author: Adeel Mujahid <3840695+am11@users.noreply.github.com>
Date:   Thu Aug 29 14:27:43 2024 +0300

    Address CR feedback
```

> I see that Fedora 40 and Rawhide are still based on 2.1.7, but I am unsure what you were using.

**Comment by KungFuJesus** [comment]
Doing a ton of time travel with our repo and pigz' and I don't have a smoking gun yet.  I do, however, find it strange that the file just happens to be above the 4GB mark and many of the zlib functions expect 32 bit arguments.  I'm starting to think that's a pretty important piece of the puzzle.

**Comment by Dead2** [comment]
I mirrored the 4GB file here, for easier download without needing Docker
http://mirror.circlestorm.org/1db71b1d7c67607172266cd839e3e429bf523aab5b0df4761fc0d05ec55dc727.gz

Edit: Add .gz to prevent browsers from unpacking the file while downloading..

**Comment by KungFuJesus** [comment]
@giuseppe are you sure your patch fixed the issue?  I'm not seeing any difference disabling those functions in the function table.  I was hoping that was a helpful clue but it's coming up empty.

**Comment by KungFuJesus** [comment]
Oh, "with_native" evidently overrides things in the function table these days.  I'll see if I can sniff it out.  Thanks for the report.
