### ISSUE TITLE
cmake version 3.30.2 warning about FetchContent_Populate

### ISSUE THREAD

**Issue by gdevenyi** [zlib-ng/zlib-ng#1788]
```
-- Git checking out GoogleTest release-1.12.1
CMake Warning (dev) at /usr/share/cmake-3.30/Modules/FetchContent.cmake:1953 (message):
  Calling FetchContent_Populate(googletest) is deprecated, call
  FetchContent_MakeAvailable(googletest) instead.  Policy CMP0169 can be set
  to OLD to allow FetchContent_Populate(googletest) to be called directly for
  now, but the ability to call it with declared details will be removed
  completely in a future version.
Call Stack (most recent call first):
  test/CMakeLists.txt:153 (FetchContent_Populate)
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by mtl1979** [comment]
I've seen "latest" cmake versions deprecate features that are still used actively for backwards compatibility... We try to support older cmake versions and having more than one way to do anything adds extra burden in maintaining the build scripts.

Personally I think we should only add "workarounds" when the function or feature is completely removed. Setting one specific CMake policy to `OLD` means we need to figure out when the policy was added, not when the recommended setting was changed from `OLD` to `NEW`. Almost always we want the `OLD` behaviour when it's still supported.

**Comment by gdevenyi** [comment]
Ref for policy, https://cmake.org/cmake/help/latest/policy/CMP0169.html

**Comment by gdevenyi** [comment]
The recommended "new" way (FetchContent_MakeAvailable) was added in 3.14 which is newer than the minimum version currently supported, so the only way for now is to silence the warning.

**Comment by mtl1979** [comment]
> The recommended "new" way (FetchContent_MakeAvailable) was added in 3.14 which is newer than the minimum version currently supported, so the only way for now is to silence the warning.

I only have cmake 3.11, so I can't test... Usually @nmoinvaz will update the tests as he has newer cmake version.
