### ISSUE TITLE
MemorySanitizer: SEGV on unknown address in deflate_medium.c:168

### ISSUE THREAD

**Issue by sebpop** [zlib-ng/zlib-ng#192]
MemorySanitizer:DEADLYSIGNAL
==4908==ERROR: MemorySanitizer: SEGV on unknown address 0x730fffffffff (pc 0x0000004b1b97 bp 0x7ffd4bf59a00 sp 0x7ffd4bf598a0 T4908)
==4908==The signal is caused by a READ memory access.
    #0 0x4b1b96 in fizzle_matches /home/spop/s/zlib-ng/deflate_medium.c:168:12
    #1 0x4b009c in deflate_medium /home/spop/s/zlib-ng/deflate_medium.c:296:21
    #2 0x4a181d in zng_deflate /home/spop/s/zlib-ng/deflate.c:951:18
    #3 0x497da9 in zng_compress2 /home/spop/s/zlib-ng/compress.c:59:15
    #4 0x4970cc in check_compress_level /home/spop/s/zlib-ng/test/fuzz/compress_fuzzer.c:18:3
    #5 0x496cc2 in LLVMFuzzerTestOneInput /home/spop/s/zlib-ng/test/fuzz/compress_fuzzer.c:70:3
    #6 0x496840 in main /home/spop/s/zlib-ng/test/fuzz/standalone_fuzz_target_runner.c:23:5

**Comment by mtl1979** [comment]
Most likely either n.match_start or n.strstart has invalid value... can't say which one... It's possible either one is zero, which would cause read of one byte before start of s->window.

**Comment by sebpop** [comment]
The last values before entering the loop and crash are:
```
n.strstart = 274
n.match_start = 5
MemorySanitizer:DEADLYSIGNAL
```

**Comment by sebpop** [comment]
and then the loop decrements both until we reach -1 which crashes:
```
orig = 272
match = 3
orig = 271
match = 2
orig = 270
match = 1
orig = 269
match = 0
orig = 268
match = -1
MemorySanitizer:DEADLYSIGNAL
```

**Comment by mtl1979** [comment]
```
if (n.match_start <= 0)
    break;
```
should stop the loop before that happens...

**Comment by nmoinvaz** [comment]
match_start is unsigned so will <= 0 condition apply?

**Comment by mtl1979** [comment]
You could try changing it to ```< 2```. and printing actual value of ```n.match_start``` before that line.

**Comment by sebpop** [comment]
Yes, `< 2` or `<= 1` works.
`< 1` fails.

**Comment by mtl1979** [comment]
Like I said, there was some weird bugs in deflate_medium... One less to be found ;)
