### ISSUE TITLE
[fuzzer] oss-fuzz timeouts

### ISSUE THREAD

**Issue by sebpop** [zlib-ng/zlib-ng#195]
I ran the fuzzers on my laptop and it stopped on timeouts at 25 sec.
I may need to split the fuzzer into several pieces.
I'm not sure what is the recommended way to fix the timeouts.
I will ask on oss-fuzz.

**Comment by mtl1979** [comment]
I would rather split it to multiple tests as that would allow seeing results of remaining sub-tests even if one sub-test takes too long to execute.

**Comment by sebpop** [comment]
Fixed in https://github.com/Dead2/zlib-ng/pull/181/commits/cb5e35c3920cf3a0654657ed091fab7671214358
