### ISSUE TITLE
Nginx Compile Error: "assignment discards 'const' qualifier from pointer target type"

### ISSUE THREAD

**Issue by PDowney** [zlib-ng/zlib-ng#196]
I'm not sure if I'm doing something incorrectly in relation to using zlib-ng with Nginx. When compiling Nginx 1.15.2 using GCC 8, the compile is failing here:

**src/http/modules/ngx_http_gzip_filter_module.c: In function 'ngx_http_gzip_filter_deflate':
src/http/modules/ngx_http_gzip_filter_module.c:837:26: error: assignment discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
         ctx->in_buf->pos = ctx->zstream.next_in;
                          ^
cc1: all warnings being treated as errors
objs/Makefile:1069: recipe for target 'objs/src/http/modules/ngx_http_gzip_filter_module.o' failed**

**Comment by mtl1979** [comment]
You're trying to assign read-only variable to another variable that is read-write...

**Comment by PDowney** [comment]
What could be causing this to happen though? I'm simply doing git clone on the develop branch and then compiling Nginx with it using --with-zlib=path

I've also tried compiling zlib-ng and installing it to a directory, then pointing nginx to that location instead. It still gets caught at the same point.

**Comment by mtl1979** [comment]
It's a bug in nginx, not zlib-ng. You can use const_cast as a work-around, but that will just mask the warning so it can't be treated as an error.
