### ISSUE TITLE
Integration of oss-fuzz in make test

### ISSUE THREAD

**Issue by sebpop** [zlib-ng/zlib-ng#204]
The requirements for an [ideal integration](https://github.com/google/oss-fuzz/blob/master/docs/ideal_integration.md) of a project in oss-fuzz are:
- Is maintained by code owners in their RCS (Git, SVN, etc).
- Is built with the rest of the tests - no bit rot!
- Has a seed corpus with good code coverage.
- Is continuously tested on the seed corpus with ASan/UBSan/MSan
- Is fast and has no OOMs
- Has a fuzzing dictionary, if applicable

**Comment by sebpop** [comment]
https://github.com/Dead2/zlib-ng/pull/181 has the initial set of patches for an ideal integration in oss-fuzz.

One item that I missed, and I will submit a patch shortly to fix that: we need the configure script to detect whether the compiler has ASan/UBSan/MSan and in that case compile and run the test/fuzz/*_fuzzer with the available sanitizers.  Done in https://github.com/Dead2/zlib-ng/pull/181/commits/2c56fddc24599752f0c1a6587cb95b3d1a0a97c1.

**Comment by sebpop** [comment]
To improve the code coverage, I will adapt the code from test/infcover.c to run under oss-fuzz.

**Comment by Dead2** [comment]
If you can make a separate cleaned-up PR with only the test implementation (no fixes for bugs found), I am quite eager to get it merged 👍

**Comment by sebpop** [comment]
I will prepare a patch that merges all the patches for test/fuzz into one.

I was not able to adapt the code in `test/infcover.c` for the fuzzers.  I think we will have to pick-up ideas and move them to the existing fuzzers: the checks in `test/infcover.c` are too strict and would be difficult to adapt to random input data.  For a given input they check a specific output, and I am not sure how much these strict tests would benefit in varying the input in a random way.

**Comment by sebpop** [comment]
Closing this ticket as the code of the fuzzers have been merged into develop branch.
I will send a patch to update the git location where oss-fuzz pulls from.
