### ISSUE TITLE
Port deflate_quick to ARM

### ISSUE THREAD

**Issue by sebpop** [zlib-ng/zlib-ng#205]
In #199 @Dead2 wrote:
> If only we could port deflate_quick to ARM too.

**Comment by sebpop** [comment]
deflate_quick is only called at compression level 1 on x86_64.
There is too much code to implement for aarch64/aarch32 before the release.
We may revisit this after the release.

**Comment by Myriachan** [comment]
ARM doesn't have anything similar to the `pcmpestri` SSE4.2 instruction used by the `compare258` function of `deflate_quick`.  This instruction is a huge part of the performance: it's used to do a miniature `strstr`-like operation to find matching patterns in the dictionary.

**Comment by nmoinvaz** [comment]
It seems like we could replace `match_len = compare258(s->window + s->strstart, s->window + s->strstart - dist)` with `match_len = longest_match(s, hash_head)` if SSE4.2 not supported. If that is the case, perhaps we could extend `compare258` to deflate_slow, deflate_medium, etc if SSE4.2 is supposed. So of like a `functable.longest_match`. What do you think?

**Comment by mtl1979** [comment]
compare258 is essentially compare of 256 bytes followed by compare of trailing 2 bytes... Only difference is that for all iterations of the loop, it needs to find the first non-matching index in the vector and calculate length from it... If we assume that it is likely that all lanes are equal most of the time, it should not have performance penalty when the trailing bytes are not equal. Trailing bytes can be handled using uint8_t, uint16_t, uint32_t and uint64_t.

**Comment by nmoinvaz** [comment]
This is now complete.
