### ISSUE TITLE
review and merge performance changes from chromium/zlib

### ISSUE THREAD

**Issue by sebpop** [zlib-ng/zlib-ng#219]
For the past year chromium.org pushed performance related changes in https://chromium.googlesource.com/chromium/src/third_party/zlib
See https://crbug.com/687631 for an explanation.

We need to review (analyze performance) and decide which changes need to be merged in zlib-ng.

**Comment by mtl1979** [comment]
Our policy is one issue per enhancement or bug fix, so we can track individual progress cleanly... Sometimes there is overlap between several patches or patch sets and that means they have to be either applied in specific order or merged as single issue.

**Comment by sebpop** [comment]
Understood. I will close this ticket and open one bug or pull request at a time.
