### ISSUE TITLE
[aarch64] performance of zlib-ng deflate compiled by gcc is 30% below the performance of zlib.org

### ISSUE THREAD

**Issue by sebpop** [zlib-ng/zlib-ng#266]
Similar bug to #263 except that this is when gcc targets aarch64, and it does not seem to be as much dependent on the input data as in the x86_64 bug.  Performance data from a HiKey970 A73 running at 2.36 GHz comparing the performance of zlib-ng against zlib.org when compiled with gcc and clang: https://gist.github.com/sebpop/dc90cc4da63f4a48573515e8f687fcbd

The patch #264 that I submitted to fix #263 does not fix this issue.

**Comment by sebpop** [comment]
The problem is that gcc does a lot more spills than clang in both longest_match() and deflate*(). The fact that the longest_match is not inlined makes gcc save and restore a bunch of registers.  With https://github.com/sebpop/zlib-ng/commit/dbca5814b405301e653eaebef3cb150685fcd359 that forces the compilers to inline longest_match we get better performance by avoiding the save restore regs.  I still have to measure the performance of that patch on different architectures, although on x86_64 it looks good so far: https://gist.github.com/sebpop/17d9c340cfaf16c1854017efefce6fc3

The patch only solves a part of the problem: gcc is still generating more spills and reloads than clang on aarch64.

**Comment by sebpop** [comment]
aarch64 clang performance is much worse with the patch: https://gist.github.com/sebpop/aec3e068a61c1daddf9c72ab4bc33281
Edit: I will have to rerun these numbers as the base was measured with "cpufreq-set -c 4 -g performance" which sets the cpu frequency to top performance 2.36 GHz, whereas the patch was measured with a cpu frequency pegged at 1.21 GHz.  Sorry for not having checked this before posting the diff numbers.

**Comment by Dead2** [comment]
Has anyone checked what version of longest_match is optimal on aarch64? And that goes for LLVM too.
There is a reason we kept 3 versions of that function after all :)

**Comment by sebpop** [comment]
That is a very good idea: I will benchmark the other two algorithms and see which one is best for aarch64.

For x86_64, inlining the current version of longest_match is a win for both clang and gcc.
gcc compiled zlib-ng improves up to 8% with the patch: https://gist.github.com/sebpop/451160356fc4e73541a1b8eef7dceb97

**Comment by sebpop** [comment]
I updated the performance difference of clang with the patch after rerunning the aarch64 experiment with the frequency set to 2.36 GHz: https://gist.github.com/sebpop/aec3e068a61c1daddf9c72ab4bc33281
With the patch, zlib-ng compiled by clang at -O3 improves overall and up to 3.6% on aarch64 hikey970.

With the patch, zlib-ng compiled by gcc at -O3 improves overall and up to 3.5% on aarch64 hikey970: https://gist.github.com/sebpop/f0d4e6bfd58d95b313c955b5d747a74f

**Comment by bmrzycki** [comment]
Hello @Dead2 , I work with @sebpop and he asked me to run the numbers comparing std1, std2, std3. 
Here is a summary of the testing:

Tested on https://github.com/zlib-ng/zlib-ng/commit/06bd4c8b105fc97cf4998d2ac22acbbc41df951a

GCC: https://github.com/gcc-mirror/gcc/commit/e5cb96dac5d7be
LLVM: https://github.com/llvm-project/llvm-project-20170507/commit/56e0888ce8787f

The following patch was applied to zlib-ng to allow me to alter the algorithm at configure-time:
```
diff --git a/zlib/ng_snappy/src/match.c b/zlib/ng_snappy/src/match.c
index fd55c3e1..ab86c8f8 100644
--- a/zlib/ng_snappy/src/match.c
+++ b/zlib/ng_snappy/src/match.c
@@ -11,23 +11,6 @@
 #include "zbuild.h"
 #include "deflate.h"

-#if (defined(UNALIGNED_OK) && MAX_MATCH == 258)
-
-   /* Only use std3_longest_match for little_endian systems, also avoid using it with
-      non-gcc compilers since the __builtin_ctzl() function might not be optimized. */
-#  if defined(__GNUC__) && defined(HAVE_BUILTIN_CTZL) && ((__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__) \
-        || defined(__LITTLE_ENDIAN__))
-#    define std3_longest_match
-#  elif(defined(_MSC_VER) && defined(_WIN32))
-#    define std3_longest_match
-#  else
-#    define std2_longest_match
-#  endif
-
-#else
-#  define std1_longest_match
-#endif
-

 #if defined(_MSC_VER) && !defined(__clang__)
 # if defined(_M_IX86) || defined(_M_AMD64) || defined(_M_IA64)
```

I also cherry-picked @sebpop 's patches to apply Google's snappy tester, as well as his patch to fix arm 32-bit configuration.

The tests were run in the following manner for both arm and aarch64:
```
# Repeat everything twice, once with gcc and once with clang.
# export CC=/path/to/gcc
# export CXX=/path/to/G++
for level in 1 2 3; do
    export CFLAGS="-O3 -Dstd${level}_longest_match"
    ./configure --with-benchmarks
done
```

The tests were done on a Hikey 970 device, core 4 (an A73) with the frequency locked to 1.2GHz to prevent thermal throttling (and to make comparisons to other devices a bit easier).

The decompress score are below and are the arithmetic mean where larger is better outputted from the chromium_zlib_bench tool in megabytes/sec.

> aarch64_h02_std1_gcc_e5cb96dac5d7be/score.out   = 12.194940
> aarch64_h02_std1_llvm_56e0888ce8787f/score.out  = 12.188393
> aarch64_h02_std2_gcc_e5cb96dac5d7be/score.out   = 12.430655
> aarch64_h02_std2_llvm_56e0888ce8787f/score.out  = 12.497619
> aarch64_h02_std3_gcc_e5cb96dac5d7be/score.out   = 12.760119
> aarch64_h02_std3_llvm_56e0888ce8787f/score.out  = 12.697619
> arm_h02_std1_gcc_e5cb96dac5d7be/score.out       =  9.564583
> arm_h02_std1_llvm_56e0888ce8787f/score.out      =  9.912202
> arm_h02_std2_gcc_e5cb96dac5d7be/score.out       =  9.844345
> arm_h02_std2_llvm_56e0888ce8787f/score.out      = 10.003869
> arm_h02_std3_gcc_e5cb96dac5d7be/score.out       =  7.969345
> arm_h02_std3_llvm_56e0888ce8787f/score.out      =  9.232440

The numbers for aarch64 don't really show much of a difference. There are wins and losses for all of them but it seems to be highly dependent on the source input files. If you'd like to see the raw data let me know and I can post it somewhere.

The case for arm, however, shows a strong preference for std2 on both gcc and llvm.  My recommendation is to check for GNUC (which both GCC and Clang define) and arm and prefer std2 in match.c as shown in this patch:
```
diff --git a/zlib/ng_snappy/src/match.c b/zlib/ng_snappy/src/match.c
index fd55c3e1..0b9dba25 100644
--- a/zlib/ng_snappy/src/match.c
+++ b/zlib/ng_snappy/src/match.c
@@ -12,11 +12,16 @@
 #include "deflate.h"

 #if (defined(UNALIGNED_OK) && MAX_MATCH == 258)
-
-   /* Only use std3_longest_match for little_endian systems, also avoid using it with
-      non-gcc compilers since the __builtin_ctzl() function might not be optimized. */
-#  if defined(__GNUC__) && defined(HAVE_BUILTIN_CTZL) && ((__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__) \
-        || defined(__LITTLE_ENDIAN__))
+    /* ARM 32-bit Clang/GCC builds perform better, on average, with std2. */
+#  if defined(__GNUC__) && defined(__arm__) && !defined(__aarch64__)
+#    define std2_longest_match
+    /* Only use std3_longest_match for little_endian systems, also avoid using
+     * it with non-gcc compilers since the __builtin_ctzl() function might not
+     * be optimized.
+     */
+#elif (defined(__GNUC__) && defined(HAVE_BUILTIN_CTZL) && \
+       ((__BYTE_ORDER__ == __ORDER_LITTLE_ENDIAN__) ||    \
+        defined(__LITTLE_ENDIAN__)))
 #    define std3_longest_match
 #  elif(defined(_MSC_VER) && defined(_WIN32))
 #    define std3_longest_match
```

**Comment by Dead2** [comment]
@bmrzycki That is very interesting results.
However, @sebpop committed PR #264 that changes std3_longest_match code in a way that changes its performance. So I would appreciate it if you could re-test based on a recent snapshot of the develop branch.
Actually, the same changes that were done in PR #264 might also be valid for std2_longest_match, and might then make that even faster.

Also, please test using -O2, since most distros will compile using -O2, especially for important libraries, we should probably spend more time optimizing for that rather than for what enthusiasts like us do.

**Comment by bmrzycki** [comment]
@Dead2 here are the updated runs you requested.

I ran these on https://github.com/zlib-ng/zlib-ng/commit/cb5166a3ed54e50b58340205a85a43934159ca87 for both arm 32-bit and aarch64.

I also bumped the nightly compilers of llvm and gcc to ones built on January 16. I altered the CFLAGS for all runs to the following:
```
export CFLAGS="-O2 -Dstd${i}_longest_match"
```
And I moved my previous patch on `match.c` to `match_p.h`.

The results are mostly the same.  For aarch64 recent gcc and llvm tip compilers std3 performs the best, but only by the slimmest of margins.

For arm 32-bit it's still clear std2 is preferred.
```
aarch64_h02_std1_gcc_0ca47588bd2e38/score.out = 12.200298
aarch64_h02_std1_llvm_2e8efbb084ae87/score.out = 12.317560
aarch64_h02_std2_gcc_0ca47588bd2e38/score.out = 12.475298
aarch64_h02_std2_llvm_2e8efbb084ae87/score.out = 12.658631
aarch64_h02_std3_gcc_0ca47588bd2e38/score.out = 12.779167
aarch64_h02_std3_llvm_2e8efbb084ae87/score.out = 12.896131
arm_h02_std3_gcc_0ca47588bd2e38/score.out = 7.964881
arm_h02_std3_llvm_2e8efbb084ae87/score.out = 9.522024
arm_h02_std1_gcc_0ca47588bd2e38/score.out = 9.641071
arm_h02_std2_gcc_0ca47588bd2e38/score.out = 9.919345
arm_h02_std1_llvm_2e8efbb084ae87/score.out = 9.925893
arm_h02_std2_llvm_2e8efbb084ae87/score.out = 10.049107
```

**Comment by sebpop** [comment]
Looking at the perf numbers @bmrzycki reported, the bug seems to have been fixed in a recent version of gcc.  The version of gcc for which I reported this bug is `gcc (Debian 6.3.0-18+deb9u1) 6.3.0 20170516`.
I am not sure it is worth keeping this bug open: closing for now.
@Dead2 please feel free to reopen this issue if you think we need to do something to address this performance issue on aarch64 with older gcc compilers.
