### ISSUE TITLE
DYNAMIC_CRC_TABLE build error

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#337]
When building with #define `DYNAMIC_CRC_TABLE`, functable.c references static variable _crc_table_empty_ and static function _make_crc_table_, which are found in crc32.c.

```
1>functable.c(107): error C2065: 'crc_table_empty': undeclared identifier
1>functable.c(108): warning C4013: 'make_crc_table' undefined; assuming extern returning int
```

**Comment by mtl1979** [comment]
I think we need "extern" declaration for those two symbols at the top of functable.c ... Makes no sense to create private header just so they can be used in two files.

**Comment by nmoinvaz** [comment]
Looks like this was merged. Thanks.
