### ISSUE TITLE
ZLIB-NG Benchmark

### ISSUE THREAD

**Issue by powturbo** [zlib-ng/zlib-ng#358]
zlib-ng is now integrated into [TurboBench - Compression Benchmark](https://github.com/powturbo/TurboBench).
Due to linker conflicts (in tree.c) it is not possible to 
have both zlib-ng (not zlib_compatible) and original zlib  compiled in the same executable.
The current zlib-ng (SSE4.2) in also benchmarked in the [Static/Dynamic web content compression benchmark](https://sites.google.com/site/powturbo/home/web-compression). Better compression and decompression speed than zlib. Decompression is even faster than brotli.

Here is another benchmark with large files
Text:enwik8 (100MB):
<pre><b>      C Size  ratio%     C MB/s     D MB/s   Name  (bold = pareto)</b> MB=1.000.0000
    36475786    36.5   <b>   21.08</b>   <b>  410.17</b>   <b>zlib_ng 9       </b>
    36475796    36.5      17.30     281.10   zlib 9          
    36548925    36.5   <b>   21.13</b>     280.70   <b>zlib 6          </b>
    36879096    36.9   <b>   28.39</b>     277.60   <b>zlib 5          </b>
    37022957    37.0   <b>   36.87</b>   <b>  440.90</b>   <b>zlib_ng 6       </b>
    42298778    42.3   <b>   63.79</b>     273.13   <b>zlib 1          </b>
    56030799    56.0   <b>  187.14</b>     351.88   <b>zlib_ng 1       </b>
   100000004   100.0   <b>14160.29</b>   <b>14351.32</b>   <b>memcpy          </b>
</pre>

Text 58% +binary 42%: silesia.tar
<pre><b>      C Size  ratio%     C MB/s     D MB/s   Name  </b>
    67646927    31.9   <b>   14.15</b>   <b>  464.59</b>   <b>zlib_ng 9       </b>
    67647204    31.9      11.46     349.50   zlib 9          
    68225985    32.2   <b>   26.60</b>     345.96   <b>zlib 6          </b>
    68504069    32.3   <b>   48.32</b>   <b>  479.54</b>   <b>zlib_ng 6       </b>
    69159650    32.6      37.20     339.46   zlib 5          
    77256401    36.5   <b>   74.80</b>     323.19   <b>zlib 1          </b>
   100862036    47.6   <b>  222.74</b>     433.71   <b>zlib_ng 1       </b>
   211948036   100.0   <b>13937.53</b>   <b>14077.31</b>   <b>memcpy</b>

**Comment by mtl1979** [comment]
Can you post the linker output here? We might fix so that it's possible to link against both libraries in the same executable... Most of the symbols are already prefixed in zlib-ng with compatibility mode disabled.

**Comment by powturbo** [comment]
/usr/bin/ld: zlib/deflate.o:(.rodata+0x0): multiple definition of `deflate_copyright'; zlib-ng_/libz-ng.a(deflate.o):(.rodata+0x0): first defined here
zutil.c:(.text+0x50): multiple definition of `zcfree'; zlib-ng_/libz-ng.a(zutil.o):zutil.c:(.text+0x50): first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile:526: turbobench] Error 1

compiled with gcc-8.3:
make ZLIB_ZNG=1

**Comment by mtl1979** [comment]
So it would be fixed something like this:

zlib symbol		| zlib-ng symbol
------------------------|----------------------------
deflate_copyright	| zng_deflate_copyright
inflate_fast		| zng_inflate_fast
inflate_table		| zng_inflate_table
inflate_copyright	| zng_inflate_copyright
_length_code		| zng_length_code
_dist_code		| zng_dist_code
_tr_init		| zng_tr_init
_tr_stored_block	| zng_tr_stored_block
_tr_flush_bits		| zng_tr_flush_bits
_tr_align		| zng_tr_align
_tr_flush_block		| zng_tr_flush_block
_tr_tally		| zng_tr_tally
z_errmsg		| zng_errmsg
zcalloc			| zng_calloc
zcfree			| zng_cfree

Last two use underscore for consistency with other symbols in zlib-ng.

**Comment by nmoinvaz** [comment]
@powturbo, how often is the benchmark run? Also, it seems zlib-ng is missing from Compressor results?

**Comment by powturbo** [comment]
New rebuild and benchmarks with the modified  "nmoinvaz/zlib-ng".
Not sure what are your expectations, but there is no doubt about the linked zlib-ng or the timings.
All benchmarks are repeated 15 times and each benchmark is repeated a minimum of 2 seconds.  
The CPU is not overclocked, the results are stable between several runs.
cmd: "./turbobench html8.dat -m -I15 -J15" (see [Turbobench Compression Benchmark](https://github.com/powturbo/TurboBench)). 
zlib is compiled directly from the sources w/ turbobench (gcc -O3). The used "libz-ng.a" can be found under the directory "zlib-ng_" . Note that the small average file length of 84k for this benchmark.
------------------------------------------------------------------------------------------------------------------------------
No more linker errors, but  conflict between "zlib.h" and "zlib-ng.h":
zlib-ng/zlib-ng.h:1055:61: error: conflicting declaration ‘typedef uint32_t (* in_func)(void*, const unsigned char**)’
 typedef uint32_t (*in_func) (void *, const unsigned char * *);
                                                             ^
In file included from plugins.cc:665:
zlib/zlib.h:1092:20: note: previous declaration as ‘typedef unsigned int (* in_func)(void*, unsigned char**)’
 typedef unsigned (*in_func) OF((void FAR *,

**Comment by powturbo** [comment]
New rebuild and benchmarks with the modified  "nmoinvaz/zlib-ng".
Not sure what are your expectations, but there is no doubt about the linked zlib-ng or the timings.
All benchmarks are repeated 15 times and each benchmark is repeated a minimum of 2 seconds.  
The CPU is not overclocked, the results are stable between several runs.
cmd: "./turbobench html8.dat -m -I15 -J15" (see [Turbobench Compression Benchmark](https://github.com/powturbo/TurboBench)). 
zlib is compiled directly from the sources w/ turbobench (gcc -O3), no SSE. The used "libz-ng.a" can be found under the directory "zlib-ng_" . Note the small average file length of 84k for this benchmark.


No more linker errors, but  conflict between "zlib.h" and "zlib-ng.h":
zlib-ng/zlib-ng.h:1055:61: error: conflicting declaration ‘typedef uint32_t (* in_func)(void*, const unsigned char**)’
 typedef uint32_t (*in_func) (void *, const unsigned char * *);
                                                             ^
In file included from plugins.cc:665:
zlib/zlib.h:1092:20: note: previous declaration as ‘typedef unsigned int (* in_func)(void*, unsigned char**)’
 typedef unsigned (*in_func) OF((void FAR *,

**Comment by powturbo** [comment]
Here is another benchmark with a large file enwik8 (100MB):
<pre>
      C Size  ratio%     C MB/s     D MB/s   Name            
    36475786    36.5      21.08     410.17   zlib_ng 9       
    36475796    36.5      17.30     281.10   zlib 9          
    36548925    36.5      21.13     280.70   zlib 6          
    37022957    37.0      36.87     440.90   zlib_ng 6       
    42298778    42.3      63.79     273.13   zlib 1          
    56030799    56.0     187.14     351.88   zlib_ng 1       
</pre>

**Comment by mtl1979** [comment]
@powturbo We will fix any new conflicts as you post more recent logs... This has been in our TODO for a long time...

**Comment by nmoinvaz** [comment]
@powturbo, I *believe* you can overcome that by defining `ZLIB_CONST` in zlib library.

**Comment by nmoinvaz** [comment]
@powturbo, did defining `ZLIB_CONST` solve the problem?

**Comment by powturbo** [comment]
Thank you, I've declared the used 2 functions prototypes directly into the source. It is enough for this benchmark.

**Comment by nmoinvaz** [comment]
@powturbo, can you review #363 and see if those changes solve all your problems?

**Comment by powturbo** [comment]
- Still the same linker errors.
- zlib-ng is now also benchmarked on ARM A73. Significant decompression speedup againsdt zlib
see: [Web compression Benchmark](https://sites.google.com/site/powturbo/home/web-compression)

**Comment by nmoinvaz** [comment]
The exact same linker errors? How is that possible now that all the functions have been renamed?

**Comment by powturbo** [comment]
/usr/bin/ld: zlib/deflate.o:(.rodata+0x0): multiple definition of `deflate_copyright'; zlib-ng_/libz-ng.a(deflate.o):(.rodata+0x0): first defined here
/usr/bin/ld: zlib/zutil.o: in function `zcfree':
zutil.c:(.text+0x50): multiple definition of `zcfree'; zlib-ng_/libz-ng.a(zutil.o):zutil.c:(.text+0x50): first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile:543: turbobench] Error 1

**Comment by powturbo** [comment]
The file trees.c is not updated since 1 month.

**Comment by nmoinvaz** [comment]
For,  #363, it should be: https://github.com/nmoinvaz/zlib-ng/tree/fixes/zlib-dual-link-v2

**Comment by powturbo** [comment]
NOW:
/usr/bin/ld: zlib/inffast.o: in function `inflate_fast':
inffast.c:(.text+0x0): multiple definition of `inflate_fast'; zlib-ng_/libz-ng.a(inffast.o):inffast.c:(.text+0x0): first defined here
/usr/bin/ld: zlib/inftrees.o: in function `inflate_table':
inftrees.c:(.text+0x0): multiple definition of `inflate_table'; zlib-ng_/libz-ng.a(inftrees.o):inftrees.c:(.text+0x0): first defined here

**Comment by nmoinvaz** [comment]
@powturbo, Thanks for reviewing that PR branch. I have made some additional changes which should get rid of those last two.

**Comment by Dead2** [comment]
This has all been merged now @powturbo, could you please test and verify that things are all good now?

**Comment by Dead2** [comment]
I should also mention that one of the commits I merged today gave a minor improvement in compression ratio for levels 4-6, but also losing a minor bit of speed.

**Comment by powturbo** [comment]
Thanks. There are no more linker errors now.

**Comment by Dead2** [comment]
Closing this since the bug has been fixed.
