### ISSUE TITLE
undefined symbol

### ISSUE THREAD

**Issue by PhanaticD** [zlib-ng/zlib-ng#43]
configure and make worked fine, after doing make install I get these kind of errors:

man: symbol lookup error: /usr/lib/man-db/libman-2.6.2.so: undefined symbol: gzclose

apt-get: symbol lookup error: /usr/lib/x86_64-linux-gnu/libapt-pkg.so.4.12: undefined symbol: gzdopen

Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.68-1+deb7u1 x86_64 GNU/Linux

**Comment by Dead2** [comment]
Use:
./configure --zlib-compat

Also, beware that this is not production ready and will break some applications that dont actually call the init functions (some allocate memory based on assumptions about memory needs).
