### ISSUE TITLE
zlib-ng on OS X

### ISSUE THREAD

**Issue by RJVB** [zlib-ng/zlib-ng#44]
As promised elsewhere, I just tried zlib-ng on OS X (v 10.9.5).
It builds out of the box, except for a small modification in crc32.c (see below).

```
diff --git a/crc32.c b/crc32.c
index 34343b2..76f7a8a 100644
--- a/crc32.c
+++ b/crc32.c
@@ -21,6 +21,8 @@
 # else
 #  error Unknown endianness!
 # endif
+#elif defined(__APPLE__)
+# include <machine/endian.h>
 #else
 # include <endian.h>
 #endif
```

And here's a benchmark on my Macbook Pro 13" (a 2011 model with a 2.7Ghz, 2*2 core i7), zlib-ng configured with `--zlib-compat` and everyone compiled with `clang -O3 -march=native -g". It would seem the zlib-ng mostly does better than zlib-Intel except where the Intel patches cause a performance loss (and there zlib-ng actually loses more). The CloudFlare patches still provide the most performance gain though, possibly because they don't bother with runtime instruction set checks?

```
                     baseline               cloudflare             intel                  NG                  
decompress executable (100 iterations)
 Execution time [s]:  5.64 ± 0.11 (100.00%)  5.68 ± 0.07 (100.74%)  5.61 ± 0.02 ( 99.45%)  5.67 ± 0.05 (100.47%)
decompress executable.gz (100 iterations)
 Execution time [s]:  0.54 ± 0.02 (100.00%)  0.53 ± 0.01 ( 98.00%)  0.53 ± 0.01 ( 97.68%)  0.53 ± 0.01 ( 97.94%)
decompress html (100 iterations)
 Execution time [s]:  3.39 ± 0.05 (100.00%)  3.41 ± 0.01 (100.63%)  3.41 ± 0.02 (100.70%)  3.49 ± 0.03 (102.84%)
decompress jpeg (100 iterations)
 Execution time [s]:  1.14 ± 0.01 (100.00%)  1.17 ± 0.03 (102.51%)  1.18 ± 0.02 (103.35%)  1.17 ± 0.01 (102.80%)
decompress pngpixels (100 iterations)
 Execution time [s]:  3.80 ± 0.04 (100.00%)  3.84 ± 0.03 (101.14%)  3.92 ± 0.03 (103.21%)  3.81 ± 0.01 (100.29%)

compress executable -5 (5 iterations)
  Compression ratio:  0.33                   0.34                   0.34                   0.34               
 Execution time [s]:  1.01 ± 0.01 (100.00%)  0.62 ± 0.01 ( 61.28%)  0.64 ± 0.01 ( 63.56%)  0.61 ± 0.01 ( 60.92%)
compress executable.gz -5 (5 iterations)
 Execution time [s]:  0.02 ± 0.00 (100.00%)  0.02 ± 0.00 ( 97.78%)  0.02 ± 0.00 ( 96.26%)  0.02 ± 0.00 ( 96.85%)
compress html -5 (5 iterations)
  Compression ratio:  0.34                   0.33                   0.33                   0.33               
 Execution time [s]:  0.76 ± 0.03 (100.00%)  0.44 ± 0.02 ( 58.69%)  0.43 ± 0.00 ( 56.26%)  0.40 ± 0.00 ( 52.67%)
compress jpeg -5 (5 iterations)
  Compression ratio:  1.00                   1.00                   1.00                   1.00               
 Execution time [s]:  0.51 ± 0.01 (100.00%)  0.49 ± 0.02 ( 95.80%)  0.59 ± 0.01 (115.77%)  0.59 ± 0.01 (115.25%)
compress pngpixels -5 (5 iterations)
  Compression ratio:  0.14                   0.14                   0.14                   0.14               
 Execution time [s]:  1.05 ± 0.03 (100.00%)  0.58 ± 0.02 ( 54.97%)  0.60 ± 0.01 ( 57.36%)  0.55 ± 0.00 ( 52.61%)

compress executable -7 (5 iterations)
  Compression ratio:  0.33                   0.34                   0.33                   0.33               
 Execution time [s]:  3.00 ± 0.04 (100.00%)  1.40 ± 0.01 ( 46.69%)  2.24 ± 0.04 ( 74.94%)  2.20 ± 0.07 ( 73.40%)
compress executable.gz -7 (5 iterations)
 Execution time [s]:  0.02 ± 0.00 (100.00%)  0.02 ± 0.00 (100.66%)  0.02 ± 0.00 (104.59%)  0.02 ± 0.00 (107.03%)
compress html -7 (5 iterations)
  Compression ratio:  0.33                   0.33                   0.33                   0.33               
 Execution time [s]:  1.51 ± 0.02 (100.00%)  0.79 ± 0.02 ( 52.26%)  1.35 ± 0.02 ( 89.03%)  1.36 ± 0.05 ( 89.84%)
compress jpeg -7 (5 iterations)
  Compression ratio:  1.00                   1.00                   1.00                   1.00               
 Execution time [s]:  0.58 ± 0.00 (100.00%)  0.53 ± 0.01 ( 91.89%)  0.54 ± 0.01 ( 93.68%)  0.54 ± 0.01 ( 93.57%)
compress pngpixels -7 (5 iterations)
  Compression ratio:  0.13                   0.13                   0.13                   0.13               
 Execution time [s]:  3.51 ± 0.01 (100.00%)  1.82 ± 0.02 ( 51.82%)  2.91 ± 0.03 ( 82.80%)  2.38 ± 0.01 ( 67.87%)

compress executable -9 (5 iterations)
  Compression ratio:  0.33                   0.33                   0.33                   0.33               
 Execution time [s]:  8.10 ± 0.06 (100.00%)  3.87 ± 0.03 ( 47.75%)  6.55 ± 0.06 ( 80.78%)  6.37 ± 0.02 ( 78.67%)
compress executable.gz -9 (5 iterations)
 Execution time [s]:  0.02 ± 0.00 (100.00%)  0.02 ± 0.00 ( 96.70%)  0.02 ± 0.00 ( 93.94%)  0.02 ± 0.00 (100.92%)
compress html -9 (5 iterations)
  Compression ratio:  0.33                   0.33                   0.33                   0.33               
 Execution time [s]:  2.38 ± 0.03 (100.00%)  1.45 ± 0.02 ( 60.89%)  2.27 ± 0.12 ( 95.27%)  2.11 ± 0.02 ( 88.34%)
compress jpeg -9 (5 iterations)
  Compression ratio:  1.00                   1.00                   1.00                   1.00               
 Execution time [s]:  0.64 ± 0.01 (100.00%)  0.57 ± 0.00 ( 89.00%)  0.59 ± 0.00 ( 91.94%)  0.59 ± 0.01 ( 92.21%)
compress pngpixels -9 (5 iterations)
  Compression ratio:  0.12                   0.12                   0.12                   0.12               
 Execution time [s]: 26.94 ± 0.21 (100.00%) 14.42 ± 0.17 ( 53.52%) 21.80 ± 0.29 ( 80.89%) 18.74 ± 0.25 ( 69.54%)
```

**Comment by RJVB** [comment]
PS: I understand that the cmake-based build method isn't yet finalised?

**Comment by Dead2** [comment]
This is great information, thank you.
We will get the apple define fixed soon (sooner if you make a pull request) :)

Regarding the latest cloudflare optimizations, most of these are on the wall for future improvements, but with changes to improve portability and separation of the changes into separate commits.

The cmake-based build is not yet at a functional parity with the regular configure script, it lacks checking and enabling of architecture-dependent defines (for optimizations) for example.

**Comment by RJVB** [comment]
On Monday June 08 2015 12:20:18 Hans Kristian Rosbach wrote:

> We will get the apple define fixed soon (sooner if you make a pull request) :)

Yeah, but it feels just a tad overkill to clone the repo in order to be able to make a pull request for something this trivial, don't you think.
I noticed the lack of functionality in the cmake file; if adding the missing optimisation defines is going to be similar to the ones already present I just might give that a whirl, and then have something more substantial to pull-request (pull-push seems a more appropriate term ;))

> Regarding the latest cloudflare optimizations, most of these are on the wall for future improvements, but with changes to improve portability and separation of the changes into separate commits.

I'm less "worried" about the additional gain in their changes (what would remain of those IRL?), more so about the performance hit I see in some of the test. 15% speed loss is a bit more than I would aim for.

R

**Comment by Dead2** [comment]
As far as I know, nobody is working on the cmake files at the moment, so go right ahead.

The checks in configure are (afaik) working as intended and are currently all we need to enable the correct optimizations and/or workarounds for the given targets. (Although, x86 and x86_64 are the only archs with any significant tests for enabling features. ARM has a few defines without tests (none needed for those). Optimizations are hopefully coming for Power, so I suspect that will need its own section.

**Comment by RJVB** [comment]
On Monday June 08 2015 22:56:16 Hans Kristian Rosbach wrote:

> The checks in configure are (afaik) working as intended and are currently all we need to enable the correct optimizations and/or workarounds for the given targets. 

And they only have to test whether the optional instruction sets are supported in the sense that code using them will compile and link (because any actual runtime use is dependent on a runtime check), right?

> (Although, x86 and x86_64 are the only archs with any significant tests for enabling features. ARM has a few defines without tests (none needed for those).

Good, because I could only check if those tests fail properly on x86 hardware ;)

> Optimizations are hopefully coming for Power, so I suspect that will need its own section.

I no longer have a PPC Mac, sadly. I could probably test G4 optimisations in a VM, though (with Apple's Rosetta emulator).

R.

**Comment by Dead2** [comment]
Some of the defines might disable runtime checking where not needed, such as doing the SSE2 check on x86_64 is not needed since it is implemented by default. I cant remember any other cases at the moment, but the code in configure should be pretty easy to follow I think.

Testing in an emulator will only test how fast the emulator is (something that can be good to possibly work around huge performance drops for certain emulated instructions), but unless an emulator can be detected runtime then there is not not much point in spending much time optimizing for it since it might result in worse performance on the real thing (a separate flag for optimizing for the emulated cpu could be done of course, if that is a common use-case).

And changes for other arches that need testing can still be valuable, since it is easier to get someone else to test a pull request that likely works, than to get someone to actually make one.

Btw, we are usually in #zlib-ng on the freenode IRC network ;)

**Comment by RJVB** [comment]
On Tuesday June 09 2015 02:26:46 Hans Kristian Rosbach wrote:

> Testing in an emulator will only test how fast the emulator is (something that can be good to possibly work around huge performance drops for certain emulated instructions)

I was not thinking of performance optimisation here, just verification of configure-time tests :)
That said, Apple did do a (very) good job with their PPC emulator, but optimising for it really is besides the point (and has been for 3 OS updates already _after_ Rosetta was discontinued in 10.7).

> Btw, we are usually in #zlib-ng on the freenode IRC network ;)

Duly noted - and at least 1 other person in a "compatible" timezone it seems :)

R.

**Comment by RJVB** [comment]
On Tuesday June 09 2015 02:26:46 Hans Kristian Rosbach wrote:

> Btw, we are usually in #zlib-ng on the freenode IRC network ;)

Time for me to wind down (= watch me some Deadwood :)), but in case no one noticed: https://github.com/RJVB/zlib-ng contains an updated cmake file with a bunch of stuff ported from the configure script. 

R.

**Comment by Dead2** [comment]
Most of this has been solved now, and we even have osx added to travis tests. So I guess its time to retire this report.
