### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by somasis** [zlib-ng/zlib-ng#45]
I was considering packaging this for my Linux distribution. Is there any chance of this getting a tagged release some time?

**Comment by Dead2** [comment]
Some time, yes. Soon? Depends on when we implement a workaround to the buffer problem in issue #4. Strictly speaking the affected applications are not doing things like they should (run the init function before attempting to deflate/inflate data), instead they assume they can cheat and do a faster dirty init themselves. Unfortunately this is highly dependant on data-structures and features not changing so it breaks.

I cannot promise anything regarding timelines unfortunately.
