### ISSUE TITLE
quick_insert_string needs MSVC inline assembly

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#451]
The function `quick_insert_string` that is part of deflate_quick.c needs MSVC inline assembly. 

```
static inline Pos quick_insert_string(deflate_state *const s, const Pos str) {
    Pos ret;
    unsigned h = 0;

#ifdef _MSC_VER
    h = _mm_crc32_u32(h, *(unsigned *)(s->window + str));
#else
    __asm__ __volatile__ (
        "crc32l (%[window], %[str], 1), %0\n\t"
    : "+r" (h)
    : [window] "r" (s->window),
      [str] "r" ((uintptr_t)str)
    );
#endif
```

Notice how `insert_string_sse` has the MSVC inline assembly version:

```
#if defined(X86_SSE42_CRC_INTRIN)
#  ifdef _MSC_VER
        h = _mm_crc32_u32(h, val);
#  else
        h = __builtin_ia32_crc32si(h, val);
#  endif
#else
#  ifdef _MSC_VER
        __asm {
            mov edx, h
            mov eax, val
            crc32 eax, edx
            mov val, eax
        };
#  else
        __asm__ __volatile__ (
            "crc32 %1,%0\n\t"
            : "+r" (h)
            : "r" (val)
        );
#  endif
#endif
```
It is also missing `#if defined(X86_SSE42_CRC_INTRIN)` and `h = __builtin_ia32_crc32si(h, val);`. I don't know enough assembly to do it. I figured it might be an easier task for somebody else.

**Comment by nmoinvaz** [comment]
The solution I had come up with was:

```
static inline Pos quick_insert_string(deflate_state *const s, const Pos str) {
    Pos ret;
    unsigned h = 0;
    unsigned int val;

    memcpy(&val, (unsigned *)(s->window + str), sizeof(val));

#if defined(X86_SSE42_CRC_INTRIN)
#  ifdef _MSC_VER
        h = _mm_crc32_u32(h, val));
#  else
        h = __builtin_ia32_crc32si(h, val);
#  endif
#else
#  ifdef _MSC_VER
        __asm {
            mov edx, h
            mov eax, val
            crc32 eax, edx
            mov val, eax
        };
#  else
        __asm__ __volatile__ (
            "crc32 %1,%0\n\t"
            : "+r" (h)
            : "r" (val)
        );
#  endif
#endif
```

But I don't think the additional `memcpy` would be acceptable, however the code would be the same as in `insert_string_sse`.

**Comment by mtl1979** [comment]
Obviously it should copy the result back to "h", not "val". The test for "X86_SSE42_CRC_ASM" is inadequate as it should also test for "_MSC_VER", because the syntax for inline assembly is different.

**Comment by nmoinvaz** [comment]
I was experimenting with some code. But I think it would be better to have inline that doesn't use memcpy.

**Comment by mtl1979** [comment]
The problem is that the initial value must be stored in register, not memory.

**Comment by nmoinvaz** [comment]
I also tried `register unsigned int val = *(unsigned int *)(s->window + str);` but it complains about not being 4-byte aligned.

**Comment by mtl1979** [comment]
Unaligned loads and stores are perfectly safe using general-purpose registers on x86 and AMD64 architectures, so any complains are false positives.

**Comment by nmoinvaz** [comment]
I think it might matter more for the other architectures such as ARM 32-bit and SPARC.

**Comment by nmoinvaz** [comment]
Could do something such as:

```
unsigned int val;
....
#if defined(UNALIGNED_OK)
    val = *(unsigned int *)(s->window + str);
#else
    memcpy(&val, (unsigned *)(s->window + str), sizeof(val)); 
#endif
```

What do you think?

**Comment by turol** [comment]
@mtl1979 Unaligned reads are safe in assembler code but NOT in C/C++. See [A bug story: data alignment on x86](https://pzemtsov.github.io/2016/11/06/bug-story-alignment-on-x86.html)

**Comment by mtl1979** [comment]
@turol That is why I said general-purpose registers, that excludes vector registers. If the code does not crash when compiled as release binary, it really does not need a workaround. There is zillion bugs in various gcc versions, but normal code rarely hits any of them. I already said the code was bad, so it does not matter what issues might result in using memcpy vs. C assignment.

**Comment by turol** [comment]
@mtl1979 Did you read the article? The compiler automatically used vector registers and got it wrong because the programmer violated the alignment rules. It was not a compiler bug. Even if the code compiles and works with the current compiler it might break with some future one which is always "fun".

As far as I know the GCC/clang optimizer works something like this: it sees a read from a pointer which has a higher than 1-byte alignment requirement, uses it to establish a fact like "here the low bits must be 0" and then propagates it to other operations/variables. There's no way to know what some future compiler will decide to do with that information.

Treating alignment rules with the carelessness you seem to makes me very nervous about using this (otherwise excellent) library in any of my projects.

**Comment by mtl1979** [comment]
@turol I've read the article more than once as I work with the Linaro team to fix arch-specific bugs. When there is issues with mixed C/assembler code, my first solution is always hand-written assembler code, including naked functions with Visual C++.

**Comment by nmoinvaz** [comment]
Code has been merged. This can be closed now.
