### ISSUE TITLE
Unresolved external symbols in maketrees

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#456]
```
maketrees.c.obj : error LNK2019: unresolved external symbol _z_error referenced in function _tr_static_init
trees.c.obj : error LNK2001: unresolved external symbol _z_error
trees.c.obj : error LNK2019: unresolved external symbol _send_bits referenced in function _zng_tr_flush_block
trees.c.obj : error LNK2001: unresolved external symbol _z_verbose
```
This happens in debug mode: 
```
cmake . --DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Debug
cmake --build . --config Debug
```
It appears trees.c requires some functions which are in zlib library and only work with static library. 

If I change CMakeLists.txt and add zutil.c:
```
add_executable(maketrees tools/maketrees.c trees.c zutil.c)
```
And then move `send_bits()` function from deflate.c to trees.c it works, but I'm not sure moving `send_bits()` is something we want to do.

**Comment by mtl1979** [comment]
I don't see send_bits() used anywhere else than trees.c as deflate_quick.c has its own version, so moving it to trees.c isn't really a bad idea at all...
