### ISSUE TITLE
zlib-ng not compiling in 32 bits mode with a 64 bits multilib toolchain

### ISSUE THREAD

**Issue by gilles-chanteperdrix** [zlib-ng/zlib-ng#46]
Hi,

I am running an x86 distribution where gcc supports building both 32 bits and 64 bits binaires. And I have troubles compiling zlib-ng.

I am passing environment variables:
CHOST="i686-pc-linux-gnu"
CC="gcc"
CFLAGS="-m32 -g -O2"

The first part of the configure script detects ARCH=i686 correctly, then we reach the point where configure does:
 # Re-check arch if gcc is a cross-compiler
  GCC_ARCH=`$CC -dumpmachine | sed 's/-.*//g'`
gcc -dumpmachine on the machine on which I am compiling returns:
x86_64-slackware-linux
so ARCH is replaced with x86_64, which causes compilation  errors since the -m32 flag is passed to gcc.

**Comment by Dead2** [comment]
I am not sure what the proper way to fix this is.
A simple check for -m32 and override could be implemented, but I am thinking there might be a more universal way of doing this?

**Comment by gilles-chanteperdrix** [comment]
According to this bug:
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=52096

gcc -dumpmachine does not seem to be the right way to detect the target architecture.

You could look for 

```
#define __i386__ 
```

or 

```
#define __x86_64__ 
```

in 

```
$CC $CFLAGS  -dM -xc -E /dev/null 
```

output, but why do all that at all, since the first part of the configure script seems to already detect the architecture correcly?

From what I understand, what the configure script is trying to do is to add the -m64 CFLAG if architecture is 32 bits but build64 is true. So why not simply use the ARCH that was detected by the first check, instead of trying and obtaining GCC_ARCH by  another way?

IOW, why not:

```
--- configure~  2015-08-05 20:00:21.000000000 +0200
+++ configure   2015-08-23 16:03:57.444776198 +0200
@@ -202,16 +202,12 @@
   echo ... using gcc >> configure.log
   CC="$cc"
 # Re-check arch if gcc is a cross-compiler
-  GCC_ARCH=`$CC -dumpmachine | sed 's/-.*//g'`
-  case $GCC_ARCH in
+  case $ARCH in
     i386 | i486 | i586 | i686)
 # Honor user choice if gcc is multilib and 64-bit is requested 
       if test $build64 -eq 1; then
         ARCH=x86_64
-      else
-        ARCH=$GCC_ARCH 
       fi ;;
-    x86_64) ARCH=$GCC_ARCH ;;
   esac
   CFLAGS="${CFLAGS--O3} ${ARCHS} -Wall"
   SFLAGS="${CFLAGS--O3} -fPIC"
```

**Comment by mtl1979** [comment]
If I remember correctly, successful build on MinGW required usage of "gcc -dumpmachine"... This is because MSYS is inherently 32-bit, but MinGW can be both 32-bit and 64-bit at the same time.

**Comment by mtl1979** [comment]
The correct way to fix this IMHO is to add configure flag that forces 32-bit build like there is configure flag that forces 64-bit build... That flag should reset $build64 to 0.

**Comment by gilles-chanteperdrix** [comment]
If you pass the correct CHOST variable to configure, the mingw case should be handled fine with the
patch I propose. Calling gcc -dumpmachine kind of overrides the choices made with the CHOST variable. So, what I would find it logicial to only use gcc -dumpmachine if CHOST was not set.

**Comment by mtl1979** [comment]
CHOST is only used to select alternative gcc version, when more than one is installed... it's up to gcc to specify correct target platform...

**Comment by gilles-chanteperdrix** [comment]
gcc -dumpmachine does not do that. See the gcc bugzilla entry mentioned above.

**Comment by mtl1979** [comment]
```
diff --git a/configure b/configure
index 0b9ae30..dd0a20c 100755
--- a/configure
+++ b/configure
@@ -102,6 +102,7 @@ shared=1
 gzfileops=0
 compat=0
 cover=0
+build32=0
 build64=0
 without_optimizations=0
 without_new_strategies=0
@@ -133,7 +134,7 @@ case "$1" in
     -h* | --help)
       echo 'usage:' | tee -a configure.log
       echo '  configure [--zlib-compat] [--prefix=PREFIX]  [--eprefix=EXPREFIX]' | tee -a configure.log
-      echo '    [--static] [--64] [--libdir=LIBDIR] [--sharedlibdir=LIBDIR]' | tee -a configure.log
+      echo '    [--static] [--32] [--64] [--libdir=LIBDIR] [--sharedlibdir=LIBDIR]' | tee -a configure.log
       echo '    [--includedir=INCLUDEDIR] [--archs="-arch i386 -arch x86_64"]' | tee -a configure.log
         exit 0 ;;
     -p*=* | --prefix=*) prefix=`echo $1 | sed 's/.*=//'`; shift ;;
@@ -150,6 +151,7 @@ case "$1" in
     -t | --static) shared=0; shift ;;
     --zlib-compat) compat=1; shift ;;
     --cover) cover=1; shift ;;
+    -3* | --32) build32=1; shift ;;
     -6* | --64) build64=1; shift ;;
     -a*=* | --archs=*) ARCHS=`echo $1 | sed 's/.*=//'`; shift ;;
     --sysconfdir=*) echo "ignored option: --sysconfdir" | tee -a configure.log; shift ;;
@@ -209,7 +211,11 @@ if test "$gcc" -eq 1 && ($cc -c $test.c) >> configure.log 2>&1; then
       else
         ARCH=$GCC_ARCH
       fi ;;
-    x86_64) ARCH=$GCC_ARCH ;;
+# Honor user choice if gcc is multilib and 32-bit is requested
+    x86_64)
+      if test $build32 -ne 1; then
+        ARCH=$GCC_ARCH
+      fi ;;
   esac
   CFLAGS="${CFLAGS--O3} ${ARCHS} -Wall"
   SFLAGS="${CFLAGS--O3} -fPIC"
```

**Comment by mtl1979** [comment]
I don't think it's up to gcc bugzilla to make decisions how zlib-ng works... it's up to zlib-ng developers to make sure all versions of gcc work on all supported platforms...

**Comment by gilles-chanteperdrix** [comment]
Of course I am not a zlib-ng developer, so I understand if you do not take my opinion into account. Still,
to obtain a 64 bits build, you can
- use CHOST
- or use --64

Since I found the first solution more convenient, I was trying to also get it working for 32 bits builds.

**Comment by mtl1979** [comment]
I take all opinions in account, but I also have to remember why some piece of code was added or modified... As this piece of code was originally written by myself, remembering the reason was easier than for code added or modified by one of the other developers.

**Comment by mtl1979** [comment]
It makes no sense to fix something by breaking it on some other platform.

**Comment by gilles-chanteperdrix** [comment]
Of couse. I agree that patch I posted broke the case where CHOST was not set, but if you only call gcc
-dumpmachine if CHOST was not set, you allow users to use the CHOST variable to explicitly specify the architecture for which zlib-ng is compiled without resorting to --32, in the same way it currently works for 64 bits builds. Without breaking anything. Hopefully.

**Comment by mtl1979** [comment]
Currently for 64-bit builds it requires specifying --64, as 32-bit build is the default on some platforms even though the processor is 64-bit capable.

**Comment by gilles-chanteperdrix** [comment]
Then the beginning of the configure script, which uses CHOST and CFLAGS to detect x86 32 or 64 bits build is redundant.

**Comment by mtl1979** [comment]
Like I said above, CHOST is used on platforms where it is possible to deduce target platform from name of the gcc executable. This includes for example MinGW64 and some Linux distributions.

**Comment by mtl1979** [comment]
CHOST is mainly used for cross-compiling, the other alternatives are used for native compiling with or without multilib.

**Comment by gilles-chanteperdrix** [comment]
Ok. Thanks for adding the --32, option.

**Comment by mtl1979** [comment]
No problem... If there is anything else that doesn't work, just let us know :)

**Comment by gilles-chanteperdrix** [comment]
This patch fixes the issue i had. Thanks.
