### ISSUE TITLE
Buildkite CI

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#467]
Maybe now that we have GitHub Actions, is there a reason to keep around Buildkite or can we get rid of it? I never was able to access it, maybe it is invite only?

**Comment by Dead2** [comment]
It is invite only, and it still serves a purpose.
As I mentioned earlier, GitLab CI would likely have been the best choice for us because it allows a combination of cloud and private runners.
The private runners can handle stuff that the cloud cannot, such as CI benchmarking.

**Comment by nmoinvaz** [comment]
GitHub Actions now supports private runners in beta..
https://github.blog/2019-11-05-self-hosted-runners-for-github-actions-is-now-in-beta/?utm_campaign=1572989126&utm_medium=social&utm_source=twitter&utm_content=1572989126
