### ISSUE TITLE
Debug configuration asserts in CI

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#471]
There are two debug mode asserts that I have run into on CI:

**compress_fuzzer**
Using input [match2.zip](https://github.com/zlib-ng/zlib-ng/files/3770892/match2.zip). Original extension is pdb.

```
scan += 2, match+=2;
Assert(*scan == *match, "match[2]?");
```
There are multiple of the same line but the one that was hit was in match_p.h at line 460. The comment above this line suggests that scan and match don't have to be equal. 

**example_dict_fuzzer**
Using input [CMakeLists.txt](https://github.com/zlib-ng/zlib-ng/files/3770909/CMakeLists.txt).

```
Assert((uint16_t)dist < (uint16_t)MAX_DIST(s) &&
               (uint16_t)lc <= (uint16_t)(MAX_MATCH-MIN_MATCH) &&
               (uint16_t)d_code(dist) < (uint16_t)D_CODES,  "zng_tr_tally: bad match");
```
This is in trees.c at line 747.

I'm not sure if these asserts are necessary. Maybe they can be converted to `Tracev` statements instead of `Assert` statements.

**Comment by nmoinvaz** [comment]
Or perhaps we want to turn off fuzzers in debug configuration in CI.

**Comment by Dead2** [comment]
That depends on whether these bugs are caused by the fuzzing itself or whether the fuzzing triggered a real bug.
If it is caused by the fuzzing, then perhaps we should bypass them by using a define check ZFUZZING for example. But if these are real bugs, then we would be much better off fixing them.
So this will need some investigation I guess.

**Comment by mtl1979** [comment]
First two bytes of scan and match are not equal when it runs out of input... That check is incorrect as it should check MIN_MATCH bytes, which is 3 bytes, not 2... In some places we already reordered the test to avoid the assert completely.

**Comment by Dead2** [comment]
I don't have time to work on this real soon, do any of you want to suggest PRs for one or both of these?
Without actually looking at the code, I am thinking perhaps the first assert might benefit from another conditional so it does not trigger on end-of-input, if that check is in the assert then it also won't affect performance of release builds.

The second one kind of looks like it could potentially be a real bug, and perhaps checking whether stock zlib does something different there, or even whether it fails on the same fuzzer. (Can our fuzzers run on stock zlib btw? That would actually be a great feature if they could.)

**Comment by nmoinvaz** [comment]
In the case of the example_dict_fuzzer, `dist < MAX_DIST(s)` is the offending condition. I believe this may be because in deflate_medium.c the `MAX_DIST` is actually defined as `MAX_DIST2`. One way to solve this might be to pass in the max distance into the function.

I'm not so sure about the compress_fuzzer issue, it doesn't appear to happen at the end-of-input like was suggested.

**Comment by nmoinvaz** [comment]
In the compress_fuzzer issue, I think there is no guarantee that `*scan == *match` condition be true.  When starting the match it checks the first two bytes, but there is no guarantee that the next two bytes should match, so having the `Assert` doesn't make much sense unless it happens before `scan += 2, match += 2`. By the way, in this instance the match length ends up being only 2.

**Comment by mtl1979** [comment]
I already suggested we get rid of the checking of just first two bytes, as there is corner case when third byte is not the same... We should everywhere check 3 bytes directly as that is minimum match length. This avoids need of asserts completely and makes the code a lot more readable.

**Comment by nmoinvaz** [comment]
@mtl1979 you mentioned you had removed the need for the assert completely in a previous instance. What is the commit?

**Comment by mtl1979** [comment]
@nmoinvaz I haven't pushed it to GitHub yet... Comparing three bytes instead of two is a little slower on most architectures, but if it fixes more than one issue, then the pros win the cons...

**Comment by nmoinvaz** [comment]
@mtl1979 that sounds like a good change.

**Comment by mtl1979** [comment]
@nmoinvaz I have been quite busy with other projects since I bought a new PC so I haven't had much time doing pull requests lately... Also, I'm not sure how much surrounding code needs to or should be changed after changing the compare length...

**Comment by nmoinvaz** [comment]
@mtl1979 any thoughts on my commit https://github.com/nmoinvaz/zlib-ng/commit/28d6b1fe086d8afe1989bae85dbcffe0c63b72b0?

**Comment by mtl1979** [comment]
@nmoinvaz Not really... It looks cleaner than the previous code. I don't see any new relevant failures in CI tests.

**Comment by nmoinvaz** [comment]
@mtl1979 Actually it looks like CI does fail on ARM machines, https://github.com/nmoinvaz/zlib-ng/runs/375035410. When I removed the assert I would get -3 return code from inflate after deflate. And the same happens with my changes too.  But now perhaps my changes have revealed something new?

**Comment by mtl1979** [comment]
@nmoinvaz I think those "failed to intercept" issues need to be resolved first... Some people have suggested it has something to do with Docker permissions...

**Comment by nmoinvaz** [comment]
All the necessary pull requests have been merged in.
