### ISSUE TITLE
IBM Z (s390x): DFLTCC code compilation failure

### ISSUE THREAD

**Issue by mundaym** [zlib-ng/zlib-ng#477]
I'm seeing a compilation failure when compiling zlib-ng configured using `./configure --with-dfltcc-deflate --with-dfltcc-inflate` due to the use of an unknown variable name. The following code change appears to fix the issue:

```diff
diff --git a/arch/s390/dfltcc_deflate.c b/arch/s390/dfltcc_deflate.c
index 3710dc0..454a0bb 100644
--- a/arch/s390/dfltcc_deflate.c
+++ b/arch/s390/dfltcc_deflate.c
@@ -79,7 +79,7 @@ static inline void send_eobs(PREFIX3(streamp) strm, const struct dfltcc_param_v0
 {
     deflate_state *state = (deflate_state *)strm->state;
 
-    send_bits(state, bi_reverse(param->eobs >> (15 - param->eobl), param->eobl), param->eobl, s->bi_buf, s->bi_valid);
+    send_bits(state, bi_reverse(param->eobs >> (15 - param->eobl), param->eobl), param->eobl, state->bi_buf, state->bi_valid);
     flush_pending(strm);
     if (state->pending != 0) {
         /* The remaining data is located in pending_out[0:pending]. If someone
```

Can you take a look @iii-i? I'm also seeing `make test` fail - not sure if that is expected or not.

Thanks!

**Comment by iii-i** [comment]
@mundaym thanks for the patch - it looks good to me. Would you mind sending a PR?

I'm seeing the following test failures:

```
Expected compression level Z_NO_COMPRESSION, got 1
```
This one is unfortunately expected - one cannot switch compression levels when using the NXU. I think I should change the test so as to allow this.

```
./switchlevels 1 5 9 3 <zlib-ng/test/GH-364/test.bin >/dev/null
deflateParams() failed with code -2
```
This is the same I think.

Do you see anything in addition to these two?

**Comment by mundaym** [comment]
Thanks. Test failure looks the same to me.

**Comment by Dead2** [comment]
So, any of you want to make a PR with this fix?

**Comment by nmoinvaz** [comment]
@Dead2, I think this issue can be closed now.
