### ISSUE TITLE
armv6/v7: overriding -march, -mfloat-abi and --mfpu with incompatible values

### ISSUE THREAD

**Issue by MilhouseVH** [zlib-ng/zlib-ng#478]
https://github.com/zlib-ng/zlib-ng/pull/386/files#diff-af3b638bc2a3e6c650974192a53c7291R189-R204 incorrectly detects `softfp` when cross-compiling on Linux as it overrides `-mfloat-abi` and `-mfpu` unnecessarily.

`zlib-ng` also incorrectly sets `-march=armv8-a+crc` when building for arvm7 and armv6.

From `CMakeOutput.log` (building for armv7, Raspberry Pi2):
```
The target system is: Linux - 1 - arm
The host system is: Linux - 4.4.0-166-generic - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel-next/toolchain/bin/armv7ve-libreelec-linux-gnueabi-gcc
Build flags: -march=armv7ve;-mtune=cortex-a7;-mabi=aapcs-linux;-Wno-psabi;-Wa,-mno-warn-deprecated;-mfloat-abi=hard;-mfpu=neon-vfpv4;-Wall;-pipe;;-O2;-fomit-frame-pointer
Id flags:
```

The result of `-dumpmachine` from gcc-9.2.0 when cross-compiling for armv7 is:
```
armv7ve-libreelec-linux-gnueabi
```

This results in:
```
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: MinSizeRel (selected)
 * ZLIB_COMPAT, Provide a zlib-compatible API
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * WITH_ACLE, Build with ACLE CRC
 * WITH_NEON, Build with NEON intrinsics
 * NEON_FILLWINDOW, Support NEON instructions in fill_window_arm, using "-mfloat-abi=softfp -mfpu=neon"
 * ACLE_CRC, Support CRC hash generation using the ACLE instruction set, using "-march=armv8-a+crc"

-- The following features have been disabled:

 * WITH_GZFILEOP, Compile with support for gzFile-related functions
 * WITH_SANITIZERS, Build with address sanitizer and all supported sanitizers other than memory sanitizer
 * WITH_MSAN, Build with memory sanitizer
 * WITH_FUZZERS, Build test/fuzz
 * MAINTAINER, Build with maintainer warnings and tests enabled
```
and the build fails as `gnu/stubs-soft.h` is not available.
```
[ 11%] Building C object CMakeFiles/maketrees.dir/tools/maketrees.c.o
In file included from /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel-next/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/features.h:474,
                 from /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel-next/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/bits/libc-header-start.h:33,
                 from /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel-next/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/stdio.h:27,
                 from /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel-next/zlib-5bd3c582908503135fd8d6326ca0e2a6a947b44f/tools/makecrct.c:6:
/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel-next/toolchain/armv7ve-libreelec-linux-gnueabi/sysroot/usr/include/gnu/stubs.h:7:11: fatal error: gnu/stubs-soft.h: No such file or directory
    7 | # include <gnu/stubs-soft.h>
      |           ^~~~~~~~~~~~~~~~~~
compilation terminated.
```

For Raspberry Pi 1 (`arm1176jzf-s`) we get:

`CMakeOutput.log`:
```
The target system is: Linux - 1 - arm
The host system is: Linux - 4.4.0-166-generic - x86_64
Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
Compiler: /home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi.arm-9.80-devel-next/toolchain/bin/armv6zk-libreelec-linux-gnueabi-gcc
Build flags: -march=armv6zk;-mtune=arm1176jzf-s;-mabi=aapcs-linux;-Wno-psabi;-Wa,-mno-warn-deprecated;-mfloat-abi=hard;-mfpu=vfp;-Wall;-pipe;;-O2;-fomit-frame-pointer
Id flags:
```

`gcc-9.2.0 -dumpmachine`:
```
armv6zk-libreelec-linux-gnueabi
```

Build config:
```
 * CMAKE_BUILD_TYPE, Build type: MinSizeRel (selected)
 * ZLIB_COMPAT, Provide a zlib-compatible API
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * WITH_ACLE, Build with ACLE CRC
 * WITH_NEON, Build with NEON intrinsics
 * NEON_FILLWINDOW, Support NEON instructions in fill_window_arm, using "-mfloat-abi=softfp -mfpu=neon"
 * ACLE_CRC, Support CRC hash generation using the ACLE instruction set, using "-march=armv8-a+crc"

-- The following features have been disabled:

 * WITH_GZFILEOP, Compile with support for gzFile-related functions
 * WITH_SANITIZERS, Build with address sanitizer and all supported sanitizers other than memory sanitizer
 * WITH_MSAN, Build with memory sanitizer
 * WITH_FUZZERS, Build test/fuzz
 * MAINTAINER, Build with maintainer warnings and tests enabled
```

and a similar build failure.

`zlib-ng` also appears to be enabling NEON support for armv6 even though the target hardware doesn't support NEON.

Would it be better to respect `-march`, `-mfloat-abi` and `-mfpu` when these flags are already set, rather than to always try (and possibly fail) to determine them?

**Comment by mtl1979** [comment]
Cmake has limited support for cross-compiling, so all build parameters must be specified in the toolchain file, not command line. Not all combinations are supported as they must be manually inserted to CMakeFiles.txt...

**Comment by MilhouseVH** [comment]
OK fair enough. In that case it looks like `zlib-ng` only really supports armv8 when cross-compiling for ARM. Anything older than armv8 is just not going to build.

It's not a big deal, as I'm just testing this to see if `zlib-ng` could be used as a drop-in replacement for `zlib` but apparently not without working around these cross-compile ARMv6/v7 build issues by patching out the broken tests.

**Comment by mtl1979** [comment]
Fixing those issues require actually having the hardware and exactly same compiler version... Successful build doesn't always result in binaries that actually run as expected.

**Comment by MilhouseVH** [comment]
I'm not really sure how relevant the hardware is to the issue I'm raising, to be honest. I'm just pointing out that the current arm support in the `zlib-ng` build system is not working correctly for anything prior to armv8. If the resulting binaries actually work or not I have no idea (yet) but being able to build them for non-armv8 targets would be a good start! :smile:

Anyway, [`nss`](http://ftp.mozilla.org/pub/security/nss/releases/NSS_3_47_1_RTM/src/) just failed to build with `zlib-ng`  - presumably an ABI issue - so it's back to `zlib`... http://ix.io/22Id

**Comment by mtl1979** [comment]
When I started the ARM support in zlib-ng, I used compiler that targets armv2 and armv7. Obviously the build system has changed a lot since those days.

Most people don't know that cross-compilers don't have same preprocessor definitions and command-line parameters even if the target architecture is the same. It depends on who did the cross-compiler and what has been modified since it branched out from default build.

**Comment by MilhouseVH** [comment]
> When I started the ARM support in zlib-ng, I used compiler that targets armv2 and armv7. Obviously the build system has changed a lot since those days.

It looks like these armv8/float/neon issues have been added in the last 2 months (#386).

As the distribution I'm building only supports hard float, the fix in `zlib-ng` for my project is quite simple:
```
diff --git a/CMakeLists.txt b/CMakeLists.txt
index e472984..001b31d 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -206,7 +206,7 @@ else()
                 if ("${GCC_MACHINE}" MATCHES "eabihf")
                     set(FLOATABI "-mfloat-abi=hard")
                 else()
-                    set(FLOATABI "-mfloat-abi=softfp")
+                    set(FLOATABI "-mfloat-abi=hard")
                 endif()
                 # NEON
                 if("${ARCH}" MATCHES "aarch64")
--
2.7.4
```
However that's not a "proper" solution (I'm rubbish at `cmake`, so can't really help there).

Unfortunately other packages I need to build don't appear to be `zlib-ng` compatible so that's the end of my `zlib-ng` investigation until my curiosity (or more likely, concerns over the dire state of upstream `zlib`) gets the better of me again! :smile:

**Comment by mtl1979** [comment]
That distribution obviously is broken and such something we can't fix without breaking build on other distributions. However I'm not sure if it is warranted to add extra sanity check to fall back to hard-float if compiler reports wrong triplet. Obviously it is pretty easy to add simple compile check to verify.

**Comment by MilhouseVH** [comment]
Thanks, I'll look into the `eabi`/`eabihf` distro issue - that might be a valid fix on our end. But the other armv8/neon issues remain.

**Comment by Dead2** [comment]
@MilhouseVH Interesting feedback, thank you for that, this is something we will have to look into further.
I wonder though, did you test compiling zlib-ng using the configure script instead of cmake? That implementation is simpler and might currently work better in this case. Could you test and report back whether we have bugs there as well?

**Comment by MilhouseVH** [comment]
@Dead2 I'll test `configure` and let you know.

**Comment by MilhouseVH** [comment]
Couple of `configure` issues:

1. This test for arch is a bit optimistic:

    https://github.com/zlib-ng/zlib-ng/blob/5bd3c582908503135fd8d6326ca0e2a6a947b44f/configure#L1075

    It fails to match `armv6zk` (RaspberryPi0/1) and `armv7e` (RPi2) and possibly a hundred other minor pre-armv8 variants. :smile:

    Would the following test be more suitable (and far less likely to fail)?
    ```
    arm | arm[345678]* | armv[345678]*)
    ```
    or even:
    ```
    arm*)
    ```

    Is there any reason for the test to be so precise when detecting arm variants, as that's going to be almost impossible to maintain...

    Without either of the above changes the build will fail as an arm cross-compile will build as `arch/generic`:
```
ARCH: armv7ve
Using arch directory: arch/generic
ls: cannot access '/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel/zlib-5bd3c582908503135fd8d6326ca0e2a6a947b44f/arch/generic/*.c': No such file or directory
ls: cannot access '/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel/zlib-5bd3c582908503135fd8d6326ca0e2a6a947b44f/arch/generic/*.c': No such file or directory
Executing (target): make
make[1]: Entering directory '/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-RPi2.arm-9.80-devel/zlib-5bd3c582908503135fd8d6326ca0e2a6a947b44f/.armv7ve-libreelec-linux-gnueabihf'
```

2) In `--zlib-compat` mode, `$VER` is set to `1.2.11.zlib-ng` because `ZLIB_VERSION` is `1.2.11.zlib-ng` in `zlib.h`:
    https://github.com/zlib-ng/zlib-ng/blob/5bd3c582908503135fd8d6326ca0e2a6a947b44f/zlib.h#L48 
    This results in the shared library being created with the soname `libz.so.1.2.11.zlib-ng` when in `--zlib-compat` mode we want need the soname `libz.so.1.2.11`. Consequently, packages fail to find `-lz` due to the incorrect soname.

    Removing the `.zlib-ng` suffix from `ZLIB_VERSION` in `zlib.h` works. Or it could be stripped in `configure`. Not sure what the best option is.

With these issues fixed, I've been able to build `zlib-ng` using `configure` for both x86_64 (host) and armv6zk/armv7ve (targets). An RPi2 build of LibreELEC using `zlib-ng` as `zlib` replacement seems to be working OK.

----

What should I do about the `nss` build failure mentioned in a previous post?
```
zip.c: In function 'JzipAdd':
zip.c:325:28: error: passing argument 2 of 'handle_zerror' discards 'const' qualifier from pointer target type [-Werror=discarded-qualifiers]
         handle_zerror(err, zstream.msg);
                            ^
zip.c:92:1: note: expected 'char *' but argument is of type 'const char *'
```
Presumably this is a `zlib-ng` ABI issue (I'm using `--zlib-compat` mode, `cmake` and `configure` both result in the same `nss` failure). If so I can open a new `zlib-ng` issue for this failure.

**Comment by Dead2** [comment]
@MilhouseVH 
1. The arm* would indeed be my preference. Would you care to make a PR doing that?
2.  I am thinking adding a symlink from libz.so.1.2.11 to libz.so.1.2.11.zlib-ng might be a good solution to that, what do you think? I want to make it pretty obvious that it is a zlib-ng and not a stock zlib library. An alternative would be a similar symlink from libz.so.1.2.11 to a zlib-ng-compat.so.1.2.11 file for example. Not sure what would be the best option for keeping compatibility while at the same time making it easy to spot that the system is using zlib-ng (for bug reports etc).

The nss build failure is a separate issue, so I'd appreciate if you could make a new issue for that.

Thanks a lot :)

**Comment by MilhouseVH** [comment]
1. Done, #480 

2. A sym link from `libz.so.1.2.11` to `libz.so.1.2.11.zlib-ng` should work, but it's probably worth noting that the `cmake` build currently strips the `.zlib-ng` suffix from the library version and only creates `libz.so.1.2.11` (plus sym links `libz.so`, and `libz.so.1` of course): https://github.com/zlib-ng/zlib-ng/blob/5bd3c582908503135fd8d6326ca0e2a6a947b44f/CMakeLists.txt#L30-L31

    So whatever solution ensures consistency between `configure` and `cmake`, and also compatibility with upstream `zlib` would be best!

3. Done, #481

**Comment by dhewg** [comment]
The hard/softfp detection could be improved. Right now it relies on the triple of the toolchain. A prepocessor check for `__ARM_PCS_VFP` on 32bit arm would be more reliable, like e.g. chromium/v8 is doing:
https://github.com/v8/v8/blob/master/src/base/platform/platform-posix.cc#L156
That would work for LibreELEC's current toolchain, and who knows how many more.

For 32bit arm `-mfloat-abi` is always added, it doesn't check if the flag is already given or even conflicts with others. Maybe don't add it at all if cross compiling?

And then `FLOATABI` is set in a common 32/64bit block, but only used for 32bit. That confused me for a second :)

**Comment by mtl1979** [comment]
The original version I wrote had separate blocks for 32-bit and 64-bit ARM... It got totally butchered by other contributors... I try to clean up the mess the best I can, but even my skills have limits...

**Comment by MilhouseVH** [comment]
@Dead2, @mtl1979: I've been discussing with colleagues working on the LibreELEC distribution how `zlib-ng` attempts to detect `hard` or `soft` float support and overrides the `-mfloat-abi` flag (and other flags) in `cmake`, and we're fairly sure the current detection method can't ever work reliably.

Currently, `zlib-ng` uses this method to set `FLOATABI`: https://github.com/zlib-ng/zlib-ng/blob/3ea747396dcc3d63924eedbdf05bacf7866e1b29/CMakeLists.txt#L202-L210

However there is no requirement that a hard-float arm (and almost certainly never aarch64) toolchain must use `eabihf` in the multiarch tuple.

For example, see: https://wiki.debian.org/Multiarch/Tuples (in particular, "[historical note](https://wiki.debian.org/Multiarch/Tuples#Why_not_use_GNU_triplets.3F)":

> Historical note: On ARM, the canonical GNU triplet for EABI systems, whether using hard-float or soft-float, **was** arm-linux-gnueabi, despite the fact that hard-float and soft-float libraries use different calling conventions and can't be intermixed. The advice given by upstream GCC developers was to use the vendor field in the GNU triplet to express this difference1; however, the vendor field is private by design, making this unreliable for cross-distribution use. Work finally succeeded to push the arm-linux-gnueabihf triplet upstream, but there may still be some broken packages around for a while. 

For 32-bit arm it may be OK to test for `arm-linux-gnueabihf`, but without being 100% reliable on all distributions.

However for aarch64, which always builds with `hard` float, there's really no need to include `hf` in `eabi` (all references to `eabihf` seem to be in relation to 32-bit arm and not aarch64/arm64). And indeed, there doesn't seem to be any effort to use `eabihf` on aarch64 - just a couple of common aarch64 toolchains and distributions that do not use `eabihf`:

| Source | `gcc -dumpmachine` |
| :----: | ----- |
| ARM official toolchain | aarch64-linux-gnu |
| Debian | aarch64-linux-gnu |

`zlib-ng` will build the above toolchains/distributions with `-mfloat-abit=softfp` (**edit:** which may or may not fail - it seems the `-mfloat-abi` directive may only apply to 32-bit arm and may not actually have any effect on aarch64).

So, the hard-or-soft test used by `zlib-ng` is unreliable at best (32-bit arm) and wrong for aarch64 (any `eabihf` aarch64 tuple seems to be the exception rather than the norm).

Is there any particular reason why `zlib-ng` is overriding `-mfloat-abi`? If `-mfloat-abi` is already set in `$CFLAGS` then `cmake` will respect what has been set in the environment - there's no need to use `-dumpmachine`. If `-mfloat-abi` isn't already set - and assuming it needs to be set to something - then there may be a better way to determine if hard or softfp is available using `gcc` but not using `-dumpmachine`.

Similarly with `-mfpu` - if it's already set in `$CFLAGS` then `zlib-ng` should use the configured value in `cmake` rather than replace it with a potentially sub-optimal alternative. For 32-bit arm there are at least 3 possible arm FPUs with NEON support (`neon`, `neon-fp16`, and `neon-vfpv4`), and with aarch64 there are again multiple choices (eg. `-mfpu=crypto-neon-fp-armv8`).

The code that unilaterally sets `ACLEFLAG` to "-march=armv8-a+crc" even on armv7 and armv6 is another concern, but it doesn't seem to cause an issue (is ACLE being built - I'm not really sure). I do see the following on armv7:
```
 * CMAKE_BUILD_TYPE, Build type: MinSizeRel (selected)
 * ZLIB_COMPAT, Provide a zlib-compatible API
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * WITH_ACLE, Build with ACLE CRC
 * WITH_NEON, Build with NEON intrinsics
 * NEON_FILLWINDOW, Support NEON instructions in fill_window_arm, using "-mfloat-abi=hard -mfpu=neon"
 * ACLE_CRC, Support CRC hash generation using the ACLE instruction set, using "-march=armv8-a+crc"
```

I'd like to propose one solution for hard/soft if it is actually necessary to set this within `cmake` (although there may be other/better solutions): Add a `-DWITH_HARD_FLOAT` cmake option, and default this option to `ON`. Anyone building `zlib-ng` that needs to build with `softfp` can disable the option.

Ideally, however, `-mfloat-abi` and `-mfpu` would not be set at all by `zlib-ng` in `cmake`. Or at the very least they should only be set (detected/defaulted/etc) if they are not already set.

**Comment by MilhouseVH** [comment]
(sorry - totally missed the post from @dhewg who beat me to this!)

**Comment by mtl1979** [comment]
Blindly setting hard float as default is no option as there is too many modern platforms that require soft float.

**Comment by MilhouseVH** [comment]
It couldn't be any worse than setting float to the wrong value based on an unreliable test which can't be influenced by the user, meaning the build fails. Setting `hard` as a default and providing an option to use `softfp` would at least put the user in control.

Trusting the compiler flags (`-mfloat-abi`, `-mfpu`, `-march`) that are already set correctly would make all of this unnecessary.

**Comment by mtl1979** [comment]
Trusting user input pretty much makes using cmake totally pointless... I can understand it when using configure as it already has support for overriding things on command line. Like I said before, we're not going to support all broken compilers, but we can make things work better with compilers that actually don't fight logic. @Dead2 will merge in any improvements that don't break build with existing targets.

**Comment by nmoinvaz** [comment]
The detection logic was added for continuous integration. I think @MilhouseVH makes some good points. However, the idea of `WITH_HARD_FLOAT` option would get kind of messy considering that there is 3 types of floating point configurations. I think it is best to set floating point type with `CMAKE_C_FLAGS` and remove the detection logic I added to CMake. I started looking into this again due to #560 where it was mentioned that the compiler flags were different between cmake and configure for `arm-linux-gnueabihf-gcc`.

**Comment by nmoinvaz** [comment]
@MilhouseVH I believe this should be fixed in latest `develop` - you can specify `-mfloat-abi` in `CMAKE_C_FLAGS` and it will not be overriden. Also `-mfpu=neon` is now only set on source files that use neon - as instruction set flags are now set only on the files that use them.

**Comment by nmoinvaz** [comment]
If this is still an issue it can always be reopened, but it should be resolved now.
