### ISSUE TITLE
mariadb: error: conflicting types for 'crc32'

### ISSUE THREAD

**Issue by MilhouseVH** [zlib-ng/zlib-ng#483]
Building latest `mariadb-10.4.10` on Linux with latest `zlib-ng` (5bd3c582908503135fd8d6326ca0e2a6a947b44f from develop branch) and `--zlib-compat` for x86_64 host (not cross-compiling) results in the following build failure:
```
[16/179] Building C object mysys/CMakeFiles/mysys.dir/my_compress.c.o
FAILED: mysys/CMakeFiles/mysys.dir/my_compress.c.o 
/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/bin/host-gcc -DHAVE_CONFIG_H -D_FILE_OFFSET_BITS=64 -I../wsrep-lib/include -I../wsrep-lib/wsrep-API/v26 -Iinclude -I../include -I../mysys -march=native -O2 -Wall -pipe -I/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/include -Wno-format-security -pie -fPIC -Wl,-z,relro,-z,now -fstack-protector --param=ssp-buffer-size=4 -O2 -g -DNDEBUG -D_FORTIFY_SOURCE=2 -DDBUG_OFF   -fPIC -MD -MT mysys/CMakeFiles/mysys.dir/my_compress.c.o -MF mysys/CMakeFiles/mysys.dir/my_compress.c.o.d -o mysys/CMakeFiles/mysys.dir/my_compress.c.o   -c ../mysys/my_compress.c
In file included from ../mysys/my_compress.c:24:0:
/home/ubuntu/projects/LibreELEC.tv/build.LibreELEC-Generic.x86_64-9.80-devel/toolchain/include/zlib.h:1683:26: error: conflicting types for 'crc32'
 ZEXTERN uint32_t ZEXPORT crc32(uint32_t crc, const unsigned char *buf, uint32_t len);
                          ^
In file included from ../mysys/my_compress.c:20:0:
../include/my_sys.h:932:14: note: previous declaration of 'crc32' was here
 extern ulong crc32(ulong crc, const uchar *buf, uint len);
              ^
```
`mariadb` build log: http://ix.io/22Qz

No such build issue with upstream `zlib-1.2.11`.

Using `gcc-9.2.0`.

I don't currently have a fix for this, but happy to test any proposals.

**Comment by mtl1979** [comment]
This is basically result of when we added support for 64-bit architectures... "long" and "unsigned long" can be too wide so implementing the crc code in assembly would complain about register size mismatch.

**Comment by MilhouseVH** [comment]
@mtl1979 What is the `zlib-ng` policy on `--zlib-compat`? From your reply here it's not clear to me if this (and the other issues I've raised) is an acceptable/by-design break of ABI, or if maintaining 100% compatibility with upstream `zlib` is the goal and that this issue will be fixed.

If 100% `zlib` ABI compatability is not the goal for `zlib-ng` (when using `--zlib-compat`) then I'll stop posting any further ABI-related issues (I'm currently building 600+ packages cross-compiled for arm) as staying with upstream `zlib` - despite all it's problems - is going to give me the easiest life. :smile:

**Comment by mtl1979** [comment]
Policy is that zlib-ng should be 99.99% source compatible excluding macros. It will never be binary-compatible.

**Comment by Dead2** [comment]
We'll need to add some workarounds for compat mode, so compat mode supplies zlib-compatible function definitions.

**Comment by MilhouseVH** [comment]
@Dead2 many thanks. I've finished building 600+ packages with `zlib-ng` (using `--zlib-compat`) for x86_64 and arm (`armv7ve`), and I can confirm the only build issues identified so far have been #481, #482 and #483, which isn't too bad at all! :)

If you can ping me on these issues when fixes become available I'll have another go at testing.

**Comment by mtl1979** [comment]
@Dead2 Basically we need wrapper function, that converts "unsigned long" to "uint32_t" and back... it should be pretty easy but I haven't looked at the code in weeks...
