### ISSUE TITLE
Zlib-ng's CI detection in cmake causes my own CI to fail

### ISSUE THREAD

**Issue by malytomas** [zlib-ng/zlib-ng#487]
There in the cmake:
https://github.com/zlib-ng/zlib-ng/blob/3ea747396dcc3d63924eedbdf05bacf7866e1b29/CMakeLists.txt#L100
you detect CI and change build configuration based on it.
This causes my own CI for a project that would integrate zlib-ng to fail at link stage with missing __gcov_init and few more symbols.
Furthermore, it prevents CI from testing the cmake configuration without the maintainer and codecoverage switches.
I suggest to set the maintainer switch directly in travis.yml instead (and also have at least one test without it).

**Comment by mtl1979** [comment]
Looks like @Dead2 needs to revert the commit adding that if() block and do it in more compatible way...

**Comment by nmoinvaz** [comment]
I think this can be closed now.
