### ISSUE TITLE
Downloading zlib-ng using releases

### ISSUE THREAD

**Issue by dkrutsko** [zlib-ng/zlib-ng#488]
Hello, please forgive me if this has already been addressed but does zlib-ng have a standard release cycle? We are currently downloading this library by cloning the default develop branch on GitHub but that doesn't feel like a very safe approach.

Do you have a plan to use the GitHub releases feature so that we can download specific versions of zlib-ng without relying on the default GitHub branch?

**Comment by mtl1979** [comment]
I think we should at least tag some versions when the remaining bugs are fixed. I'm not sure if we release binaries for all supported targets.

**Comment by dkrutsko** [comment]
Yeah I'm not sure the binaries are as important as tagging certain releases so there's less of a chance for issues when compiling this software side by side with something like nginx.

**Comment by nmoinvaz** [comment]
I have done something similar for minizip project; where when you tag a release in master branch, it will automatically create a release and upload the assets. It is not too difficult but having a release any time soon is unlikely.

**Comment by dzenanz** [comment]
I vote for occasionally tagging some commits as more stable than average until the first release is made.

**Comment by dvershinin** [comment]
Looking for a release/tag that can be used as a reference for packaging purposes.
Is there still no release planned?

**Comment by Dead2** [comment]
We are real close now. I want to have #717 #724 #725 and #704 merged before I make a stable branch and tag an beta release.

#704 is the only one of those that is stalled currently, until someone can come up with some better macro names (or a way to do it with fewer macros). Suggestions are welcome.

The rest of them are just maturing a little until I think they are ready to be merged. (Preferably with 2 other people reviewing the code first, to speed up the maturing.)

Edit: those PRs are only the ones I think needs to go in before the branch, some of the others would be nice to get in as well but none of the others currently in the list are things I consider blockers.

**Comment by donny-dont** [comment]
@Dead2 is it time? 🤞

**Comment by nmoinvaz** [comment]
We are using GitHub Releases which now lists 2 pre-releases. I think we can close this issue. See #816 for most recent release info.
