### ISSUE TITLE
Replace bi_reverse

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#511]
I noticed this commit replacing bi_reverse with a 32-bit version only:
https://gitlab.freedesktop.org/lyudess/linux/commit/8b235f2f16a472b8cfc10e8ef1286fcd3331e033
Maybe worth a look.

**Comment by mtl1979** [comment]
Obviously we can't replace something with alternative that is Linux-specific.

**Comment by nmoinvaz** [comment]
I agree, but perhaps a 32-bit version of bit swapping will be quicker than variable length version.

**Comment by mtl1979** [comment]
I'm just worried that using faster implementation would increase binary size and memory usage considerably... It would require either 16-bit or 32-bit lookup table to be portable...

**Comment by nmoinvaz** [comment]
We can do something like [this](https://helloacm.com/how-to-reverse-bits-for-32-bit-unsigned-integer-in-cc/):
```
   uint32_t reverseBits(uint32_t n) {
        n = (n >> 1) & 0x55555555 | (n << 1) & 0xaaaaaaaa;
        n = (n >> 2) & 0x33333333 | (n << 2) & 0xcccccccc;
        n = (n >> 4) & 0x0f0f0f0f | (n << 4) & 0xf0f0f0f0;
        n = (n >> 8) & 0x00ff00ff | (n << 8) & 0xff00ff00;
        n = (n >> 16) & 0x0000ffff | (n << 16) & 0xffff0000;
        return n;
    }
```

**Comment by mtl1979** [comment]
That's pretty much unreadable... Not to mention using large constants is always slow as they have to be stored in memory.

**Comment by nmoinvaz** [comment]
There is a method `brev_knuth` here that uses less constants.
https://stackoverflow.com/a/32093050/610692

**Comment by mtl1979** [comment]
The problem is that some architectures actually have assembler instruction to do it automatically, but others need shifting in loop... 80x86 can do it shifting with carry.
