### ISSUE TITLE
Suggestion: add type prefixes to commits/PRs

### ISSUE THREAD

**Issue by gdevenyi** [zlib-ng/zlib-ng#514]
As mostly a lurker, I'm trying to follow development but its not immediately clear to me what specific PRs are doing to the codebase. The Insight Toolkit (ITK) team has a clever method of making their commit stream more readable, with commit prefixes:

> BUG: Fix for runtime crash or incorrect result
> COMP: Compiler error or warning fix
> DOC: Documentation change
> ENH: New functionality
> PERF: Performance improvement
> STYLE: No logic impact (indentation, comments)
> WIP: Work In Progress not ready for merge

from: https://github.com/InsightSoftwareConsortium/ITK/blob/master/CONTRIBUTING.md#commit-messages

I was wondering of zlib-ng might consider such an process change.

**Comment by nmoinvaz** [comment]
I went through the open PRs and added labels. That should help give more visibility in where each PR is focused. I personally don't really want to any type of commit message style enforced.

**Comment by nmoinvaz** [comment]
I'm going to close for now, if anybody has anything else to contribute we can reopen.
