### ISSUE TITLE
Benchmark/compare -O vs -O2 vs -O3 on a variety of platforms.

### ISSUE THREAD

**Issue by gdevenyi** [zlib-ng/zlib-ng#515]
Following up on #507, Fedora defaults cmake to -O2, while upstream cmake defaults to -O3. Testing by @Dead2 noted that there are indeed performance differences between the settings and it is not currently clear which is optimal.

**Comment by nmoinvaz** [comment]
Do we still need to do this since everything has been harmonized?

**Comment by Dead2** [comment]
Probably not necessary anymore
