### ISSUE TITLE
Uniformize cmake vs configure build configuration

### ISSUE THREAD

**Issue by gdevenyi** [zlib-ng/zlib-ng#516]
Following up on #507 and #515, @Dead2 noted that configure vs cmake on his system has a ~2% difference in performance.

We also discovered that cmake on Fedora is patched to be different than upstream cmake, which -O2 instead of -O3 for the "Release" configuration.

In order to avoid these inconsistencies, after #515 the cmake and configure settings should be uniformized to what zlib-ng devs consider the best choice by default, rather than relying on the platform.

**Comment by nmoinvaz** [comment]
I think this should be resolved now. CMake now uses -O2. @dankegel do know anything we are missing? I think they should be building the same with pkgcheck.sh correct?

**Comment by dankegel** [comment]
I know of no further problems (though I haven't really looked).  pkgcheck.sh is now hands off with respect to cflags.  OK to close as fixed IMHO.
