### ISSUE TITLE
X86 CPU feature flags optimized out

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#527]
When compiling `checksum_fuzzer` against static zlib (aka zlibstatic), the `x86_cpu_*` flags are optimized out when compiling with `-O3`. This happens because `x86_check_features()` is only called in `inflate()` and `deflate()`. And in the `checksum_fuzzer` it is only using the `crc32` functions which have a potential to use architecture specific codes.

I think perhaps the CPU features check should be removed from inflate() and deflate() and instead moved to the `functable` stubs. Thoughts?

**Comment by Dead2** [comment]
That might be a good idea.

**Comment by nmoinvaz** [comment]
Code has been merged.
