### ISSUE TITLE
ZLIB_COMPAT library artifact naming

### ISSUE THREAD

**Issue by kreuzerkrieg** [zlib-ng/zlib-ng#533]
I'm trying to create [vcpkg](https://github.com/microsoft/vcpkg) port for `zlib-ng` and it looks like `-DZLIB_COMPAT` does not affect the output library name.
Looks like it should
```
if (ZLIB_COMPAT)
    add_definitions(-DZLIB_COMPAT)
    set(WITH_GZFILEOP ON)
    set(LIBNAME1 libz)
    set(LIBNAME2 zlib)
    set(SUFFIX "")
else()
    set(LIBNAME1 libz-ng)
    set(LIBNAME2 zlib-ng)
    set(SUFFIX "-ng")
endif()
```

but these `LIBNAMExxx` are not used

**Comment by nmoinvaz** [comment]
@kreuzerkrieg can you verify that #534 fixes your issue?

**Comment by kreuzerkrieg** [comment]
> @kreuzerkrieg can you verify that #534 fixes your issue?

affirmative

**Comment by kreuzerkrieg** [comment]
Any chance above PR will be merged soon?

**Comment by Dead2** [comment]
It will be soon I hope, but at least one week out.
I am trying to let codecov.io have a look at a stable state for the corruption bugs (on their end) when analyzing our repo/coverage data. 
Ref: https://community.codecov.io/t/codecov-server-500-error-and-endless-processing/1012/5

**Comment by kreuzerkrieg** [comment]
Thanks for the update

**Comment by nmoinvaz** [comment]
Fix was merged into `develop`.
