### ISSUE TITLE
deflate_quick questions

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#539]
These are some questions I have about deflate_quick() that perhaps somebody (@jtkukunas ?) can answer - at least it is good to have it documented.

1. Why is deflate quick window only 8K? It seems like it would be beneficial for it to be 32K and lead to better compression rates.

2. Sometimes `dist` is greater than `s->w_size`. Is there anything that can be done to prevent it from trying to read at greater distances?
   1. Perhaps this has to do with switching the deflate level mid-stream. If it goes from level 6 (32k window size) to level 1 (8k window size) then it will still be reading 32k distances because window size doesn't change when level is updated in `deflateParams`.
3. When switching deflate level, from level 1 (8k window size) to level 6 (32k window size), since the window size never updates (nor the window buffer alloc itself), then compression performance at level 6 suffers because window size is permanently at 8k.
   1. I'm not suggesting the size of the window be reallocated or even updated, but rather that deflate_quick() support 32k window size with more lens and dist codes.
4. What method/algorithm was used in constructing the `quick_len_codes` and `quick_len_dists`? 
   1. If we had the algorithm perhaps we could have a makequick.exe that generated these automatically and is part of CI, similar to makefixed, makecrct, or maketrees..

**Comment by nmoinvaz** [comment]
With 32k window size quick deflate is ~9% slower and compresses ~7% better. 
```
sslkeylogfile.log  154,465,349
sslkeylogfile8k.log.gz 96,917,999
sslkeylogfile16k.log.gz 93,809,389
sslkeylogfile32k.log.gz 90,912,856
```
To generate the quick dist codes where `QUICK_MAX_WINDOW` is 8192:
```
/* Generate quick distance codes */
for (dist = 1; dist <= QUICK_MAX_WINDOW; dist++) {
    int32_t code = d_code(dist-1);
    int32_t code_rev = bi_reverse((unsigned)code, 5);
    int32_t extra = (dist-1) - base_dist[code];
    int32_t extra_bits = extra_dbits[code];

    quick_dist_codes[dist-1] = (extra << 13) | (code_rev << 8) | (5 + extra_bits);
}
```
Pros:
* Better compression when switching compression levels
   * Level 1 with 8K window size -> level 6 with 32k window size (window not resized)
* Supports all window sizes up to 32k (still supports 8k window size for speed)

Cons:
* Requires 128k byte table for all codes
* Slower if using max window size

**Comment by nmoinvaz** [comment]
In my tests, it seems using `longest_match` with `compare258_sse` is faster than only using `compare258_sse`. Perhaps because it gets through the content quicker because `s->strstart` is increased by `match_len`. When larger matches are found, it finishes overall compression quicker. However, more testing would need to be done to verify my results.

**Comment by mtl1979** [comment]
I think being slower is no option for deflate_quick. Too high memory usage is also bad as not all PCs have a lot of memory, especially when zlib-ng is linked statically and used by several applications at the same time.

As I see it, having better compression ratio doesn't justify all the cons, especially as one is supposed to use the other deflate versions for better compression rate.

**Comment by nmoinvaz** [comment]
After moving `compare258` out of `deflate_quick` we might no longer need `deflate_quick`. The same speed could be achieved with `deflate_fast` with 8k window.

**Comment by mtl1979** [comment]
I think deflate_quick is still useful when processor has support for SSE4... deflate_fast might be better for processors without SSE4 including non-x86 processors.

**Comment by nmoinvaz** [comment]
I am saying after `compare258` is moved out of `deflate_quick` then there is no SSE4 code in deflate_quick.

**Comment by mtl1979** [comment]
I am saying compare258 could be used in other deflate versions too, but there isn't any reason to replace it in deflate_quick...

**Comment by nmoinvaz** [comment]
I'm not suggesting replacing it in `deflate_quick`. I'm saying getting rid of `deflate_quick` if `deflate_fast` is capable of the same level of performance using SSE 4.2.

**Comment by mtl1979** [comment]
I don't know... For some reason I started writing AVX2 version of compare258 ;)

**Comment by nmoinvaz** [comment]
Even better!

**Comment by nmoinvaz** [comment]
Using the following code it is possible to get rid of precomputed len/dist tables:
```
#define send_literal(s, lc, ltree, bit_buf, bits_valid) \
    send_code(s, lc, ltree, bit_buf, bi_valid)

#define send_match_length(s, lc, dist, ltree, dtree, bit_buf, bits_valid) {\
    uint32_t code = zng_length_code[lc];\
    uint32_t c = code+LITERALS+1;\
    uint32_t len_bits = ((lc - base_length[code]) << ltree[c].Len) | ltree[c].Code; \
    uint32_t len_bits_len = ltree[c].Len + extra_lbits[code]; \
    uint32_t d = (dist-1);\
    code = d_code(d);\
    Assert(code < D_CODES, "bad d_code");\
    uint32_t dist_bits = ((d - base_dist[code]) << dtree[code].Len) | dtree[code].Code; \
    uint32_t dist_bits_len = dtree[code].Len + extra_dbits[code]; \
    send_bits(s, (dist_bits << len_bits_len) | len_bits, dist_bits_len + len_bits_len, bit_buf, bits_valid); \
}
```

The `send_match_length` can also be used in `compress_block`. Then it will only need to `send_bits` once, versus 2-4 times it currently does in `compress_block`.

While it is not as fast, it is nearly as fast, except when outputting matches. Plus there is no need for a 32KB table (`quick_dist_codes`)  + 1KB table (`quick_len_codes`). And we can support 32k window size for `deflate_quick`.
