### ISSUE TITLE
Illegal AVX instructions on older Xeon systems

### ISSUE THREAD

**Issue by todd-richmond** [zlib-ng/zlib-ng#553]
AVX instructions were added in pull #502 but cause illegal instructions on older Xeon systems. I had to disable with -DHAVE_AVX2_INTRIN=OFF even though they were enabled by default using cmake

model name	: Intel(R) Xeon(R) CPU E5-2407 0 @ 2.20GHz
cpuid level	: 13
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf eagerfpu pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm arat xsaveopt pln pts dtherm pti retpoline tpr_shadow vnmi flexpriority ept vpid

**Comment by mtl1979** [comment]
Can you test what is the exact instruction that is not implemented on that Xeon?

**Comment by todd-richmond** [comment]
all I get is an illegal instruction exception when running ccache and gcc but it doesn't say what the instruction id is. Do you have a way to tell?

**Comment by mtl1979** [comment]
It shouldn't throw exception when running either ccache or gcc because in that stage it's not executing any zlib-ng code... When running cmake it should only throw exception in the configuration stage as that is where it tests if the current processor supports AVX2... When I test if some specific instruction causes an error, I will surround it with fprintf statements, so I see what is the last text that gets printed...  You can use fprintf to print to standard error output so it won't interfere with regular output of minigzip and the other binaries.

**Comment by gdevenyi** [comment]
> ause illegal instructions on older Xeon systems.

Do you have an actual output showing exactly the error you claim?

**Comment by todd-richmond** [comment]
it definitely does. We build a complete 100% local toolchain with 150 or so components including gcc and everything else - nothing from the OS libraries. When narrowing down the offending component, I determined that zlib-ng was the only component necessary to cause a failure. A git checkout from before AVS instructions works fine and disabling the new cmake define also works. 

I just deleted my toolchain to build again from scratch, but this is the outcome of the tree I was trying to build

```
make[2]: Entering directory '/home/user/8.16.0/src'
[ 14%] Building CXX object lib/cryptoapi/src/security/CMakeFiles/cryptoapi_security.dir/rsapublicvalue.cpp.o
{standard input}: Assembler messages:
{standard input}: Internal error (Illegal instruction).
Please report this bug.
```

**Comment by mtl1979** [comment]
That's not even using zlib-ng code, the compiler itself is crashing...

**Comment by mtl1979** [comment]
Sandy Bridge definitely doesn't have AVX2 so it should never pass the complile-and-run test that cmake uses...

**Comment by todd-richmond** [comment]
I can take the exact same tree and replace only zlib-ng from before AVX instructions and compilation succeeds. Same goes for disabling them in CMAKE. 

Note that we build EVERYTHING we use - that is more than rare - probably unique. ccache would use zlib-ng in our case because we compile zlib-ng with compatibility extensions

**Comment by todd-richmond** [comment]
I'm actually building tools on a different system than the one compiling our code - a slightly newer xeon, but still without avx2
`flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon xtopology tsc_reliable nonstop_tsc unfair_spinlock pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand hypervisor lahf_lm 3dnowprefetch arat fsgsbase smep`

**Comment by mtl1979** [comment]
We need output of the AVX2 detection in both cmake and inside zlib-ng... It either thinks you are cross-compiling and skip the run test, or the operating system reports the CPU supports AVX2 when CPU definitely doesn't support it...

**Comment by mtl1979** [comment]
Like was mentioned when adding AVX2 support, it is possible that if ECX contains non-zero value before cpuid is run, the cpuid intrinsic on gcc can return wrong value... That was addressed in later fix mentioned in the pull request. That's an oversight in gcc, as ECX is cleared when using Visual C++.

**Comment by mtl1979** [comment]
Quick test to check cpuid output:
```
#include <cpuid.h>
#include <stdio.h>

static void cpuid(int info, unsigned* eax, unsigned* ebx, unsigned* ecx, unsigned* edx) {
    __cpuid(info, *eax, *ebx, *ecx, *edx);
}

static void cpuidex(int info, int subinfo, unsigned* eax, unsigned* ebx, unsigned* ecx, unsigned* edx) {
    __cpuid_count(info, subinfo, *eax, *ebx, *ecx, *edx);
}

void x86_check_features(void) {
    unsigned eax, ebx, ecx, edx;
    unsigned maxbasic;

    cpuid(0, &maxbasic, &ebx, &ecx, &edx);

    cpuid(1, &eax, &ebx, &ecx, &edx);

    if (maxbasic >= 7) {
        cpuidex(7, 0, &eax, &ebx, &ecx, &edx);

        // Reference: https://software.intel.com/sites/default/files/article/405250/how-to-detect-new-instruction-support-in-the-4th-generation-intel-core-processor-family.pdf
        fprintf(stderr, "EBX = %4x\n", ebx);
    }
}

int main() {
    x86_check_features();
    return 0;
}
```

**Comment by todd-richmond** [comment]
EBX =    0

**Comment by mtl1979** [comment]
If EBX is 0, then the AVX2 detection fails inside cmake's configuration stage... That means cmake thinks it is cross-compiling and doesn't try to run the test as according to Intel's own website, one of the instructions in the test requires AVX2 support.

**Comment by todd-richmond** [comment]
anything else you want me to try? We build several other projects (libarchive, hyperscan, image processing...) that use various SSE/AVX/... assembly instructions without problem or custom build configuration. I think some of those detect at runtime and some at compile time

**Comment by mtl1979** [comment]
Try to compile and run the AVX2 test from CMakeLists.txt:

```
#include <immintrin.h>
int main(void) {
  __m256i x = _mm256_set1_epi16(2);
  const __m256i y = _mm256_set1_epi16(1);
  x = _mm256_subs_epu16(x, y);
  (void)x;
  return 0;
}
```

**Comment by todd-richmond** [comment]
Using gcc 9.2

`z.c:3:11: warning: AVX vector return without AVX enabled changes the ABI [-Wpsabi]
    3 |   __m256i x = _mm256_set1_epi16(2);
      |           ^
In file included from /tools/arch/Linux_2.6.32-x86_64/gcc-9.2.0-pps-8.16.0/gcc-9.2.0/lib64/gcc/x86_64-pc-linux-gnu/9.2.0/include/immintrin.h:53,
                 from z.c:1:
/tools/arch/Linux_2.6.32-x86_64/gcc-9.2.0-pps-8.16.0/gcc-9.2.0/lib64/gcc/x86_64-pc-linux-gnu/9.2.0/include/avx2intrin.h:850:1: error: inlining failed in call to always_inline ‘_mm256_subs_epu16’: target specific option mismatch
  850 | _mm256_subs_epu16 (__m256i __A, __m256i __B)
      | ^~~~~~~~~~~~~~~~~
z.c:5:7: note: called from here
    5 |   x = _mm256_subs_epu16(x, y);
`

**Comment by mtl1979** [comment]
Try adding ```-mavx2``` to the compile command... It should force it to use vector ABI.

**Comment by todd-richmond** [comment]
thx - now printing : Illegal instruction

**Comment by mtl1979** [comment]
That means the AVX2 test in CMakeLists.txt is working correctly... It only leaves possibility of cmake thinking it's cross-compiling.

**Comment by todd-richmond** [comment]
I am setting -DCMAKE_C_COMPILER=$bindir/gcc and CXX, but don't set CMAKE_CXX_COMPILER_TARGET which would indicate a x-compile

Tomorrow I'll try exporting environment vars instead (CC/CXX) - its getting late and that is a non-trivial tweak to our toolchain build system...

**Comment by Dead2** [comment]
@mtl1979 
This looks like CMakeLists.txt's `add_intrinsics_option` flag's fault, it adds -mavx2 to the global cflags for all compiled files. GCC sees this flag and also enables msse3, mssse3 msse4.1, msse4.2, mpopcnt and mxsave (on x86-64 sse2 and older are implicit).

All those flags enabled means gcc can use all those instruction sets to optimize any code anywhere. These flags needs to be set per .c file/compile unit, and the code in those files needs to be hidden behind runtime checks to prevent executing illegal instructions on older cpus.

In this case, it just so happens that this was not a problem on these cpus before avx2 was enabled, because they do support the sse4.2-era instructions.

CMakeLists needs a rewrite in how it handles instruction sets and arch-specific files to solve this properly.
(Bonus points to those that remember when I made these arguments years ago when this way of doing things was introduced)

@todd-richmond If you could test with zlib-ng build using the configure instead, that should be a good test to verify this, because the configure script only enables instruction sets for the specific files that need them.

Pinging @nmoinvaz to make sure he also sees this.

**Comment by mtl1979** [comment]
@Dead2 The AVX2 test still should fail as cmake runs the test, configure only tries to compile. Nevertheless, this is one good reason to rewrite the CMakeLists.txt completely to make sure we only enable instruction set support in files that actually require them.

**Comment by nmoinvaz** [comment]
@todd-richmond can you try my PR and see if it fixes your problem with CMake?

**Comment by todd-richmond** [comment]
@nmoinvaz sorry for the long wait. I was finally able to pull this new CMakeLists.txt and my test build completed successfully this time. I noticed the PR needs a rebase, but should be good to go after - thx

**Comment by todd-richmond** [comment]
@nmoinvazy  any chance of rebasing and merging? I updated our zlib-ng tag last week after seeing other cmake related changes but it still causes apps to crash with illegal instructions unless I add -DHAVE_AVX2_INTRIN. This time I cleaned up our build system to use LTO and now the gnu assembler crashes. Disabling avx2 allows it to run again

I just spent a bit more time and this only fails for cmake build. configure script adds avx2 files to the build, but assembler works correctly. I'll convert back to configure for now for zlib, though I just spent a week converting our whole tree to cmake when it is available

**Comment by nmoinvaz** [comment]
I don’t have ability to do merges. You can find the rebased commit in #560. It is the first one in the PR.

**Comment by todd-richmond** [comment]
thx for the feedback. I can wait for that PR merge and will just use configure until then to get the avx2 functionality

**Comment by nmoinvaz** [comment]
Can you please confirm that the latest `develop` solves the problem for you?

**Comment by todd-richmond** [comment]
> Can you please confirm that the latest `develop` solves the problem for you?

@nmoinvaz looks good. I removed -DHAVE_AVX2_INTRIN=OFF  and compiles on our old system now complete w/o illegal instructions. Thx...
