### ISSUE TITLE
kde-frameworks/karchive  invalid conversion from const unsigned char to Bytef

### ISSUE THREAD

**Issue by brothermechanic** [zlib-ng/zlib-ng#564]
Hello
Thank you for develiping!
I switch all system to zlib-ng, all fine exept karchive
Can you help me to patch karchive package?
https://gist.github.com/c3b70630ded5e3c9aa59c93a640e02ea

**Comment by mtl1979** [comment]
As I see it, in zlib.h we need to change next_in to be "unsigned char *"... We won't revert the change in zlib-ng.h as it was security fix to change it to "const unsigned char *".

**Comment by brothermechanic** [comment]
worked!
thank you!
