### ISSUE TITLE
fill_window_stub should be removed once sse2 check is removed

### ISSUE THREAD

**Issue by pps83** [zlib-ng/zlib-ng#568]
https://github.com/zlib-ng/zlib-ng/blob/42aa81beafa2ea14cd780a9acf3359a0a09ca44b/functable.c#L89

same goes for all other so called stub functions that are resolved fully at compile time once sse2 is assumed to be available.

**Comment by nmoinvaz** [comment]
What SSE2 check? Right now all of the CPU flags are applied globally to all files but we are planning on moving toward something where flags are only applied to the files that need them and CPU support is determined at runtime. See #555.

**Comment by pps83** [comment]
`fill_window_stub` has this:

```
ZLIB_INTERNAL void fill_window_stub(deflate_state *s) {
    // Initialize default
    functable.fill_window = &fill_window_c;

#if defined(X86_SSE2)
# if !defined(__x86_64__) && !defined(_M_X64) && !defined(X86_NOCHECK_SSE2)
    if (x86_cpu_has_sse2)
# endif
        functable.fill_window = &fill_window_sse;
```

`x86_cpu_has_sse2` flag should be removed. sse2 is more than 20 years old. MS compilers afaik will generate sse2 code even if you don't enable sse2. If that `x86_cpu_has_sse2` flag is removed, then this fill_window_stub becomes pointless, and should be resolved at compile time without dynamic dispatch (same applies for other functions). In this PR (for my own use) I removed it: https://github.com/zlib-ng/zlib-ng/pull/570, see https://github.com/zlib-ng/zlib-ng/pull/570/commits/7a66d2af417cf8f81b70f8113cc7e32651413f64 (note, that it also removes BMI check, because other commit in that PR removes need for the check)

**Comment by mtl1979** [comment]
fill_window_stub and the other stubs are not used just for x86 and x86_64 (AMD64). They are also used for other architectures... We still support modern PPC architectures where it is possible to have two different versions of vector instruction sets... Once the PPC patch is merged in, we can't remove the stubs...

**Comment by pps83** [comment]
It clearly makes no sense to have stubs for intels because they are needed on some other archs

**Comment by mtl1979** [comment]
A lot of things don't make sense, but having exceptions for just one architecture would make the code almost unreadable.

**Comment by pps83** [comment]
There is absolutely no reason for code to be unreadable.
```
// *.h:
void fill_window(args);

// *_x86.c
void fill_window(args) 
{
...
}

// *_arm.c
void fill_window(args) 
{
...
}

# *_ppc.c
void fill_window_x(args) 
{
...
}

static int has_feature_x;
// dispatch happens only for ppc:
void fill_window(args) 
{
  if (has_feature_x)
    fill_window_x(args);
  else
    fill_window_y(args);
}
```

Another option (where ppc version may also call c version)

```
// *.h:
void fill_window_c(args);
void fill_window_arm(args);
void fill_window_ppc(args);

// *_x86.c
void fill_window_c(args) 
{
...
}

// *_arm.c
void fill_window_arm(args) 
{
...
}

# *_ppc.c
void fill_window_x(args) 
{
...
}

static int has_feature_x;
// dispatch happens only for ppc:
void fill_window_ppc(args) 
{
  if (has_feature_x)
    fill_window_x(args);
  else
    fill_window_c(args);
}

// file that uses fill_window:
#if X86
#define fill_window fill_window_c
#elif ARM
#define fill_window fill_window_arm
#elif PPC
#define fill_window fill_window_ppc
#endif
```

**Comment by mtl1979** [comment]
We used to have simple functions without stubs, but it was a lot slower that way. There was also cases where we couldn't choose the correct version because the function was called from external code directly and would have required modifications there to initialize the instruction set flag variables.

**Comment by nmoinvaz** [comment]
There is currently a PR to clean up the fill_window implementations. One is not needed per architecture.

**Comment by nmoinvaz** [comment]
The PR #530 to remove `fill_window` has been merged. Is this still needed?

**Comment by Dead2** [comment]
Closing, reopen if this is still a problem.
