### ISSUE TITLE
Lots of arrays are simply declared as-is with no extern keyword

### ISSUE THREAD

**Issue by pps83** [zlib-ng/zlib-ng#569]
I'm kind of shocked that C is ok with that. Actual array is declared in trees.h
zlib-ng, unlike plain old zlib, is full of such issues, and even if it's OK in C (is it really OK, how does linker even know which one of the arrays is correct?!) I think this and all other places should be fixed.

One easy way to see all these bugs is to try to compiler it with c++ compiler. All the issues and bugs will come out.

https://github.com/zlib-ng/zlib-ng/blob/42aa81beafa2ea14cd780a9acf3359a0a09ca44b/arch/x86/deflate_quick.c#L146

**Comment by nmoinvaz** [comment]
Those arrays in `deflate_quick.c` will be removed if #549 is merged. Do you have the output from the C++ compiler?

**Comment by pps83** [comment]
In c++ that wouldn't compile if compiling amalgamated version (all .c files concatenated), or it wouldn't link if simply compiling as c++, as this clearly declares uninitialized array and linker would eventually have duplicates. Note, as part of https://github.com/zlib-ng/zlib-ng/pull/570 I have this one addressed as well: https://github.com/zlib-ng/zlib-ng/pull/570/commits/fc594f918bf61c14446131c6c8b447377fa5d2d4

**Comment by mtl1979** [comment]
There is no valid reason to compile zlib-ng as amalgamated single file... A lot of structures and functions are meant to be private to their compilation unit. As Visual C++ is C++ compiler and not C compiler, we are already catching about half of the issues that would arise from compiling with C++ compiler instead of C compiler.

**Comment by pps83** [comment]
> There is no valid reason to compile zlib-ng as amalgamated single file

I want amalgamated zlib (and I'm sure many others would prefer to have amalgamated version). For me that's valid enough. Clearly, many people love libraries that can be turned into a single file: https://github.com/nothings/stb
Zlib is just a function that compresses one bin array to another one. 

> A lot of structures and functions are meant to be private to their compilation unit

I don't see how that can be relevant in any way to amalgamated build. These structs are different (old zlib had a bug that different units had similarly named structs, zlib-ng doesn't have it anymore afaik)
Note, that compiler clearly has much better chances to optimize amalgamated version. [sqlite](https://github.com/sqlite/sqlite), for example, is a library with many files, but release is always an [amalgamated version](https://github.com/sqlite/sqlite#the-amalgamation):

> The amalgamation is the recommended way of using SQLite in a larger application

With all the complexity of sqlite of handling all filesystems it can be made into a single .c file. zlib should also, at least, work for those who prefer it that way.

**Comment by nmoinvaz** [comment]
What value is there in amalgamation? It seems more like a programmer fetish. Why cant the compiler make optimizations with source code in separate files?

With cmake it is possible to just include a sub directory and not worry about how the sub project’s source code is structured.

**Comment by pps83** [comment]
> What value is there in amalgamation? It seems more like a programmer fetish.

with an amalgamated version one can simply add zlib.c to their build and just use it (that's how I use it myself).

> Why cant the compiler make optimizations with source code in separate files?

because compiler doesn't know anything about other functions that aren't available at compile time of .c file? With amalgamated build compiler sees them all and can optimize better. [LTO](https://en.wikipedia.org/wiki/Interprocedural_optimization) partially exist for this reason

**Comment by nmoinvaz** [comment]
Whether or not the compiler does the optimization while compiling the source or linking the source it still gets optimized. It is not a powerful argument for amalgamation.

**Comment by pps83** [comment]
> Whether or not the compiler does the optimization while compiling the source or linking the source it still gets optimized

LTO (or LTCG, link time code generation with VS) isn't plain linking. It's a fairly recent thing, most of projects do not use it for various reasons. In short, with LTO functions might be inlined even if they are in different translation units (different cpp files). With regular compilation/linking this obviously cannot happen. Either LTO is needed, or amalgamation.

> ... It is not a powerful argument for amalgamation.

I'm not saying that zlib-ng should do amalgamation, and certainly I'm not doing it for some optimizations. I simply prefer to have a single file that I can easily add to any of my projects.

**Comment by neurolabusc** [comment]
@pps83 for you use case you may want to look at [miniz](https://github.com/richgel999/miniz)

**Comment by dankegel** [comment]
This bug's title describes a non-problem for the normal use-case of zlib and zlib-ng; zlib-ng's private headers are compiled as C, and C/C++ toolchains are really, really good at combining those properly.

Maybe change the title of this bug to "zlib-ng harder to include as a single source file than miniz"?

**Comment by nmoinvaz** [comment]
The initial extern references that were mentioned in the description of this issue have been removed. This issue further describes a currently unsupported use-case: compiling as an single source file. There are pros and cons to doing that and supporting it. If it is still something that a lot of people want it would be better as a Feature Request in GitHub Discussions.
