### ISSUE TITLE
clang-11 -Weverything at 1e280ca517976f464116a460729cd0a34b5dd682

### ISSUE THREAD

**Issue by gdevenyi** [zlib-ng/zlib-ng#595]
```
$ clang-11 --version
clang version 11.0.0-++20200523063809+304b0ed4039-1~exp1~20200523164413.1701
$ CC=clang-11 cmake -DCMAKE_C_FLAGS_RELEASE:STRING='-O3 -DNDEBUG -Weverything' .
make -j40 2> clang-warnings.log
```

[clang-warnings.log](https://github.com/zlib-ng/zlib-ng/files/4674049/clang-warnings.log)

**Comment by nmoinvaz** [comment]
Cleaning up every single warning will take ages.

**Comment by gdevenyi** [comment]
Sure, I realize this is a huge amount of warnings, possibly many of these spurious. But I hope at least some of these might provide beneifical hints.

Would there be interest in getting this into the CI?

**Comment by nmoinvaz** [comment]
In CI we do `WITH_MAINTAINER_WARNINGS` option.
