### ISSUE TITLE
Publish as biicode block

### ISSUE THREAD

**Issue by lilith** [zlib-ng/zlib-ng#61]
I'm a new [biicode](http://www.biicode.com/) user. I've found it to dramatically speed up builds and I'm replacing all my existing build systems with it. It co-exists beautifully with CMake. 

Biicode comprehends the full dependency tree of all libraries and source files involved, thus it is slightly more work to set up than using CMake alone.

I'm currently using [stock zlib on biicode](http://www.biicode.com/zlib/zlib), but am doing very perf-sensitive work and would prefer to build against zlib-ng. 

I don't know zlib-ng's build needs enough to translate everything, but stock zlib seems to be a good starting point:

http://www.biicode.com/zlib/zlib/zlib/master/2/biicode.conf
http://www.biicode.com/zlib/zlib/zlib/master/2/CMakeLists.txt

Do you accept donations?

**Comment by Dead2** [comment]
We do not have enough manpower to start looking into biicode unfortunately.
If you want make a github fork of zlib-ng and make the relevant changes, then depending on the maintenance burden they will impose on use, we might consider merging the changes.
