### ISSUE TITLE
longest_match_unaligned_64 trips the alignment trap on armv7

### ISSUE THREAD

**Issue by NiLuJe** [zlib-ng/zlib-ng#624]
Tested on a Cortex A8 & a Cortex A9 (Linux, GCC 7.5, @ 1a3d80677fa3bfce74f521c278040a2a8bfb04ad).

My feeble understanding of the ARM specs would indicate that it makes sense (those are 32-bit processor, this is more that word-sized) ;).

Even if the kernel is setup in fixup mode, the performance penalty is not worth it. Which means, ideally, this shouldn't be compiled in on 32-bit arm, even with `UNALIGNED_OK`.

I'm not sure I see a better solution than adding another preprocessor define (say, `UNALIGNED64_OK`), which means buildsystem tweaks :/. Iff this limitation (can't load > word size) happened to be true on every supported 32-bit arch, something like a `__SIZEOF_POINTER__ == 8` check would do the trick (with the caveat that this is non-standard, I can vouch for it with GCC & Clang, but that's it), but I don't even know if that assumption is sound to begin with ;).

(FWIW, I currently simply disable the `HAVE_BUILTIN_CTZLL` configure check on my end, and everything's peachy :)).

**Comment by nmoinvaz** [comment]
I think `UNALIGNED64_OK` would be a good path forward. Do you want to make a PR?

**Comment by NiLuJe** [comment]
Sure, I can do that.

**Comment by NiLuJe** [comment]
Quick question: this should be enabled on x86 (32-bit), right?

**Comment by mtl1979** [comment]
Unaligned access is safe on 32-bit x86 processors using general purpose registers.

**Comment by nmoinvaz** [comment]
Probably only for 64-bit apps.
