### ISSUE TITLE
invalid instruction exception on mac

### ISSUE THREAD

**Issue by malytomas** [zlib-ng/zlib-ng#633]
My application crashes with EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP) on this line:
https://github.com/zlib-ng/zlib-ng/blob/53f9257a24362386e75504836eaeb2788360b1e8/memcopy.h#L133

callstack:
```
chunkmemset_1
chunkmemset
zng_inflate_fast
inflate
png_zlib_inflate
```

Running on iMac (mid 2011)
macos High Sierra (version 10.13.6)

cmake output:
```
-- The C compiler identification is AppleClang 9.1.0.9020039
-- The CXX compiler identification is AppleClang 9.1.0.9020039

-- Using CMake version 3.14.3
-- ZLIB_HEADER_VERSION: 1.2.11
-- ZLIBNG_HEADER_VERSION: 1.9.9
-- Arch detected: 'x86_64'
-- Basearch of 'x86_64' has been detected as: 'x86'
-- Architecture supports unaligned reads
-- Architecture-specific source files: arch/x86/x86.c;arch/x86/slide_avx.c;arch/x86/insert_string_sse.c;arch/x86/deflate_quick.c;arch/x86/fill_window_sse.c;arch/x86/slide_sse.c;arch/x86/crc_folding.c
-- The following features have been enabled:

 * CMAKE_BUILD_TYPE, Build type: Release (selected)
 * ZLIB_COMPAT, Provide a zlib-compatible API
 * WITH_OPTIM, Build with optimisation
 * WITH_NEW_STRATEGIES, Use new strategies
 * AVX2_SLIDEHASH, Support AVX2-optimized slide_hash, using "-mavx2"
 * SSE42_CRC, Support CRC hash generation using the SSE4.2 instruction set, using "-msse4"
 * SSE42_DEFLATE_QUICK, Support SSE4.2-accelerated quick compression
 * PCLMUL_CRC, Support CRC hash generation using PCLMULQDQ, using "-mpclmul"

-- The following features have been disabled:

 * WITH_GZFILEOP, Compile with support for gzFile-related functions
 * WITH_SANITIZERS, Build with address sanitizer and all supported sanitizers other than memory sanitizer
 * WITH_MSAN, Build with memory sanitizer
 * WITH_FUZZERS, Build test/fuzz
 * WITH_MAINTAINER_WARNINGS, Build with project maintainer warnings
 * WITH_CODE_COVERAGE, Enable code coverage reporting
```

The 53f9257a24362386e75504836eaeb2788360b1e8 is the first bad commit.

The 0b39a43490aea6024cc57bb577be58c675142d6d (current devel) has the same issue.

I have no issues on other devices/platforms (windows, linux, ios, ~emscripten~).

Please, let me know if I should provide any more information.

Thanks.

**Comment by mtl1979** [comment]
All x86_64 processors should support SSE2. What processor does that iMac have?

**Comment by Dead2** [comment]
You could try compiling with configure instead of cmake, we might have some problems with code compiled with the wrong instruction sets enabled, or it could depend on PR #560.

Your cpu does not support AVX2, so I think that is the likely culprit.
Could you help us debug this? Please try compiling with WITH_AVX2=OFF and see whether that helps.

**Comment by malytomas** [comment]
> All x86_64 processors should support SSE2. What processor does that iMac have?

```bash
$ sysctl -n machdep.cpu.brand_string
Intel(R) Core(TM) i5-2400S CPU @ 2.50GHz
```
Which seems to have these vector instructions:  Intel® SSE4.1, Intel® SSE4.2, Intel® AVX

> Your cpu does not support AVX2, so I think that is the likely culprit.
> Could you help us debug this? Please try compiling with WITH_AVX2=OFF and see whether that helps.

Building with WITH_AVX2=OFF (with cmake, not configure) does make it work.
(Tested on fe69810c265858b7b4242663d51336726f4a98be)

Do I have to know the target cpu at build time? Or is this an issue in runtime detection? Would building with configure instead of cmake fix runtime detection? (configure is very inconvenient for me)

Thanks

**Comment by mtl1979** [comment]
There is still some unfinished work in the run-time detection....cmake has lagged behind configure ever since it was added.

**Comment by nmoinvaz** [comment]
@malytomas can you please confirm if the latest `develop` branch solves your problem? Thank you.

**Comment by malytomas** [comment]
Yes this works for me.
Tested on 630f9658f9f2e5b27156d78aacabf93044d11366
Thanks.
