### ISSUE TITLE
crc32_combine_{gen,op} originated in zlib-1.2.12?, but are listed as 1.2.9 in zlib.map?

### ISSUE THREAD

**Issue by dankegel** [zlib-ng/zlib-ng#658]
Running test/pkgcheck.sh from 
https://github.com/dankegel/zlib-ng/tree/cmake-intrinics-files-v2-plus-bug638
after editing it to not pass --no-added-syms to abidiff fails with:
```
+ abidiff test/zlib-1.2.11-x86_64-linux-gnu.abi zlib-built.abi
Function symbols changes summary: 0 Removed, 31 Added function symbols not referenced by debug info
Variable symbols changes summary: 0 Removed, 4 Added variable symbols not referenced by debug info

31 Added function symbols not referenced by debug info:

... 
  crc32_combine_gen64
  crc32_combine_gen@@ZLIB_1.2.9
  crc32_combine_op@@ZLIB_1.2.9
```

Strictly speaking, zlib.so (when built in compat mode) probably shouldn't offer any
new symbols, as that might make it hard for users to flip back to classic
zlib.  But if they're not in zlib.h, trouble is unlikely.

Those symbols came from https://github.com/madler/zlib/commit/41d86c73b21 in zlib,
which was merged along with zlib.map changes as https://github.com/zlib-ng/zlib-ng/commit/cc36e352bafd42a2cdd

That means they're alien functions from the future :-) as far as zlib-1.2.11 is concerned...
so they probably shouldn't be exported as ZLIB_1.2.9.  Maybe 1.2.12?

Also, those symbols weren't in zlib.h in 1.2.11, so maybe they should be protected with
```
#if defined(ZLIB_INTERNAL) || !defined(ZLIB_COMPAT)
...
#endif 
```
in zlib.h until zlib actually releases a new version?

I guess it depends on which version of zlib we're trying to be compatible with, and how compatible --zlib-compat really is.

**Comment by nmoinvaz** [comment]
We could do `#if ZLIB_VERNUM > 0x12b0 || !defined(ZLIB_COMPAT)`?

**Comment by nmoinvaz** [comment]
Great work! Were those crc32_combine functions the only ones that were different?

**Comment by dankegel** [comment]
They were the only ones that jumped out at me so far, but I have not yet really looked at the map file and symbol versions.

**Comment by nmoinvaz** [comment]
@dankegel is this part of your PR, or did you want me to make one?

**Comment by dankegel** [comment]
It's not part of my PR, and is fair game.

**Comment by nmoinvaz** [comment]
Full list of functions
```
31 Added function symbols not referenced by debug info:

  adler32_avx2
  adler32_c
  adler32_ssse3
  chunkcopy_c
  chunkcopy_safe_c
  chunkcopy_safe_sse2
  chunkcopy_sse2
  chunkmemset_c
  chunkmemset_safe_c
  chunkmemset_safe_sse2
  chunkmemset_sse2
  chunksize_c
  chunksize_sse2
  chunkunroll_c
  chunkunroll_sse2
  compare258_c
  compare258_unaligned_16
  compare258_unaligned_32
  compare258_unaligned_64
  compare258_unaligned_avx2
  compare258_unaligned_sse4
  crc32_combine_gen64
  crc32_combine_gen@@ZLIB_1.2.9
  crc32_combine_op@@ZLIB_1.2.9
  longest_match_c
  longest_match_unaligned_16
  longest_match_unaligned_32
  longest_match_unaligned_64
  longest_match_unaligned_avx2
  longest_match_unaligned_sse4
  zlibng_version

4 Added variable symbols not referenced by debug info:

  zlibng_string
  zng_deflate_copyright
  zng_errmsg
  zng_inflate_copyright
```

**Comment by dankegel** [comment]
And all the unversioned ones probably need versions.

**Comment by nmoinvaz** [comment]
Yea, I will open a PR for it. Btw, your script works quite well!

**Comment by nmoinvaz** [comment]
The PR has been merged.
