### ISSUE TITLE
minigzip creates invalid gz files at compression level 1

### ISSUE THREAD

**Issue by neurolabusc** [zlib-ng/zlib-ng#680]
Building zlib using the default settings of configure or cmake, the resulting minigzip will create invalid gzip files when asked to compress to level 1. This does not happen for all files, but it does happen for some files. Examples of problematic files are the webster and reymont files from the [silesia corpus](http://sun.aei.polsl.pl/~sdeor/index.php?page=silesia). This may be an unintended consequence of the fix for [issue 6540(https://github.com/zlib-ng/zlib-ng/issues/654), as I did not observe this behavior before.

Here is a minimal script to replicate. It assumes that the file `reymont` is on the Desktop.
```
git clone https://github.com/zlib-ng/zlib-ng
cd zlib-ng
./configure
make
./minigzip -1 -k ~/Desktop/reymont
gzip -f -d ~/Desktop/reymont.gz
  gzip: /home/chris/Desktop/reymont.gz: invalid compressed data--crc error
```

**Comment by nmoinvaz** [comment]
This algorithm seems hard to get right. All the other algorithms are designed to output literals/matches one particular way except for this quick algorithm..

**Comment by nmoinvaz** [comment]
I tried with `-DUSE_MMAP=ON` and cmake on Windows and decompress with minigzip and then with WinRAR.using reymont file with no problems.

**Comment by nmoinvaz** [comment]
Looks like it is not related to `USE_MMAP`, I reprocued it without it.
