### ISSUE TITLE
configure's --native and cmake's -DWITH_NATIVE_INSTRUCTIONS don't do quite the same thing, but it's ok?

### ISSUE THREAD

**Issue by dankegel** [zlib-ng/zlib-ng#697]
This is a followon to #681 

configure's --native still links in some code that is dead because it's not supported by build machine.

cmake's  -DWITH_NATIVE_INSTRUCTIONS avoids that by doing a configure-time run check.

Because *runtime* runtime checks keep the behavior the same, this discrepancy will probably not matter to end users.

It could affect users who are insanely focused on small code size (and/or possibly small working set size / fitting everything in cache) or who expect configure and cmake to always produce identical output.

So... it's one of those little tiny bit of tech debt lint that will just hang around until it bites someone.
If this affects you, please speak up.

**Comment by nmoinvaz** [comment]
Is this still the case? I reviewed both `-DWITH_NATIVE_INSTRUCTIONS` and `--native` and they appear very similar.

**Comment by dankegel** [comment]
Are the .so's bit for bit identical?

**Comment by nmoinvaz** [comment]
Yes I think so.

Beyond Compare:

![image](https://user-images.githubusercontent.com/1364432/108781869-6f7f9400-751f-11eb-89cd-f33063ef1283.png)

CMake:

![image](https://user-images.githubusercontent.com/1364432/108782169-f3d21700-751f-11eb-98fe-53cbcaf2cdbd.png)

Configure:

![image](https://user-images.githubusercontent.com/1364432/108782373-50353680-7520-11eb-9b27-c65ea8523b6a.png)

**Comment by dankegel** [comment]
As long as they have the same sha256sum, cool.  (Couldn't tell if you checked that.)

**Comment by nmoinvaz** [comment]
BeyondCompare did binary comparison and it says "Binary same" in the bottom left, but here is `sha256sum` output:

![image](https://user-images.githubusercontent.com/1364432/108785363-1cf5a600-7526-11eb-9f1e-dc96237efc3b.png)

**Comment by dankegel** [comment]
Great, wasn't familiar with that tool.

If I figure out what I was talking about, and it's still real, I'll reopen.

**Comment by nmoinvaz** [comment]
Actually I thought about it and figured I'd try it out in CI just to make sure. I can reproduce it.
