### ISSUE TITLE
Volunteers needed: Windows makefiles need updating

### ISSUE THREAD

**Issue by Dead2** [zlib-ng/zlib-ng#7]
Windows makefiles have not been updated since the fork from zlib.

The makefiles needs to get cleaned up and updated, support for old compilers can be removed if it brings a benefit to the project.

**Comment by mtl1979** [comment]
Basically Visual C++ 2013 needs -DNOT_TWEAK_COMPILER added to WFLAGS and match.obj to OBJS in win32/Makefile.msc before it even tries to compile...

**Comment by Dead2** [comment]
After the pull from mtl1979, does this fix building of a basic zlib.dll on windows?

Next would likely be to add defines to enable optional optimizations, preferably along with some benchmarks to show that they actually make sense with the MSVC compiler.

**Comment by mtl1979** [comment]
If you add the various test cases, I can run the benchmarks with Visual Studio 2013. If something doesn't compile, I will try to fix it again... You can make a separate branch for the benchmark testing, so you won't clutter the main develop branch...

**Comment by mtl1979** [comment]
Building with Cygwin's make works now too... I ended up installing Cygwin64 and fixing win32/Makefile.gcc ... it is still pretty minimal, but "git status" gives clean source tree after "distclean" target, which I added. Makefile.bor and support for Borland C compiler is gone for good... We promised to not support legacy compilers and MSDOS has been dead for years.

**Comment by Dead2** [comment]
Great. cherry-picked :)

**Comment by mtl1979** [comment]
Next on my TODO list is getting all the assembler code to build when using nmake... I already converted one file from GNU syntax to MSVC intrinsics... Testing the code will be hard though as my CPU doesn't have SSE4.2 or AVX instructions.

**Comment by Dead2** [comment]
Sounds exciting, lots of interesting changes around intrinsics these days and I am looking forward to seeing what will emerge as the final solution :)

**Comment by mtl1979** [comment]
By looking at the code, I can conclude some of the asm blocks need complete rewrite for MSVC because there is no inline assembler for AMD64... I still need to figure out what all the remaining blocks are supposed to do...
