### ISSUE TITLE
compat mode not yet ABI compatible with classic zlib on 64 bit machines

### ISSUE THREAD

**Issue by dankegel** [zlib-ng/zlib-ng#700]
Noticed while fixing #699.

https://github.com/dankegel/zlib-ng/tree/abicheck-tmpsssh is a draft of a new script, tmp/abicheck.sh,
that compares zlib and zlib-ng --compat ABIs (as well as makes sure zlib-ng non-compat ABI remains stable).

It complains that quite a few functions have arguments of the wrong size, e.g.
```
  [C]'function uLong adler32(uLong, const Bytef*, uInt)' at adler32.c:88:1 has some indirect sub-type changes:
    return type changed:
    parameter 1 of type 'typedef uLong' changed:
      underlying type 'unsigned long int' at types.h:41:1 changed:
        entity changed from 'unsigned long int' to compatible type 'typedef __uint32_t' at types.h:41:1
          type name changed from 'unsigned long int' to 'unsigned int'
          type size changed from 64 to 32 bits
```

Evidently ZLIB_COMPAT needs to be sprinkled around the codebase a little more, a la
https://github.com/zlib-ng/zlib-ng/blob/develop/crc32.c#L64

**Comment by mtl1979** [comment]
I can make a pull request to fix this...

**Comment by dankegel** [comment]
While looking into this, I noticed 32-bit-only problems, and filed https://github.com/zlib-ng/zlib-ng/issues/705 for them.

(In short, the recent commit
"For gzseek, gzoffset, gzopen, adler32_combine, crc32_combine and crc32_combine_gen, export 32-bit and 64-bit versions for zlib-compatible api and only 64-bit version (without 64 suffix) for zlib-ng native api",
https://github.com/zlib-ng/zlib-ng/commit/6dcc7bf815c803fe7712e449b3c8fee8f3ab6dda#diff-ce3e5ac484a4ca73e6533421950dbe15
seems to introduce z_off64_t problems when building --zlib-compat on -m32 and/or real 32 bit machines.)

**Comment by mtl1979** [comment]
@nmoinvaz might need to make pull request with partial revert to fix that issue... We do still support 32-bit processors.

**Comment by dankegel** [comment]
Y'know, I should probably file a separate bug for the 32 bit problems... done.

**Comment by mtl1979** [comment]
@dankegel Indeed...

**Comment by nmoinvaz** [comment]
@dankegel anything more to do on this or can we close it out? Seems like all the PRs have been merged..

**Comment by dankegel** [comment]
The 64 bit story is pretty good, but you may want to expand the matrix in .github/worlfloat/abicheck.yml and make sure all the 64 bit architectures you care about are passing before closing it out?
