### ISSUE TITLE
arm-unknown-linux-gnueabi failure: "You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h"

### ISSUE THREAD

**Issue by joshtriplett** [zlib-ng/zlib-ng#722]
When trying to do a build (via CI) on arm-unknown-linux-gnueabi:

```
In file included from /project/src/zlib-ng/arch/arm/adler32_neon.c:11:0:
/usr/lib/gcc-cross/arm-linux-gnueabi/5/include/arm_neon.h:31:2: error: #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
 #error You must enable NEON instructions (e.g. -mfloat-abi=softfp -mfpu=neon) to use arm_neon.h
```
(Followed by a cascade of errors about not finding SIMD types and functions.)

**Comment by nmoinvaz** [comment]
Do you have a simplified GitHub Actions workflow that this can be reproduced in?

**Comment by nmoinvaz** [comment]
The detection in CMake has been improved since this was opened. Is it possible to retry with the latest version?

**Comment by joshtriplett** [comment]
I can no longer reproduce this with current zlib-ng.
