### ISSUE TITLE
z_const vs const

### ISSUE THREAD

**Issue by bjne** [zlib-ng/zlib-ng#77]
src/http/modules/ngx_http_gzip_filter_module.c:804:26: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
         ctx->in_buf->pos = ctx->zstream.next_in;

in next_in is z_const:

zconf.h

221 #if defined(ZLIB_CONST) && !defined(z_const)
222 #  define z_const const
223 #else
224 #  define z_const
225 #endif¬

**Comment by mtl1979** [comment]
This is expected behaviour... input buffer is read-only, and trying to circumvent it by copying a pointer to non-const variable is supposed to throw an error. Compare with next_out, which is not defined as const, as output buffer is read-write.
