### ISSUE TITLE
UBSAN error in trees.c

### ISSUE THREAD

**Issue by nmoinvaz** [zlib-ng/zlib-ng#782]
```
Running: /Users/runner/work/zlib-ng/zlib-ng/example_dict_fuzzer /Users/runner/work/zlib-ng/zlib-ng/deflate_fast.c
/Users/runner/work/zlib-ng/zlib-ng/trees.c:357:19: runtime error: unsigned integer overflow: 0 - 1 cannot be represented in type 'unsigned long'
```

https://github.com/nmoinvaz/zlib-ng/runs/1197163500?check_suite_focus=true see macOS Clang run. 

https://github.com/zlib-ng/zlib-ng/blob/b55680bab51aacfeb8f9bf3f7f01d5a1122f15a0/trees.c#L357

For some reason the CI fails to stop on sanitizer error.

**Comment by nmoinvaz** [comment]
Oddly enough these UBSAN warnings only show up on macOS.

**Comment by mtl1979** [comment]
It's not uncommon that specific operating systems or processors trigger errors in compilers or compiled code... I've written a few articles about for example gcc 7 series crashing inside virtual machine but working correctly on real CPU.

**Comment by nmoinvaz** [comment]
This happens because `zng_tr_flush_block` is being called even when no symbols are ready for `build_trees` calculation. Ideally `build_trees` should only be called if `s->sym_next > 0`. Since all deflate algorithms use `s->sym_next` to keep symbol count this works, except deflate quick which does not use `zng_tr_flush_block` at all. 

Just checking `s->sym_next > 0` causes a stored length block to be emitted and the gz output to be 3 bytes larger.

![image](https://user-images.githubusercontent.com/1364432/97768005-2e312780-1add-11eb-9a64-0e49563e9665.png)

But we can make it go to building an empty static tree which is the same bytes as before using this:

![image](https://user-images.githubusercontent.com/1364432/97767916-a519f080-1adc-11eb-9aaa-4d597069a479.png)
Empty static tree branch gets emitted:
![image](https://user-images.githubusercontent.com/1364432/97767950-d1357180-1adc-11eb-83c7-e29eb77515be.png)

But we can also easily ignore setting `buf = NULL` and it will still work because the first if statement checks `stored_len`:

![image](https://user-images.githubusercontent.com/1364432/97768158-6c7b1680-1ade-11eb-99cb-99349232708e.png)


I was able to reproduce using macOS Xcode, undefined behavior sanitizer and the `example` program. It easily reproduces. 

So we can either emit a stored length block or an empty static tree. I suspect madler/zlib suffers from this problem as well, but it has never shown itself because our `example` gz tests are more extensive.
