### ISSUE TITLE
different compressed data

### ISSUE THREAD

**Issue by xuchunmei000** [zlib-ng/zlib-ng#795]
I use zlib-ng and configure with --zlib-compat, and base on it I build [https://github.com/latchset/jose](jose) and run testcase of jose, found that [https://github.com/latchset/jose/blob/master/tests/alg_comp.c](alg_comp) will get failed because of zlib-ng.

alg_comp call deflate to get the compressed data and compare with the pre-defined data, since zlib-ng has optimised deflate with simd or any other optimise issues, the length and content of the compressed data is different from the pre-defined data.

baseed on zlib-ng, also I try to decompress the compressed data from call deflate, the decompressed data is the same with the origin data.

so my question is that zlib-ng do not guarantee the compressed data same with zlib-compressed data, is it by-design or any other influence.

my test platform is aarch64 with gcc10/glibc2.32.

**Comment by mtl1979** [comment]
Obviously we won't guarantee that the compressed data is bit-identical but when you decompress both streams, the result should be same. If it isn't, there is a bug that we need to fix.

**Comment by xuchunmei000** [comment]
> Obviously we won't guarantee that the compressed data is bit-identical but when you decompress both streams, the result should be same. If it isn't, there is a bug that we need to fix.

I have tried to decompress the compressed data and the result is the same with the origin，no bug.
