### ISSUE TITLE
Incompatibility with libpng ≥ 1.6.26

### ISSUE THREAD

**Issue by nmlgc** [zlib-ng/zlib-ng#80]
As of version 1.6.26, [libpng uses the undocumented inflateValidate() function when compiled with zlib version ≥ 1.8.2.1](https://github.com/glennrp/libpng/commit/35cbe7640baea6fc8466ac14db877e42505b56a7#diff-6b2a2c08b86b9ca2566040b914e34576R421). zlib-ng [defines itself as version 1.2.8.f](https://github.com/Dead2/zlib-ng/blob/343c4c549107d31f6eeabfb4b31bec4502a2ea0e/zlib.h#L48), but doesn't have inflateValidate(), so libpng can't compile.

So zlib-ng would have to either change ZLIB_VERNUM back to 0x1280, or [copy inflateValidate() and all the related branches in other functions](https://github.com/madler/zlib/commit/9852c209ac49c0d8d1192e46115d7c37d4344bbd). Or should I just go back to the regular zlib for this?

**Comment by Dead2** [comment]
Hi again, sorry for such a late reply. Real life happened :)

Hmm, 1.2.8.f is the version number supposed to be used for modified versions, so it is a bit unfortunate that this causes such problems.

I have been looking at merging the new patches, but monni said there was a problem with one of them that made some SSE4 code generate corrupt output, so I have to make time to figure out what causes that at some point. Meanwhile, you could apply a patch to set a different ZLIB_VERNUM locally.

**Comment by Dead2** [comment]
I have merged those (and a lot of other backlogged commits) to the hacknslash4 branch.
More of the backlogged upstream zlib commits will be merged soon hopefully.

**Comment by Dead2** [comment]
hacknslash5 has been merged into the develop branch, closing
