### ISSUE TITLE
Use of _CRT_NONSTDC_NO_WARNINGS in Visual Studio builds

### ISSUE THREAD

**Issue by KaoDome** [zlib-ng/zlib-ng#800]
Hi! Just stumbled upon the project looking for zlib, I'm glad it's under active development.

When building the original zlib using Visual Studio one always needed to define that preprocessor macro to avoid warnings or errors on some calls to `open`, `read`, `write` and `close` with a message stating that those POSIX names were deprecated and one should use the ISO C/C++ ones: `_open`, `_read`, `_write` and `_close`.

I noted the macro is still being defined in the Visual Studio makefile with the source files still using those functions (if I'm not mistaken it's `gzlib.c`, `gzread.c` and `gzwrite.c`).

Would switching to the ISO C/C++ nomenclature be a problem in other platforms? I mean, is it just a cosmetic change or does it imply some change in functionality as well?

If it's a trivial change it would be nice to be able to get rid of the `_CRT_NONSTDC_NO_WARNINGS` macro now that Visual Studio is finally going to be compliant with the C11 and C17 (2018) standards in the next release.

**Comment by mtl1979** [comment]
In other projects, I just redefined the names when using Visual C++... With GCC and most other compilers, the underscore is added by linker, not compiler... Microsoft versions of most file I/O functions have slight differences, so just using same for GCC and others will most likely fail. This is because Microsoft uses underscore for also preprocessor macros that the I/O functions use.

**Comment by KaoDome** [comment]
Oh! I see! After reading your comment I delved a bit more into what the fuss is about regarding the deprecation of the name of those functions (because apparently the functionality remained the same in VS).

I came across [an article](https://docs.microsoft.com/en-us/cpp/c-runtime-library/reference/open?view=msvc-160) in their docs that reads the following for `open()`:

> The name is deprecated because it doesn't follow the Standard C rules for implementation-specific names.

I wondered what that meant, _rules for implementation-specific names_, tried to look into a draft of the C standard for more information, but it turned out to be a "needle" in a 500+ document and I wasn't able to find anything concrete. I did note that those file I/O functions aren't in fact part of the standard, but I couldn't see why they can't be named without underscores.

In [another page](https://docs.microsoft.com/en-us/cpp/error-messages/compiler-warnings/compiler-warning-level-3-c4996?view=msvc-160#posix-function-names) of the docs for Visual Studio regarding the deprecation warning they seem to point to the same thing, a restriction imposed by the standard:

> Microsoft renamed some POSIX and Microsoft-specific library functions in the CRT to conform with C99 and C++03 constraints on reserved and global implementation-defined names.

In any case, considering `zlib` is a core library, widely used by plenty other projects and products, it doesn't seem worthwhile to use underscores in the code directly to forgo the warning (or error, depends on the settings) in a single platform; especially when a macro definition does away with it.

No other compiler complains about it right?

**Comment by mtl1979** [comment]
@KaoDome In Unix world, C library is not tied to compiler,  it's separate package... Later GNU C library versions have deprecated some functions and types, but I'm not sure if zlib-ng uses them.

**Comment by KaoDome** [comment]
I'm sorry for the delay guys, I've been swamped this week.

I'm going to close the issue already, we have debated about it and there was enough time for other 3rd parties to add input, but more importantly because at least the GNU C library doesn't implement nor alias those functions with underscores.

I didn't do a comprehensive test, just switched the occurrences where VS was complaining to underscored calls and tried to build the package in a Linux environment that relied on that C library (most common for Linux, right?). So yep, the current state of things is actually the optimum defining _CRT_NONSTDC_NO_WARNINGS for VS, otherwise it'd break many other systems.

I think the issue could be re-opened, or at least referenced though if at some point in the future someone thinks otherwise, but from my point of view all is good and working as expected.

Thanks @mtl1979 and @nmoinvaz!
