### ISSUE TITLE
Better usage documentation 

### ISSUE THREAD

**Issue by caiowakamatsu** [zlib-ng/zlib-ng#809]
I'm currently using this for a project, and I'm wondering if you guys have this on any type of package manager? I've tried looking around and couldn't actually find much for Mint / Ubuntu (The ones I care about). Is there anyway that there can be documentation on this / Cmake installation instructions?

**Comment by mtl1979** [comment]
I'm running Ubuntu, so eventually there will be `.deb` packages... There hasn't been much discussion yet about when we are starting to make binary packages for different Ubuntu versions... I would assume that there will be binary packages around the first official release.

**Comment by mtl1979** [comment]
I tried building `.deb` file with following scripts:

debian/control:
```
Source: zlib-ng
Maintainer: Mika Lindqvist <postmaster@raasu.org>
Section: misc
Priority: optional
Standards-Version: 3.9.2
Build-Depends: debhelper (>= 9)

Package: zlib-ng
Architecture: any
Depends: ${misc:Depends}, ${shlibs:Depends}
Description: Next Generation compression library based on zlib.

Package: zlib-ng-dev
Architecture: any
Depends: ${misc:Depends}, zlib-ng (= ${binary:Version})
Description: Development files for zlib-ng.
```

debian/rules:
```
#!/usr/bin/make -f
DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)

%:
        dh $@

override_dh_auto_configure:
        ./configure --prefix=/usr --includedir=\${prefix}/include --sysconfdir=/etc --localstatedir=/var --libdir=\${prefix}/lib/$(DEB_HOST_MULTIARCH)
```

There is some other files under the `debian` subdirectory too, but I made a separate zip file, so I can reuse the files with any source zip file.

**Comment by gdevenyi** [comment]
I think the idea is to use cpack since we already have cmake

**Comment by mtl1979** [comment]
We don't have cpack support in the build tree yet... using dh was minimalistic approach as it only requires the flags to configure...

**Comment by nmoinvaz** [comment]
Since package managers vary, the instructions will also vary. CPack has been added in #1556. I have created a PR to add instructions to the readme #1579.
