### ISSUE TITLE
nginx: "gzip filter failed to use preallocated memory" alerts appeared in logs when using zlib-ng as drop-in replacement

### ISSUE THREAD

**Issue by HansBull** [zlib-ng/zlib-ng#811]
As the title says, being on Ubuntu 20.04 amd64. This is likely a nginx problem (they made a fix for a similar problem with a Intel gzip version: https://git.kizub.ru/mirrors/nginx/-/commit/f1c4853ea1a981073b067cd1356febd08b86f898 ), but I consider it nevertheless worth reporting here.

**Comment by mtl1979** [comment]
Preallocating memory has been discouraged since early days of zlib... Some applications do it nevertheless. As long as the application developer knows how much smaller than necessary their allocation is, they can adjust the code to allocate more.

**Comment by nmoinvaz** [comment]
Nginx issue is also mentioned in #4.

**Comment by mtl1979** [comment]
I don't know how many open issues we need to track if nginx and other libraries/programs that misuse zlib API fail on zlib-ng... Obviously those will fail on all optimized forks of zlib, not just Intel or zlib-ng.

**Comment by Dead2** [comment]
@HansBull I have released the patch I personally use to make nginx compile cleanly with zlib-ng in native mode, as part of that it also fixes the allocation sizes.
Please see https://github.com/zlib-ng/patches
