### ISSUE TITLE
Oss-fuzz issue 24294

### ISSUE THREAD

**Issue by Dead2** [zlib-ng/zlib-ng#815]
https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=24294

**Comment by mtl1979** [comment]
Commit range in the regression report is too broad... it doesn't identify single commit that introduced triggering the assertion failure.

**Comment by nmoinvaz** [comment]
Appears to be an issue with `invalid match` in `deflate_slow`. Turning off `WITH_OPTIM` doesn't help.

**Comment by nmoinvaz** [comment]
I believe `s->prev_length` needs to be reset (maybe to 0?) in `fill_window`. What happens is `fill_window` is called and `s->prev_match` is off between deflate calls.

![image](https://user-images.githubusercontent.com/1364432/103111414-a27dd800-4601-11eb-9d17-f22e26c7f402.png)

Results in compressed length of 22016 bytes.

**Comment by nmoinvaz** [comment]
Here is another option:

![image](https://user-images.githubusercontent.com/1364432/103111541-03f27680-4603-11eb-986f-d4152faea55a.png)

This results in compressed length of 21911 bytes. Basically what it does, is it doesn't fill in the window until it has written the last/prev match so long as it is at least > MIN_MATCH. 

With the oss-fuzz use case, it was using level 7.

|Level|7|9|
|-|-|-|
|Gzip|21969 b|21917 b|. 
|Method 1|21998 b|21958 b|
|Method 2|21890 b|21848 b|
|Master (bad output)|21911 b |21862 b|

**Comment by nmoinvaz** [comment]
Looks like Method 2 fails on two CI instances though: https://github.com/nmoinvaz/zlib-ng/runs/1606988187?check_suite_focus=true.

**Comment by nmoinvaz** [comment]
This has been resolved and the 2 open OSS-fuzz issues have been fixed.
