### ISSUE TITLE
Stable release

### ISSUE THREAD

**Issue by silvioprog** [zlib-ng/zlib-ng#816]
Hi.

Is there any plan to publish a stable version?

cheers

**Comment by mtl1979** [comment]
Yes... There isn't exact date yet, but we are really close already...

**Comment by Neustradamus** [comment]
@Dead2, @nmoinvaz: Can you create a build today?

Really important.

Thanks in advance.

**Comment by Dead2** [comment]
@Neustradamus I had planned to do a Release Candidate this week, and can likely do that today.

The first release should follow 2-3 weeks after that, unless a major bug is found. At this point I think that is unlikely, but you never know what could crop up with more widespread testing and scrutiny.

**Comment by Dead2** [comment]
And the release is out :)

**Comment by silvioprog** [comment]
Thank you very much dudes! 👍 Now I'm going to update [my library](https://github.com/risoflora/libsagui/issues/48) to replace the zlib to zlib-ng.
