### ISSUE TITLE
CMake syntax string(REGEX) error on Ubuntu.

### ISSUE THREAD

**Issue by reworks-org** [zlib-ng/zlib-ng#818]
Trying to configure on ubuntu, recieved the following error:

-- Basearch of 'x86_64' has been detected as: 'x86'
CMake Error at dependencies/zlib-ng/CMakeLists.txt:254 (string):
  string sub-command REGEX, mode REPLACE needs at least 6 arguments total to
  command.

Seems there are some missing arguments.

**Comment by gdevenyi** [comment]
Please provide the complete configure log.

**Comment by mtl1979** [comment]
If variable CMAKE_C_FLAGS_RELEASE is empty, it can fail... In most cases it should not be empty.

**Comment by nmoinvaz** [comment]
This was resolved in https://github.com/zlib-ng/zlib-ng/commit/052b9fcb1b4df1321c6fbe5fccc895beeda3c903#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20a.
