### ISSUE TITLE
Dependent libraries fail to include zconf.h

### ISSUE THREAD

**Issue by mojca** [zlib-ng/zlib-ng#827]
If I add `zlib-ng` to `external/zlib-ng` inside my project as use it like this
```cmake
cmake_minimum_required(VERSION 3.8)
project (hello VERSION 0.1)

add_subdirectory(external/zlib-ng)

add_library(hello STATIC hello.cpp hello.h)
target_link_libraries(hello PRIVATE zlibstatic)
```
I get an error when building the library:
```
C:\path\to\project\external\zlib-ng\zlib.h(35,10): fatal error C1083: Cannot open include file: 'zconf.h': No such file or directory
```
The file is available under
```
C:\path\to\project\build\external\zlib\zconf.h
```
but most likely the build directory has not been added to the include path.

The relevant code in `CMakeLists.txt` says
```cmake
foreach(ZLIB_INSTALL_LIBRARY ${ZLIB_INSTALL_LIBRARIES})
    target_include_directories(${ZLIB_INSTALL_LIBRARY} PUBLIC
        ${CMAKE_CURRENT_BINARY_DIR} ${CMAKE_CURRENT_SOURCE_DIR})
endforeach()
```
but `${CMAKE_CURRENT_BINARY_DIR}` points to `...\build\external\zlib-ng` rather than `...\build\external\zlib` which is where the `zconf.h` file has been created.

Just for testing purposes I tried to change the above code into
```cmake
foreach(ZLIB_INSTALL_LIBRARY ${ZLIB_INSTALL_LIBRARIES})
    target_include_directories(${ZLIB_INSTALL_LIBRARY} PUBLIC
        "$<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR};${CMAKE_CURRENT_BINARY_DIR};${CMAKE_CURRENT_BINARY_DIR}/../zlib/>"
        "$<INSTALL_INTERFACE:include/zlib>"
        )
endforeach()
```
which seems to have solved this particular problem of finding the file, but the compilation broke later because `Z_EXTERN` doesn't seem to be defined (`external\zlib-ng\zlib.h(218,10): error C2143: syntax error: missing ';' before 'const'`).

What eventually solved the problem was to replace
```diff
-#include "zconf.h"
+#include "zconf-ng.h"
```
in `zlib.h` (there seem to be considerable differences between these two files), but this should probably be addressed in `CMakeLists.txt` rather than in the header file.

(I wanted to use the plain `zlib` to build a third-party project, but that one seems hopeless given that the absence of any maintenance.)

**Comment by mtl1979** [comment]
add_subdirectory() is missing second parameter. This will add the required files to include path so it can find Z_EXTERN and all other zlib-ng related defines. Without second parameter it doesn't include any files created inside CMakeLists.txt of zlib-ng.

**Comment by mojca** [comment]
What should the second parameter be?

Note that I slightly edited the description. The main problem is not even finding `zconf.h`, but the difference between
```
build/external/zlib/zconf.h
build/external/zlib-ng/zconf-ng.h
```
where only the second one contains the required definitions (the first one does not), but `zlib.h` includes the first one. If I edit `zlib.h` to include the second file, everything works fine, but that doesn't sound like "the correct solution" to me.

**Comment by mtl1979** [comment]
Second parameter overrides default binary directory of the subproject so it is subdirectory of the parent project's binary directory.

**Comment by nmoinvaz** [comment]
Original `zlib` also only produces `zconf.h` in the build directory. I have found that you have to add the `zlib` build directory to [include_directories](https://cmake.org/cmake/help/latest/command/include_directories.html). 

Here is an example of me doing it in another project that uses `zlib`: 
https://github.com/zlib-ng/minizip-ng/blob/6f17da582d2327c8cdc43622ddd31a185b6ef5fb/CMakeLists.txt#L219

For additional information related to madler/zlib see:
https://github.com/madler/zlib/issues/489

**Comment by nmoinvaz** [comment]
@mojca I was not able to reproduce your results with CMake 3.18.5. Maybe you have zlib artifacts from when you attempted to incorporate zlib. 

CMakeLists.txt:
```
cmake_minimum_required(VERSION 3.8)
project (hello VERSION 0.1)

add_subdirectory(external/zlib-ng)

add_library(hello STATIC hello.cpp hello.h)
target_link_libraries(hello PRIVATE zlibstatic)
```
hello.cpp:
```
#include "zlib-ng.h"
int main() {
    uint8_t buf[10];
    zng_adler32(0, buf, sizeof(buf));
    return 0;
}
```
Commands (Windows):
```
mkdir external
cd external
git clone git@github.com:zlib-ng/zlib-ng
cd ..
cmake . 
cmake --build .
```
Build output (no errors):
```
Microsoft (R) Build Engine version 16.8.2+25e4d540b for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  zlib.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\zlib-ngd2.dll
  adler32_test.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\adler32_test.exe
  example.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\example.exe
  zlibstatic.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\zlib-ngd.lib
  hello.cc
  hello.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\Debug\hello.lib
  infcover.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\infcover.exe
  makecrct.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\makecrct.exe
  makefixed.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\makefixed.exe
  maketrees.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\maketrees.exe
  minideflate.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\minideflate.exe
  minigzip.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\minigzip.exe
  switchlevels.vcxproj -> C:\Users\Nathan\Source\zlib-ng\zconf\external\zlib-ng\Debug\switchlevels.exe
```
Source directory contains `zlib-ng.h`, `zconf-ng.h` and `zlib.h`. 

When using `-DZLIB_COMPAT=ON`, the source directory contains `zlib-ng.h`, `zconf.h` and `zlib.h` and also builds with no errors.

**Comment by mojca** [comment]
With
```c++
#include "zlib-ng.h"
```
it works for me as well. It's apparently just with
```c++
#include "zlib.h"
```
for the same example that I'm getting build failures.

**Comment by mtl1979** [comment]
zlib.h or zconf.h should not be used with zlib-ng when compatibility mode is disabled...

**Comment by ilharp** [comment]
Same problem here... And the preprocessor here did not produce error:

```h
#ifndef ZCONF_H
#  error Missing zconf.h add binary output directory to include directories
#endif
```

It would be nice to be able to prompt the user to use `zlib-ng.h` when `#ifndef ZCONF_H`.

**Comment by mtl1979** [comment]
> Same problem here... And the preprocessor here did not produce error:
> 
> ```c
> #ifndef ZCONF_H
> #  error Missing zconf.h add binary output directory to include directories
> #endif
> ```
> 
> It would be nice to be able to prompt the user to use `zlib-ng.h` when `#ifndef ZCONF_H`.

Make sure it actually tries to include that file and not the same filename from stock zlib. When compiling anything against zlib-ng, the stock zlib headers shouldn't be in include search path.
