### ISSUE TITLE
libpng fails to link on ARM

### ISSUE THREAD

**Issue by Adenilson** [zlib-ng/zlib-ng#83]
Trying to build libpng with zlib-ng will fail at link time (tried both autotools and cmake build system).

Compiler: gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5)

libpng: libpng-1.6.28

zlib-ng: master hash 343c4c549107d31f6eeabfb4b31bec4502a2ea0e

It seems to build and link just fine on Intel.

**Comment by Adenilson** [comment]
(precise)adenilson@localhost:~/forks/zlib-ng/build$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-float=hard --with-fpu=vfpv3-d16 --with-mode=thumb --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 

(precise)adenilson@localhost:~/forks/zlib-ng/build$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/arm-linux-gnueabihf/4.6/lto-wrapper
Target: arm-linux-gnueabihf
Configured with: ../src/configure -v --with-pkgversion='Ubuntu/Linaro 4.6.3-1ubuntu5' --with-bugurl=file:///usr/share/doc/gcc-4.6/README.Bugs --enable-languages=c,c++,fortran,objc,obj-c++ --prefix=/usr --program-suffix=-4.6 --enable-shared --enable-linker-build-id --with-system-zlib --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --with-gxx-include-dir=/usr/include/c++/4.6 --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --enable-gnu-unique-object --enable-plugin --enable-objc-gc --enable-multilib --disable-sjlj-exceptions --with-arch=armv7-a --with-float=hard --with-fpu=vfpv3-d16 --with-mode=thumb --disable-werror --enable-checking=release --build=arm-linux-gnueabihf --host=arm-linux-gnueabihf --target=arm-linux-gnueabihf
Thread model: posix
gcc version 4.6.3 (Ubuntu/Linaro 4.6.3-1ubuntu5) 

(precise)adenilson@localhost:~/forks/zlib-ng/build$ cmake ..
-- The C compiler identification is GNU
-- Check for working C compiler: /usr/bin/gcc
-- Check for working C compiler: /usr/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of off64_t
-- Check size of off64_t - done
-- Looking for fseeko
-- Looking for fseeko - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Configuring done
-- Generating done
-- Build files have been written to: /home/adenilson/forks/zlib-ng/build

(precise)adenilson@localhost:~/forks/zlib-ng/build$ cmake --version
cmake version 2.8.7

(precise)adenilson@localhost:~/forks/zlib-ng/build$ time make -j4
Scanning dependencies of target zlib
Scanning dependencies of target zlibstatic
[  2%] [  8%] [  8%] Building C object CMakeFiles/zlibstatic.dir/adler32.o
Building C object CMakeFiles/zlib.dir/adler32.o
[ 11%] Building C object CMakeFiles/zlibstatic.dir/compress.o
Building C object CMakeFiles/zlib.dir/compress.o
[ 14%] [ 17%] Building C object CMakeFiles/zlib.dir/crc32.o
Building C object CMakeFiles/zlib.dir/deflate.o
[ 20%] [ 23%] Building C object CMakeFiles/zlib.dir/deflate_fast.o
Building C object CMakeFiles/zlibstatic.dir/crc32.o
[ 26%] Building C object CMakeFiles/zlib.dir/deflate_medium.o
[ 29%] Building C object CMakeFiles/zlib.dir/deflate_slow.o
[ 32%] Building C object CMakeFiles/zlibstatic.dir/deflate.o
[ 35%] Building C object CMakeFiles/zlib.dir/inflate.o
[ 38%] Building C object CMakeFiles/zlibstatic.dir/deflate_fast.o
[ 41%] Building C object CMakeFiles/zlibstatic.dir/deflate_medium.o
[ 44%] Building C object CMakeFiles/zlibstatic.dir/deflate_slow.o
[ 47%] Building C object CMakeFiles/zlibstatic.dir/inflate.o
[ 50%] [ 52%] Building C object CMakeFiles/zlib.dir/infback.o
Building C object CMakeFiles/zlib.dir/inftrees.o
[ 55%] Building C object CMakeFiles/zlibstatic.dir/infback.o
[ 58%] Building C object CMakeFiles/zlib.dir/inffast.o
[ 61%] Building C object CMakeFiles/zlibstatic.dir/inftrees.o
[ 64%] Building C object CMakeFiles/zlibstatic.dir/inffast.o
[ 67%] Building C object CMakeFiles/zlibstatic.dir/match.o
[ 70%] [ 73%] Building C object CMakeFiles/zlibstatic.dir/trees.o
[ 76%] Building C object CMakeFiles/zlib.dir/trees.o
Building C object CMakeFiles/zlib.dir/match.o
[ 79%] Building C object CMakeFiles/zlibstatic.dir/uncompr.o
[ 82%] Building C object CMakeFiles/zlibstatic.dir/zutil.o
[ 85%] Building C object CMakeFiles/zlib.dir/uncompr.o
[ 88%] Building C object CMakeFiles/zlib.dir/zutil.o
Linking C shared library libz.so
Linking C static library libz.a
[ 88%] Built target zlib
Scanning dependencies of target minigzip
Scanning dependencies of target example64
Scanning dependencies of target example
[ 88%] Built target zlibstatic
[ 91%] [ 94%] [ 97%] Building C object CMakeFiles/example.dir/test/example.o
Building C object CMakeFiles/minigzip.dir/test/minigzip.o
Building C object CMakeFiles/example64.dir/test/example.o
Scanning dependencies of target minigzip64
[100%] Building C object CMakeFiles/minigzip64.dir/test/minigzip.o
Linking C executable minigzip
Linking C executable example64
[100%] Built target minigzip
[100%] Built target example64
Linking C executable example
Linking C executable minigzip64
[100%] [100%] Built target minigzip64
Built target example

real	0m1.799s
user	0m4.264s
sys	0m0.820s

(precise)adenilson@localhost:~/forks/zlib-ng/build$ sudo make install
[ 44%] Built target zlib
[ 47%] Built target example
[ 50%] Built target example64
[ 52%] Built target minigzip
[ 55%] Built target minigzip64
[100%] Built target zlibstatic
Install the project...
-- Install configuration: ""
-- Installing: /usr/local/lib/libz.so.1.2.8.zlib-ng
-- Up-to-date: /usr/local/lib/libz.so.1
-- Installing: /usr/local/lib/libz.so
-- Installing: /usr/local/lib/libz.a
-- Installing: /usr/local/include/zconf.h
-- Installing: /usr/local/include/zlib.h
-- Installing: /usr/local/share/man/man3/zlib.3
-- Installing: /usr/local/share/pkgconfig/zlib.pc

**Comment by Adenilson** [comment]
(precise)adenilson@localhost:~/libpng-1.6.28/build$ pkg-config --cflags --libs zlib
-I/usr/local/include  -L/usr/local/lib -lz  
(precise)adenilson@localhost:~/libpng-1.6.28/build$ ls -lh /usr/local/lib/libz.*
-rw-r--r--. 1 root root 92K Feb  7 14:46 /usr/local/lib/libz.a
lrwxrwxrwx. 1 root root   9 Feb  7 14:47 /usr/local/lib/libz.so -> libz.so.1
lrwxrwxrwx. 1 root root  21 Feb  7 14:42 /usr/local/lib/libz.so.1 -> libz.so.1.2.8.zlib-ng
-rw-r--r--. 1 root root 87K Feb  7 14:46 /usr/local/lib/libz.so.1.2.8.zlib-ng
(precise)adenilson@localhost:~/libpng-1.6.28/build$ ../configure 
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /bin/mkdir -p
checking for gawk... no
checking for mawk... mawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether to enable maintainer-specific portions of Makefiles... no
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking dependency style of gcc... gcc3
checking build system type... aarch64-unknown-linux-gnu
checking host system type... aarch64-unknown-linux-gnu
checking for a sed that does not truncate output... /bin/sed
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for fgrep... /bin/grep -F
checking how to print strings... printf
checking for ld used by gcc... /usr/bin/ld
checking if the linker (/usr/bin/ld) is GNU ld... yes
checking how to run the C preprocessor... gcc -E
checking for gawk... (cached) mawk
checking whether ln -s works... yes
checking whether make sets $(MAKE)... (cached) yes
checking for BSD- or MS-compatible name lister (nm)... /usr/bin/nm -B
checking the name lister (/usr/bin/nm -B) interface... BSD nm
checking the maximum length of command line arguments... 1572864
checking how to convert aarch64-unknown-linux-gnu file names to aarch64-unknown-linux-gnu format... func_convert_file_noop
checking how to convert aarch64-unknown-linux-gnu file names to toolchain format... func_convert_file_noop
checking for /usr/bin/ld option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... pass_all
checking for dlltool... no
checking how to associate runtime and link libraries... printf %s\n
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /usr/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /bin/dd
checking how to truncate binary pipes... /bin/dd bs=4096 count=1
checking for mt... mt
checking if mt is a manifest tool... no
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... yes
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -fPIC -DPIC
checking if gcc PIC flag -fPIC -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (/usr/bin/ld) supports shared libraries... yes
checking whether -lc should be explicitly linked in... no
checking dynamic linker characteristics... GNU/Linux ld.so
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking that AWK works... ok
checking if we need to force back C standard to C89... no
checking for ANSI C header files... (cached) yes
checking for an ANSI C-conforming const... yes
checking for size_t... yes
checking whether struct tm is in sys/time.h or time.h... time.h
checking for C/C++ restrict keyword... __restrict
checking for working strtod... yes
checking for memset... yes
checking for pow... no
checking for pow in -lm... yes
checking for clock_gettime... no
configure: WARNING: not building timepng
checking for zlibVersion in -lz... yes
checking for feenableexcept in -lm... yes
checking for feenableexcept... yes
checking if using Solaris linker... no
checking if libraries can be versioned... yes
checking for symbol prefix... 
configure: pkgconfig directory is ${libdir}/pkgconfig
configure: Extra options for compiler: 
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libpng.pc
config.status: creating libpng-config
config.status: creating config.h
config.status: executing depfiles commands
config.status: executing libtool commands

**Comment by Adenilson** [comment]
(precise)adenilson@localhost:~/libpng-1.6.28/build$ time make -j4
rm -f pnglibconf.c pnglibconf.tf[45]
mawk -f ../scripts/options.awk out=pnglibconf.tf4 version=search\
	    ../pngconf.h ../scripts/pnglibconf.dfa\
	    ../pngusr.dfa  1>&2
mawk -f ../scripts/options.awk out=pnglibconf.tf5 pnglibconf.tf4 1>&2
rm pnglibconf.tf4
mv pnglibconf.tf5 pnglibconf.c
rm -f pnglibconf.out pnglibconf.tf[12]
test -d scripts || mkdir scripts || test -d scripts
gcc -E -DHAVE_CONFIG_H -I. -I.. \
	     -DPNGLIB_LIBNAME='PNG16_0' -DPNGLIB_VERSION='1.6.28' -DSYMBOL_PREFIX='' -DPNG_NO_USE_READ_MACROS -DPNG_BUILDING_SYMBOL_TABLE  pnglibconf.c > pnglibconf.tf1
mawk -f "../scripts/dfn.awk" out="pnglibconf.tf2" pnglibconf.tf1 1>&2
rm -f pnglibconf.tf1
mv pnglibconf.tf2 pnglibconf.out
rm -f pnglibconf.h
cp pnglibconf.out pnglibconf.h


... Abbreviated for brevity...


/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2 -no-undefined -export-dynamic -version-number 16:28:0  -Wl,--version-script=libpng.vers   -o libpng16.la -rpath /usr/local/lib png.lo pngerror.lo pngget.lo pngmem.lo pngpread.lo pngread.lo pngrio.lo pngrtran.lo pngrutil.lo pngset.lo pngtrans.lo pngwio.lo pngwrite.lo pngwtran.lo pngwutil.lo arm/arm_init.lo arm/filter_neon.lo arm/filter_neon_intrinsics.lo mips/mips_init.lo mips/filter_msa_intrinsics.lo   -lm -lz -lm 
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o png-fix-itxt contrib/tools/png-fix-itxt.o  -lm -lz -lm 
libtool: link: rm -fr  .libs/libpng16.a .libs/libpng16.la .libs/libpng16.lai .libs/libpng16.so .libs/libpng16.so.16 .libs/libpng16.so.16.28.0
libtool: link: gcc -shared  -fPIC -DPIC  .libs/png.o .libs/pngerror.o .libs/pngget.o .libs/pngmem.o .libs/pngpread.o .libs/pngread.o .libs/pngrio.o .libs/pngrtran.o .libs/pngrutil.o .libs/pngset.o .libs/pngtrans.o .libs/pngwio.o .libs/pngwrite.o .libs/pngwtran.o .libs/pngwutil.o arm/.libs/arm_init.o arm/.libs/filter_neon.o arm/.libs/filter_neon_intrinsics.o mips/.libs/mips_init.o mips/.libs/filter_msa_intrinsics.o   -lz -lm  -g -O2 -Wl,--version-script=libpng.vers   -Wl,-soname -Wl,libpng16.so.16 -o .libs/libpng16.so.16.28.0
libtool: link: (cd ".libs" && rm -f "libpng16.so.16" && ln -s "libpng16.so.16.28.0" "libpng16.so.16")
libtool: link: (cd ".libs" && rm -f "libpng16.so" && ln -s "libpng16.so.16.28.0" "libpng16.so")
libtool: link: ar cru .libs/libpng16.a  png.o pngerror.o pngget.o pngmem.o pngpread.o pngread.o pngrio.o pngrtran.o pngrutil.o pngset.o pngtrans.o pngwio.o pngwrite.o pngwtran.o pngwutil.o arm/arm_init.o arm/filter_neon.o arm/filter_neon_intrinsics.o mips/mips_init.o mips/filter_msa_intrinsics.o
libtool: link: ranlib .libs/libpng16.a
libtool: link: ( cd ".libs" && rm -f "libpng16.la" && ln -s "../libpng16.la" "libpng16.la" )
libtool: link: gcc -g -O2 -o png-fix-itxt contrib/tools/png-fix-itxt.o  -lz -lm
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o pngtest pngtest.o libpng16.la -lm -lz -lm 
/bin/bash ./libtool  --tag=CC   --mode=link gcc  -g -O2   -o pngunknown contrib/libtests/pngunknown.o libpng16.la -lm -lz -lm 
libtool: link: gcc -g -O2 -o .libs/pngtest pngtest.o  ./.libs/libpng16.so -lz -lm
libtool: link: gcc -g -O2 -o .libs/pngunknown contrib/libtests/pngunknown.o  ./.libs/libpng16.so -lz -lm
./.libs/libpng16.so: undefined reference to `inflateValidate'
collect2: ld returned 1 exit status
make[1]: *** [pngtest] Error 1
make[1]: *** Waiting for unfinished jobs....
./.libs/libpng16.so: undefined reference to `inflateValidate'
collect2: ld returned 1 exit status
make[1]: *** [pngunknown] Error 1
make[1]: Leaving directory `/home/adenilson/libpng-1.6.28/build'
make: *** [all] Error 2

**Comment by Adenilson** [comment]
Is inflateValidate a missing exported symbol?

**Comment by Dead2** [comment]
It is, upstream introduced it in a minor version 1.2.8.1, and our version follows the spec for modified by using 1.2.8.f, but that appears to be newer than .1 and so it tries to use that missing function. That function is in place in the hacknslash5 branch though. Hoping to finish merging and testing the new stuff within a week or two.
Modifying the zlib-ng version to be 1.2.8.0 instead should be an ok workaround.

**Comment by Adenilson** [comment]
Using hacknslash5 branch will allow libpng to build, but the test apps will fail at runtime:

(precise)adenilson@localhost:~/libpng-1.6.28/build/.libs$ LD_LIBRARY_PATH=./ ./pngtest ~/g.png 

 Testing libpng version 1.6.28
   with zlib   version 1.2.8.zlib-ng

libpng version 1.6.28 - January 5, 2017
Copyright (c) 1998-2002,2004,2006-2017 Glenn Randers-Pehrson
Copyright (c) 1996-1997 Andreas Dilger
Copyright (c) 1995-1996 Guy Eric Schalnat, Group 42, Inc.
 library (10628): libpng version 1.6.28 - January 5, 2017

 pngtest (10628): libpng version 1.6.28 - January 5, 2017

 Testing /home/adenilson/g.png:/home/adenilson/g.png: libpng warning: bad parameters to zlib
libpng error: bad parameters to zlib
/home/adenilson/g.png -> pngout.png: libpng read error

 Testing /home/adenilson/g.png: FAIL

 Testing /home/adenilson/g.png:/home/adenilson/g.png: libpng warning: bad parameters to zlib
libpng error: bad parameters to zlib
/home/adenilson/g.png -> pngout.png: libpng read error

 Testing /home/adenilson/g.png: FAIL

 Testing /home/adenilson/g.png:/home/adenilson/g.png: libpng warning: bad parameters to zlib
libpng error: bad parameters to zlib
/home/adenilson/g.png -> pngout.png: libpng read error
 FAIL
 libpng FAILS test
 Default limits:
  width_max  = 1000000
  height_max = 1000000
  cache_max  = 1000
  malloc_max = 8000000

**Comment by Adenilson** [comment]
Expected output:
(precise)adenilson@localhost:~/libpng-1.6.28/build$ ./pngtest ~/g.png 

 Testing libpng version 1.6.28
   with zlib   version 1.2.11

libpng version 1.6.28 - January 5, 2017
Copyright (c) 1998-2002,2004,2006-2017 Glenn Randers-Pehrson
Copyright (c) 1996-1997 Andreas Dilger
Copyright (c) 1995-1996 Guy Eric Schalnat, Group 42, Inc.
 library (10628): libpng version 1.6.28 - January 5, 2017

 pngtest (10628): libpng version 1.6.28 - January 5, 2017

 Testing /home/adenilson/g.png:
Files /home/adenilson/g.png and pngout.png are different
   Was /home/adenilson/g.png written with the same maximum IDAT chunk size (8192 bytes),
   filtering heuristic (libpng default), compression level (zlib default),
   and zlib version (1.2.11)?


 Pass 0: rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrw
Files /home/adenilson/g.png and pngout.png are different

Files /home/adenilson/g.png and pngout.png are different

 PASS (10006 zero samples)
 libpng passes test
 Default limits:
  width_max  = 1000000
  height_max = 1000000
  cache_max  = 1000
  malloc_max = 8000000

**Comment by Adenilson** [comment]
Ok, it seems that today's hackandslash5 branch is passing pngtest:
(precise)adenilson@localhost:~/libpng-1.6.28/build$ ./pngtest ~/g.png 
 Testing libpng version 1.6.28
   with zlib   version 1.2.11.zlib-ng

libpng version 1.6.28 - January 5, 2017
Copyright (c) 1998-2002,2004,2006-2017 Glenn Randers-Pehrson
Copyright (c) 1996-1997 Andreas Dilger
Copyright (c) 1995-1996 Guy Eric Schalnat, Group 42, Inc.
 library (10628): libpng version 1.6.28 - January 5, 2017

 pngtest (10628): libpng version 1.6.28 - January 5, 2017

 Testing /home/adenilson/g.png:
Files /home/adenilson/g.png and pngout.png are different
   Was /home/adenilson/g.png written with the same maximum IDAT chunk size (8192 bytes),
   filtering heuristic (libpng default), compression level (zlib default),
   and zlib version (1.2.11.zlib-ng)?


 Pass 0: rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrw
Files /home/adenilson/g.png and pngout.png are different

Files /home/adenilson/g.png and pngout.png are different

 PASS (10006 zero samples)
 libpng passes test
 Default limits:
  width_max  = 1000000
  height_max = 1000000
  cache_max  = 1000
  malloc_max = 8000000
(precise)adenilson@localhost:~/libpng-1.6.28/build$ ./pngtest ~/min.png 

 Testing libpng version 1.6.28
   with zlib   version 1.2.11.zlib-ng

libpng version 1.6.28 - January 5, 2017
Copyright (c) 1998-2002,2004,2006-2017 Glenn Randers-Pehrson
Copyright (c) 1996-1997 Andreas Dilger
Copyright (c) 1995-1996 Guy Eric Schalnat, Group 42, Inc.
 library (10628): libpng version 1.6.28 - January 5, 2017

 pngtest (10628): libpng version 1.6.28 - January 5, 2017

 Testing /home/adenilson/min.png:
Files /home/adenilson/min.png and pngout.png are different
   Was /home/adenilson/min.png written with the same maximum IDAT chunk size (8192 bytes),
   filtering heuristic (libpng default), compression level (zlib default),
   and zlib version (1.2.11.zlib-ng)?


 Pass 0: rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrwrw
         rwrwrwrwrwrwrwrwrwrwrw
Files /home/adenilson/min.png and pngout.png are different

Files /home/adenilson/min.png and pngout.png are different

 PASS (1969643 zero samples)
 libpng passes test
 Default limits:
  width_max  = 1000000
  height_max = 1000000
  cache_max  = 1000
  malloc_max = 8000000

**Comment by Dead2** [comment]
hacknslash5 has been merged into the develop branch, closing
