### ISSUE TITLE
Bigger compression dara stream than madler/zlib

### ISSUE THREAD

**Issue by wongjlm** [zlib-ng/zlib-ng#850]
After we tested, we noticed that zlib-ng is much faster than madler/zlib, but compressed data stresms are always bigger than madler/zlib.

Is this a limitation or any setting to be defined?

**Comment by mtl1979** [comment]
If the file contains a lot of short matches (3 bytes), it is possible that zlib-ng creates larger compressed data streams as optimized functions can only find and compare multiples of 4 bytes. Almost none of the current processors is able to compare 3 bytes directly and in the past the 4th byte has been masked out before comparing, or compared byte by byte which is really slow.

**Comment by nmoinvaz** [comment]
Zlib-ng tries to make the best trade off between compression speed and size. So to your question, it is by design.

The deflate compression levels between Zlib and Zlib-ng are different and the comparison is documented in the Wiki. There are a few algorithms we have that Zlib does not.

**Comment by nmoinvaz** [comment]
PR #828 has my latest benchmarks if you are interested.
