### ISSUE TITLE
Please don't hard-code LIB_INSTALL_DIR

### ISSUE THREAD

**Issue by Polynomial-C** [zlib-ng/zlib-ng#881]
In Gentoo Linux x86_64 libs need to go into `/usr/lib64` but the current CMakeLists.txt file hard-codes `"${CMAKE_INSTALL_PREFIX}/lib" ` which will make installation in Gentoo fail because `/usr/lib` is reserved for x86_32 libraries.

**Comment by Dead2** [comment]
You are right, this is an oversight on my part.

This (and the others) were supposed to be enclosed in `if (NOT DEFINED LIB_INSTALL_DIR)` blocks, so they can be easily overridden on the command line like `cmake . -DLIB_INSTALL_DIR=/usr/lib64/`.
```
set(LIB_INSTALL_DIR "${CMAKE_INSTALL_PREFIX}/lib" CACHE PATH "Installation directory for libraries")
```

I will make a PR for this later, and it will be included in a future minor release.

**Comment by floppym** [comment]
It would be nice if you would use the [GNUInstallDirs](https://cmake.org/cmake/help/v3.0/module/GNUInstallDirs.html) module, or at least follow the same naming convention (CMAKE_INSTALL_LIBDIR / CMAKE_INSTALL_FULL_LIBDIR).

**Comment by Dead2** [comment]
Hmm, the current names were chosen to match the ones used by the %cmake macros used in rpm.

The GNUInstallDirs names are the fourth suggested naming convention IIRC. It is obvious there are no right names.
What I do know is the names that are currently used, are used by a lot of applications already.

Only good solution would perhaps be to have detection for different sets of names from the command line, and copy their content over if found.

**Comment by mtl1979** [comment]
It could even be possible to add optional support for GNUInstallDirs using command-line option... it would basically convert the variable names to the ones we are currently using...

For example:

```cmake -DGNU_INSTALL=YES```

**Comment by nmoinvaz** [comment]
I use `GNUInstallDirs` in minizip-ng and it works good.
https://github.com/zlib-ng/minizip-ng/blob/1593060ecf093411f1f20f655e50992913c6d5b9/CMakeLists.txt#L79

**Comment by Dead2** [comment]
@nmoinvaz But does it handle this parameter properly? `cmake . -DLIB_INSTALL_DIR=/usr/lib64/`

**Comment by nmoinvaz** [comment]
I think just looking at [GNUInstallDirs.cmake](https://github.com/Kitware/CMake/blob/773df911c12958b29ad761100e1873c611819cc9/Modules/GNUInstallDirs.cmake#L327) it would be something like `cmake . -DCMAKE_INSTALL_LIBDIR=/usr/lib64/`

**Comment by Dead2** [comment]
I made a patch for this, it seems to work locally in my limited manual testing. Waiting for CI to catch up before I make a PR.
https://github.com/zlib-ng/zlib-ng/commit/1f03b95321ee3e5b9359c6c841c9cc6e1b2fe902
