### ISSUE TITLE
Problems with integration zlib-ng to lzbench

### ISSUE THREAD

**Issue by data-man** [zlib-ng/zlib-ng#883]
Hello!

I'm trying to integrate `zlib-ng` to `lzbench` in my https://github.com/inikep/lzbench/pull/100 PR.
And got this error:
>In file included from _lzbench/compressors.cpp:1526:
././zlib-ng/zlib-ng.h:1076:20: error: conflicting declaration ‘typedef uint32_t (* in_func)(void*, const uint8_t**)’
 1076 | typedef uint32_t (*in_func) (void *, const uint8_t * *);
      |                    ^~~~~~~
In file included from _lzbench/compressors.cpp:1502:
././zlib/zlib.h:1092:20: note: previous declaration as ‘typedef unsigned int (* in_func)(void*, unsigned char**)’
 1092 | typedef unsigned (*in_func) OF((void FAR *,
      |                    ^~~~~~~

Any help is very appreciated!

**Comment by mtl1979** [comment]
You're mixing headers from stock zlib and zlib-ng... It won't work...

**Comment by Dead2** [comment]
The problem is caused by including both zlib.h and zlib-ng.h in the same compilation unit, and both of them typedef the above types.

Maybe we need to prefix the names of `in_func` and `out_func`.
I am uncertain what that would mean for users though, do they use those names?

**Comment by mtl1979** [comment]
Those two are callback prototypes... they are not used directly, but as types for callback functions in function signatures...

**Comment by data-man** [comment]
> Maybe we need to prefix the names of in_func and out_func.

Yes, please!

**Comment by Dead2** [comment]
@mtl1979 So it would not be considered an API change?

**Comment by mtl1979** [comment]
@Dead2 It definitely is API change... Even if we fix these two callbacks, there is still quite a few internal functions that cause conflicts when both zlib and zlib-ng are used in same compilation unit.

**Comment by Dead2** [comment]
Yeah, that is what I thought.
So if we do want to change this, it would have to be for the next stable branch, not the 2.0 one.

We should make a complete list so we can decide whether it is worth changing.

A workaround for this case would be either don't compile zlib and zlib-ng at the same time, or you could try moving the zlib-ng include and wrappers into a separate compile unit (.c file)

**Comment by mtl1979** [comment]
@Dead2 I don't think this is the right place for this kind of discussion, but as I mentioned earlier, we shouldn't use the wrapper macros in externally visible headers. This means only functions can have prefixes, not variable types, including callback prototypes.

**Comment by data-man** [comment]
> you could try moving the zlib-ng include and wrappers into a separate compile unit (.c file)

Thanks, will try it!

**Comment by data-man** [comment]
Sorry, yet another error for 32-bit arch:

>_lzbench/zlib-ng.c: In function ‘int64_t lzbench_zlib_ng_compress(char*, size_t, char*, size_t, size_t, size_t, char*)’:
_lzbench/zlib-ng.c:7:44: error: invalid conversion from ‘uLongf*’ {aka ‘long unsigned int*’} to ‘size_t*’ {aka ‘unsigned int*’} [-fpermissive]
    7 |  int err = zng_compress2((uint8_t*)outbuf, &zcomplen, (uint8_t*)inbuf, insize, level);
      |                                            ^~~~~~~~~
      |                                            |
      |                                            uLongf* {aka long unsigned int*}
In file included from _lzbench/zlib-ng.c:2:
_lzbench/../zlib-ng/zlib-ng.h:1226:46: note:   initializing argument 2 of ‘int32_t zng_compress2(uint8_t*, size_t*, const uint8_t*, size_t, int32_t)’
 1226 | int32_t zng_compress2(uint8_t *dest, size_t *destLen, const uint8_t *source, size_t sourceLen, int32_t level);
      |                                      ~~~~~~~~^~~~~~~
_lzbench/zlib-ng.c: In function ‘int64_t lzbench_zlib_ng_decompress(char*, size_t, char*, size_t, size_t, size_t, char*)’:
_lzbench/zlib-ng.c:16:45: error: invalid conversion from ‘uLongf*’ {aka ‘long unsigned int*’} to ‘size_t*’ {aka ‘unsigned int*’} [-fpermissive]
   16 |  int err = zng_uncompress((uint8_t*)outbuf, &zdecomplen, (uint8_t*)inbuf, insize);
      |                                             ^~~~~~~~~~~
      |                                             |
      |                                             uLongf* {aka long unsigned int*}
In file included from _lzbench/zlib-ng.c:2:
_lzbench/../zlib-ng/zlib-ng.h:1249:47: note:   initializing argument 2 of ‘int32_t zng_uncompress(uint8_t*, size_t*, const uint8_t*, size_t)’
 1249 | int32_t zng_uncompress(uint8_t *dest, size_t *destLen, const uint8_t *source, size_t sourceLen);

**Comment by mtl1979** [comment]
@data-man This is also caused by using wrong header file. zlib-ng deprecated support for FAR specifier for pointers at early stage, so it is never used in its own headers

**Comment by data-man** [comment]
Thanks!

**Comment by nmoinvaz** [comment]
Perhaps this should be added to the porting guide, the list of types we have deprecated?
`FAR`, `Bytef`,...

**Comment by mtl1979** [comment]
Some function parameter types were changed to support 64-bit operating systems and to discontinue support for 16-bit operating systems and processors.

Also, some function parameters that were supposed to be read-only, use now always "const" specifier when compatibility mode is disabled.

**Comment by Dead2** [comment]
@data-man The problem here is that in your wrappers you convert `size_t` to `uLongf` before calling zlib-ng.
This was required by zlib, but zlib-ng in native mode uses the modern `size_t` instead.

**Comment by nmoinvaz** [comment]
@Dead2 what do you think about adding a `#ifdef ZLIBNG_VERSION` into zlib.h and `#ifdef ZLIB_VERSION` into zlib-ng.h?
```
// zlib.h
#ifdef ZLIBNG_VERSION
#  error Include zlib-ng.h for zlib-ng API or zlib.h for zlib-compatible API but not both
#endif

// zlib-ng.h
#ifdef ZLIB_VERSION
#  error Include zlib-ng.h for zlib-ng API or zlib.h for zlib-compatible API but not both
#endif
```

**Comment by Dead2** [comment]
Good idea, not sure of the wording though. Something that conveys both the above and the following?
"Including both zlib.h and zlib-ng.h in the same compilation unit is not compatible."

I am also not completely convinced that we cannot make this work, but this might be a good short-term workaround.

**Comment by mtl1979** [comment]
@Dead2 I'm pretty confident that we can eventually make it work, but it should be done for 2.1 or later releases...
