### ISSUE TITLE
Question: would like to configure static build, with specific library name for windows

### ISSUE THREAD

**Issue by boxerab** [zlib-ng/zlib-ng#887]
Hello,
I just read about this library in HN, and I would like to replace my standard zlib code with zlib-ng.
The parent project is also a cmake project. While the parent can build with shared libraries, I always want zlib
to build as a static library.

I currently have these lines in my zlib cmake file:

```
if(MSVC)
  set_target_properties(${LIBTARGET} PROPERTIES PREFIX "lib")
endif(MSVC)

set_target_properties(${LIBTARGET}
    PROPERTIES
    OUTPUT_NAME "${LIBTARGET}"
    ARCHIVE_OUTPUT_DIRECTORY ${CMAKE_BINARY_DIR}/thirdparty/lib
)
```

How can I configure zlib-ng to:

1. always build as static
2. have a `libzd.lib /libz.lib` name on windows
3. output to above directory

Thank you!

**Comment by nmoinvaz** [comment]
You can set zlib-compatible mode before calling `add_subdirectory`:
```
set(ZLIB_COMPAT ON)
...
add_subdirectory(thirdparty/lib/zlib-ng)
```

**Comment by nmoinvaz** [comment]
For doing static builds use `EXCLUDE_FROM_ALL` when calling `add_subdirectory` and then to link against `zlibstatic`.

```
add_subdirectory(thirdparty/lib/zlib-ng EXCLUDE_FROM_ALL)
target_link_libraries(${PROJECT_NAME} PRIVATE zlibstatic)
```

**Comment by boxerab** [comment]
@nmoinvaz thank you! I used a combination of your two suggestions:
```
set(ZLIB_COMPAT ON)
add_subdirectory(thirdparty/lib/zlib)
.
.
.
target_link_libraries(${PROJECT_NAME} PRIVATE zlibstatic)
```

**Comment by boxerab** [comment]
@nmoinvaz thanks again for your help. I've just noticed the following issue: when I install my parent project with
`sudo make install`, (to `/usr/local/lib`), it also installs the static libz library `libz.a`. Is there a way for me to tell libz-ng to not install the static library ? I want to link my parent project with the static lib, but I don't want it installed.  Thanks!

Here are the relevant lines in my parent project's cmake file:

```
  set(ZLIB_COMPAT ON)
  set(BUILD_SHARED_LIBS OFF)
  add_subdirectory(libz)
  set(Z_LIBNAME zlibstatic PARENT_SCOPE)
```

**Comment by boxerab** [comment]
got it, I used your original suggestion of `EXCLUDE_FROM_ALL` :)
