### ISSUE TITLE
PNG with zlib-ng: output not binary equal to PNG with zlib, but uncompressed results are equal

### ISSUE THREAD

**Issue by boxerab** [zlib-ng/zlib-ng#894]
Not a big issue, but I have noticed that png + zlib-ng  is not binary equal to png + zlib. 
Just reporting this in case it's news ( I am guessing it isn't, but....)

**Comment by mtl1979** [comment]
This has already been reported before and is by design.. As long as the uncompressed results are equal, there is nothing for us to fix.

**Comment by boxerab** [comment]
ok, thanks!
