### ISSUE TITLE
PVS-Studio report

### ISSUE THREAD

**Issue by pavel-pimenov** [zlib-ng/zlib-ng#901]
http://oracle.fly-server.ru/pvs-studio/zlib-ng
PVS-Studio Version:	7.12.46137.2843
Total Warnings (GA):	103
Total Warnings (OP):	5
Total Warnings (64):	10

**Comment by nmoinvaz** [comment]
It might be worth rerunning.

**Comment by nmoinvaz** [comment]
I have fixed a few more issues that are now available in `develop` branch. Please rerun and reopen if you have more concerns.
