### ISSUE TITLE
Question: does zlib-compat mode change library speed ?

### ISSUE THREAD

**Issue by boxerab** [zlib-ng/zlib-ng#902]
Hopefully, compression/decompression speed remains the same, whether in compatibility mode or not ?

**Comment by thesamesam** [comment]
There may be improvements in non-compatibility / native mode because it can use [more suitable types](https://github.com/zlib-ng/zlib-ng/blob/develop/PORTING.md#zlib-ng-native-mode) and refine the API to be suited for real world modern usage.

**Comment by Dead2** [comment]
Compression speed is practically the same in zlib-compat and native mode.
The only differences are in relation to the API, and some extra wrappers for some of the old-style functions there.

**Comment by boxerab** [comment]
Great, thanks @thesamesam and @Dead2
