### ISSUE TITLE
Sign conversion warnings

### ISSUE THREAD

**Issue by boxerab** [zlib-ng/zlib-ng#903]
My project is now linked with zlib-ng, and I like to turn up the warning level, especially for sign conversion warnings,
as this can lead to real bugs. 

There is now one conversion warning coming from zlib-ng:

https://my.cdash.org/viewBuildError.php?type=1&buildid=1984952

Thanks.

**Comment by nmoinvaz** [comment]
Looks like that link no longer works. If you see any warnings feel free to make a PR.

**Comment by boxerab** [comment]
Thanks, this was fixed in a PR. Closing.
