### ISSUE TITLE
Provide Windows ARM and ARM64 binaries in releases

### ISSUE THREAD

**Issue by MichalPetryka** [zlib-ng/zlib-ng#909]
Currently releases provide only x86 and x64 Windows binaries, since Windows 10 also supports ARM CPUs, it would be nice to also have builds for those provided.

**Comment by nmoinvaz** [comment]
GitHub Actions does not currently support Windows ARM.

**Comment by MichalPetryka** [comment]
You can build for ARM from x64 though, and as I can see the actions do that?
![image](https://user-images.githubusercontent.com/35800402/112038143-cb4f3400-8b42-11eb-80b9-b4e5992a65ee.png)

**Comment by nmoinvaz** [comment]
I forgot about that. We do cross compile so it may be possible to deliver binaries, but we don't run any tests because there is no Windows ARM platform in CI.

**Comment by mtl1979** [comment]
AARCH64 compiler is still unreliable for Windows... I have been working with Microsoft for long before it was introduced. There is some cases where ARM and AARCH64 compilers won't trigger error even when they should and some intrinsics are still missing.

**Comment by nmoinvaz** [comment]
This should be resolved for the next release.
