### ISSUE TITLE
better compat with zlib?

### ISSUE THREAD

**Issue by zhangn1985** [zlib-ng/zlib-ng#914]
in zlib's zconf.h
```h
#ifndef ZEXTERN
#  define ZEXTERN extern
#endif
#ifndef ZEXPORT
#  define ZEXPORT
#endif
#ifndef ZEXPORTVA
#  define ZEXPORTVA
#endif
```
thus some programs need ZEXTERN will fail to build with zlib-ng, even build zlib-ng with `ZLIB_COMPAT`

here is an example:
https://github.com/libretro/hatari/blob/master/libretro/utils/unzip/zlib.h

**Comment by nmoinvaz** [comment]
It seems old versions of minizip use these. It should only be added to zlib-compat API imo.
