### ISSUE TITLE
Building breaks when both _FILE_OFFSET_BITS=64 and ZLIB_COMPAT are defined

### ISSUE THREAD

**Issue by DerickEddington** [zlib-ng/zlib-ng#923]
With the `develop` branch (`9f78490`) or the latest release version 2.0.2:

When both `ZLIB_COMPAT` and `_FILE_OFFSET_BITS=64` are defined, building breaks due to `Z_WANT64` getting defined and activating the definition of the macros that rename some function names to be suffixed with "64" which causes compiler errors due to multiple definitions of these functions.

On Solaris (SunOS 5.10, using GCC 5.2.0, at least), `_FILE_OFFSET_BITS` is automatically defined by the system headers when it is not already defined (`/usr/include/sys/feature_tests.h`), and so building for 64-bit breaks on Solaris currently.

It also breaks on Linux (Ubuntu 18.04 at least) if you do `-D_FILE_OFFSET_BITS=64`.

If I interpret the Large File Support specs correctly, explicitly defining `_FILE_OFFSET_BITS` is permitted, and so building with that should work.

E.g., here is one of the errors:
```
In file included from adler32.c:6:0:
adler32.c:132:32: error: redefinition of ‘adler32_combine64’
 unsigned long Z_EXPORT PREFIX4(adler32_combine)(unsigned long adler1, unsigned long adler2, z_off64_t len2) {
                                ^
zbuild.h:17:22: note: in definition of macro ‘PREFIX4’
 #  define PREFIX4(x) x ## 64
                      ^
zlib.h:1802:29: note: previous definition of ‘adler32_combine64’ was here
 #    define adler32_combine adler32_combine64
                             ^
zbuild.h:14:21: note: in definition of macro ‘PREFIX’
 #  define PREFIX(x) x
                     ^
adler32.c:128:31: note: in expansion of macro ‘adler32_combine’
 unsigned long Z_EXPORT PREFIX(adler32_combine)(unsigned long adler1, unsigned long adler2, z_off_t len2) {
                               ^~~~~~~~~~~~~~~
Makefile:258: recipe for target 'adler32.o' failed
make: *** [adler32.o] Error 1
```

The problem is that after `PREFIX(ident)` expands to `ident` then `ident` refers to one of the renaming macros defined due to `Z_WANT64` and so `ident` then expands to `ident64`, but there is already another definition of `ident64`.

This can be reproduced in Ubuntu 18 (and I assume other Linux distros) by doing either:
```bash
cmake -D "CMAKE_C_FLAGS=-D_FILE_OFFSET_BITS=64" -D ZLIB_COMPAT=ON ../zlib-ng
cmake --build .
```
or
```bash
CFLAGS="-D_FILE_OFFSET_BITS=64" ../zlib-ng/configure --zlib-compat
make
```

And can be reproduced in Solaris 10 by simply trying to build without giving `-D_FILE_OFFSET_BITS=64` (and with giving `-m64` if needed).

**Comment by mtl1979** [comment]
Thanks for catching the regression.

**Comment by nmoinvaz** [comment]
This should be resolved now in `develop`.
