### ISSUE TITLE
recent changes to deflate_fast,deflate_medium and deflate_slow cause breaking changes

### ISSUE THREAD

**Issue by boxerab** [zlib-ng/zlib-ng#932]
The recent one line changes in these files:

```
deflate_fast.c
deflate_medium.c
deflate_slow.c
```

will break some of my unit tests here:

https://github.com/GrokImageCompression/grok

**Comment by nmoinvaz** [comment]
Which recent changes in particular?

**Comment by boxerab** [comment]
```
Author: Ilya Leoshkevich <iii@linux.ibm.com>  2021-03-18 09:54:46
Committer: Hans Kristian Rosbach <hk-github@circlestorm.org>  2021-03-20 18:35:48
Parent: bc33b26ca5391eb6b2c952cd032920033be27a53 (Added preprocessor error guards to ensure proper library usage.)
Child:  2c8fd54fb8043597cbe526832ea8d0a94de6fe83 (Only perform auto-detection of floating point ABI on ARM arch. #895)
Branches: develop, remotes/origin/2.0.x, remotes/origin/coverage-flags, remotes/origin/develop, remotes/origin/pre-release, remotes/origin/rebalance, remotes/origin/stable
Follows: 2.0.1
Precedes: 2.0.2

    Restore hash_head != 0 checks
    
    Commit bc5915e2dec7 ("Fixed unsigned integer overflow ASAN error when
    hash_head > s->strstart.") removed hash_head != 0 checks in fast,
    medium and slow deflate, because it improved performance [1].
    
    Unfortunately, the attached test started failing after that.
    Apparently, as the comments suggest, the code implicitly relies on
    matches with the beginning of the window being skipped. So restore the
    check.
    
    [1] https://github.com/zlib-ng/zlib-ng/pull/772#issuecomment-710760300
```

**Comment by iii-i** [comment]
There is indeed a problem with stable (does this need to be sorted out before #1014 is merged?):

```
$ git clone https://github.com/GrokImageCompression/grok.git
$ git clone https://github.com/GrokImageCompression/grok-test-data.git
$ cd grok
$ rm -r thirdparty/libz/*
$ curl -L https://github.com/zlib-ng/zlib-ng/tarball/pre-release | tar -C thirdparty/libz --strip-components=1 -xz
$ cmake -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_C_COMPILER=gcc-10 -DCMAKE_CXX_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER=g++-10 -DBUILD_THIRDPARTY=ON -DBUILD_TESTING=ON -DGRK_DATA_ROOT=../grok-test-data .
$ make -j $(nproc)
$ make test -j $(nproc)
```

results in

```
	1246 - NR-DEC-a1_mono.j2c-214-decode-md5 (Failed)
	1248 - NR-DEC-a1_mono.j2c-215-decode-md5 (Failed)
	1282 - NR-DEC-p0_14.j2k-232-decode-md5 (Failed)
	1284 - NR-DEC-p0_14.j2k-233-decode-md5 (Failed)
	1286 - NR-DEC-p0_14.j2k-234-decode-md5 (Failed)
	1288 - NR-DEC-p0_14.j2k-235-decode-md5 (Failed)
	1290 - NR-DEC-p0_14.j2k-236-decode-md5 (Failed)
	1292 - NR-DEC-p0_14.j2k-237-decode-md5 (Failed)
	1294 - NR-DEC-p0_14.j2k-238-decode-md5 (Failed)
	1296 - NR-DEC-p0_14.j2k-239-decode-md5 (Failed)
	1298 - NR-DEC-p0_14.j2k-240-decode-md5 (Failed)
	1300 - NR-DEC-basn6a08.jp2-241-decode-md5 (Failed)
	1302 - NR-DEC-basn6a08.jp2-242-decode-md5 (Failed)
	1304 - NR-DEC-basn6a08.jp2-243-decode-md5 (Failed)
	1306 - NR-DEC-basn6a08.jp2-244-decode-md5 (Failed)
	1308 - NR-DEC-basn6a08.jp2-245-decode-md5 (Failed)
	1310 - NR-DEC-basn6a08.jp2-246-decode-md5 (Failed)
	1312 - NR-DEC-basn6a08.jp2-247-decode-md5 (Failed)
	1314 - NR-DEC-basn6a08.jp2-248-decode-md5 (Failed)
	1316 - NR-DEC-basn6a08.jp2-249-decode-md5 (Failed)
	1423 - NR-DEC-BMP_v5_with_ICC.jp2-301-decode-md5 (Failed)
	1425 - NR-DEC-BMP_v5_with_ICC2.jp2-302-decode-md5 (Failed)
	1427 - NR-DEC-BMP_v5_with_ICC.jp2-303-decode-md5 (Failed)
	1429 - NR-DEC-BMP_v5_with_ICC2.jp2-304-decode-md5 (Failed)
```

Without zlib-ng update there are no failures.

**Comment by Dead2** [comment]
@iii-i I would prefer getting that fixed before 2.0.5, yes. But since 2.0.5 fixes other bugs too, I will release it with a caveat if this is not fixed in time.

**Comment by iii-i** [comment]
@boxerab I think what happens here is related to what this comment is warning about: https://github.com/GrokImageCompression/grok/blob/a4fc7e3edfc71ff1a332882656f156699dc6d95d/tests/nonregression/checkmd5refs.cmake#L25

When I run `./bin/grk_decompress -i ../grok-test-data/input/conformance/a1_mono.j2c -o a1_mono_png-1.png -L 9 -p 1S` manually with both upgraded and non-unpgraded zlib-ng, the resulting images are visually identical. So apparently the upgraded zlib-ng produces a different, but nevertheless valid, deflate stream.

**Comment by Dead2** [comment]
@iii-i But it would still be a bug if zlib-ng does not output the same bitstream as it received, since we are supposed to be lossless.
Unless the problem is elsewhere of course.

**Comment by boxerab** [comment]
@iii-i yes, you are probably right. Can you verify that the images are identical ?

If you use Graphics Magick, then you can run

`$ gm compare foo.png bar.png -metric PSNR`

and you should get `INF` as your result if `foo` and `bar` are identical.

**Comment by iii-i** [comment]
@Dead2 I think the uncompressed data stays the same, it's just that with my change zlib-ng finds different matches, so the compressed streams differ.

@boxerab It's inf:

```
$ md5sum a1_mono_png-1-new.png a1_mono_png-1-old.png
f182ada2a851d826c4c46d313c409d92  a1_mono_png-1-new.png
f1f3e8f6bc7dfc0d4ad168842943d822  a1_mono_png-1-old.png

$ gm compare a1_mono_png-1-new.png a1_mono_png-1-old.png -metric PSNR
Image Difference (PeakSignalToNoiseRatio):
           PSNR
          ======
     Red: inf   
   Green: inf   
    Blue: inf   
   Total: inf   
```

![a1_mono_png-1-new](https://user-images.githubusercontent.com/45998171/123012510-a75df180-d3c2-11eb-8d02-7d238d488379.png)
![a1_mono_png-1-old](https://user-images.githubusercontent.com/45998171/123012512-a7f68800-d3c2-11eb-840e-0bb7ec993c5c.png)

**Comment by boxerab** [comment]
@iii-i in that case, I have no issue with the latest changes :)

**Comment by Dead2** [comment]
@iii-i But if the md5sum of the file differs before and after compression/decompression cycle, then something is wrong. Is that not what you just proved above? Input and ouhtput should always be bit-identical..
PSNR only compares the resulting bitmaps, the corruption can easily lie in the metadata.

**Comment by iii-i** [comment]
If I understand the test correctly, it's just compression during png creation. And comparing compressed data is always prone to changes in how zlib-ng finds matches.

**Comment by Dead2** [comment]
@iii-i Oh, in that case that makes sense. A simple test for that would be to let it compress using stock zlib with a "wrong" compression level if possible, that would lead to a fully valid file but one that does not pass the md5sum check.

What makes me think that this is not the case is that it apparently started failing after your change, and if it worked before that then the theory cannot be right since we have been making very different compressed files for a long time. Unless we somehow manage to match stock in this case, but it seems unlikely since we have so many different things that affect the compressed size of the same file, for example matching a minimum of 4 bytes instead of 3, the changed hashing in insert_string and the bigger hash buffer.

So IDK, but at the moment I am not feeling confident either way.

I got my second vaccine shot yesterday, so unfortunately I am running a high fever and all the fun pain that comes with it, so I am useless today and likely for another day or two. 🤒

**Comment by nmoinvaz** [comment]
Even though we match 4 bytes, his data could be structured in a way that there would never have been a 3 byte match in stock zlib. It might occur in the case of repeating 32-bit RGBA data.

@Dead2 hope you feel better soon.

**Comment by boxerab** [comment]
@nmoinvaz none of my test images are 32 bit. And the example above is mono.

**Comment by iii-i** [comment]
So, I did a couple extra checks. The pixels are intact:
```
$ convert a1_mono_png-1-new.png a1_mono_png-1-new.bmp
$ convert a1_mono_png-1-old.png a1_mono_png-1-old.bmp
$ diff -u a1_mono_png-1-new.bmp a1_mono_png-1-old.bmp ; echo $?
0
```

The metadata too (used https://github.com/Hedroed/png-parser for that):
```
$ diff -u <(png-parser --crc a1_mono_png-1-old.png) <(png-parser --crc a1_mono_png-1-new.png)
@@ -18,12 +18,12 @@
 CRC : 9fd6e33d
 Data size : 1
 
-[00000046-00002400] (2)
+[00000046-00002398] (2)
 IDAT:
-CRC : edd33588
-Data size : 2343
+CRC : b4385d8c
+Data size : 2341
 
-[00002401-00002412] (3)
+[00002399-00002410] (3)
 IEND:
 CRC : ae426082
 Data size : 0
```

Only IDAT chunk checksum differs, which is as expected.



@Dead2 get well soon!

**Comment by nmoinvaz** [comment]
Also see https://github.com/zlib-ng/zlib-ng/discussions/905 and https://github.com/zlib-ng/zlib-ng/issues/894.

**Comment by mtl1979** [comment]
Can the "Bug" label be removed if it is the test that is incorrect, and there is no bug in zlib-ng...

Just the assumption that test is correct if zlib or older zlib-ng version passes doesn't mean that the test is 100% correct.

**Comment by boxerab** [comment]
thanks all, will close this.
