### ISSUE TITLE
Binary compatibility problems with zlib

### ISSUE THREAD

**Issue by heikoklein** [zlib-ng/zlib-ng#94]
Hi,
I try to use zlib-ng as drop-in binary replacement for zlib. I'm currently on Ubuntu 16.04 and compile zlib-ng (fresh clone) with --zlib-compat.

Running 
ncdump test.nc
works (ncdump uses zlib internally to decompress compressed chunks of data)

Running
LD_PRELOAD=/disk1/tmp/zlib-ng_build/lib/libz.so ncdump test.nc
fails with a HDF error, i.e. error while inflating data.

I'm not sure how the HDF library internally calls libz, so I can't give a better example.

Heiko

**Comment by RJVB** [comment]
When I do the same in my home-built "LinuxPorts" install prefix (on Ubuntu 14.04) I get messages like this:

```
libpng error: unsupported zlib version
org.kde.kwindowsystem: Loaded plugin "/opt/local/share/qt5/plugins/kf5/org.kde.kwindowsystem.platforms/KF5WindowSystemX11Plugin.so" for platform "xcb"
ark.libarchive: Could not open the archive: Internal error initializing compression library: invalid library version
libpng error: unsupported zlib version
```

```
> CD /opt/local/site-ports/ git push
/opt/local/site-ports
fatal: inflateInit: wrong version (no message)
```

I can swap zlib "stock" 1.2.8; 1.2.11 and zlib/cloudflare (based on 1.2.8) without that error.

**Comment by RJVB** [comment]
Found the culprit: 

```
int inflateInit2_(z_stream *, int, const char *, int): client built against version=1.2.8 specifies stream_size=112,expected=104
```

IOW, the z_stream struct definitions aren't compatible (this is in 64bit). Not yet certain which of the differences in struct member types causes this and whether or not padding is involved.

It seems though that this is something that should be caught by the ZLIB compatibility mode, no?

**Comment by RJVB** [comment]
A quick test suggests that this does the trick:

```
diff --git a/zlib.h b/zlib.h
index 05b28c2..df34690 100644
--- a/zlib.h
+++ b/zlib.h
@@ -109,6 +109,9 @@ typedef struct z_stream_s {
     int                   data_type;  /* best guess about the data type: binary or text
                                          for deflate, or the decoding state for inflate */
     uint32_t              adler;      /* Adler-32 or CRC-32 value of the uncompressed data */
+#ifdef ZLIB_COMPAT
+    uint32_t              padding;    /* pad out to the same size as the zlib struct */
+#endif
     unsigned long         reserved;   /* reserved for future use */
 } z_stream;
 
```

There is indeed padding: the zlib-ng struct is 104 bytes total for a cumulative member size of 96 bytes; the zlib struct is 112 bytes for 100 bytes.

Using a 2nd 32bit padding member instead of making `adler` a 64bit variable to avoid side-effects.

**Comment by Dead2** [comment]
This might now work, please test :)

**Comment by heikoklein** [comment]
I just downloaded the latest zlib-ng develop branch and applied your patch from May 23. I can confirm that the issue is solved. Thanks, Heiko

**Comment by Dead2** [comment]
Thanks!

**Comment by heikoklein** [comment]
I don't see the patch in the development-branch? The last commit there is from 17.03. Eventually, there is a forgotten git push, or am I looking at the wrong place?

**Comment by Dead2** [comment]
See PR #115
