### ISSUE TITLE
Uninstallation?

### ISSUE THREAD

**Issue by N-Accumbens** [zlib-ng/zlib-ng#968]
Hello,

So I wasn't thinking through the documentation very carefully and I ran `make install` at the end before realizing that I should have done `LD_PRELOAD`. I'm wondering if there's a way to undo my changes?

Thanks

**Comment by mtl1979** [comment]
It's quite easy to get the list of files and directories zlib-ng creates, but it is not easy to undo if it replaces existing files.

**Comment by N-Accumbens** [comment]
> It's quite easy to get the list of files and directories zlib-ng creates, but it is not easy to undo if it replaces existing files.

Not being able to undo the replacement is understandable. How can I get the list of files that were created?

Also, for future reference, what am I supposed to do after the `make test` step in the readme, if I don't want to make zlib-ng into the default for all programs?

**Comment by mtl1979** [comment]
To get list of directories and files zlib-ng creates, use commands:
```
rm -rf /tmp/zlib-ng
make prefix=/tmp/zlib-ng install
find /tmp/zlib-ng
```
