### ISSUE TITLE
incorporating fast zlib changes

### ISSUE THREAD

**Issue by arsnyder16** [zlib-ng/zlib-ng#97]
Is there any plan of incorporating the changes made by fast zlib. The speed differences are significant.

https://github.com/gildor2/fast_zlib
https://github.com/gildor2/fast_zlib/wiki

**Comment by mtl1979** [comment]
It would need pretty exhaustive cleanup because a lot of macros and defines are either different or removed in zlib-ng.

**Comment by sebpop** [comment]
I just abandoned the patch that ports the changes from fast-zlib.
Can we close this issue as well? The change is too intrusive to get merged in zlib-ng. It also does not provide enough performance speedup or better compression on several data sets.

**Comment by 0181532686cf4a31163be0bf3e6bb6732bf** [comment]
@sebpop so in your opinion, is it still worth the time/work? or zlib-ng should outperform fast-zlib in most cases?

**Comment by gdevenyi** [comment]
I suggest integrating fastzlib into the latest benchmarking and see if it's worth investigating

**Comment by nmoinvaz** [comment]
From the description of the algorithm changes on fastzlib website:

> Original implementaition was very straightforward. It takes first 3 bytes of the string, computes their hash, and looks over history using hash table to find a match. If it will find a longer string, it remembers it, and continues search using the same hash for first 3 bytes. The penalty of this approach is when code looks for a string which first 3 bytes (or bytes with the same hash value) are used very often in a file.

> Optimized version does an attempt to look over history with smaller number of checks. The idea is very simple: when algorithm finds a match (intermediate one), it computes hashes for all matching bytes, and selects a different hash chain - that one which points farther from current position. This is obvious - if we have 2 hash chains, one points at distance 10, and another one at distance 1000, it is not worth checking distance 10 because other bytes will not match - the closest possible match will occur at position 1000 or farther.

It sounds like the algorithm will skip ahead and make some assumptions that farther matches will always yield better results. Perhaps this is what @sebpop encountered when he said that it does not provide better compression on several data sets.

**Comment by mtl1979** [comment]
Comparing hashes of first 3 bytes is almost always inefficient if best match is longer than 3 bytes... That is why some levels hash 4 bytes instead... It could be future optimization to switch to hashing 4 bytes after the initial comparing on levels that still hash just first 3 bytes. Hashing more than 4 bytes might require more bits or there would be too many collisions.

**Comment by nmoinvaz** [comment]
> The penalty of this approach is when code looks for a string which first 3 bytes (or bytes with the same hash value) are used very often in a file.

Also I think they have to be frequent in the window, not necessarily the file.

**Comment by gildor2** [comment]
> It sounds like the algorithm will skip ahead and make some assumptions that farther matches will always yield better results. 

No assumptions, algorithm just allows to perform longer jumps when seeking for match, without losing anything. These longer jumps. So, if there's a limit say for 100 jumps, performance will be the same as for original zlib, however my algorithm will process larger set of data, what makes compression better when compression level is smaller than 9. At level 9, longest_match function is almost unrestricted, so both versions of algorithm looks over whole sliding window - but with my algorithm, it does less checks due to longer jumps, so it works faster.

Again, there's no "assumptions" done, the algorithm is not losing anything compared to original one.

> Perhaps this is what @sebpop encountered when he said that it does not provide better compression on several data sets.

It don't have to provide *better* compression on *all* data sets. In the worst case, compression will be the same, with the same speed. But in average, it's better.

**Comment by nmoinvaz** [comment]
My first benchmark test:
## MADLER
```
 Tool: minigzip-madler.exe
 Runs: 32
 Levels: 1-9
 Trimworst: 10

 Level   Comp   Comptime min/avg/max  Decomptime min/avg/max  Compressed size
 1      36.452%    2.715/2.773/2.853       0.966/1.001/1.044  77259041
 2      35.387%    3.032/3.086/3.150       0.969/0.992/1.022  75002289
 3      34.427%    3.705/3.762/3.837       0.948/0.974/0.999  72967052
 4      33.500%    4.001/4.074/4.164       0.940/0.964/0.989  71002829
 5      32.632%    5.483/5.562/5.691       0.926/0.957/0.995  69161697
 6      32.191%    7.508/7.608/7.829       0.929/0.946/0.977  68228443
 7      32.055%    8.967/9.070/9.223       0.920/0.949/0.980  67939659
 8      31.939% 13.656/13.834/14.211       0.923/0.939/0.960  67693439
 9      31.916% 17.365/17.589/18.047       0.925/0.943/0.965  67644560

 avg1   33.389%                7.484                   0.963
 tot                        1481.883                 190.664
```
## FAST-ZLIB
```
 Tool: minigzip-fast-zlib.exe
 Runs: 32
 Levels: 1-9
 Trimworst: 10

 Level   Comp   Comptime min/avg/max  Decomptime min/avg/max  Compressed size
 1      36.452%    2.678/2.753/2.856       0.977/1.000/1.031  77259041
 2      35.387%    2.863/2.995/3.121       0.950/0.989/1.040  75002289
 3      34.427%    3.424/3.568/3.735       0.936/0.984/1.023  72967052
 4      33.482%    3.758/3.944/4.098       0.918/0.966/1.012  70963457
 5      32.489%    4.898/5.081/5.254       0.911/0.950/0.991  68859143
 6      32.065%    5.879/6.090/6.283       0.903/0.946/0.987  67961891
 7      31.983%    6.216/6.415/6.613       0.907/0.947/0.989  67786277
 8      31.913%    6.714/6.953/7.137       0.901/0.944/0.982  67639830
 9      31.910%    7.017/7.222/7.516       0.902/0.939/0.980  67633229

 avg1   33.345%                5.002                   0.963
 tot                         990.481                 190.642
```
## ZLIB-NG
 ```
 Tool: minigzip-head.exe
 Runs: 32
 Levels: 1-9
 Trimworst: 10

 Level   Comp   Comptime min/avg/max  Decomptime min/avg/max  Compressed size
 1      47.684%    1.022/1.051/1.085       0.687/0.699/0.720  101065293
 2      35.540%    1.803/1.881/1.965       0.710/0.734/0.759  75325919
 3      34.226%    2.153/2.216/2.302       0.692/0.717/0.744  72541436
 4      32.953%    2.591/2.680/2.775       0.668/0.686/0.715  69843427
 5      32.665%    2.819/2.889/2.994       0.670/0.692/0.725  69233255
 6      32.515%    3.307/3.427/3.584       0.670/0.690/0.738  68914325
 7      32.257%    4.498/4.645/4.834       0.668/0.690/0.729  68367431
 8      32.172%    6.996/7.175/7.433       0.667/0.686/0.717  68186831
 9      32.156%   9.657/9.915/10.146       0.668/0.688/0.714  68154021

 avg1   34.685%                3.987                   0.698
 tot                         789.356                 138.226
```
And here is another longer run to make sure my benchmarks weren't messed up:

## MADLER
```
 Tool: minigzip-madler.exe
 Runs: 120
 Levels: 1-9
 Trimworst: 90

 Level   Comp   Comptime min/avg/max  Decomptime min/avg/max  Compressed size
 1      36.452%    2.708/2.724/2.733       0.977/0.986/0.992  77259041
 2      35.387%    3.010/3.023/3.032       0.967/0.978/0.986  75002289
 3      34.427%    3.653/3.678/3.691       0.957/0.967/0.973  72967052
 4      33.500%    3.954/3.971/3.983       0.943/0.956/0.961  71002829
 5      32.632%    5.371/5.396/5.405       0.936/0.947/0.951  69161697
 6      32.191%    7.371/7.388/7.397       0.932/0.941/0.944  68228443
 7      32.055%    8.782/8.814/8.828       0.924/0.936/0.941  67939659
 8      31.939% 13.378/13.412/13.427       0.924/0.936/0.940  67693439
 9      31.916% 17.014/17.039/17.056       0.926/0.934/0.938  67644560

 avg1   33.389%                7.272                   0.953
 tot                        1963.357                 257.435
```
## FAST-ZLIB
```
 Tool: minigzip-fast-zlib.exe
 Runs: 120
 Levels: 1-9
 Trimworst: 90

 Level   Comp   Comptime min/avg/max  Decomptime min/avg/max  Compressed size
 1      36.452%    2.623/2.644/2.654       0.984/0.992/0.999  77259041
 2      35.387%    2.828/2.842/2.853       0.964/0.977/0.984  75002289
 3      34.427%    3.379/3.403/3.412       0.953/0.970/0.974  72967052
 4      33.482%    3.699/3.721/3.734       0.944/0.956/0.961  70963457
 5      32.489%    4.807/4.832/4.842       0.930/0.947/0.952  68859143
 6      32.065%    5.760/5.774/5.782       0.932/0.940/0.944  67961891
 7      31.983%    6.075/6.098/6.108       0.926/0.936/0.940  67786277
 8      31.913%    6.592/6.612/6.618       0.925/0.934/0.939  67639830
 9      31.910%    6.857/6.874/6.884       0.926/0.933/0.939  67633229

 avg1   33.345%                4.755                   0.954
 tot                        1283.984                 257.525
```
## ZLIB-NG
```
 Tool: minigzip-head.exe
 Runs: 120
 Levels: 1-9
 Trimworst: 90

 Level   Comp   Comptime min/avg/max  Decomptime min/avg/max  Compressed size
 1      47.684%    1.046/1.056/1.060       0.697/0.703/0.705  101065293
 2      35.540%    1.819/1.830/1.835       0.716/0.724/0.727  75325919
 3      34.226%    2.155/2.169/2.177       0.698/0.708/0.712  72541436
 4      32.953%    2.606/2.620/2.625       0.686/0.691/0.693  69843427
 5      32.665%    2.813/2.825/2.834       0.681/0.686/0.689  69233255
 6      32.515%    3.305/3.320/3.327       0.678/0.685/0.688  68914325
 7      32.257%    4.480/4.492/4.500       0.678/0.685/0.688  68367431
 8      32.172%    6.933/6.951/6.961       0.677/0.682/0.685  68186831
 9      32.156%    9.589/9.611/9.621       0.679/0.683/0.687  68154021

 avg1   34.685%                3.875                   0.694
 tot                        1046.243                 187.395
```

**Comment by nmoinvaz** [comment]
It seems that the _fast-zlib_ method is not currently compatible with _zlib-ng_ because _zlib-ng_ hash table consists of 4 byte hashes, where as original _zlib_ uses rolling hash or hash of consecutive bytes. _Fast-zlib_ takes advantage of the _zlib_ hashing method to optimize `longest_match` lookup. 

From @mtl1979:
> It's faster to hash 4 bytes starting from some location than to constantly accumulate rolling hash. There was also a case when rolling hash didn't give correct result, because the next byte to hash was not one byte after the previously hashed byte, sometimes it hashed things backwards and that caused performance penalty when using rolling hash.

I'm not sure if this can be overcome.

**Comment by nmoinvaz** [comment]
Here is another longer run to make sure my benchmarks weren't messed up:

## MADLER
```
 Tool: minigzip-madler.exe
 Runs: 120
 Levels: 1-9
 Trimworst: 90

 Level   Comp   Comptime min/avg/max  Decomptime min/avg/max  Compressed size
 1      36.452%    2.708/2.724/2.733       0.977/0.986/0.992  77259041
 2      35.387%    3.010/3.023/3.032       0.967/0.978/0.986  75002289
 3      34.427%    3.653/3.678/3.691       0.957/0.967/0.973  72967052
 4      33.500%    3.954/3.971/3.983       0.943/0.956/0.961  71002829
 5      32.632%    5.371/5.396/5.405       0.936/0.947/0.951  69161697
 6      32.191%    7.371/7.388/7.397       0.932/0.941/0.944  68228443
 7      32.055%    8.782/8.814/8.828       0.924/0.936/0.941  67939659
 8      31.939% 13.378/13.412/13.427       0.924/0.936/0.940  67693439
 9      31.916% 17.014/17.039/17.056       0.926/0.934/0.938  67644560

 avg1   33.389%                7.272                   0.953
 tot                        1963.357                 257.435
```
## FAST-ZLIB
```
 Tool: minigzip-fast-zlib.exe
 Runs: 120
 Levels: 1-9
 Trimworst: 90

 Level   Comp   Comptime min/avg/max  Decomptime min/avg/max  Compressed size
 1      36.452%    2.623/2.644/2.654       0.984/0.992/0.999  77259041
 2      35.387%    2.828/2.842/2.853       0.964/0.977/0.984  75002289
 3      34.427%    3.379/3.403/3.412       0.953/0.970/0.974  72967052
 4      33.482%    3.699/3.721/3.734       0.944/0.956/0.961  70963457
 5      32.489%    4.807/4.832/4.842       0.930/0.947/0.952  68859143
 6      32.065%    5.760/5.774/5.782       0.932/0.940/0.944  67961891
 7      31.983%    6.075/6.098/6.108       0.926/0.936/0.940  67786277
 8      31.913%    6.592/6.612/6.618       0.925/0.934/0.939  67639830
 9      31.910%    6.857/6.874/6.884       0.926/0.933/0.939  67633229

 avg1   33.345%                4.755                   0.954
 tot                        1283.984                 257.525
```
## ZLIB-NG
```
 Tool: minigzip-head.exe
 Runs: 120
 Levels: 1-9
 Trimworst: 90

 Level   Comp   Comptime min/avg/max  Decomptime min/avg/max  Compressed size
 1      47.684%    1.046/1.056/1.060       0.697/0.703/0.705  101065293
 2      35.540%    1.819/1.830/1.835       0.716/0.724/0.727  75325919
 3      34.226%    2.155/2.169/2.177       0.698/0.708/0.712  72541436
 4      32.953%    2.606/2.620/2.625       0.686/0.691/0.693  69843427
 5      32.665%    2.813/2.825/2.834       0.681/0.686/0.689  69233255
 6      32.515%    3.305/3.320/3.327       0.678/0.685/0.688  68914325
 7      32.257%    4.480/4.492/4.500       0.678/0.685/0.688  68367431
 8      32.172%    6.933/6.951/6.961       0.677/0.682/0.685  68186831
 9      32.156%    9.589/9.611/9.621       0.679/0.683/0.687  68154021

 avg1   34.685%                3.875                   0.694
 tot                        1046.243                 187.395
```

**Comment by nmoinvaz** [comment]
Fast-zlib changes have been merged into develop.
